<?php 
/**
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 */
    $getNegativeValues = function($array,$merge = ['']) {
        if(!is_array($array)){
            return ['','','','','','','','','',''];
        }
        return array_merge(
            $merge,
            array_map(
                function($val){
                    if(empty($val)){
                        return $val;
                    }
                    return round(-$val); 
                }, 
                $array
            )
        );
    };
   if($lado == 'direito'){
       $tit = 'Orelha Direita';
       $lineplot = [
            'marktype' => MARK_FILLEDCIRCLE,
            'markcolor' => 'red',
            'markwidth' => 3,
            'weight' => 1,
            'color' => 'red',
        ];
   } else {
       $tit = 'Orelha Esquerda';
       $lineplot = [
            'marktype' => MARK_STAR,
            'markcolor' => 'blue',
            'markwidth' => 3,
            'weight' => 1,
            'color' => 'blue',
        ];
   }
/* @var $this \Application\View\Model\GraphModel */
    $ydata  = $getNegativeValues($ydata);
    $ydata2 = $getNegativeValues($ydata2,['','']);
    $this->newGraph(
        400,
        300,
        [
            'scale' => ['textlin', -120, 10], 
            'legend' => $tit, 
            'ydata' => $ydata,
            'lineplotOptions' => $lineplot,
        ]
    );
    $ydata3 = array(-25,-25,-25,-25,-25,-25,-25,-25,-25,-25);
    $this->setNewLineplot($ydata3)->addLineplot();
    $lineplot['color'] = 'green';
    $this->setNewLineplot($ydata2)->addLineplot($lineplot);
    $this->getGraph()->SetFrame(true,'blue',1); 
    $this->getGraph()->SetColor('lightblue');
    $this->getGraph()->SetMarginColor('lightblue');
    $this->getGraph()->yscale->ticks->Set(10,10);
    $this->getGraph()->SetAxisStyle(AXSTYLE_BOXOUT);
    $this->getGraph()->img->SetMargin(40,40,40,50);
    $this->getGraph()->SetShadow();
    $this->getGraph()->ygrid->Show(true,true);
    $this->getGraph()->xgrid->Show(true,false);
    $datax = array("0","0.25","0.5","1","2","3","4","6","8","");
    $this->getGraph()->xaxis->SetTickLabels($datax);
    $this->getGraph()->xaxis->title->Set("kHz");
    $this->getGraph()->yaxis->title->Set("dB");
    $this->getGraph()->title->SetFont(FF_FONT1, FS_BOLD);
    $this->getGraph()->yaxis->title->SetFont(FF_FONT1, FS_BOLD);
    $this->getGraph()->xaxis->title->SetFont(FF_FONT1, FS_BOLD);
    $this->getGraph()->yaxis->SetLabelFormatCallback(function($aVal){
        return round(-$aVal);
    });
    $this->getGraph()->yaxis->SetColor("black");