<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;
$partial    = $this->partialObj('tcmed');

$form->setAttribute('id', 'formCopyRisco');

/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();

$fh->getIdFor('idOcupacao');
$fh->openCol(12)->select('ocupacaoCopy')->closeCol();

$fh->formEnd();
