<?php
/* @author Allan Davini */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];

/* @var $table \Application\View\Helper\Table */
$table      = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action'     => $action,
), [], FALSE, $this->dataView['ajax']));

// Messenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

?>
<h2><?php echo $title ?></h2>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Novo</button>
</p>
<?php

$fh->formInit(); // ============================================================
    $this->partialObj('application')->partial('index/partial-form-listafiltros', null, ['this' => &$this, 'fh' => $fh, 'dataView' => $this->dataView]);

    $fh->lineDown();

    $fh->openCol(12);
        $table->openTable(TRUE);

        $table->setLambda(function($entity, $data) {
            echo "<td>";
            echo "<i class='fa fa-pencil hand edit' title='Editar Ocorrencia' data-id='{$entity->getId()}'></i>";
            if("ATIVO" == $entity->getStatus()) {
                echo "&nbsp;&nbsp;<i class='fa fa-trash hand delete' title='Deletar Ocorrencia' data-id='{$entity->getId()}'></i>";
            }
            echo "</td>";
        });

        $table->renderThead([
            'ID',
            'Nome do Setor',
            'Cargo',
            'Apelido Cargo',
            'Ação'
        ]);

        /* @var $entity \Tcmed\Entity\Ocupacao */
        foreach ($this->data as $entity) {

            switch ($entity->getStatus()) {
                case 'INATIVO':
                    $colorStatus = "danger";
                    break;
                case 'CANCELADO':
                    $colorStatus = "warning";
                    break;
                default:
                    $colorStatus = "";
                    break;
            }

            $table->renderLine([
                $entity->getId(),
                $entity->getSetor()->getNomeSetor(),
                $entity->getCargo()->getCargo(),
                is_null($entity->getCargoApelido()) ? '-' : $entity->getCargoApelido()->getApelido(),
                $entity,
            ], "class={$colorStatus}");
        }

        $table->renderCloseTable();

        echo '<center>', $this->paginationControl($this->data,'Sliding','partials/paginator'), '</center>';

    $fh->closeCol();
$fh->formEnd(); // =============================================================

?>
<br />
<br />
<script lang="javascript">
    $(function () {
        $('.edit').click(function() {
            var id = $(this).data('id');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>/"  + id,
                savePage: false
            });
        });

        $('.delete').click(function() {
            var id = $(this).data('id');

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>/"  + id,
                        savePage: false
                    });
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover esta ocupação?')
                .showModal()
            ;

        });
    });
</script>
