<?php
/**
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 */
$table      = $this->table();
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$data       = $this->listaRiscoOcupacao;
$partial    = $this->partialObj('tcmed');
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

echo $this->partial('partials/modal', array());


echo "<legend>{$title}</legend>";

$table->openTable(TRUE);
$table->setLambda(function ($value, $data) {
    echo '<td nowrap><ul style="list-style-type: none; padding: 0px;">',
    '<li><span class="removerRiscoOcupacao hand" data-id="' . $value . '" title="Remover"><i class="fa fa-trash"></i> Remover </span></li>',
    '<li><span class="hand addEpc" data-id="' . $value . '" title="Adicionar EPC"><i class="fa fa-plus"></i> Add EPC </span></li>',
    '<li><span class="hand addEpi" data-id="' . $value . '" title="Adicionar EPI"><i class="fa fa-plus"></i> Add EPI </span></li>',
    '</td></ul>', PHP_EOL;
});

$table->renderThead([
    ['label' => "Risco"  ],
    ['label' => "Epc"],
    ['label' => "Epi"],
    ['label' => "Ação"],
]);

foreach ($data as $riscoOcupacao) {
    $risco = $riscoOcupacao->getRisco();
    /**
     * Monta a lista com todos os apelidos deste cargo
     */
    $epcs = '<ul style="list-style-type: none; padding: 0px;">';
    foreach ($riscoOcupacao->listEpcRiscoOcupacao() as $epcRiscoOcupacao) {
        $iconRemover = '<i class="removerEpc fa fa-times" data-id="' . $epcRiscoOcupacao->getId() . '"></i>';
        $epcs .= '<li class="hand">' . $iconEditar . ' ' . $iconRemover . ' ' . $epcRiscoOcupacao->getEpc()->getEpc() . '</li>';
    }
    $epcs .= '</ul">';

    $epis = '<ul style="list-style-type: none; padding: 0px;">';
    foreach ($riscoOcupacao->listEpiRiscoOcupacao() as $epiRiscoOcupacao) {
        $iconRemover = '<i class="removerEpi fa fa-times hand" data-id="' . $epiRiscoOcupacao->getId() . '"></i>';
        $epis .= '<li class="hand">' . $iconEditar . ' ' . $iconRemover . ' ' . $epiRiscoOcupacao->getEpi()->getEpi() . '</li>';
    }
    $epis .= '</ul">';

    $table->renderLine([
        $risco->getRisco(),
        $epcs,
        $epis,
        $riscoOcupacao->getId()
    ]);
}
$table->renderCloseTable();

?>
<script type="text/javascript">
    $(function () {

        /**
         * Remove o EPI da lista
         */
        $(".removerEpi").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url: "<?= $this->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret: "#listaRiscos"
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover este EPI?')
                .showModal()
            ;
        });

        /**
         * Remove o EPC da lista
         */
        $(".removerEpc").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url: "<?= $this->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret: "#listaRiscos"
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover este EPC?')
                .showModal()
            ;
        });
        /**
         * Remove a relação de risco e ocupação
         */
        $(".removerRiscoOcupacao").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url: "<?= $this->url($route, array('controller' => 'riscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret: "#listaRiscos"
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover este risco?')
                .showModal()
            ;
        });

        $(".addEpc").click(function(){
            $.processa({
                 url: "<?php echo $this->url($route, array('controller' => 'Epcs', 'action' => 'formForOcupacao'), [], FALSE, FALSE); ?>"
                ,savePage: false
                ,type: 'POST'
                ,data: {
                    idRiscoOcup: $(this).data("id"),
                    idOcupacao : $("#idOcupacao").val()
                }
                ,callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        var $form = $('#formEpcOcupacao');

                        $.processa({
                            url: "<?php echo $this->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'addEpc'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            data: {
                                ocupacao     : $form.find("#idOcupacao").val(),
                                epc          : $form.find("#id").val(),
                                riscoOcupacao: $form.find("#idRiscoOcup").val()
                            },
                            ret: "#listaRiscos"
                        });
                    })
                    .showModal();
                }
            });
        });

        $(".addEpi").click(function(){
            $.processa({
                 url: "<?php echo $this->url($route, array('controller' => 'Epis', 'action' => 'formForOcupacao'), [], FALSE, FALSE); ?>"
                ,savePage: false
                ,type: 'POST'
                ,data: {
                    idRiscoOcup: $(this).data("id"),
                    idOcupacao : $("#idOcupacao").val()
                }
                ,callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        var $form = $('#formEpiOcupacao');

                        $.processa({
                            url: "<?php echo $this->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'addEpi'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            data: {
                                ocupacao     : $form.find("#idOcupacao").val(),
                                epi          : $form.find("#id").val(),
                                riscoOcupacao: $form.find("#idRiscoOcup").val()
                            },
                            ret: "#listaRiscos"
                        });
                    })
                    .showModal();
                }
            });
        });

    });
</script>
