<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;


$fh->closeLine()->renderFieldsetIni('')->setPreFix('ocupacao');
$idOcupacao = $fh->getIdFor('idOcupacao');

$isHorizontal = isset($d["horizontal"]) ? $d["horizontal"] : FALSE;
$colSize = ($isHorizontal) ? 4 : 6;
($isHorizontal) ? $fh->setHorizontal(FALSE) : "";

$fh->setPreFix('setor');
$idSetor = $fh->getIdFor('idSetor');
$fh->openCol($colSize)->text('nomeSetor', ['dt-clear' => $idSetor])->closeCol();
$nomeSetor = $fh->getLastId();
$fh->removePreFix();

($isHorizontal) ? "" : $fh->lineDown();

$fh->setPreFix('cargo');
$idCargo = $fh->getIdFor('idCargo');
$fh->openCol($colSize)->text('cargo', ['dt-clear' => $idCargo])->closeCol();
$cargo = $fh->getLastId();


($isHorizontal) ? "" : $fh->lineDown();

$fh->openCol($colSize)->text('cbo', ['dt-clear' => $idCargo . "," . $cargo])->closeCol();
$cbo = $fh->getLastId();
$fh->removePreFix();

$fh->setHorizontal(TRUE);
$fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();

$this->fieldsOcupacao = [
    "idOcupacao" => $idOcupacao,
    "idSetor"=> $idSetor,
    "idCargo"=> $idCargo,
    "nomeSetor"=> $nomeSetor,
    "cargo"=> $cargo,
    "cbo"=> $cbo,
];
?>
<script type="text/javascript">
    $(function () {
        
        var fields = <?php echo json_encode($this->fieldsOcupacao) ?>;

        var aux = <?php echo json_encode($this->fieldsEmpresa) ?>;
        fields = $.extend(fields, aux, fields);

        $$(fields.nomeSetor).auto({
            primary: "nomeSetor",
            width: 300,
            serviceUrl: "<?php echo $d["this"]->url('tcmed/default', array('controller' => 'Setors', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            responseTo: {
                idSetor: [fields.idSetor],
                idOcupacao: [fields.idOcupacao]
            },
            filters: function(query){
                query["idEmpresa"] = $$(fields.idEmpresa).val()
            },
        });

        $$(fields.cargo).auto({
            primary: "cargo",
            width: 500,
            serviceUrl: "<?php echo $d["this"]->url('tcmed/default', array('controller' => 'Ocupacaos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                idSetor: [fields.idSetor],
                idCargo: [fields.idCargo],
                cargo: [fields.cargo],
                nomeSetor: [fields.nomeSetor],
                cbo: [fields.cbo],
                idOcupacao: [fields.idOcupacao]
            },
            filters: function(query){
                query["idEmpresa"] = $$(fields.idEmpresa).val()
                query["idSetor"] = $$(fields.idSetor).val()
            },
            showCols: ["nomeSetor", "cargo", "apelido", "cbo"]
        });

        $$(fields.cbo).auto({
            primary: "cbo",
            width: 500,
            serviceUrl: "<?php echo $d["this"]->url('tcmed/default', array('controller' => 'Ocupacaos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            responseTo: {
                idSetor: [fields.idSetor],
                idCargo: [fields.idCargo],
                cargo: [fields.cargo],
                nomeSetor: [fields.nomeSetor],
                cbo: [fields.cbo],
                idOcupacao: [fields.idOcupacao]
            },
            filters: function(query){
                query["idEmpresa"] = $$(fields.idEmpresa).val()
                query["idSetor"] = $$(fields.idSetor).val()
            },
            showCols: ["nomeSetor", "cargo", "apelido", "cbo"]
        });

    });
</script>