<?

$controller = $d['dataView']['controller'];
$action     = $d['dataView']['action'];
$route      = $d['dataView']['route'];
$title      = $d['dataView']['titulo'];
$entities   = $d['entities'];

$ppra         = ($d['ppra'])         ?? 0;
$ret          = ($d['ret'])          ?? '#inter';
$redirectTo   = ($d['redirectTo'])   ?? 'edit';
$idEntity     = ($d['idEntity'])     ?? 0;
$hideFields   = ($d['hideFields'])   ?? [];

// Quando um destes botões for ocultado pelo pai deste modal, então não reduzir
// a arvore de ocorrencias
$noHiddenTree =  FALSE;
if(in_array('.fa-plus-circle', $hideFields) OR in_array('.fa-minus-circle', $hideFields)) {
    $noHiddenTree =  TRUE;
}

/* @var $table \Application\View\Helper\Table */
$table      = $d['this']->table();

// Modal
echo $d['this']->partial('partials/modal', array());

$table->openTable(TRUE);
$table->setEditLine(FALSE);

$table->renderThead([
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]);

$lastSetor = false;

/* @var $entity \Tcmed\Entity\Ocupacao */
foreach ($entities as $i => $entity) {

    $idSetor    = $entity->getSetor('id');
    $trocaSetor = false;

    if($lastSetor != $idSetor) {
        $lastSetor  = $idSetor;
        $trocaSetor = true;

        $table->setTdopt([
           "colspan='8' class='novoSetor' data-id='{$idSetor}'",
        ]);

        $icon = "<i class='fa fa-minus-circle hand'></i><i class='fa fa-plus-circle hand'></i>";

        $table->renderLine([
            "<h3>&nbsp;{$icon}&nbsp;Setor: " . strtoupper($entity->getSetor('nomeSetor')) . "</h3>"
        ], "style='border-top: 3px solid #999'");
    }

    // -------------------------------------------------------------------------

    $table->setTdopt([
        'width="50px"',
        'colspan="6"',
        'width="150px"',
    ]);

    $table->renderLine([
        "",
        "<h4> Cargo: " . strtoupper($entity->getCargo('cargo')) . "</h4>",
        "<span class='hand addRisco' data-id='{$entity->getId()}'><i class='fa fa-plus'></i> Incluir Risco</span><br /><span class='hand editOcupacao' data-ocupacao='{$entity->getId()}'><i class='fa fa-pencil'></i> Editar Cargo</span><br /><span class='hand rmvOcupacao'  data-id='{$entity->getId()}'><i class='fa fa-trash'></i> Remover Cargo</span>"
    ]);

    // -------------------------------------------------------------------------

    $table->setTdopt([
        'colspan="2" width="100px"',
        'colspan="6"',
    ]);

    $table->renderLine([
        "",
        $entity->getDescricaoCargo('descricao')
    ]);

    // -------------------------------------------------------------------------

    if(empty($entity->listaRiscoOcupacao())) {
        $table->setTdopt([
            'colspan="2"',
            'colspan="5"',
            ''
        ]);

        $table->renderLine([
            "",
            "<span class='hand copyRisco' data-ocupacao='{$entity->getId()}' data-cargo='{$entity->getCargo('id')}' data-ppra='{$entity->getPpra('id')}'><i class='fa fa-clone'></i> Copiar Risco de outro Cargo</span>",
            "",
        ]);
    }

    foreach ($entity->listaRiscoOcupacao() as $riscoOcupacao) {
        /* ==================  Linha 1: titulo risco  ================*/
        $table->setTdopt([
            'colspan="2"',
            'colspan="5"',
            ''
        ]);

        $table->renderLine([
            "",
            "<b>RISCO: " . $riscoOcupacao->getRisco('risco') . "</b>",
            "<span class='hand editRisco' data-ocupacao='{$entity->getId()}' data-riscoOcupacao='{$riscoOcupacao->getId()}'><i class='fa fa-pencil'></i> Editar Risco</span><br /><span class='hand rmvRisco' data-id='{$riscoOcupacao->getId()}'><i class='fa fa-trash'></i> Remover Risco</span>",
        ]);

        /* ==================  Linha 2: Info 1  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            'colspan="4"',
        ]);

        $table->renderLine([
            "",
            "Tipo",
            $riscoOcupacao->getTipo()
        ]);

        /* ==================  Linha 3: Info 2  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            '',
            '',
            '',
            '',
        ]);

        $table->renderLine([
            "",
            "Agente",
            $riscoOcupacao->getAgente(),
            "Prioridade",
            $riscoOcupacao->getPrioridade(),
            "",
        ]);

        /* ==================  Linha 4: Info 3  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            '',
            '',
            '',
            '',
        ]);

        $table->renderLine([
            "",
            "Classificação do Agente",
            $riscoOcupacao->getClassifAgente(),
            "Controle",
            $riscoOcupacao->getControle(),
            "",
        ]);

        /* ==================  Linha 5: Info 4  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            '',
            '',
            '',
            '',
        ]);

        $table->renderLine([
            "",
            "Classificação da Exposição",
            $riscoOcupacao->getClassifExposicao(),
            "Somatoria",
            $riscoOcupacao->getSomatoria(),
            "",
        ]);

        /* ==================  Linha 6: Info 5  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            '',
            '',
            '',
            '',
        ]);

        $table->renderLine([
            "",
            "Intensidade/ Concentração",
            $riscoOcupacao->getIntensConc(),
            "Técnica Utilizada",
            $riscoOcupacao->getTecnicaUtil(),
            "",
        ]);

        /* ==================  Linha 7: Info 6  ================*/

        $table->setTdopt([
            'colspan="3"',
            '',
            '',
            '',
            '',
            '',
        ]);

        $table->renderLine([
            "",
            "EPC Eficaz",
            "",
            "EPI Eficaz",
            "",
            "",
        ]);

        /* ==================  Linha 8: lista de EPCs  ========*/

        /**
         * Monta a lista com todos os apelidos deste cargo
         */
        $listaEpcs = $riscoOcupacao->listEpcRiscoOcupacao();

        $epcs = '-';
        if(count($listaEpcs)) {
            $epcs = '<ul style="list-style-type: none; padding: 0px;">';
            foreach ($listaEpcs as $epcRiscoOcupacao) {
                $iconRemover = '<i class="rmvEpc fa fa-times" data-id="' . $epcRiscoOcupacao->getId() . '"></i>';
                $epcs .= '<li class="hand">' . $iconRemover . ' ' . $epcRiscoOcupacao->getEpc()->getEpc() . '</li>';
            }
            $epcs .= '</ul">';
        }

        $listaEpis = $riscoOcupacao->listEpiRiscoOcupacao();

        $epis = '-';
        if(count($listaEpis)) {
            $epis = '<ul style="list-style-type: none; padding: 0px;">';
            foreach ($listaEpis as $epiRiscoOcupacao) {
                $iconRemover = '<i class="rmvEpi fa fa-times hand" data-id="' . $epiRiscoOcupacao->getId() . '"></i>';
                $epis .= '<li class="hand">' . $iconRemover . ' ' . $epiRiscoOcupacao->getEpi()->getEpi() . '</li>';
            }
            $epis .= '</ul">';
        }

        /* ==================  Linha 8: lista de EPCs  ========*/

        $table->setTdopt([
            'colspan="3"',
            'style="text-align: right"',
            'colspan="3"',
            ''
        ]);

        $table->renderLine([
            "",
            "EPC",
            $epcs,
            "<span class='hand addEpc' data-riscoocupacao='{$riscoOcupacao->getId()}' data-ocupacao='{$riscoOcupacao->getOcupacao('id')}'><i class='fa fa-plus'></i> Incluir EPC</span>",
        ]);

        /* ==================  Linha 8: lista de EPIs  ========*/

        $table->setTdopt([
            'colspan="3"',
            'style="text-align: right"',
            'colspan="3"',
            ''
        ]);

        $table->renderLine([
            "",
            "EPI",
            $epis,
            "<span class='hand addEpi' data-riscoocupacao='{$riscoOcupacao->getId()}' data-ocupacao='{$riscoOcupacao->getOcupacao('id')}'><i class='fa fa-plus'></i> Incluir EPI</span>",
        ]);

        /* ==================  LINEDOWN  ================*/

        $table->setTdopt([
            'colspan="8"',
        ]);

        $table->renderLine([
            "&nbsp;",
        ]);
    }

    // -------------------------------------------------------------------------

    $table->setTdopt([
        'colspan="8"',
    ]);

    $table->renderLine([
        "&nbsp;",
    ]);

    // -------------------------------------------------------------------------

}

// Apenas para estabelecer um fim do setor, para os ocultadores/exibidores
$table->setTdopt([
    'colspan="8" class="novoSetor"',
]);

$table->renderLine([
    "&nbsp;",
], 'class="hideOn"');


// Finaliza a exibição da tabela
$table->renderCloseTable();

$transp = compact(
    'ret',
    'redirectTo',
    'ppra',
    'idEntity',
    'hideFields',
    'noHiddenTree'
);

?>
<br />
<br />
<script lang="javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;

        /**
         * Adiciona uma nova ocupacao
         */
        $('#addOcupacao').click(function() {
            $.processa({
                url     : "<?php echo $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'getFormModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ppra: transp.ppra
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){
                            $('#formOcupacaoModal').processa({
                                url : "<?php echo $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                                type: "POST",
                                savePage: false,
                                ret : transp.ret,
                                data: {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                },
                            });
                        })
                        .showModal()
                    ;
                }
            });
        });

        $('.editOcupacao').click(function() {
            var ocupacao      = $(this).data('ocupacao');

            $.processa({
                url     : "<?php echo $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'getFormModal'), [], FALSE, FALSE); ?>/" + ocupacao,
                savePage: false,
                type    : "POST",
                data    : {
                    ppra: transp.ppra
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){
                            $('#formOcupacaoModal').processa({
                                url : "<?php echo $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'edit'), [], FALSE, FALSE); ?>",
                                type: "POST",
                                savePage: false,
                                ret : transp.ret,
                                data: {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                },
                            });
                        })
                        .showModal()
                    ;
                }
            });
        });

        /**
        * Remove o EPI da lista
        */
        $(".rmvOcupacao").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
            .setClickOk(function () {
                $.processa({
                    url     : "<?= $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        redirectTo: transp.redirectTo,
                        idEntity  : transp.idEntity,
                        id        : id
                    },
                })
            })
            .setLabelOk("SIM")
            .setLabelNg("NÃO")
            .setMsg('Deseja realmente remover este Cargo?')
            .showModal()
            ;
        });

        $('.copyRisco').click(function() {
            var ocupacao = $(this).data('ocupacao');
            var ppra     = $(this).data('ppra');

            $.processa({
                url     : "<?php echo $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'copyRisco'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ocupacao: ocupacao,
                    ppra    : ppra,
                    getForm : true
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $('#formCopyRisco').processa({
                                url: "<?= $d['this']->url($route, array('controller' => 'Ocupacaos', 'action' => 'copyRisco'), [], FALSE, FALSE); ?>",
                                savePage: false,
                                type: "POST",
                                ret : transp.ret,
                                data: {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                }
                            });

                        })
                        .showModal()
                    ;
                }
            });
        });

        $('.addRisco').click(function() {
            var idOcupacao = $(this).data('id');

            $.processa({
                url     : "<?php echo $d['this']->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ocupacao: idOcupacao
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $('#formModalRiscoOcup').processa({
                                url: "<?= $d['this']->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                                savePage: false,
                                type: "POST",
                                ret : transp.ret,
                                data: {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                }
                            });

                        })
                        .showModal()
                    ;
                }
            });
        });

        $('.editRisco').click(function() {
            var ocupacao      = $(this).data('ocupacao');
            var riscoOcupacao = $(this).data('riscoocupacao');

            $.processa({
                url     : "<?php echo $d['this']->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>/" + riscoOcupacao,
                savePage: false,
                type    : "POST",
                data    : {
                    ocupacao: ocupacao
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $('#formModalRiscoOcup').processa({
                                url: "<?= $d['this']->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'edit'), [], FALSE, FALSE); ?>",
                                savePage: false,
                                type: "POST",
                                ret : transp.ret,
                                data: {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                }
                            });

                        })
                        .showModal()
                    ;
                }
            });
        });

        /**
        * Remove o Risco da lista
        */
        $(".rmvRisco").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
            .setClickOk(function () {
                $.processa({
                    url     : "<?= $d['this']->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        redirectTo: transp.redirectTo,
                        idEntity  : transp.idEntity,
                        id        : id
                    },
                })
            })
            .setLabelOk("SIM")
            .setLabelNg("NÃO")
            .setMsg('Deseja realmente remover este Risco?')
            .showModal()
            ;
        });

        $(".addEpc").click(function(){

            var ocupacao  =  $(this).data('ocupacao');
            var riscoOcup =  $(this).data('riscoocupacao');

            $.processa({
                url: "<?php echo $d['this']->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type: 'POST',
                data: {
                    ocupacao      : ocupacao,
                    riscoOcupacao : riscoOcup
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $('#formModalEpcOcupacao').processa({
                                url     : "<?php echo $d['this']->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                                type    : "POST",
                                savePage: false,
                                ret     : transp.ret,
                                data    : {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                },
                            });

                        })
                        .showModal()
                    ;
                }
            });
        });

        /**
        * Remove o EPI da lista
        */
        $(".rmvEpc").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
            .setClickOk(function () {
                $.processa({
                    url     : "<?= $d['this']->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        redirectTo: transp.redirectTo,
                        idEntity  : transp.idEntity,
                        id        : id
                    },
                })
            })
            .setLabelOk("SIM")
            .setLabelNg("NÃO")
            .setMsg('Deseja realmente remover este EPC?')
            .showModal()
            ;
        });

        $(".addEpi").click(function(){

            var ocupacao  =  $(this).data('ocupacao');
            var riscoOcup =  $(this).data('riscoocupacao');

            $.processa({
                url: "<?php echo $d['this']->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type: 'POST',
                data: {
                    ocupacao      : ocupacao,
                    riscoOcupacao : riscoOcup
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $('#formModalEpiOcupacao').processa({
                                url     : "<?php echo $d['this']->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                                type    : "POST",
                                savePage: false,
                                ret     : transp.ret,
                                data    : {
                                    redirectTo: transp.redirectTo,
                                    idEntity  : transp.idEntity
                                },
                            });

                        })
                        .showModal()
                    ;
                }
            });
        });

        /**
        * Remove o EPI da lista
        */
        $(".rmvEpi").click(function () {
            var id = $(this).attr("data-id");

            gModal.reset("confirm", 1)
            .setClickOk(function () {
                $.processa({
                    url     : "<?= $d['this']->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        redirectTo: transp.redirectTo,
                        idEntity  : transp.idEntity,
                        id        : id
                    },
                })
            })
            .setLabelOk("SIM")
            .setLabelNg("NÃO")
            .setMsg('Deseja realmente remover este EPI?')
            .showModal()
            ;
        });

        /* ================== Gerenciacores da listaShow ====================
         * Funções de gerenciamento da listagem de tópicos para armazenar
         * aqueles que foram abertos/fechados pelo usuário. Vou utilizar esta
         * estrutura para manter os tópicos abertos mesmo quando virar a página
         */

        function setLista(lista) {
            $.jsSessao('listaShow' + transp.ppra, JSON.stringify(lista));
        }

        function getLista() {
            return JSON.parse($.jsSessao('listaShow' + transp.ppra) || "[]");
        }

        function addLista(id) {
            var lista = getLista();
            var index = lista.indexOf(id);

            if(index == -1) {
                lista.push(id);
            }

            setLista(lista);
        }

        function rmvLista(id) {
            var lista = getLista();
            var index = lista.indexOf(id);

            if(index > -1) {
                lista.splice(index, 1);
            }

            setLista(lista);
        }

        /* ================================================================== */

        /**
         * Ao clicar no '-', fecha o topico (setor) selecionado
         */
        $('.fa-minus-circle').click(function() {
            var $tr  = $(this).closest('tr');
            var next = true;

            rmvLista($tr.children().data('id'));

            while(next) {
                var $tr = $tr.next();

                if($tr.find('td').hasClass('novoSetor')) {
                    next = false;
                    continue;
                }
                $tr.hide();
            }

            $(this).hide();
            $(this).parent().find('.fa-plus-circle').show();
        });

        /**
         * Ao clicar no '+', abre o topico (setor) selecionado
         */
        $('.fa-plus-circle').click(function() {
            var $tr  = $(this).closest('tr');
            var next = true;

            addLista($tr.children().data('id'));

            while(next) {
                var $tr = $tr.next();

                if($tr.find('td').hasClass('novoSetor')) {
                    next = false;
                    continue;
                }
                $tr.show();
            }

            $(this).hide();
            $(this).parent().find('.fa-minus-circle').show();
        });

        /**
         * Abre todos os topicos (setores) que estão na listagem de getLista()
         * mesmo após virar a página
         */
        if(!transp.noHiddenTree) {
            $('.novoSetor').each(function() {
                var id = $(this).data('id');

                if(getLista().indexOf(id) == -1) {
                    $(this).find(".fa-minus-circle").click();
                } else {
                    $(this).find(".fa-plus-circle").click();
                }

            });
        }

        $.each(transp.hideFields, function(key, val) {
            $(val).hide();
        });

    });
</script>
