<?php

/* @var $medico \Tcmed\Entity\Medico */
/* @var $empresa Tcmed\Entity\Empresa */

$corSistema           = "#f00";
$abreFolha            = "<div class='folha'>";
$fechaFolha           = "</div>";
$quebraPagina         = "<div style='page-break-before: always;'></div>";
$closeTable           = "</tbody></table>";
$examesComplementares = 0;

$this->__set('controller', '')     ; // ================================ CSS ==+
$this->__set('subMod', 'partials') ;
include $this->partial('style-pdf'); // =======================================+

?>
<style type="text/css">
    h2, td, th, p{
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-weight: 500;
        line-height: 1.1;
    }
    
    .small
    {
        font-size: 15px;
        color: #444;
    }
    
    .subl{
        text-decoration: underline;
    }
    
</style>
<?php 

/**
 * Atribui em $quantFuncionarios, a quantidade de funcionários na empresa entre
 * os periodos
 */
$quantFuncionarios = 0;
foreach ($listaFuncionarios as $val) {
    $quantFuncionarios += count($val);
}
/**
 * Percorre a lista de consultas, buscando todos os tipos de consultas. Então,
 * estes valores serão atribuídos na lista de tipos (Se um tipo específicio já 
 * estiver na lista de tipos, então não será adicionado este tipo);
 */
$listaDeTipos = array();
foreach ($listaConsultas as $aux) {
    foreach (array_keys($aux) as $tipoDaConsulta) {
        if (!in_array($tipoDaConsulta, $listaDeTipos)) {
            $listaDeTipos[] = $tipoDaConsulta;
        }
    }
}

echo $openFolha;

$path      = $empresa->getAdministradora('hold', ['pathLogo']);
$holdImage = $param('path', 'hold_dir') . $path;
$imageHold = "<img style='width: 150px' id='imagemLogoHold' src='{$holdImage}'>";
    
echo <<<TOPO
        <table id='topo' style="width: 100%;">
            <tbody>
                <tr>
                    <td style='width: 165px'>{$imageHold}</td>
                    
                    <td id="topo-descr">
                        <h2>Relatório Anual</h2> 
                        <span class='small'>Programa de Controle Médico de Saúde Ocupacional</span>
                        <br>
                        Período {$periodo['ini']} a {$periodo['fim']} Emitido em {$periodo['emissao']}
                    </td>
                </tr>
            </tbody>
        </table>
        <hr>
TOPO;
                        
echo <<<CABECALHO
    <table class='table'>
        <thead>
            <tr>
                <th colspan="3">Identificação</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">Administradora</td>
                <td colspan='2'>{$empresa->getAdministradora('razaoSocial')}</td>
            </tr>
            <tr>
                <td class="text-right">Empresa</td>
                <td>{$empresa->getFantasiaEmpresa()}</td>
                <td>CNPJ: {$empresa->getCnpj()}</td>
            </tr>
            <tr>
                <td class="text-right">Endereco</td>
                <td colspan='2'>{$empresa->getEndereco()}</td>
            </tr>
            <tr>
                <td class="text-right">Funcionarios</td>
                <td colspan='2'>{$quantFuncionarios}</td>
            </tr>
            <tr style="background-color: #eee">
                <td colspan="3">Deve-se manter o original do documento arquivado, à disposição do agente de inpeção de trabalho.</td>
            </tr>
            <tr style="background-color: #eee">
                <td colspan="3">Consta ainda um planejamento preliminar para os próximos 12 meses.</td>
            </tr>
        </tbody>
    </table>
    <br>
                
CABECALHO;
                
?>

<table class='table'>
    <thead>
        <tr>
            <td class="text-center" colspan="13">
                <h3>Estatística do Controle Médico de Saúde Ocupacional / PCMSO</h3>
                <h4>Programa de Controle Médico do <?php echo "Periodo " . $periodo["ini"] . " a " . $periodo["fim"] . " Emitido em " . $periodo["emissao"] ?></h4>
            </td>
        </tr>
        <tr>
            <th rowspan="2">Setor</th>
            <?php
            $listaTipos = array("ADM", "PER", "DEM", "RET", "MDF", "PEA");
            foreach ($listaTipos as $nomeTipo) {
                echo '<th colspan="2">' . $param($nomeTipo, 'FC_tipo_exame') . '</th>';
            }

            echo '</tr>';
            echo '<tr>';
            
            for ($i = 0; $i < count($listaTipos); $i++) {
                echo '<th>Apto</th>';
                echo '<th>Inapto</th>';
            }
            ?>
        </tr>
    </thead>
    <tbody>
        <?php
        $apto = array();
        $inapto = array();
        foreach ($listaConsultas as $setor => $tipos) {
            echo '<tr>';
            echo '<td>' . $setor . '</td>';

            foreach ($listaTipos as $nomeTipo) {
                if (isset($tipos[$nomeTipo])) {
                    echo '<td class="text-right">' . $tipos[$nomeTipo]["apto"] . '</td>';
                    echo '<td class="text-right">' . $tipos[$nomeTipo]["inapto"] . '</td>';
                } else {
                    echo '<td  class="text-right">-</td>';
                    echo '<td  class="text-right">-</td>';
                }
                if (!isset($apto[$nomeTipo]) or ! isset($inapto[$nomeTipo])) {
                    $apto[$nomeTipo] = 0;
                    $inapto[$nomeTipo] = 0;
                }
                !isset($apto[$nomeTipo])   && $apto[$nomeTipo] = 0;
                !isset($inapto[$nomeTipo]) && $inapto[$nomeTipo] = 0;
                if(isset($tipos[$nomeTipo])){
                    $apto[$nomeTipo]   += $tipos[$nomeTipo]["apto"];
                    $inapto[$nomeTipo] += $tipos[$nomeTipo]["inapto"];
                }
            }
            echo '</tr>';
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <th>Total</th>
            <?php
            foreach ($listaTipos as $nomeTipo) {
                echo '<th class="text-right">' . $apto[$nomeTipo] . '</th>';
                echo '<th class="text-right">' . $inapto[$nomeTipo] . '</th>';
            }
            ?>
        </tr>
    </tfoot>
</table>
<br>

<table class='table'>
    <thead>
        <tr>
            <td class="text-center" colspan="6">
                <h4>Relatório Anual<br>
                    <?php echo "Periodo " . $periodo["ini"] . " a " . $periodo["fim"] ?></h4>
            </td>
        </tr>

        <!-- Só irá imprimir estes valores se a houver dados na listaConsulta ou listaFuncionario -->
        <?php if (0 < count($listaConsultas) or 0 < count($listaFuncionarios)): ?>
            <tr>
                <th>Setor</th>
                <th>Natureza do Exame</th>
                <th>Exames</th>
                <th>Resultados Anormais</th>
                <th>Percentual de Anormais</th>
                <th>Planejamento próximo 12 meses</th>
            </tr>
        <?php endif; ?>

    </thead>
    <?php
    if (0 < count($listaConsultas)) {
        echo '<tbody>';
    }
    /**
     * Para a montagem do relatório anual, dividi em 3 partes para cada setor:
     * Na primeira parte, consta todos os exames cujo o tipo seja diferente
     * de 'PER';
     * 
     * Na segunda parte, consta todos os exames cujo o tipo seja 'PER' (e 
     * estes dados serão mesclados com o $listaFuncionarios, que é uma lista
     * contendo os setores e a quantidade de funcionários. Desta forma, é
     * possível fazer a montagem da coluna 'Planejamento proximo 12 meses mesmo
     * quando existem exames para este tipo);
     * 
     * Na terceira parte, consta todos os setores que contém funcionarios mas
     * que não possuem exames realizados com o tipo 'PER'
     */
    foreach ($listaConsultas as $setor => $tipos) {
        $aux = array();

        if (array_key_exists("PER", $tipos)) {
            $aux = $tipos["PER"];
            unset($tipos["PER"]);
        }

        /**
         * Primeira parte
         */
        foreach ($tipos as $tipo => $res) {

            $total = $res['apto'] + $res['inapto'];
            $totalPercent = ($res['inapto'] * 100) / $total;

            echo '<tr>';
            echo '<td>' . $setor . '</td>';
            echo '<td>' . $tipo . '</td>';
            echo '<td>' . $total . '</td>';
            echo '<td>' . $res['inapto'] . '</td>';
            echo '<td>' . round($totalPercent, 2) . ' %</td>';
            echo '<td>-</td>';
            echo '</tr>';
        }

        /**
         * Segunda parte
         */
        echo '<tr>';
        echo '<td>' . $setor . '</td>';
        echo '<td>PERIÓDICO</td>';
        if (!empty($aux)) {
            $total = $aux['apto'] + $aux['inapto'];

            $totalPercent = ($aux['inapto'] * 100) / $total;

            echo '<td>' . $total . '</td>';
            echo '<td>' . $aux['inapto'] . '</td>';
            echo '<td>' . round($totalPercent, 2) . ' %</td>';
        } else {
            echo '<td>-</td>';
            echo '<td>-</td>';
            echo '<td>-</td>';
        }

        if (isset($listaFuncionarios[$setor])) {
            echo '<td>' . count($listaFuncionarios[$setor]) . '</td>';
            unset($listaFuncionarios[$setor]);
        } else {
            echo '<td>-</td>';
        }

        echo '</tr>';
    }

    /**
     * Terceira parte
     */
    foreach ($listaFuncionarios as $setor => $val) {
        echo '<tr>';
        echo '<td>' . $setor . '</td>';
        echo '<td>PERIÓDICO</td>';
        echo '<td>-</td>';
        echo '<td>-</td>';
        echo '<td>-</td>';
        echo '<td>' . count($val) . '</td>';
        echo '</tr>';
    }

    if (0 < count($listaConsultas)) {
        echo '<t/body>';
    }
    ?>
    <tfoot>
        <tr>
            <td class="color-sis" colspan="5" style="text-align: right">Total de Funcionarios</td>
            <td><?php echo $quantFuncionarios ?></td>
        </tr>
    </tfoot>
</table>
<br>
    <div class="text-center" style="width: 300px">
        <?php
        $img = $param('all','medicoDirAss') . $medico->getAssinatura();
        echo '<img width="180" height="45" style="margin-bottom: -10px" src="' . $img . '">';
        ?>
        <p style="font-size: 10px">_________________________________________
        <br>
        Médico Coordenador
        <br>    
        <?php 
            echo $medico->getNomeMedico();
            echo " - CRM: " . $medico->getCrm() . "<br>";
            echo "Tel: " . $medico->getContato('meioDeContatoPrincipal', ['telefone']) . "<br>";
        ?>
        </p>
    </div>


<?php
echo $closeFolha;