<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;

$horizontal = $fh->getHorizontal();
$fh->setHorizontal(TRUE);
$fh->renderFieldsetIni('Doenças Familiares',['notOpenLine'=>TRUE, 'fAtrb' => 'id="DoenFam"'])->setPreFix('questionario');


$inputsAntecedentes = $fh->getForm()->getPrefixInterrogatio(4);
foreach ($inputsAntecedentes as $prefix) { 
    $type = 'MultiCheckbox';
    if(is_array($prefix)){
        $type   = $prefix[1];
        $prefix = $prefix[0];
    }  
    $fh->openLine()->setPreFix($prefix);
    if($type == 'MultiCheckbox'){
        $fh->openCol('12')->renderInputMultiCheckbox('respostaCheck',['noClean'=>true,'labelWidth' => '8'])->closeCol();         
    }else{
        $fh->setHorizontal(FALSE);  
        $fh->openCol('12')->renderInputTextArea('resposta')->closeCol();         
        $fh->setHorizontal(TRUE);  
    }
    $fh->closeLine()->removePreFix();
}


$fh->renderFieldsetFim()->removePreFix();   
$fh->setHorizontal($horizontal);
?>

<script lang="javascript">

// validar preenchimento dos campos Doença Familiar
var isValidHistorioFamiliar = function(){
    var checked = false;    
    $doenFam = $("#DoenFam");
    removeAlert($doenFam);
    $doenFam.find("input[type=checkbox]").each(function() {
        if($(this).prop('checked')){
            checked = true;
        }
    });
    if(!checked){
        var $test = $doenFam.find("textarea");
        if($test.size() === 1){
            if($test.eq(0).val() === ''){
                makeDivError($doenFam, "Deve ser selecionado ao menos um ou escrever no campo Outras");
                return false;
            }
        }else{
            alert('text area nao encontrado');
        }
    }
    return true;
};

</script>