<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;

$horizontal = $fh->getHorizontal();
$fh->setHorizontal(FALSE);
$fh->renderFieldsetIni('Interrogatorio ' . $d["interrogatorio"],['notOpenLine'=>TRUE, 'fAtrb' => 'id="Int' . $d["interrogatorio"] . '"'])->setPreFix('questionario');
$inputsInterrogatorio = $fh->getForm()->getPrefixInterrogatio($d["interrogatorio"]);
foreach ($inputsInterrogatorio as $prefix) {
    $fh->openLine()->setPreFix($prefix);
        $fh->openCol('9')->renderInputText('resposta')->closeCol();
        $fh->openCol('3')->renderInputRadio('respostaCheck',['sep' => ' | '])->closeCol();
    $fh->closeLine()->removePreFix();
}
$fh->renderFieldsetFim()->removePreFix();   
$fh->setHorizontal($horizontal);

?>

<script lang="javascript">
function checkResposta(obj){
    var divBox  = $(obj).closest('.row');        
    var inLabel = divBox.find("label").html();
    var txt     = divBox.find("input[type=text]");
    var rdo1    = divBox.find("input[type=radio]");
    
    if(obj.type === "radio"){
        if(txt.val() === "" && rdo1.eq(0).prop('checked')){
            alert("Deve ser preenchido a descrição da pergunta: " + inLabel);
            txt.focus();
        }   
        return;
    }
    if(obj.type === "text"){
        if($(txt).val() !== ""){
            rdo1[0].checked = true;
        }else{
            rdo1[1].checked = true;
        }        
    }
}

// validar preenchimento dos campos interrogatorios
var isValidInterrogatorio = function(){
    var flag = true;
    // validar interrogatorio 1
    if(validaInterrogatorio($("#Int1")) === false){
        flag = false;
    }
    // validar interrogatorio 2
    if(validaInterrogatorio($("#Int2")) === false){
        flag = false;
    }
    return flag;
};


var validaInterrogatorio = function($fieldSet){ 
    var flag = true;   
    // validar interrogatorio 
    $fieldSet.find(".row").each(function() {
        var $divRow = $(this);
        var inLabel = $divRow.find("label").html();
        var $txt     = $divRow.find("input[type=text]");
        var $rdo1    = $divRow.find("input[type=radio]");
        if($txt.val() === "" && $rdo1.eq(0).prop('checked')){
            makeDivError($divRow.find("div:eq(0)"), inLabel);
            flag = false;
        }else{
            removeAlert($divRow.find("div:eq(0)"));
        }    
    });
    return flag;
};


</script>