<?php
/** ===========================================================================|
 * FORM - SET_ENTITY
 * @author SET_AUTHOR
 * @since SET_SINCE
 *
 * IncludeView - v1
 */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
/* @var $form \Tcmed\Form\PpraVigenciaModelo */
$form       = $this->form;
$partial    = $this->partialObj('application');
$frm = 'formPpraVigenciaModelo';
$form->setAttribute('id', $frm);
/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

echo '<h3>Você precisa digitar um nome para usar os textos desse ppra como modelo para novos PPRA.</h3>';

$fh->formInit();

$fh->openCol(4)->text('nome')->closeCol();
$fh->openCol(8)->textarea('descricao')->closeCol();
$fh->closeLine();

$fh->formEnd(); // =================================================


// Var de transferencia PHP to JS
$transp = array(
    'action' => $this->dataView['action']
);
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        if("edit" == transp.action) {
            $.processa({
                url: "<?= $this->url($route, array('controller' => 'PpraVigenciaTextos', 'action' => 'texto'), [], FALSE, FALSE); ?>",
                savePage: false,
                ret: "#textos"
            });
        }

//        $$(transp.cbo).auto({
//            primary: "cbo",
//            width: 500,
//            noCache: true,
//            responseTo: {
//                cargo: [transp.cargo],
//            },
//            filters: function (query) {
//                query["idEmpresa"] = $$(transp.idEmpresa).val()
//            },
//            showCols: ["nomeSetor"]
//        });
    });

</script>
