<?php

$result = $this->resultSet;

/* @var $entity \Tcmed\Entity\Medico */
if ($result) {
    $array = [];
    $array[] = [
        'menu_idMedico' => "ID Medico",
        'menu_referencia' => "Referencia",
        'menu_nomeMedico' => "Nome do Medico",
        'menu_status' => "Status",
        'menu_crm' => "Crm",
        'menu_especialidade' => "Especialidade",
        'menu_sexo' => 'Sexo',
        'menu_rg' => "Rg",
        'menu_cpf' => "Cpf",
        'menu_estadoCivil' => "Estado Civil",
    ];
    foreach ($result as $medico) {

        $array[] = [
            'idMedico' => $medico->getIdMedico(),
            'referencia' => $medico->getReferencia(),
            'nomeMedico' => $medico->getNomeMedico(),
            'status' => $medico->getStatus(),
            'crm' => $medico->getCrm(),
            'especialidade' => $medico->getEspecialidade(),
            'sexo' => $medico->getSexo(),
            'rg' => $medico->getRg(),
            'cpf' => $medico->getCpf(),
            'estadoCivil' => $medico->getEstadoCivil(),
        ];
    }
}

echo json_encode($array);
