<?php
/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();
/**
 * @var Object Partials (pedacos) de outras entidades presentes neste form
 */
$partialObject = $this->partialObj('tcmed');
/**
/**
 * @var string $controller Controller da entidade
 */
$controller = 'medicos';
/**
 * @var string $route Rota do Controller
 */
$route = 'tcmed/default';
/**
 * Titulo da view
 */
echo "<h2>" . $this->dataView['titulo'] . "</h2>";

/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));
$fh->formInit('Cadastro de Medicos:');
$fh->setHorizontal(FALSE);
$fh->openCol('3')->text('referencia')->closeCol();
$fh->lineDown();
$fh->openCol('6')->text('nomeMedico')->closeCol();
$fh->openCol('3')->select('status')->closeCol();
$fh->lineDown();
$fh->openCol('3')->text('crm')->closeCol();
$fh->openCol('3')->text('especialidade')->closeCol();
$fh->openCol('3')->select('sexo')->closeCol();
$fh->lineDown();
$fh->openCol('3')->text('rg')->closeCol();

$fh->openCol(3)->cpf('cpf')->closeCol();
$cpf = $fh->getLastId();

$fh->openCol('3')->select('estadoCivil')->closeCol();
$fh->lineDown();
$fh->openCol('3')->calend('dataAdmissao')->closeCol();
$fh->openCol('3')->calend('dataDemissao')->closeCol();
$fh->lineDown();
$fh->openCol('6')->file('fileAssinatura')->closeCol();
$fh->lineDown();

// Carrega o partial de contatos
$fh->openCol(12);
$partialObject->partial('contatos/partial-form-contato', $fh, [
    'this' => &$this,
    'entity' => $entity,
    'noContatoField' => TRUE,
    'noContatoList' => TRUE
]);
$fh->closeCol();

$fh->closeLine();

$fh->renderFieldsetIni('Dados de Endereço');
$fh->openCol(12);
$this->partialObj('tcmed')->partial('enderecos/partial-form-all', $fh, ['this' => &$this]);
$fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeCol();
$fh->renderFieldsetFim();
$fh->closeLine()->formEnd();

$fieldsEntity = [
    "cpf" => $cpf,
];
?>
<script lang="javascript">

    function isValid() {
        return true;
    }

    $(function () {
        
        //== MENSAGENS DO SISTEMA ==============================================
        /**
         * @see (PHP) flashMessenger
         * @property {object} messagesGroup Necessário para exibir mensagens 
         * na tela
         */
        var messagesGroup = <?php echo json_encode($messages) ?>;
        /**
         * @event Exibe as mensagens do servidor na view
         */
        $.each(messagesGroup, function (type, messages) {
            $.each(messages, function (_, message) {
                $.notify({
                    "message": message,
                    "type": type
                });
            });
        });
        // ========================================================== FIM ======
    });

</script>
