<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table = $this->table();
$controller = 'histOcupacionals';
$route = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Histórico Ocupacional</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'Data Inicio','Data Fim','Nome Funcionario','Nome Empresa','Nome Adm', 'Ocupacao','Status', 'Ação']);
/* @var $entity \Tcmed\Entity\HistOcupacional */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getDtIni(),
        $entity->getDtFim(),
        $entity->getFuncionario(),
        $entity->getEmpresa(),
        $entity->getAdministradora(),
        $entity->getOcupacao()->getSetor()->getNomeSetor()."/".$entity->getOcupacao()->getCargo(TRUE),
        $entity->getStatus(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    $(function () {

    });
</script>