<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form);
?>
<!-- Modal -->
<div class="modal fade" id="changeData" data-hist="<?php echo $this->fromRote ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Alterar Data</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <?php
                        $fh->setHorizontal(false);
                        $fh->renderAllHidden();
                        $idFuncao = $fh->getIdFor('idHistOcupacional');
                        $fh->openCol('12')->calend('dtFim',[], ["id"=>"dataFim"])->closeCol();
                        $dtFim = $fh->getLastId();
                        $fh->setHorizontal(true)
                        ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default sairModal" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="changeData()" id="incluirFun" class="btn btn-primary">Inserir</button>
            </div>
        </div>
    </div>
</div>
<script>
    function changeData(){
        
        var $modal = $("#changeData");
        
        action.processa({
            url: "<?php echo $this->url('tcmed/default', array('controller' => 'histOcupacionals', 'action' => 'changeData'), [], FALSE, FALSE); ?>",
            type: "POST",
            data:{
                "idHistOcupacional": $modal.attr("data-hist"),
                "dtFim": $("#dataFim").val(),
            },
            callback: function(data){
                $("#table_histOcupacional").html(data); //Exibe retorno na tela
                $(".sairModal").click();
            }
        });
    }
    
</script>