<?php
/* @var $form  Adm\Form\Fornecedor */
/* @var $table \Application\View\Helper\Table */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('adm');
$form       = $this->form;

echo '<h3>', $title, '</h3>';
?>

<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Novo</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>"><i class='fa fa-refresh'></i> Atualiza</button>
</p>


<?php
// $ret        = $form->getValue('ret', '#inter');
// $form->setAttribute('target', $ret);
$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('adm')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));

$fh->formInit();
$fh->openCol(12);
$fh->openCol(4)->closeCol();

$fh->openCol(12);
$table->openTable(TRUE);
$table->setEditLine(0);
$table->setOrderList($this->dataView['orderBy']);
$table->renderThead([
    ['label' => 'Ação'                 ],
    ['label' => 'Nome'                 ],
    ['label' => 'Nome fantasia'        ],
    ['label' => 'Telefone'             ],
    ['label' => 'Celular '             ],
    ['label' => 'Cnpj'                 ],
    ['label' => 'Inscrição estadual'   ],
    ['label' => 'Contato'              ],
    ['label' => 'Home page'            ],
    ['label' => 'Email'                ],
    ['label' => 'Setor'                ],
    ['label' => 'Cadastrado em'        ],
    ['label' => 'Cidade'               ],
    ['label' => 'Status'               ],
    ['label' => 'ID'                   ],
]);
/* @var $entity \Adm\Entity\Fornecedor */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getNomeFornec(),
        $entity->getNomeFantasia(),
        $entity->getTelefone(),
        $entity->getCelular(),
        $entity->getCnpj(),
        $entity->getInscricaoEstadual(),
        $entity->getContato(),
        $entity->getHomePage(),
        $entity->getEmail(),
        $entity->getSetor(),
        $entity->getCreatedAt(),
        $entity->getEndereco('format', ['c']),
        $entity->getStatus(),
        $entity->getId(),
    ]);
}
    $table->renderCloseTable();

$fh->closeCol();
$fh->closeLine();
$fh->formEnd();
echo $this->partial('partials/modal');
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
</center>

<?php 
// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'
); 
?>
<script lang="javascript">
    
    //Função do auto-complete
    function isValid(){
        return true;
    }

    function edit(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key,
        });
        
    }
    function del(key) {
        gModal.reset('confirm',2).setMsg('Deseja mesmo excluir este registro?').setClickOk(function(){
            var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
            $.processa(data);
        }).showModal();
    }
    
</script>
