<h3><?php echo $this->dataView['titulo']; ?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url('app/default',array('controller'=>'appMenus','action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Menus');
    $fh->openCol('12')->text('descricao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('label')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('route')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('controller')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('action')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('atributos')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('icons')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('class')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('pagesContainerClass')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('wrapClass')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('ordem')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('resource')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('privilege')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('inMenu')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    function isValid(){
        return true;
    }
</script>
