<?php
/*
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 * 
 */ 
/* @var $entity \Tcmed\Entity\Cat */
$entity = $this->entity;

if(!$entity){
    echo "['error','Não foi econtrado esse registro'];";
}else{    
    $str = '[';
    $str .= '"' .  $entity->getId() . '"';
    $str .= ',"' . $entity->getIdFuncionario()->getId() . '"';
    $str .= ',"' . $entity->getIdEmpresa()->getId() . '"';
    $str .= ',"' . $entity->getIdAdministradora()->getId() . '"';
    $str .= ',"' . $entity->getIdClinica()->getId() . '"';
    $str .= ',"' . $entity->getIdConsulta()->getId() . '"';
    $str .= ',"' . $entity->getCatNumero() . '"';
    $str .= ',"' . $entity->getDtCat() . '"';
    $str .= ',"' . $entity->getCatObservacao() . '"';
    $str .= ',"' . $entity->getCatAnexo() . '"';
    $str .= '];';
    echo $str;
}