<?php
/** ===========================================================================|
 * FORM - Blocos
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 18-07-2016
 * 
 * IncludeView - v1
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$entity = $this->entity;
$form = $this->form;

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial = $this->partialObj('tcmed');
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

echo '<h3>', $title, '</h3>';
/** ============================================================================
 * Listagem de empresas que compõem o bloco
 */
$fh->openLine();
$fh->openCol(12, ['id' => 'listagem-bloco'])->closeCol();
$fh->closeLine();
// =============================================================================

/** ============================================================================
 * Listagem contendo as empresas para incluí-las no bloco
 */
$fh->openLine();
$fh->openCol(12, ['id' => 'listagem-empresa'])->closeCol();
$fh->closeLine();
// =============================================================================

// Var de transferencia PHP to JS
$transp = array(
    'pagina' => $pagina
);
?>
<br>
<br>
<script lang="javascript">

    function isValid() {
        return true;
    }


    $(function () {
        var transp = <?php echo json_encode($transp) ?>;

        /**
         * Carrega a listagem de empresas que compõem o bloco
         */
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'getEmpresaLista'), [], FALSE, FALSE); ?>",
            savePage: false,
            ret: "#listagem-empresa"
        });
        
        /**
         * Carrega a listagem contendo as empresas para incluí-las no bloco
         */
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'listaNovoBloco'), [], FALSE, FALSE); ?>",
            savePage: false,
            ret: "#lista-novo-bloco"
        });
    });

</script>