<?php
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$entity = $this->entity;
/* @var $form \Agenda\Form\Bloco */
$form = $this->form;
/* @var $table \Application\View\Helper\Table */
$table = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$fh->openCol(12);
$table->openTable(TRUE);
//$lambda = function($value, $data) {
//    echo '<td>value</td>', PHP_EOL;;
//};
//$table->setLambda($lambda);
$table->renderThead(['Seq', 'H. Inicial', 'H. Final', 'Nº Cond.', 'Endereço', 'Per.', 'Cod. Rua', 'Nº Func.', 'T.C', 'T.I', 'Ação']);
/* @var $contato \Tcmed\Entity\Contato */
$table->renderLine([
    '20',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
]);
?>
<tr id="td-edit">
    <td><?php $fh->text('seq', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '05']); ?></td>
    <td><?php $fh->text('horaIni', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <td><?php $fh->text('horaFim', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <?php $fh->setPreFix('empresa'); ?>
    <td><?php $fh->text('referenciaEmp', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <td colspan="2"><?php $fh->text('razaoSocial', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '60']); ?></td>
    <td><?php $fh->text('codigoRua', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '05']); ?></td>
    <td><?php $fh->text('qtdFunc', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <?php $fh->removePreFix(); ?>
    <td><?php $fh->text('tempoC', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <td><?php $fh->text('tempoT', ['noLabel' => TRUE, 'clean'=> FALSE], ['size'=> '06']); ?></td>
    <td>
        <span class="hand salvar-temp"><i class="fa fa-check"></i> Salvar</span>
        <br>
        <span class="hand"><i class="fa fa-ban"></i> Cancelar</span>
    </td>
</tr>
<?php

foreach ($this->data as $entity) {
    $table->renderLine([
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        $entity->getId()
    ]);
}
$table->renderCloseTable();
$fh->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = array(
    "empresasIncluidas" => $fh->getIdFor('empresasIncluidas')
);
?>
<center>
    <strong>Legenda </strong>  
    <span class="label label-success">Cond. Reagendados</span>
    <span class="label label-default">Cond. Improdutivos</span>
    <span class="label label-danger">Cond. Inativos</span>
</center>
<br>
<br>
<br>
<div id="result"></div>
<script type="text/javascript" src="/js/jquery-sortable.js"></script>
<script type="text/javascript">
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        $('#lista-novo-bloco').find('.table').sortable({
            containerSelector: 'table',
            itemPath: '> tbody',
            itemSelector: 'tr',
            placeholder: '<tr class="placeholder"/>'
        });
        
        $('.salvar-temp').click(function(){
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'salvarEmpresaTemp'), [], FALSE, FALSE); ?>",
                type: 'POST',
                callback: function(data){
                    $$(transp.empresasIncluidas).val(data);
                },
                ret: "#result"
            });
        });
    })
</script>