<?php
/** ===========================================================================|
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 18-06-2016
 * @see Agenda\Controller\ProgramacaosController::agendamentoAction()
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$partial = $this->partialObj('tcmed');

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

// Partial do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$table->openTable(TRUE);

$lambda = function($blocoItem, $data) {
    /* @var $blocoItem \Agenda\Entity\BlocoItem */
    
    $idEmpresa = $blocoItem->getEmpresa('id');
    $agendadoEm = $blocoItem->getBloco('agendadoEm');
    
    $quant = $this->quantFunc[$blocoItem->getId()];
    
    echo '<td>';
    echo "<a class='hand get-lista' data-empresa='{$idEmpresa}' data-dtagendamento='{$agendadoEm}'>{$quant}</a>";
    echo '</td>';
};

$table->setLambda($lambda);
$table->setEditLine(FALSE);
$table->renderThead([
    ['label' => "Hold"],
    ['label' => "Administradora"],
    ['label' => "ID Emp"],
    ['label' => "Empresa"],
    ['label' => "Data"],
    ['label' => "Hora"],
    ['label' => "ASO"],
]);
/* @var $bloco \Agenda\Entity\Bloco */
/* @var $blocoItem \Agenda\Entity\BlocoItem */
foreach ($this->entities as $blocoItem) {

    if('ATIVO' != $blocoItem->getEmpresa('status')){
        continue;
    }

    $idDetEmp = 0;
    $quantFuncionarios = 0;

    if(isset($this->relatorios[$blocoItem->getId()])){
        $relatorio = $this->relatorios[$blocoItem->getId()];
        $idDetEmp = $relatorio['id'];
        $quantFuncionarios = $relatorio['quantFuncionarios'];
    }

    $table->renderLine([
        $blocoItem->getEmpresa('administradora', ['hold', ['fantasiaHold']]),
        $blocoItem->getEmpresa('administradora', ['razaoSocial']),
        $blocoItem->getEmpresa('id'),
        $blocoItem->getEmpresa('razaoSocial'),
        $blocoItem->getBloco('agendadoEm'),
        $blocoItem->getHoraIni(),
        "<a class='hand get-lista' data-id='{$idDetEmp}'>{$quantFuncionarios}</a>"
    ]);
}

$table->renderCloseTable();

?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;
        
        $('.get-lista').click(function(){
            var id = $(this).data('id');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'relatorios', 'action' => 'indexAgendamento'), [], FALSE, FALSE); ?>/" + id,
            });
        });
    });
</script>

