<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('application');
/* @var $bloco \Agenda\Entity\Bloco */
$bloco      = $this->bloco;
/* @var $table \Application\View\Helper\Table */
$table = $this->table();


$table->openTable(TRUE);
$table->setEditLine(FALSE);

$table->renderThead([
    ['label' => "cod"      ],
    ['label' => "Nome"     ],
    ['label' => "Periódico"],
    ['label' => "Endereço" ],
    ['label' => "Bairro"   ],
    ['label' => "Cod Rua"  ],
    ['label' => "Qtd Fun"  ],
]);

$qtdFunc = 0;
$qtdEmp  = 0;

/* @var $blocoItem \Agenda\Entity\BlocoItem */
foreach ($bloco->listaBlocoItem() as $blocoItem) {
    $qtdFunc += $blocoItem->getEmpresa('qtdFunc');
    $qtdEmp  += 1;
    
    /*
     * Caso exista algum relatório para a empresa do item, então ele será
     * utilizado para contabilizar o total de reagendados e o total de realizados
     */
    $style = '';
    $relatorio = $blocoItem->getEmpresa("retRelatorioDetEmpBy", [$bloco->getAgendadoEm(TRUE)]);
    if ($relatorio instanceof \Agenda\Entity\RelatorioDetEmp) {
        $relatorio->getReagendar() && $style = 'style="background-color: #5cb85c; color: #fff"';
        $relatorio->getFrustrado() && $style = 'style="background-color: #777; color: #fff"';
    }

    if ("INATIVO" == $blocoItem->getEmpresa('status')) {
        $style = 'style="background-color: #d9534f; color: #fff"';
    }
    
    // Faz com que todas os textos da linha abaixo tenham 12px
    $table->setTdopt([
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    'style="font-size: 12px"',
    ]);
    
    $table->renderLine([
        $blocoItem->getEmpresa('referenciaEmp'),
        $blocoItem->getEmpresa('razaoSocial'),
        $blocoItem->getEmpresa('dtPeriodico'),
        $blocoItem->getEmpresa('endereco', ['format', ['l, n']]),
        $blocoItem->getEmpresa('endereco', ['format', ['b']]),
        $blocoItem->getEmpresa('codigoRua'),
        $blocoItem->getEmpresa('qtdFunc'),
    ], $style);
    
}

// Renderiza a linha com os totais
$table->renderLine([
    "TOTAL",
    $qtdEmp,
    "",
    "",
    "",
    "QTD FUN",
    $qtdFunc,
]);

// Renderiza a linha com as legendas
$table->setTdopt([
    'colspan="7" class="text-center"'
]);
$table->renderLine([
    "<span class='label label-success'>Cond. Reagendados</span> <span class='label label-default'>Cond. Improdutivos</span> <span class='label label-danger'>Cond. Inativos</span>"
]);

$table->renderCloseTable();
