<?php 
/* @var $entity \Tcmed\Entity\Logradouro */
if($this->resultSet){
    $array = [];

    if($this->subOpcao == '' || !isset($this->subOpcao)) {
        $array[] = [
            $this->data['idLogradouro'] => 'ID Logradouro',
            $this->data['nomeLogradouro'] => 'Rua',
            $this->data['cep'] => 'Cep',
            $this->data['tipoLogradouro'] => 'Tipo',
            $this->data['idBairro'] => 'ID Bairro',
            $this->data['nomeBairro'] => 'Bairro',
            $this->data['idCidade'] => 'ID Cidade',
            $this->data['nomeCidade'] => 'Cidade',
            $this->data['estado'] => 'ID Estado',
        ];
        foreach ($this->resultSet as $entity) {
            $array[] = [
                $this->data['idLogradouro'] => $entity->getId(),
                $this->data['nomeLogradouro'] => $entity->getNomeLogradouro(),
                $this->data['cep'] => $entity->getCep(),
                $this->data['tipoLogradouro'] => $entity->getTipoLogradouro()->getTipo(),
                $this->data['idBairro'] => $entity->getBairro()->getIdBairro(),
                $this->data['nomeBairro'] => $entity->getBairro()->getNomeBairro(),
                $this->data['idCidade'] => $entity->getBairro()->getCidade()->getIdCidade(),
                $this->data['nomeCidade'] => $entity->getBairro()->getCidade()->getNomeCidade(),
                $this->data['estado'] => $entity->getBairro()->getCidade()->getEstado()->getNomeEstado(),
            ];
        }
    }

    echo json_encode($array);
}else{
    echo '{}';
}
