<?php
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 19-10-2016
 * 
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$ajax = $this->dataView['ajax'];
$partial = $this->partialObj('application');
$form = $this->form;

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);
$partialTcmed = $this->partialObj('tcmed');


/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, $ajax));

$fh->openLine();

$fh->openCol(9);
echo "<h3>{$title}</h3>";
$fh->closeCol();

$fh->openCol(3);
$fh->buildButton(["id" => "voltaPagina", "class" => "pull-right"], "<i class='fa fa-arrow-left'></i> voltar", "primary", TRUE);
$fh->closeCol();

$fh->closeLine();

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$fh->openCol(12);
$partialTcmed->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'rules' => $rules, 'hideCnpj' => TRUE]);
$fh->closeCol();

$fh->lineDown();

$fh->setPreFix('medico');
$idMedico = $fh->getIdFor('idMedico');
$fh->openCol(9, 3)->text('nomeMedico', [
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    'dt-clear' => $idMedico,
])->closeCol();
$nomeMedico = $fh->getLastId();

$fh->removePreFix('medico');

$fh->openCol(3, 3)->calend('data')->closeCol();
$agendadoEm = $fh->getLastId();

$fh->openCol(2)->text('hora', ['mask' => '99:99'])->closeCol();

$fh->lineDown();

$fh->lineDown();

$fh->openCol(2, 1);
$fh->buildButton(["id" => "pesquisaBlocos", "class" => "btn-block"], "Pesquisar", "primary", TRUE);
$fh->closeCol();

$fh->openCol(2, 6);
$fh->buildButton(["id" => "add", "class" => "btn-block"], "Adicionar", "primary", TRUE);
$fh->closeCol();

$fh->jumpLine(2);

$fh->openCol(12, ['id' => 'lista-blocos-programacao'])->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

$fields = array(
    'nomeMedico' => $nomeMedico,
    'idMedico' => $idMedico,
);
?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;

        $('#pesquisaBlocos').click(function () {
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => 'blocos', 'action' => 'listaBlocosAgend'), [], FALSE, FALSE); ?>",
                ret: "#lista-blocos-programacao",
                savePage: false
            });
        });

        $('#pesquisaBlocos').click();

        $$(fields.nomeMedico).auto({
            primary: "nomeMedico",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'medicos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            width: 800,
            filters: function (data) {
                data.rules = {
                    "status": "EXTERNO"
                };
                return data;
            },
            responseTo: {
                "idMedico": [fields.idMedico],
            },
            showCols: ["nomeMedico"]
        });
    });
</script>