<?php
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 19-10-2016
 * 
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$ajax = $this->dataView['ajax'];
$partial = $this->partialObj('application');
$partialTcmed = $this->partialObj('application');
$form = $this->form;

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);


/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, $ajax));

$fh->openLine();

$fh->openCol(12);
echo "<h3 class='text-center'>{$title}</h3>";
$fh->closeCol();

$fh->closeLine();

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$fh->setPreFix('administradora');
$idAdministradora  = $fh->getIdFor('idAdministradora');
$fantasiaHold      = $fh->getIdFor('hold');
$referenciaSubHold = $fh->getIdFor('referenciaSubhold');
$razaoSocialAdm    = $fh->getIdFor('razaoSocial');

$fh->openCol(6, 3)->select('hold', [
    "dt-clear" => $razaoSocialAdm . "," . $idAdministradora . "," . $referenciaSubHold, 
])->closeCol();

$fh->lineDown();

$fh->openCol(2, 3)->number('referenciaSubhold', [
    "dt-clear" => $razaoSocialAdm . "," . $idAdministradora, 
])->closeCol();

$fh->openCol(4)->text('razaoSocial', [
    "dt-clear" => $referenciaSubHold . "," . $idAdministradora, 
    "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
])->closeCol();

$fh->removePreFix('administradora');

$fh->lineDown();

$fh->setPreFix('medico');
$idMedico = $fh->getIdFor('idMedico');
$fh->openCol(6, 3)->text('nomeMedico', [
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    'dt-clear' => $idMedico,
])->closeCol();
$nomeMedico = $fh->getLastId();

$fh->removePreFix('medico');

$fh->lineDown();

$fh->openCol(2, 3)->text('inicioHoraTarde', ['mask'=>'99:99'])->closeCol();
$fh->openCol(2)->checkbox('horarioManha', ['position' => 'right'])->closeCol();
$fh->openCol(2)->checkbox('horarioTarde', ['position' => 'right'])->closeCol();

$fh->lineDown();

$fh->openCol(3, 3)->calend('dataInicio')->closeCol();
$fh->openCol(3)->calend('dataFim')->closeCol();

$fh->jumpLine(2);

$fh->openCol(2, 3);
$fh->buildButton(["id" => "voltaPagina", "class" => "btn-block"], "<i class='fa fa-arrow-left'></i> voltar", "primary", TRUE);
$fh->closeCol();

$fh->openCol(2);
$fh->buildButton(["id" => "gerarLista", "class" => "btn-block"], "Gerar Lista", "success", TRUE);
$fh->closeCol();

$fh->openCol(2);
$fh->buildButton(["id" => "gerarCarta", "class" => "btn-block"], "Gerar Carta", "primary", TRUE);
$fh->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

$fields = array(
    'fantasiaHold' => $fantasiaHold,
    'razaoSocialAdm' => $razaoSocialAdm,
    'referenciaSubhold' => $referenciaSubHold,
    'idAdministradora' => $idAdministradora,
    'nomeMedico' => $nomeMedico,
    'idMedico' => $idMedico
);
?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;

        $('#gerarCarta').click(function () {
            if("" == $$(fields.referenciaSubhold).val()){
                $.notify({
                    message: "Escolha uma subhold antes!",
                    type: 'danger'
                });
                return false;
            }
            
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'carta'), [], FALSE, FALSE); ?>",
            });
        });
        
        $('#gerarLista').click(function () {
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'getPdfLista'), [], FALSE, FALSE); ?>",
            });
        });
        
        $("#voltaPagina").click(function(){
            $("#godown").click();
        });

        function getFantasiaHold() {
            var fantasiaHold = $$(fields.fantasiaHold);
            return (fantasiaHold.find("option:selected").val()
                    == fantasiaHold.find("option:first").val()) ?
                    "" : fantasiaHold.find("option:selected").text();
        }
        
        /* AUTOCOMPLETE: Administradora */
        $$(fields.referenciaSubhold).auto({
            primary: "referenciaSubhold",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'administradoras', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            width: 800,
            filters: function (query) {
                query["fantasiaHold"] = $$(fields.fantasiaHold).val();
            },
            responseTo: {
                "idAdministradora": [fields.idAdministradora],
                "razaoSocialAdm": [fields.razaoSocialAdm],
                "fantasiaHold": [fields.fantasiaHold]
            },
            showCols: ["referenciaSubhold", "razaoSocialAdm"]
        });

        /* AUTOCOMPLETE: Administradora */
        $$(fields.razaoSocialAdm).auto({
            primary: "razaoSocial",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'administradoras', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            width: 800,
            filters: function (query) {
                query["fantasiaHold"] = $$(fields.fantasiaHold).find("option:selected").val();
            },
            responseTo: {
                "razaoSocialAdm": [fields.razaoSocialAdm],
                "referenciaSubhold": [fields.referenciaSubhold],
                "idAdministradora": [fields.idAdministradora],
                "fantasiaHold": [fields.fantasiaHold],
            },
            showCols: ["referenciaSubhold", "razaoSocialAdm", "fantasiaHold"]
        });
        
        $$(fields.nomeMedico).auto({
            primary: "nomeMedico",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'medicos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            width: 800,
            filters: function (data) {
                data.rules = {
                    "status": "EXTERNO"
                };
                return data;
            },
            responseTo: {
                "idMedico": [fields.idMedico],
            },
            showCols: ["nomeMedico"]
        });
        
        

//        
    });
</script>