<style type="text/css">
    /* =========================================================================
    * CSS Bootstrap table simulation
    * @TODO tabelabootstrap
    */
    * {
        margin: 0;
        padding: 0;
    }

    .table{
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        color: #333;
        font-size: 10px;
    }

    .table tr, 
    .table td, 
    .table th {
        border: 1px solid #ccc;
    }

    .table thead tr {
        border-bottom: 2px solid #ddd;
    }

    .table thead th {
        background-color: #eee;
        font-size: 14px;
    }

    .table td{
        padding-left: 5px;
        padding-right: 5px;
    }

    .table-striped tr:nth-child(even) {
        background: #f9f9f9
    }

    .text-right {
        text-align: right;
    }

    .text-center {
        text-align: center;
    }

    .pdf-view{
        width: 270mm;
        padding: 10px;
    }

    /* ====================================================================== */

    .doutor{
        font: bold 16px verdana, "Arial black", Helvetica, sans-serif;
    }

    #listagem p {
        padding: 0px;
        margin: 0px;
    }

    .t2{
        font: bold 14px verdana, "Arial black", Helvetica, sans-serif;
    }

    .col-emp{
        font: normal 10px Arial, Helvetica, sans-serif;
    }

</style>

<div class='pdf-view'>
    <?php
    $dtm           = new \DateTime('now');
    $month         = $params($dtm->format('m'), "nome_mes");
    $dataFormatada = "São Paulo, {$dtm->format('d')} de {$month} de {$dtm->format('Y')}";
    $imageHold     = "{$params('all','vilaVelhaDir')}logoVilaVelha.png";
    
    echo <<<TOPO
        <table id='topo' style="width: 100%;">
            <tbody>
                <tr>
                    <td style='width: 165px'><img width="243px" src="{$imageHold}"></td>
                    
                    <td id="topo-descr">
                        <h2>{$dataView['titulo']}</h2> 
                        {$dataFormatada}
                    </td>
                </tr>
            </tbody>
        </table>
        <hr>
        <p class='text-center'>Segue abaixo relacionadas, as respectivas programações domiciliares (PCMSO) para encaminhamento junto aos Condomínios.</p>
TOPO;

    echo '<div id="listagem">';

    $contLine = 28;

    foreach ($entities as $blocoItem) {

        $nomeMedico    = $blocoItem->getBloco('medico', ['nomeMedico']);
        $agendadoEm    = $blocoItem->getBloco('agendadoEm');
        $horaInicio    = $blocoItem->getHoraIni();
        $razaoSocial   = $blocoItem->getEmpresa('razaoSocial');
        $enderecoEmp   = $blocoItem->getEmpresa('endereco', ['exibeEnderecoSimples']);
        $referenciaEmp = $blocoItem->getEmpresa('referenciaEmp');
        /* @var $bloco Agenda\Entity\Bloco */
        $bloco         = $blocoItem->getBloco();

        $listaHMD      = $bloco->listHorarioMedicoDia();

        /* @var $horaMedDia Agenda\Entity\HorarioMedicoDia */
        foreach ($listaHMD as $horaMedDia) {
            $agendadoEm        = $horaMedDia->getDateHoramed();
            $horaInicio        = $blocoItem->getHoraIni();
            $razaoSocialAdm    = $blocoItem->getEmpresa('administradora', ['razaoSocial']);
            $referenciaSubhold = $blocoItem->getEmpresa('administradora', ['referenciaSubhold']);
            $showDate          = FALSE;
            
            if ($bloco->getManyDays()) {
                $horaInicio = $horaMedDia->getIni();
            }

            if ($ultimaAdm != $razaoSocialAdm) {
                if (0 > $contLine) {
                    echo "<div style='page-break-before: always;'></div>";
                    $contLine =39;
                }

                echo "<br><p>{$razaoSocialAdm} Cod.: {$referenciaSubhold}</p>";
                echo "<p class='t2'>Dr(a). {$nomeMedico}</p>";
                
                $ultimoMedico = $nomeMedico;
                $ultimaAdm    = $razaoSocialAdm;
                $contLine    -= 2;
                $showDate     = TRUE;
            }

            if ($ultimoMedico != $nomeMedico) {
                echo "<p class='t2'>Dr(a). {$nomeMedico}</p>";
                $ultimoMedico = $nomeMedico;
                $contLine--;
                $showDate     = TRUE;
            }

            if ($ultimaData != $agendadoEm) {
                $showDate     = TRUE;
            }
            
            if($showDate) {
                echo "<p class='t2'>No dia {$agendadoEm}</p>";
                $ultimaData = $agendadoEm;
                $contLine--;
            }

            echo "<table width='100%' style='padding-left: 20px'><tr>"
            . "<td class='col-emp' width='60%'>{$horaInicio} hs &nbsp;&nbsp;&nbsp; {$razaoSocial} ($referenciaEmp)</td>"
            . "<td class='col-emp' width='40%'> {$enderecoEmp}</td>"
            . "</tr></table>";
            $contLine--;
        }
    }
    echo '</div>';
    ?>
</div>
