<?php
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 
 * 
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$partial = $this->partialObj('application');

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

list($date, $time) = explode(';', (new \DateTime('now'))->format('d/m/Y;H:i'));

echo <<<EOF
    <div class='row'>
        <div class='col-md-3'>
            <img src="/img/logo_tecnomed.png" style="width: 260px;">
        </div>  
        <div class='col-md-9'>
            <h3>{$title}</h3>
            <h4><b>Hora: </b>{$time} <b>Data: </b>{$date}</h4>
        </div>
    </div>
    <br>
    <hr>
    <div class='row'>
        <div class='col-md-12'>
            <div class='col-md-2'>
                <button class='voltar btn btn-primary btn-block'><i class='fa fa-arrow-left'></i> Voltar Agenda</button>
            </div>
            <div class='col-md-2 col-md-offset-8'>
                <button class='imprimir btn btn-primary btn-block'><i class='fa fa-print'></i> Imprimir lista</button>
            </div>
        </div>
    </div>
    <br>
EOF;

$table->openTable(TRUE);
$table->setEditLine(FALSE);
//$lambda = function($value, $data) {
//    echo '<td>value</td>', PHP_EOL;;
//};
//$table->setLambda($lambda);
$table->renderThead([
    ['label' => 'Hora'],
    ['label' => 'Cod'],
    ['label' => 'Administradora'],
    ['label' => 'Empresa'],
    ['label' => 'Endereço'],
    ['label' => 'Bairro'],
    ['label' => 'Ref'],
    ['label' => 'Qtd'],
    ['label' => 'rea'],
]);

$lastAgendadoEm = '';

$contadorEmpresa = 0;
$contadorFuncionario = 0;

/* @var $entity \Agenda\Entity\Bloco */
foreach ($this->data as $entity) {

    $aux = $entity->getAgendadoEm();
    if ($aux != $lastAgendadoEm) {
        echo "<tr style='background-color: #ccc'><td></td><td colspan='9'><b>{$aux}</b></td></tr>";
        $lastAgendadoEm = $aux;
    }

    /* @var $blocoItem Agenda\Entity\BlocoItem */
    foreach ($entity->listaBlocoItem() as $blocoItem) {
        $table->renderLine([
            $blocoItem->getHoraIni(),
            $blocoItem->getEmpresa('referenciaEmp'),
            substr($blocoItem->getEmpresa('administradora', ['razaoSocial']), 0, 13),
            $blocoItem->getEmpresa('razaoSocial'),
            $blocoItem->getEmpresa('endereco', ['exibeEnderecoSimples']),
            $blocoItem->getEmpresa('endereco', ['logradouro', ['bairro', ['nomeBairro']]]),
            $blocoItem->getEmpresa('codigoRua'),
            $blocoItem->getQtdFunItem(),
            '',
        ]);

        $contadorFuncionario += $blocoItem->getQtdFunItem();
        $contadorEmpresa++;
    }
}
echo "<tr  style='background-color: #bbb;'>";
echo "<td colspan='3' class='text-right'><strong>Total de Empresas</strong></td>";
echo "<td><strong>{$contadorEmpresa}</strong></td>";
echo "<td colspan='2' class='text-right'><strong>Total de Funcionarios</strong></td>";
echo "<td colspan='2'><strong>{$contadorFuncionario}</strong></td>";
echo "<td></td>";
echo "</tr>";

$table->renderCloseTable();

echo <<<EOF
    <br>
    <div class='row'>
        <div class='col-md-12'>
            <div class='col-md-2'>
                <button class='voltar btn btn-primary btn-block'><i class='fa fa-arrow-left'></i> Voltar Agenda</button>
            </div>
            <div class='col-md-2 col-md-offset-8'>
                <button class='imprimir btn btn-primary btn-block'><i class='fa fa-print'></i> Imprimir lista</button>
            </div>
        </div>
    </div>
EOF;

// Var de transferencia PHP to JS
$transp = array(
);
?>
<br>
<br>

<iframe id='iframeAso' height="0" frameborder='0'></iframe>

<script type="text/javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;

        $('.voltar').click(function () {
            $('#godown').click();
        });

        $('.imprimir').click(function () {
            $('#iframeAso').attr('src', "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE) ?>");
        });
    });
</script>

