<?php
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 19-10-2016
 * 
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$ajax = $this->dataView['ajax'];
$partial = $this->partialObj('application');
$form = $this->form;

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);


/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, $ajax));

$fh->openLine();

$fh->openCol(12);
echo "<h3 class='text-center'>{$title}</h3>";
$fh->closeCol();

$fh->jumpLine(2);


$fh->closeLine();

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$fh->setPreFix('medico');
$idMedico = $fh->getIdFor('idMedico');

$fh->openCol(6, 3)->text('nomeMedico', [
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    "dt-clear" => $idMedico
])->closeCol();

$nomeMedico = $fh->getLastId();
$fh->removePreFix('medico');

$fh->lineDown();
$fh->openCol(3, 3)->calend('dataInicio')->closeCol();
$fh->openCol(3)->calend('dataFim')->closeCol();

$fh->jumpLine(2);

$fh->openCol(2, 3);
$fh->buildButton(["id" => "voltaPagina", "class" => "btn-block"], "<i class='fa fa-arrow-left'></i> voltar", "primary", TRUE);
$fh->closeCol();

$fh->openCol(2, 2);
$fh->buildButton(["id" => "gerarRelatorio", "class" => "btn-block"], "Gerar Relatório <i class='fa fa-file-pdf-o'></i>", "success", TRUE);
$fh->closeCol();
//
$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

$fields = array(
    'nomeMedico' => $nomeMedico,
    'idMedico' => $idMedico
);
?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;

        $$(fields.nomeMedico).auto({
            primary: "nomeMedico",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'medicos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            filters: function (data) {
                data.rules = {
                    "status": "EXTERNO"
                };
                return data;
            },
            responseTo: {
                "idMedico": [fields.idMedico],
            },
            showCols: ["nomeMedico"]
        });

        $('#gerarRelatorio').click(function () {
            if ("" == $$(fields.idMedico).val()) {
                $.notify({
                    message: "Selecione um Médico!!",
                    type: "danger"
                });
                return false;
            }

            $(this).closest('form').processa({
                url: "<?php echo $this->url('agenda/default', array('controller' => $controller, 'action' => 'listaBlocoRelatorio'), [], FALSE, FALSE); ?>"
            });
        });
        
        $("#voltaPagina").click(function(){
            $("#godown").click();
        });
    });
</script>