<html>
    <head>
    </head>
  <body>
<?
/* @var $agenda \Tcmed\Entity\AgendaAmbul */ 
        $hold = $agenda->getFuncionario('referenciaHold');
        switch ($hold) {
            case '1':
            case '5':
            case '6':
            case '7':
                $holdPartial = 'get-pdf-partial-aso-vv-manual';
                break;
            case '2':
            case '4':
                $holdPartial = 'get-pdf-partial-aso-tc-manual';
                break;

            default:
                $holdPartial = $hold;
                break;
        }
        include $this->partial('get-pdf-partial-aso-vv-manual-css'); 
?>
<div class='folha'>

<? 
 
        $via = 'da Empresa';
        include $this->partial($holdPartial); 

        // Se a folha for paisagem imprime o tracejado para corte
        if($this->orientation === 'L'){
            include $this->partial('get-pdf-partial-aso-sep'); 
        }

        $via = 'do Funcionario';
        include $this->partial($holdPartial); 

?>
    
</div>
   

  </body>
</html>