<? 
/* @var $consulta \Tcmed\Entity\Consulta */ 
?>	
        <div class='aso'>
		<div class='topot1'>
			ASO - ATESTADO DE SAÚDE OCUPACIONAL<br />
			<? echo $consulta->getEmpresa('razaoSocial');?> (<? echo $consulta->getEmpresa('referenciaEmp');?>)<br /> 
                        <span class='meio2t2'><?= $consulta->getEmpresa('endereco');?></span>
		</div>
		<div class='topo'>
                    <?
                    $pathLogo = $param('all','asoDirImage') . 'tcmed3.jpg'; 
                    if(file_exists($pathLogo)):
                    ?>
			<img src="<? echo $pathLogo; ?>" class='topologo'>
                    <?
                    endif;
                    ?>
			Site: www.tcmed.com.br<br />
			E-mail: tc.med@tcmed.com.br<br />
			TECNO MED ASS E SERV TÉC. EM MED. LTDA<br />
			<span class='meio2t2'>
			Rua Cincinato Braga,59 3 Andar Cj 3D1 Tel: 3266-5850 - São Paulo - SP
			</span>
		</div>
            
		<div class='meio1'>
			Em cumprimento ao Programa de Controle Médico de Saúde Ocupacional (PCMSO) - 
			NR7 - da portaria 3.217/78 do Ministerio do trabalho.<br />
			Atesta que o Sr(a) 
                        <span class='meio1t1'>
                        <? echo $consulta->getFuncionario()->getNomeFuncionario(); ?>
                        </span><br />
			Idade de
                        <? echo $consulta->getIdadeAnos(); ?>
                        Anos e 
                        <? echo $consulta->getIdadeMeses(); ?> 
                        meses portador do RG: <span class='meio1t1'>
                        <? echo $consulta->getFuncionario()->getRg();  ?> 
                        </span> CPF: <span class='meio1t1'>
                        <? echo $consulta->getFuncionario()->getCpf();  ?> 
                        </span><br />
			<br /> 
                        <? 
                            if($consulta->getTipo() == 'MDF' AND $consulta->getGuia() AND $consulta->getGuia()->getOcupacao()){
                                echo "Cargo Anterior:	<span class='meio1t1'>", $consulta->getGuia()->getOcupacao()->getCargo(TRUE), '</span><br />';
                                echo "Setor Anterior:	<span class='meio1t1'>", $consulta->getGuia()->getOcupacao()->getSetor() , '</span><br />';
                            }
                        ?>
			Cargo:	<span class='meio1t1'>
                        <? echo $consulta->getHistOcupacional()->getOcupacao()->getCargo(TRUE);  ?> 
                        </span>
                        <br />
			Setor:	<span class='meio1t1'>
                        <? echo $consulta->getHistOcupacional()->getOcupacao()->getSetor();  ?> 
                        </span>
                        <br />
			Data da Consulta <span class='meio1t1'>
                        <? echo $consulta->getDtConsulta();  ?> 
                        </span> as 
                        <? echo $consulta->getCreatedAt('H:i');  ?> 
                        horas<br />
			<br /> 
			Exame médico:	<span class='meio1t1'>
                        <? echo $param($consulta->getTipo(), "FC_tipo_exame");  ?> 
                        </span><br />
			Foi considerado:	<span class='meio1t1'>
                        <? echo $param($consulta->getResultado(), "FC_Resultado");  ?> 
                        </span><br />
                        
                        <?
                        /* @var $exameCompl  \Tcmed\Entity\ConsultaExameCompl */
                        $exameCompls = $consulta->listExameCompls();
                        if($exameCompls AND count($exameCompls) > 0){
                            echo '<table><tr><td class="meio2t2">Exame Complementar</td><td class="meio2t2">';
                            foreach ($exameCompls as $exameCompl) {
                                echo $exameCompl->getExameCompl() . '<br>';
                            }
                            echo '</td></tr></table><br />';
                        }
                        ?>                       
                        
			Atestado Valido:	<span class='meio1t1'>
                        <? echo $param($consulta->getValidade(),'FC_validade');  ?> 
                        </span><br />
			Riscos da função:	<span class='meio1t1'>
                        <?
                            $riscos = "Ausência de Riscos Ocupacionais Específicos";
                            foreach ($consulta->getHistOcupacional()->getOcupacao()->listOfCargoRiscos() as $key => $ent) {
                                if ($key === 0) {
                                    $riscos = $ent->getRisco()->getRisco() ;
                                }else{
                                    $riscos .= ',' . $ent->getRisco()->getRisco() ;
                                }
                            }                        
                            echo $riscos;
                        ?>                             
                        </span><br />
			Obs. ASO:<span class='meio2t2'>
                        <? echo $consulta->getObservacaoFinal();  ?>                             
                        </span>		
		</div>
		<div class='meio2'>	
                    <?
                    $pathAssinatura = $param('all','medicoDirAss') . $consulta->getMedico('assinatura'); 
                    if(!file_exists($pathAssinatura)){
                        $pathAssinatura = $param('all','medicoDirAss') . 'demis.jpg';
                    }                    
                    ?>
			<img src="<? echo $pathAssinatura; ?>" class='meio2ass' alt='Assinatura do Medico'><br />
			Médico Examinador:<span class='meio2t1'>
                        <? echo $consulta->getMedico();  ?>                             
                            CRM:
                        <? echo $consulta->getMedico()->getCrm();  ?>                             
                        </span><br />
			<span class='meio2t2'>Assinatura atestada por semelhança conforme Carteira Profissional do CRM de São Paulo<br /></span>
                        <span class='meio2t2'>
                        <? 
                            if(!is_null($consulta->getClinica())){
                                echo "Exame realizado na Clinica: " . $consulta->getClinica()->getRazaoSocial() . "<br />"; 
                                echo "Endereço: " . $consulta->getClinica()->getEndereco()->__toString() ; 
                            }
                        ?>
                        </span>
		</div>
		<div class='meio2'>			
			Médico Coordenador: <span class='meio2t1'>
                            ARTHUR MOREIRA RICCA CRM-31332
                        </span><br />		
		</div>
		<div class='rodape'>
			Assumo inteira responsabilidade pelas informações prestadas durante esta consulta 
			médica- ocupacional, declarando que não omiti nenhum dado relevante, relativo a 
			minha saúde, que possa interessar ou alterar o meu diagnóstico.<br />
			Recebi a 2 via do ASO em <? echo date('d/m/Y'); ?>.
                        <br />
			<br /> 
			Ass. do Funcionário:__________________________________________.<br />
                        <div class='rodapet1'>Via <? echo $via, ' ', $consulta->getId(), '/', $consulta->getDtConsulta('Y'); 
                        $codBarra = $consulta->getDtConsulta('Ymd') . $consulta->getEmpresa('referenciaEmp') . $consulta->getFuncionario('referenciaFun');
                        ?>
                        <barcode code="<?= $codBarra;?>" type="C128A" size="0.9" height="0.5" text="<?= $codBarra;?>"/>
                        <?= $codBarra;?>
                        </div>
		</div>
	</div>