
<STYLE>
body {
	margin       : 0px;
	padding      : 0px;	
}
.folha{
        width        : 280mm;
	height       : 190mm;
	border       : #000 solid 0px;
	margin       : 0px;
	padding      : 0px;
}
.aso{	
        width        : 130mm;
	height       : 190mm;
	border       : #000 solid 1px;
	margin       : 0px;
	padding      : 0px;
        float        : left;
	position     : relative;
	border-radius: 1em;
}
.divisao{
    width        : 18mm;
	height       : 190mm;
	border       : #000 solid 0px;
	margin       : 0px;
	padding      : 0px;	
	float: left;
	position: relative;
}
.tracejado{
	width        : 50%;	
	height       : 190mm;
	border-right : #000 dashed 1px;
}
.topo, .meio1, .meio2, .rodape{
	font-size     : 9pt ;
	border-bottom : #000 solid 1px;
}
.topologo{
	float:left;	
	margin-top    : 10px;
	margin-bottom : 10px;
}
.topot1{
	font-size     : 10pt ;
	font-weight   : bold; 
	text-align    : center ;
	border-bottom : #000 solid 1px;
}
.topot2{
	font-size     : 12pt ;
	font-weight   : bold;
	color         : red; 
}
.meio1t1, .meio2t1, .rodapet1{
	font-weight   : bold; 
}
.meio2t2{
	font-size     : 7pt ;
	font-weight   : normal; 
}
.meio2ass{
	margin-left   : 80px; 
	width : 330px; 
	height: 60px;
}
.rodape{
	border-bottom : #000 solid 0px;	
}
.rodapet1{
	text-align   : center; 
} 
.esconde{
	display:none;
}
.exatit{	
	position     : relative;
	float        : left; 
	height: 60px;
}
.exaDad{	
	position     : relative;
	float        : left;
	font-size     : 7pt ;
}
.clean{
	margin       : 0px;
	padding      : 0px;
	border       : #000 solid 0px;
}
</STYLE>  