<?php
/* 
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 * 
 */ 

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
/* @var $table \Application\View\Helper\Table */
/* @var $param \Application\View\Helper\Param */
$table = $this->table();
$param = $this->Param();
?>
<?php
$table->openTable(TRUE);
$table->renderThead([
    'Realizado', 
    'Empresa', 
    'Medico', 
    'T. Consulta', 
    'Diagnosticos', 
    'alterado/normal', 
    'Coclusão', 
    'Ação'
]);
/**@autor Danilo Dorotheu <danilo.dorotheu@live.com> */
$lambda = function ($value,$data){
    echo "\t<td nowrap>",
            '<span class="hand" onClick="showProntuario(\'', $value, '\',this)" title="Exibir o prontuario desta consulta"><i class="fa fa-file-text"></i> </span>',
         "</td>", PHP_EOL;  
};
$table->setLambda($lambda);

$table->setLambda($lambda);
/* @var $entity \Tcmed\Entity\Consulta */
/* @var $cid \Tcmed\Entity\Cid */
foreach ($this->data as $entity) {
    $showCids = '<ul>';
    foreach ($entity->listCid() as $cid) {
        $showCids .= '<li>'.  $cid->getNumeroCid() .  '</li>';
    }
    $showCids .= '</ul>';
    $table->renderLine([
        $entity->getDtConsulta(),
        $entity->getEmpresa()->getRazaoSocial(),
        $entity->getMedico()->getNomeMedico(),
        $entity->getTipo(),
        $showCids,
        $param($entity->getNormal(), 'FC_normal'),
        $param($entity->getResultado(), 'FC_Resultado'),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />
<br />
<script lang="javascritp">   
    
    var showProntuario = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => 'consultas', 'action' => 'showPdf'), [], FALSE, FALSE); ?>" + "/" + key,
        });
    };
    
</script>
