<iframe id="iframeAso" width='100%' height='500' frameborder='0' src='<?php echo $this->url('tcmed/default', $this->route, [], FALSE, FALSE); ?>'></iframe>
<?php
/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();
?>
<script lang="javascript">      
    $(function(){
        /**
         * Alterar a altura para visualização do aso
         */
        $('#iframeAso').height($(document).height() * 0.89);
//== MENSAGENS DO SISTEMA ==============================================
        /**
         * @see (PHP) flashMessenger
         * @property {object} messagesGroup Necessário para exibir mensagens 
         * na tela
         */
        var messagesGroup = <?php echo json_encode($messages) ?>;
        /**
         * @event Exibe as mensagens do servidor na view
         */
        $.each(messagesGroup, function (type, messages) {
            $.each(messages, function (_, message) {
                $.notify({
                    "message": message,
                    "type": type
                });
            });
        });
// ========================================================== FIM ======s        
    });
</script>