<h3><?php
    echo $this->dataView['titulo'];
    $controller = 'funcaoApelidos';
    $route = 'tcmed/default';
    ?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro de Apelido de Funções');
$fh->setPreFix('funcao');
$idFuncao = $fh->getIdFor('idFuncao');
$fh->openCol('12')->text('funcao', ['dt-clear' => $idFuncao])->closeCol();
$funcao = $fh->getLastId();
$fh->lineDown()->removePreFix();
$fh->openCol('12')->text('apelido')->closeCol();
$fh->closeLine();
$partialObject = $this->partialObj('tcmed');
$partialObject->partial('descricao-funcaos/partial-form', $fh, ['this' => &$this]);
$descricao = $fh->getLastId();
$fh->openLine();
$fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
$fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
$fieldsFuncaoApelidos = [
    "funcao" => $funcao,
    "idFuncao" => $idFuncao,
];

$fieldsFuncaoApelidos = array_merge($partialObject->fieldsDescricaoFuncao, $fieldsFuncaoApelidos);
?>

<script lang="javascript">

    function isValid() {
        return true;
    }
    
    $(function () {
        var fields = <?php echo json_encode($fieldsFuncaoApelidos) ?>;
        console.log(fields.funcao);
        
        $$(fields.funcao).auto({
            primary: "funcao",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'Funcaos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            filters: function (query) {
                query["rules"] = {"status": "ativo"};
            },
            callback: function (data) {
                $$(fields.descricao).val(data["descricao"])
                $$(fields.idFuncao).val(data["idFuncao"])
            },
            params: {
                subOpcao: "simple"
            },
            showCols: ["funcao", "descricao"]
        });
    });

</script>
