<?php
/* @var $table \Application\View\Helper\Table */
/* @var $fh    \Application\View\Helper\FormHelp */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
/* @var $alerta \Tcmed\Entity\Alerta */
$alerta     = $this->alerta;

if($alerta){
    $resul = $alerta->toArrayNew();
    $resul['status'] = 'ok';
}else{
    $resul['status'] = 'ng';
    $resul['error'] = 'Não encontrado o registro com id ' . $this->id;
}

echo json_encode($resul);
