<?php
/* @var $table \Application\View\Helper\Table */
/* @var $fh    \Application\View\Helper\FormHelp */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$table = $this->table();
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');

// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

?>
<h3 class=""><?php echo $this->dataView['titulo']; ?></h3>
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Limpar</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<br />
<?php
$fh->formInit();
        // === DADOS DO EMPRESA  ====================================================
        $fh->openCol(12)->setPreFix('alerta');
            $partial->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'cpfAllow' => FALSE]);
        $fh->closeCol();    
    $fh->lineDown();
        $fh->setPreFix('funcionario');
        
            $idFuncionario = $fh->getIdFor('idFuncionario');
            
            $fh->openCol(3)->number('referenciaFun')->closeCol();
            $referenciaFun = $fh->getLastId();
            
            $fh->openCol(9)->text('nomeFuncionario', ["extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]])->closeCol();
            $nomeFuncionario = $fh->getLastId();
        
        $fh->removePreFix('funcionario');
    $fh->lineDown();
        $fh->openCol(12)->submit('submit',0,['value' => 'Pesquisar'])->closeCol();
    $fh->lineDown();
        $fh->openCol(12);
        $fh->setPreFix('alerta');
            $table->openTable(TRUE);
            $table->setEditLine('first');
            $table->setOrderList($this->dataView['orderBy']);
            $table->renderThead([
                'Ação'
                ,['label' => 'Funcionario'       , 'order' => 'f.nomeFuncionario']
                ,['label' => 'Empresa'           , 'order' => 'em.razaoSocial']
                ,['label' => 'Administradora'    , 'order' => 'a.razaoSocial']
                ,['label' => 'Data'              , 'order' => 'createdAt']
                ,['label' => 'Valido Até'        , 'order' => 'valido']
                ,'Descrição' 
                ]);
            /* @var $entity \Tcmed\Entity\Alerta */
            foreach ($this->data as $entity) {
                $table->renderLine([
                    $entity->getId(),
                    $entity->getFuncionario('nomeFuncionario'),
                    $entity->getEmpresa('razaoSocial'),
                    $entity->getAdministradora('razaoSocial'),
                    $entity->getCreatedAt('full'),
                    $entity->getValido(),
                    $entity->getDescricao(),
                ]);
            }
            $table->renderCloseTable();
        $fh->closeCol();
    $fh->closeLine();
$fh->formEnd();
// === TRANSPORTE ==============================================================
$fields = array_merge(
        $partial->fieldsEmpresa, 
        [
            "idFuncionario" => $idFuncionario,
            "nomeFuncionario" => $nomeFuncionario,
            "referenciaFun" => $referenciaFun,
//            "fantasiaClinica" => $fantasiaClinica,
//            "idClinica" => $idClinica,
        ]
    );
// ===================================================================== FIM ===
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;
        /*
         * Autocomp de Funcionario
         */
        $$(fields.nomeFuncionario).auto({
            primary: "nomeFuncionario",
            width: 800,
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'funcionarios', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            params: {
                subOpcao : 'new'
            },
            filters: function (data) {
                data.rules = {
                    empresa           : $$(fields.idEmpresa).val()
                };
                return data;
            },
            responseTo: {
                fantasiaHold     : [fields.fantasiaHold],
                idAdministradora : [fields.idAdministradora],
                referenciaSubhold: [fields.referenciaSubhold],
                razaoSocialAdm   : [fields.razaoSocialAdm],
                idEmpresa        : [fields.idEmpresa],
                referenciaEmp    : [fields.referenciaEmp],
                razaoSocialEmp   : [fields.razaoSocialEmp],
                funcionario      : [fields.idFuncionario],
                referenciaFun    : [fields.referenciaFun],                
                cnpj             : [fields.cnpj]
            },
            showCols: ["nomeFuncionario", "razaoSocialAdm", "referenciaEmp", "cpf"]
        });
        
    });
    
    var edit = function(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    };
    var del = function(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    };
    
</script>