<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'bairros';
$route = 'end/default';
?>
<h1>Bairros</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['Codigo', 'Cidade', 'Descricao','Ação']);
/* @var $entity \Endereco\Entity\Bairro */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getCidadeCodigo(),
        $entity->getBairroDescricao(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
</script>