<?php
/**
 * MODAL
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 7/1/2015
 */
// == VARIAVEIS ================================================================
/**
 * @property string $controller Controller do Modal
 * @todo Quando reutilizar, trocar nome do controller
 */
$controller = 'agendaAmbuls';
/**
 * @property string $route Rota de acesso
 */
$route = 'tcmed/default';
/**
 * @property object $entity Entidade
 * @todo Quando reutilizar, trocar nome da entidade
 */
$entity = $this->agendaAmbul;
/**
 * @property integer $idEntity Id da entidade
 */
$idEntity = $entity->getId();
/**
 * @property string $idModal Nome do modal (Pode ser setado pelo controller)
 */
$idModal = isset($this->idModal)? $this->idModal: "modal-form";
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));

//====================================================================== FIM ===
//
//
// == MODAL ====================================================================
?>
<div id="<?php echo $idModal ?>" class="modal fade" data-id="<?php echo $idEntity ?>" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Dados do Funcionário <small>(<?php echo $entity->getFuncionario()->getNomeFuncionario() ?>)</small></h3>
            </div>
            <div class="modal-body">
                <form id="data-to-send">
                <!-- CORPO DO MODAL (INSERIR CONTEUDO PARA COMPOR O CORPO DO MODAL) -->
                <?php
                $fh->openLine();
                $fh->openCol(8, 2);
                $fh->openLine();
                $fh->openCol(6)->renderInputFloat('peso')->closeCol();
                $fh->lineDown();
                $fh->openCol(6)->renderInputFloat('altura')->closeCol();
                $fh->lineDown();
                $fh->openCol(6)->renderInputNumber('pressaoMin')->closeCol();
                $fh->openCol(6)->renderInputNumber('pressaoMax')->closeCol();
                $fh->lineDown();
                $fh->openCol(6)->renderInputNumber('temperatura')->closeCol();
                $fh->closeLine();
                $fh->closeCol();
                $fh->closeLine();
                ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
                <button id="salvar-modal" type="button" class="btn btn-success">Salvar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
<script type="text/javascript">
    $(function(){
        /**
         * Necessário para abrir modal na tela
         * @event Exibe modal
         */
        var $modal = $("#modal-form").modal();
        /**
         * Necessário para salvar formulario no servidor
         * @event Salva formulario
         */
        $("#salvar-modal").click(function(){
            $("#modal-form").modal("hide");
            $("#data-to-send").processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => "insertInfo"), [], FALSE, FALSE); ?>" + "/" + <?php echo $idEntity ?>,
                data:{
                    date: $("#calendar").datepicker('getFormattedDate'),
                    idAgendaAmbul: <?php echo $idEntity ?>
                },
            });
        });
    });
</script>
</div>
