<?php
/**
 * @author
 */
/* @var $table \Application\View\Helper\Table */
/* @var $acl   \Application\View\Helper\Acl */
/* @var $param \Application\View\Helper\Param */
$table                  = $this->table();
$param                  = $this->Param();
$acl                    = $this->Acl($this->UserIdentity());
$controller             = 'AgendaAmbuls';
$controllerFichaClinica = 'fichaClinicas';
$route                  = 'tcmed/default';
$form                   = $this->form;
/* @var $srvConsulta \Tcmed\Service\Consulta */
$srvConsulta            = $this->dataView['srvConsulta'];
$isMedico               = $this->post['isMedico'] ?? false;

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp(
        $this, $this->form, $this->url(
                $route, array(
            'controller' => $controller,
            'action' => $this->dataView['action']
                ), [], FALSE, $this->dataView['ajax']
        )
);

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
// ===================================================================== FIM ===
//
//
// === OPCOES DA TABELA ========================================================
if ($acl('tcmed:fichaClinicas:*', 'allow')) {
    $lambda = function($value, $data) {
        echo '<td nowrap style="font-size: 14pt; marging : 0 ; padding : 0 ;">',
        '<span class="hand" onClick="newFichaClinica(this)" title="Abrir nova ficha clinica"><i class="fa fa-paste"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="showASOOfIndex(\'', $value, '\',this)" title="Exibir ASO em PDF na Tela"><i class="fa fa-file-pdf-o"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="anexarRelatorioExterno(\'', $value, '\')" title="Anexar Relatorio Externo"><i class="fa fa-download"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="newGuiaEnc(this)" title="Gerar Guia de Encaminhamento"><i class="fa fa-user"></i> </span>',
        '</td>';
    };
} else {
    $lambda = function($value, $data) {
        echo '<td nowrap style="font-size: 14pt; marging : 0 ; padding : 0 ;">',
        '<span class="hand delete" data-id="' . $value . '" title="Excluir da Agenda"><i class="fa fa-trash"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="newGuiaEnc(this)" title="Gerar Guia de Encaminhamento"><i class="fa fa-user"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="showASOOfIndex(\'', $value, '\',this)" title="Exibir ASO em PDF na Tela"><i class="fa fa-file-pdf-o"></i> </span>',
        '&nbsp;&nbsp;',
        '<span class="hand" onClick="anexarRelatorioExterno(\'', $value, '\')" title="Anexar Relatorio Externo"><i class="fa fa-download"></i> </span>',
        '</td>';
    };
}


$table->setLambda($lambda);
// ===================================================================== FIM ===
// 
echo <<<EOF
    <legend>Agenda de Funcionários</legend>
EOF;
// === TABELA ==================================================================
$table->openTable(TRUE);
$table->setTdopt([
    ''       
    ,''
    ,''
    ,''
    ,''
    ,''
    ,' class=""'
    ,' class="small"'
    ,''
    ,' class="small"'
    ,' align="center" style="font-size: 14pt;"'
    ,''
    ,' class="small"'
    ,''
]);
$table->renderThead([                
    "Seq",
    "Che-<br>gada",
    "Inicio",
    "Saida",
    "Adc",
    "Tipo",
    "Funcionário",
    "Hold",
    "Cod Emp",
    "Empresa",
    "Historico",
    "Resul",
    "Medico",
    "Ação",
]);
$table->setEditLine('last');
$avulso = 0;
$pcmso = 0;

/* @var $agendaAmbul \Tcmed\Entity\AgendaAmbul */
/* @var $funcionario \Tcmed\Entity\Funcionario */
$index = $this->data->getTotalItemCount();
foreach ($this->data as $agendaAmbul) {
    $funcionario = $agendaAmbul->getFuncionario();
    $empresa = $agendaAmbul->getEmpresa();

    if ($empresa->getAdministradora()->getHold()->getIsAvulso()) {
        $avulso += 1;
    } else {
        $pcmso += 1;
    }

    // Traz os alertas do funcionario
    if($funcionario->getAlerta('id') != '-'){        
        $ocorrencia = '<i class="fa fa-exclamation-triangle btn-show-alert" title="Click aqui para exibir a Mensagem"></i> ';
    }else{
        $ocorrencia = '';
    }
    
    //Renderiza tabela
    $tipoExa    = substr($param($agendaAmbul->getTipoConsulta(), 'FC_tipo_exame'), 0 ,3);
    $resultado  = $agendaAmbul->getConsulta('resultado');
    $medicoNome = mb_substr($agendaAmbul->getConsulta('Medico',['nomeMedico']), 0, 10);
    $table->renderLine([
            $index,
            $agendaAmbul->getChegada("h:i"),
            $agendaAmbul->getInicio("h:i"),
            $agendaAmbul->getSaida("h:i"),
            '<i class="hand callmodal fa fa-plus" title="Inserir peso, altura, pressão" style="font-size: 16pt;"></i>',
            $tipoExa . $ocorrencia,
            '<a class="getFuncionario hand">' . $funcionario->getNomeFuncionario() . '</a>',
            mb_substr($agendaAmbul->getAdministradora()->getHold()->getNomeHold(), 0 , 10),
            $agendaAmbul->getEmpresa()->getReferenciaEmp(),
            mb_substr($agendaAmbul->getEmpresa('razaoSocial'), 0 , 20),
            '<a class="getConsulta hand">' . $srvConsulta->getQtd($funcionario) . '</a>',
            ($resultado == '-') ? $resultado : $param($resultado,'FC_Resultado'),
            $medicoNome,
            $agendaAmbul->getId(),
        ],
            ' data-id="'        . $agendaAmbul->getId() 
            .'" data-idfun="'   . $funcionario->getId()              . '"' 
            .'" data-nomefun="' . $funcionario->getNomeFuncionario() . '"' 
            .'" data-ini="'     . $agendaAmbul->getInicio("h:i")     . '"' 
            .'" data-tipo="'    . substr($tipoExa, 0, 3)             . '"' 
            .'" data-alerta="'  . $funcionario->getAlerta('id')      . '"' 
    );
    $index--;
}
$table->renderCloseTable();

//
// === TABELA ==================================================================
$total = $pcmso + $avulso;
echo <<<EOF
    <center>
    <h4 style="display: inline"><span class="label label-primary">Com PCMSO: {$pcmso}</span></h4>
    <h4 style="display: inline"><span class="label label-default">Avulsos: {$avulso}</span></h4>
    <h4 style="display: inline"><span class="label label-success">Total: {$total}</span></h4>
    </center>
    <br>
    <br>
EOF;
// ===================================================================== FIM ===
echo <<<EOF
<br />

<center>
    {$this->paginationControl($this->data, 'Sliding', 'partials/paginator')}    
</center>
EOF;
//
//
//
// === TRANSPORTE ==============================================================
$fieldsAgenda = [
    "idFuncionario" => isset($idFuncionario) ? $idFuncionario : "",
    "tipoConsulta"  => isset($tipoConsulta)  ? $tipoConsulta  : "",
    "isMedico"      => $isMedico
];
// ===================================================================== FIM ===

/* +----------------------------------------------------------------------------
 * | MODAL se parametriza usando a variavel global gModal
 * +----------------------------------------------------------------------------
 *  Estrutura do modal, para Confirmar com o usuario a ação desejada.
 * 
 */
echo $this->partial('partials/modal', array());
?>
<div id="inputs-hided">
    <div id="inputs-for-acao-titulo">
    </div>
</div>
<script lang = "javascript">
    var consulta = <?php echo $acl('tcmed:fichaClinicas:*', 'allow') ? 'true' : 'false'; ?>;
    $(function () {
        /**
         * @property {Object} fields : Objeto contendo os nomes dos campos
         * do form da página 
         */
        var fields = <?php echo json_encode($fieldsAgenda) ?>;

        $(".getFuncionario").click(function () {
            if(fields.isMedico){
                newFichaClinica(this);
            }else{
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => "Funcionarios", 'action' => "edit"), [], FALSE, FALSE); ?>" + "/" + $(this).closest('tr').data("idfun")
                });
            }
        });
        /**
         * @event Deleta o registro da base de dados 
         */
        $(".delete").click(function () {
            var id = $(this).attr("data-id");
            var msg = 'Deseja realmente excluir este funcionario da agenda?';
            gModal.reset('confirm',2)
            .setMsg(msg)
            .setLabelNg('Não')
            .setClickOk(function(){
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => "delete"), [], FALSE, FALSE); ?>" + "/" + id,
                    savePage: false,
                });     
            })
            .showModal();
        });
        /**
         * @event Traz modal com informacoes de peso, altura, 
         * pressao e temperatura 
         */
        $(".callmodal").click(function () {
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => "AgendaAmbuls", 'action' => "camposInfoPessoal"), [], FALSE, FALSE); ?>" + "/" + $(this).closest('tr').data("id"),
                savePage: false,
                callback: function (data) {
                    $("#inter").find('#modal-form').remove();
                    $("#inter").append(data);
                }
            });

        });
        
        /**
         * @event Busca o alerta do funcionario e exibe para o usuario 
         * @author Paulo Watakabe <watakabe05@gmail.com>
         * @version 1.0
         * @since 23-11-2017
         */
        $('.btn-show-alert').click(function(){
            var $obj = $(this);
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => "alertas", 'action' => "get"), [], FALSE, FALSE); ?>" + "/" + $obj.closest('tr').data("alerta"),
                savePage: false,
                callback: function (data) {
                    data = JSON.parse(data);
                    if(data.status == 'ok'){
                        var msg = data.descricao;
                    }else{
                        var msg = 'Alerta não encontrado.';
                    }
                    gModal.alert(msg, 1, 'Este funcionario tem um Alerta Importante !!!!!');
                }
            });
        });
        
        /**
         * @event Busca e exibe as consultas do funcionario 
         * @author Paulo Watakabe <watakabe05@gmail.com>
         * @version 1.0
         * @since 23-11-2017
         */
        $('.getConsulta').click(function(){        
            var $obj = $(this);
            action.setPublic({notShowIndex:'segura'}, 'agendaAmbuls'); // para não atualizar index de agendaambuls quando clicar em voltar
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'consultas', 'action' => "get"), [], FALSE, FALSE); ?>",
                type : 'POST',
                data : {
                    funcionario : $obj.closest('tr').data("idfun")
                }
//                ,callback: function (data) {
//                    gModal.reset('prompt',2)
//                        .setInputs(data)
//                        .setLabelOk('Fechar')
//                        .setSizeModal('lg')
//                        .showModal() 
//                    ;
//                }
            });
        });

    });
// ========================================================== FIM ======

    var edit = function (key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    };

    var del = function (key) {
        var msg = "Deseja mesmo excluir este registro?";
        gModal.reset('confirm',3)
        .setMsg(msg)
        .setLabelNg('Não')
        .setClickOk(function(){
            var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
            $.processa(data);
        })
        .showModal();
    };

    var newFichaClinica = function (obj) {
        if (!consulta) {
            gModal.reset('alert',3).setMsg('Você nao tem Permissão para atendimento!!!').showModal();
            return;
        }
        var func = $(obj).closest("tr").data('nomefun');
        var ini  = $(obj).closest("tr").data('ini');
        var key  = $(obj).closest("tr").data('id');
        var msg  = "Deseja mesmo atender o funcionario " + func + "?"; 
        var call = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controllerFichaClinica, 'action' => 'newOfAgenda'), [], FALSE, FALSE); ?>" + "/" + key
            });          
        };
        if(ini == "-"){
            gModal.confirm(msg,call);
        }else{
            call();          
        }
    };

    var showASO = function (idConsulta) {
        var request = {
            url: "<?php echo $this->url($route, array('controller' => $controllerFichaClinica, 'action' => 'showASO'), [], FALSE, FALSE); ?>" + "/" + idConsulta,
            type: "POST",
        };
        $.processa(request);
    };

    var showASOOfIndex = function (idAgenda, obj) {
        var $linkForConsulta = $('#linkForAso' + idAgenda);
        if ($linkForConsulta.size() === 1) {
            var idConsulta = $linkForConsulta.attr('data');
            showASO(idConsulta);
            return;
        }   
        var msg = 'Esta Consulta não foi Atendida !!! \n\n Deseja imprimir o ASO Manual ?';
        gModal.reset('confirm',2)
        .setMsg(msg)
        .setLabelNg('Não')
        .setClickOk(function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controllerFichaClinica, 'action' => 'showAsoManual'), [], FALSE, FALSE); ?>" + "/" + idAgenda
            });
        })
        .showModal();
    };
    
    /*
     * 
     * @param {int} k
     * @param {string} t
     * @returns {nothing}     
     */
    var newGuiaEnc = function(obj){
        // para pegar o id do funcionario que esta em outro td vizinho
        var f = $(obj).closest('tr').data('idfun');
        var t = $(obj).closest('tr').data('tipo');
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => 'guias', 'action' => 'new'), [], FALSE, FALSE); ?>",
//            savePage : false,
//            last : false,
//            ret  : '#add-inputsmodal-sistema',
            type : 'POST',
            data : {
                funcionario : f
                ,tipo       : t
                ,subOpcao   : 'loadCad'
            }
        });
    };
    
    /*
    * @example para inserir um form dentro do modal usando processo com gModal em conjunto.
    * @since 27-12-20169
    * @author Paulo Watakabe <watakabe05@gmail.com>
     */
    var anexarRelatorioExterno = function(key){       
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => 'ConsultaAnexos', 'action' => 'newFromAgenda'), [], FALSE, FALSE); ?>" + "/" + key,
            savePage : false,
            last : false,
            ret  : '#add-inputsmodal-sistema',
            type : 'POST',
            data : {
                ret       : '#add-inputsmodal-sistema'
                ,id       : key
                ,subOpcao : 'loadCad'
            },
            callback : function(data, defaults){
                gModal.reset('prompt',2)
                .setSizeModal('lg')
                .setInputs(data)
                .setLabelOk('Incluir')
                .setClickOk(function(){ 
                    if($('#tipo').val() == ''){
                        gModal.reset('alert',3).setMsg('O tipo do arquivo é obrigatorio!!!.').showModal();      
                        return;
                    }
                    $.processa({
                        url: "<?php echo $this->url($route, array('controller' => 'ConsultaAnexos', 'action' => 'save'), [], FALSE, FALSE); ?>" 
                        ,type: "POST"
                        ,savePage: false
                        ,frm : 'formConsultaAnexo'
                        ,ret  : '#add-inputsmodal-sistema'
                        ,data : {
                            ret  : '#add-inputsmodal-sistema'
                        }
                        ,callback: function (data, defaults) {
                            data = JSON.parse(data);
                            $.flashMessenger(data.messenger);
                        }
                    }); 
                })
                .showModal();
            }
        });
    };

</script>
