<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
$entity       = $this->entity;
/* @var $form \Tcmed\Form\Teste */
$form         = $this->form;
$id           = $form->getValue('id', 0);
$partial      = $this->partialObj('application');
$tcmedPartial = $this->partialObj('tcmed');

echo '<h3>', $title, '</h3><br />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();

$fh->openCol(5,1)->renderInputText('teste')->closeCol();
$fh->lineDown();

$fh->openCol(5,1)->renderInputSelect('status')->closeCol();
$fh->lineDown();

$fh->openCol(5,1)->renderInputSubmit('submit')->closeCol();
$fh->closeLine();

$fh->formEnd();

echo $this->partial('partials/modal');

// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'
);
?>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

    });

</script>