<?php
$ocorrencias = [];

/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'ocorrencias';
$route = 'tcmed/default';
$ocorrencia = $this->ocorrencia;
$isNew = ("new" == $this->data["formType"]);

$idOcorrencia = ($ocorrencia) ? $ocorrencia->getId() : FALSE;

$table->openTable(TRUE);
$table->renderThead(['Usuario', 'email', 'Ação']);

if ($isNew) {
    $lambda = function($value, $data) {
        echo '<td><span onclick="removeUsuarioLista(' . $value . ')" class="hand" onclick=""><i class="fa fa-trash"></i> Remover</span></td>';
    };
} else {
    $lambda = function($value, $data) {
        echo '<td><span onclick="removeUsuarioOcorrencia(' . $value . ')" class="hand" onclick=""><i class="fa fa-trash"></i> Remover</span></td>';
    };
}
$table->setLambda($lambda);

foreach ($ocorrencia->listUsuario() as $usuario) {
    $table->renderLine([
        $usuario->getNomeUsuario(),
        $usuario->getEmailUsuario(),
        $usuario->getId(),
    ]);
}

/* @var $entity \Tcmed\Entity\Ocorrencia */
if ($ocorrencia) {

    //Acao
} else if (!empty($request["listaUsuarios"])) {
    //Acao
    $lambda = function($value, $data) {
        echo '<td><span onclick="removeUsuarioLista(' . $value . ')" class="hand" onclick=""><i class="fa fa-trash"></i> Remover</span></td>';
    };
    $table->setLambda($lambda);

    foreach ($request["listaUsuarios"] as $usuario) {
        $table->renderLine([
            $usuario["nomeUsuario"],
            $usuario["emailUsuario"],
            $usuario["idUsuario"],
        ]);
    }
}

$fields = [
    "idOcorrencia" => $idOcorrencia
];

$table->renderCloseTable();
?>
<script type="text/javascript">
    /**
     * Remove os usuários da lista de usuários local do form de Ocorrencia
     * 
     * @see \view\tcmed\ocorrencias\form.phtml::removeUsuarioDaLista
     * @see \view\tcmed\ocorrencias\form.phtml::getListaUsuariosServer
     * @param {int} id
     * @returns {Boolean}
     */
    function removeUsuarioLista(id) {
        $.getPublics("ocorrencia").removeUsuarioDaLista(id);
        $.getPublics("ocorrencia").getListaUsuariosFromServer();
        return false;
    }

    /**
     * Remove os usuários da lista de usuários remoto (server) do form 
     * de Ocorrencia
     * 
     * @see \view\tcmed\ocorrencias\form.phtml::removeUsuarioDaLista
     * @see \view\tcmed\ocorrencias\form.phtml::getListaUsuariosServer
     * @param {int} id
     * @returns {Boolean}
     */
    function removeUsuarioOcorrencia(id) {
        $.getPublics("ocorrencia").removeUsuarioDaLista(id);
        $.getPublics("ocorrencia").removeUsuarioDaListaServer(id);
        return false;
    }
</script>