<?php
/**
 * @author
 */
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'ocorrencias';
$route = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Ocorrências</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->setEditLine("first");
$table->renderThead(['Ação','Assunto', 'Descrição', 'Empresa', 'Funcionário', 'Data de Acomp.']);
/* @var $entity \Tcmed\Entity\Ocorrencia */
foreach ($this->data as $entity) {
    $funcionario = ($entity->getFuncionario()) ?
            $entity->getFuncionario()->getNomeFuncionario() : "-";
    
    $table->renderLine([
        $entity->getId(),
        $entity->getAssunto(),
        $entity->getDescricao(),
        $entity->getEmpresa()->getRazaoSocial(),
        $funcionario,
        $entity->getDtAcomp(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    $(function () {

    });
</script>