<?php 
/* @var $fh        \Application\View\Helper\FormHelp */
/* @var $resposta  \Tcmed\Entity\Resposta */
/* @var $entity    \Tcmed\Entity\PpraVigenciaAparelho */
/* @var $form      \Tcmed\Form\PpraVigenciaAparelho */
$title      = $this->dataView['titulo'    ];
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$entity     = $this->entity;
$user       = $this->userIdentity();
$ret = $form->getValue('ret', '#inter');

$formId     = 'formPpraVigenciaAparelho';
$form->setAttribute('id', $formId);
$form->setAttribute('target', $ret );
$form->get('ret')->setValue($ret);

echo '<h3>', $title, '</h3>';
?>
<!--
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Listagem</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => 'equipes', 'action' => 'organograma')); ?>">Organograma</button>
</p>
<br />
-->
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(false);
$fh->formInit();
    $inpId  = $fh->getIdFor('id');
    $fh->openCol(12)->renderInputSelect('ppraAparelho')->closeCol();
$fh->lineDown();
    $fh->openCol(12)->Submit('submit',['value' => 'Incluir'])->closeCol();
$fh->lineDown()->openCol(12);
    echo '<div id="showListagemPpraVigenciaAparelho"></div>';
$fh->closeLine()->formEnd();
//
// === TRANPORTE ==============================================================
$fields = [
    'action'                 => $action
    ,'ret'                   => $ret
    ,'retIndex'              => '#showListagemPpraVigenciaAparelho'
    ,'id'                    => $form->getValue('id', 0)    
    ,'inpId'                 => $inpId
];
// ===================================================================== FIM ===

// carregar modal somente quando for para o target inter
echo $this->partial('partials/modal',[]);
?>

<script lang="javascritp">   
    
    var isValid = function(){
        return true;
    };
    
    $(function(){
        // =====================================================================
        /**
         * @property {Object} fields Campos de transferencia do PHP, que serão
         * utilizados no javascript
         */
        var fields = <?php echo json_encode($fields) ?>;
        
        var changeData = function(){
            $.processa({
                url    : "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>" 
                , type : "POST"
                , frm  : true
                , data: {
                    subOpcao  : 'loadCad'
                }
            });    
        };
        
        var showPpraVigenciaAparelhoLista = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" 
                , type: "POST"
                , savePage: false
                , frm : true
                , ret: fields.retIndex
                , data: {
                    id: fields.id
                    , ret      : fields.retIndex
                }
            });    
        };
        showPpraVigenciaAparelhoLista();
        
    });
</script>
