<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $param \Application\View\Helper\Param */
$param        = $this->Param();
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

//echo '<h4>', $title, '</h4>';


if($entity):
    $aparelhos = $entity->listPpraVigenciaAparelho();
?>
    <table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tbody>
            <tr>
                <td style="line-height: 3; border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center; background-color: #E6E6E6;" colspan="3"><b>RELAÇÃO DE EQUIPAMENTOS</b></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center; width: 45mm;">AGENTE</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center; width: 80mm;">EQUIPAMENTO</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">MÉTODO</td>
            </tr>
            <? /* @var $aparelho \Tcmed\Entity\PpraVigenciaAparelho */
               foreach ($aparelhos as $aparelho) :
            ?>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;"><?= $param($aparelho->getPpraAparelho('agente'), 'ppra_agentes'); ?></td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;"><?= $aparelho->getPpraAparelho('nome'); ?></td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;"><?= $aparelho->getPpraAparelho('metodo'); ?></td>
            </tr>
            <? endforeach;?>            
        </tbody>
    </table>

<?php
endif;