<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

?>
<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%; font-size: 6pt;">
    <tbody>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center; background-color: #E6E6E6;" colspan="2">LIMITES DE TOLERÂNCIA PARA RUÍDO CONTÍNUO OU INTERMITENTE</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center; width: 50%;">NÍVEL DE RUÍDO dB(A)</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">MÁXIMA EXPOSIÇÃO DIÁRIA PERMISSIVEL</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">85</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">8 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">86</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">7 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">87</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">6 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">88</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">5 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">89</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">4 horas e 30 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">90</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">4 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">91</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">3 horas e 30 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">92</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">3 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">93</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">2 horas e 40 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">94</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">2 horas e 15 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">95</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">2 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">96</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1 horas e 45 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">98</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1 horas e 15 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">100</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1 horas</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">102</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">45 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">104</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">35 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">105</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">30 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">106</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">25 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">108</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">20 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">110</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">15 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">112</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">10 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">114</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">8 minutos</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">115</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">7 minutos</td>
        </tr>
    </tbody>
</table>
