<?php
/** ===========================================================================|
 * FORM - SET_ENTITY
 * @author SET_AUTHOR
 * @since SET_SINCE
 *
 * IncludeView - v1
 */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;
$partial    = $this->partialObj('application');

echo '<h3>', $title, '</h3><hr />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$fh->getIdFor('id');
?>
<div class="col-md-12">
            <div class="[ btn-group ]">
                <table class="table-striped">
                    <tr>
                        <td>
               <? $fh->openCol(2)->checkbox('assina');?>
                            </td>
                            <td>
                <label for="assina" class="btn btn-danger loading">
                    <strong>Marcar opção caso responsável ou engenheiro(a) assine!!!</strong>
                </label>
                            </td>
                </tr>
                </table>
            </div>
</div>
<?php
$fh->lineDown();
$fh->openCol(9)->text('nome')->closeCol();
$fh->openCol(3)->renderInputSelect("status")->closeCol();
$fh->lineDown();

$fh->openCol(3)->text('nit')->closeCol();
$fh->openCol(3)->select('respPor')->closeCol();
$fh->openCol(3)->text('regConCla')->closeCol();
$fh->lineDown();

$fh->openCol(12)->Submit('submit')->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = array(

);
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

    });
</script>
<style type="text/css">
.fundo{
/* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#fcfff4+0,dfe5d7+40,b3bead+100;Wax+3D+%233 */
background: rgb(252,255,244); /* Old browsers */
background: -moz-linear-gradient(top, rgba(252,255,244,1) 0%, rgba(223,229,215,1) 40%, rgba(179,190,173,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgba(252,255,244,1) 0%,rgba(223,229,215,1) 40%,rgba(179,190,173,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgba(252,255,244,1) 0%,rgba(223,229,215,1) 40%,rgba(179,190,173,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcfff4', endColorstr='#b3bead',GradientType=0 ); /* IE6-9 */
}

/*Author: Danilo Song */.loading,.loading>td,.loading>th,.nav li.loading.active>a,.pagination li.loading,.pagination>li.active.loading>a,.pager>li.loading>a{
    background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
    background-size: 40px 40px;
    animation: 2s linear 0s normal none infinite progress-bar-stripes;
    -webkit-animation: progress-bar-stripes 2s linear infinite;
}
.btn.btn-default.loading,input[type="text"].loading,select.loading,textarea.loading,.well.loading,.list-group-item.loading,.pagination>li.active.loading>a,.pager>li.loading>a{
    background-image: linear-gradient(45deg, rgba(235, 235, 235, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(235, 235, 235, 0.15) 50%, rgba(235, 235, 235, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
}
</style>