<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$table->openTable(TRUE);
$table->setLambda(function($value, $data) {
    echo '<td>';
    echo '<span class="hand remover-item" data-id="'.$value.'"><i class="fa fa-trash"></i></span>&nbsp;&nbsp;';
    echo '<span class="hand editar-item-resp" data-id="'.$value.'"><i class="fa fa-pencil"></i></span>';
    echo '</td>', PHP_EOL;
});

$table->renderThead([
    ['label' => "id"],
    ['label' => "Nome"],
    ['label' => "NIT", 'options' => 'title="Número de Registro do Trabalhador"'],
    ['label' => "Responsável por"],
    ['label' => "CREA", 'options' => ' title="Conselho Regional de Engenharia"'],
    ['label' => "Inicio"],
    ['label' => "Fim"],
    ['label' => "Ação"],
]);

/* @var $contato \Tcmed\Entity\Contato */
foreach ($this->lista as $data) {
    $table->renderLine([
        $data['id'],
        $data['nome'],
        $data['nit'],
        $data['respPor'],
        $data['regConCla'],
        $data['ini'],
        $data['fim'],
        $data['id'],
    ]);
}
$table->renderCloseTable();

// Var de transferencia PHP to JS
$transp = array(
    'responsaveis' => $this->field
);

?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;

        /**
         * Inicializa a lista
         * OBS: A classe mnglist foi criada no ppra-responsavels/partial-form
         */
        mnglist.init({
            url  : "<?= $this->url('tcmed/default', array('controller' => 'ppraResponsavels', 'action' => 'getListaResp'), [], FALSE, FALSE); ?>",
            ret  : "#lista",
            field: $$(transp.responsaveis)
        });

        /**
         * Remove um item da lista
         */
        $('.remover-item').click(function() {
            mnglist.rmvItem($(this).data('id'));
            mnglist.atualiza();
        });

    });
</script>
