<?php

/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

//$fh->getIdFor('idTableConfig');
$fh->openCol(12);
echo '<legend>Responsável</legend>';
$fh->closeCol();

$fh->setPreFix('ppraResponsavel');
    $idResponsavel = $fh->getIdFor('id');
    $responsaveis  = $fh->getIdFor('responsaveis');
    $nome          = $fh->getIdFor('nome');
    $ini           = $fh->getIdFor('ini');
    $fim           = $fh->getIdFor('fim');

    $fh->openCol(3)->calend('ini')->closeCol();
    $fh->openCol(3)->calend('fim')->closeCol();
    $fh->openCol(4)->text('nome', [
        "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
        "dt-clear" => $idResponsavel
    ])->closeCol();
    $fh->openCol(1)->buildButton(['id' => 'incluir',        'style' => 'margin-top: 25px', 'class' => 'btn-block'], 'Incluir', 'primary', TRUE)->closeCol();
    $fh->openCol(1)->buildButton(['id' => 'cadastrar-resp', 'style' => 'margin-top: 25px', 'class' => 'btn-block'], '<i class="fa fa-plus"></i> Novo', 'warning', TRUE)->closeCol();

    $fh->jumpLine(2);

    $fh->openCol(12, ['id' => 'lista'])->closeCol();

$fh->removePreFix('ppraResponsavel');

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

// Cria o objeto mnglist para utilizacao no js
$d['this']->partialObj('tcmed')->partial('ppra-responsavels/mnglist');

// Carrega o js do modal
echo $d['this']->partial('partials/modal');

// Var de transferencia PHP to JS
$transp = compact(
    'idResponsavel',
    'nome',
    'ini',
    'fim',
    'responsaveis'
);

$this->respData = $transp;
?>
<script lang="javascript">

    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        $$(transp.nome).auto({
            primary: "nome",
            serviceUrl: "<?= $d['this']->url('tcmed/default', array('controller' => 'ppraResponsavels', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                "id"       : [transp.idResponsavel],
            },
            showCols: ["nome", "nit", "respPor"]
        });

        /**
         * Inicializa a lista
         * OBS: Ler partial acima, que injeta o js de montagem do mnglist aqui
         */
        mnglist.init({
            url  : "<?= $d['this']->url('tcmed/default', array('controller' => 'ppraResponsavels', 'action' => 'getListaResp'), [], FALSE, FALSE); ?>",
            ret  : "#lista",
            field: $$(transp.responsaveis)
        });

        $('#incluir').click(function() {
            var id = $$(transp.idResponsavel).val();

            if("" == $$(transp.ini).val() || "" == $$(transp.fim).val()) {
                mnglist.message('Escolha o periodo!!', "danger");
                return false;
            }

            mnglist.addItem({
                id : id,
                ini: $$(transp.ini).val(),
                fim: $$(transp.fim).val(),
            });

            mnglist.atualiza();
            $$('clean_' + transp.nome).find('button').click();
        });

        mnglist.atualiza();

        $("#cadastrar-resp").click(function() {
            var $form = $(this).closest('form');

            gModal.reset("confirm", 1)
                    .setClickOk(function () {
                        $form.processa({
                            url: "<?= $d['this']->url('tcmed/default', array('controller' => 'ppraResponsavels', 'action' => 'new'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            data: {
                                fromPpraVigencia: true,
                                // Por algum motivo desconhecido, o servidor não está
                                // conseguindo ler o campo abaixo naturalmente (Como todos
                                // os outros campos do formulario). Então, eu vou enviar
                                // manualmente, forçando então o envio dos dados deste campo
                                "ppraResponsavel[responsaveis]": $$(transp.responsaveis).val()
                            }
                        })
                    })
                    .setLabelOk("SIM")
                    .setLabelNg("NÃO")
                    .setMsg('Deseja realmente cadastrar um novo responsável?')
                    .showModal();
        });

    });

</script>
