<?php
/**
 * MODAL
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 7/1/2015
 */
// == VARIAVEIS ================================================================
/**
 * @property string $controller Controller do Modal
 * @todo Quando reutilizar, trocar nome do controller
 */
$controller = 'Clinicas';
/**
 * @property string $route Rota de acesso
 */
$route = 'tcmed/default';
/**
 * @property object $entity Entidade
 * @todo Quando reutilizar, trocar nome da entidade
 */
$entity = $this->clinica;
/*@var $contato \Tcmed\Entity\Contato*/
$contato = (is_object($this->contato)) ? $this->contato : FALSE;
/**
 * @property integer $idEntity Id da entidade
 */
$idEntity = $entity->getId();
/**
 * @property string $idModal Nome do modal (Pode ser setado pelo controller)
 */
$idModal = isset($this->idModal) ? $this->idModal : "modal-form";
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));

//====================================================================== FIM ===
//
//
// == MODAL ====================================================================
?>
<div id="<?php echo $idModal ?>" class="modal fade" data-id="<?php echo $idEntity ?>" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Incluir Contato</h3>
            </div>
            <div class="modal-body">
                <form id="data-to-send">
                    <?php
                    $fh->openLine();
                    $fh->openCol(12);
                    $fh->openLine();

                    $fh->setPreFix("contato");
                    if ($contato) {
                        $fh->openCol(12);
                        echo '<input type="hidden" value="'.$contato->getId().'" name="idContato">';
                        echo '<h3 style="text-align: center">Contato: '.$contato->getNomeContato().'</h3><br>';
                    }else{
                        $fh->openCol(5);
                        $fh->text('nomeContato');
                    }
                    $fh->closeCol();

                    $fh->lineDown();

                    $fh->setPreFix("meioContato");

                    $fh->getIdFor("idContato");
                    $fh->openCol(5)->select('tipoMeioContato[0]')->closeCol();

                    $fh->openCol(7)
                            ->text('meioDeContato[0]', [], ['placeholder' => "+99 (99) 9999-9999", 'options' => ['label' => "Descrição do Contato"]])
                            ->closeCol();

                    $fh->removePreFix("meioContato");

                    $fh->removePreFix("contato");


                    //Add tipo meio contato em select

                    $fh->closeLine();
                    $fh->closeCol();
                    $fh->closeLine();
                    ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
                <button id="salvar-modal" type="button" class="btn btn-success">Salvar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $(function () {
        /**
         * Necessário para abrir modal na tela
         * @event Exibe modal
         */
        var $modal = $("#modal-form").modal();

        $("#salvar-modal").click(function () {
            $("#modal-form").modal("hide");
            $("#data-to-send").processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => "insertNewContato"), [], FALSE, FALSE); ?>" + "/" + <?php echo $idEntity ?>,
                data: {
                    idClinica: <?php echo $idEntity ?>
                },
                callback: function(data){
                    $("#listaContatos").html(data);
                }
            });
            return false;
        });
    });
</script>
