<?php

$result = $this->resultSet;

/* @var $entity \Tcmed\Entity\Clinica */
if ($result) {
    $array[] = [
        'menu_idClinica' => "ID",
        'menu_fantasiaClinica' => 'Nome Fantasia',
        'menu_cnpj' => "CNPJ",
    ];
    foreach ($result as $entity) {

        $array[] = [
            "idClinica" => $entity->getId(),
            "fantasiaClinica" => $entity->getFantasiaClinica(),
            "cnpj" => $entity->getCnpj(),
        ];
    }
}

echo json_encode($array);
