<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table      = $this->table();
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$form       = $this->form;

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh    = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
), [], FALSE, $this->dataView['ajax']));

?>
<h1><?= $title ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Novo</button>
</p>
<?php


$fh->formInit(); // ===============================================

$this->partialObj('application')->partial('index/partial-form-listafiltros', null, ['this' => &$this, 'fh' => $fh, 'dataView' => $this->dataView]);

$fh->lineDown();

$fh->openCol(12);
$table->setOrderList($orderBy);
$table->openTable(TRUE);
$table->renderThead(['ID', 'Razão Social', 'Nome Fantasia', 'CNPJ', 'Status', 'Ação']);
/* @var $entity \Tcmed\Entity\Clinica */
foreach ($this->data as $entity) {
    
    $statusRow = "default";
    $entity->getStatus() == "INATIVO"   && $statusRow = "danger";
    $entity->getStatus() == "CANCELADO" && $statusRow = "danger";
    $entity->getStatus() == "BLOQUEADO" && $statusRow = "warning";
    
    $table->renderLine([
        $entity->getId(),
        $entity->getRazaoSocial(),
        $entity->getFantasiaClinica(),
        $entity->getCnpj(),
        $entity->getStatus(),
        $entity->getId(),
    ],"class='{$statusRow}'");
}
$table->renderCloseTable();

$fh->formEnd(); // =============================================================

echo "<br>";
echo "<center>{$this->paginationControl($this->data, 'Sliding', 'partials/paginator')}</center>";

?>

<script lang="javascript">
    
    $(function () {

    });
    function edit(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key,
        });
        
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>