<?php
/**
 * MODAL Contato
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 7/1/2015
 */
// == VARIAVEIS ================================================================
/**
 * @property string $controller Controller do Modal
 * @todo Quando reutilizar, trocar nome do controller
 */
$controller = $this->dataView["controller"];
/**
 * @property string $route Rota de acesso
 */
$route = 'tcmed/default';
/**
 * @property array $data Dados obtidos do modal
 */
$idEntity = $this->data;

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));

//====================================================================== FIM ===
//
//
// == MODAL ====================================================================
?>
<div id="modal" class="modal fade" data-id="<?php echo $idEntity ?>" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Incluir Contato</h3>
            </div>
            <div class="modal-body">
                <form id="data-to-send">
                    <?php
                    $fh->openLine();
                    $fh->openCol(12);
                    $fh->openLine();

                    $fh->setPreFix("contato");
                    $fh->openCol(12)->text("nomeContato", [], ["id" => "nomeContato"])->closeCol();
                    $nomeContato = $fh->getLastId();

                    $fh->setPreFix("meioContato");
                    $fh->openCol(6)->text("meioDeContato[0]", [], ["label" => '<i class="fa fa-phone"></i> Telefone'])->closeCol();
                    $telefone = $fh->getLastId();
                    $fh->openCol(6)->text("meioDeContato[1]", [], ["label" => '<i class="fa fa-mobile"></i> Celular'])->closeCol();
                    $celular = $fh->getLastId();
                    $fh->openCol(12)->text("meioDeContato[2]", [], ["label" => '<i class="fa fa-envelope"></i> Email'])->closeCol();
                    $email = $fh->getLastId();
                    $fh->removePreFix("meioContato");
                    $fh->removePreFix("contato");

                    $fh->closeLine();
                    $fh->closeCol();
                    $fh->closeLine();
                    ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
                <button id="salvar-modal" type="button" class="btn btn-success">Salvar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $(function () {
        var $modal = $("#modal")
        $modal.modal("show");

        /**
         * Checa os dados dos campos telefone, email, celular e contato
         * e os envia ao servidor para persistencia
         */
        $("#salvar-modal").click(function () {
            var telefone = $modal.find("#meioDeContato0").val()
            var celular = $modal.find("#meioDeContato1").val()
            var email = $modal.find("#meioDeContato2").val()

            if ($modal.find("#nomeContato").val() == "") {
                $modal.modal("hide");
                $.notify({
                    message: "Você precisa definir o nome do contato!!",
                    type: "danger"
                });
                return false;
            }

            if ("" == telefone && "" == celular && "" == email) {
                $modal.modal("hide");
                $.notify({
                    message: "Vecê precisa inserir ao menos 1 meio de contato!!",
                    type: "danger"
                });
                return false;
            }

            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'addNewContatoModal'), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    "idEntity": "<?php echo $idEntity ?>",
                    "nomeContato": $modal.find("#nomeContato").val(),
                    "telefone": telefone,
                    "celular": celular,
                    "email": email,
                },
                callback: function (data) {
                    $modal.modal("hide");
                    $(".modal-backdrop").remove();
                    $.processa({
                        url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'getContatos'), [], FALSE, FALSE) . "/" . $idEntity ?>",
                        callback: function (data) {
                            $("#listaContatos").html(data);
                        }
                    });
                }
            });
        });
    });
</script>
