<?php
$titulo = $this->dataView['titulo'];
$entity = $this->entity;
$route = $this->dataView['route'];
$controller = $this->dataView['controller'];
$partialObject = $this->partialObj('tcmed');

echo '<h2>', $titulo, '</h2><br>';

/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp(
        $this, $this->form, $this->url(
                $route, array(
            'controller' => $controller,
            'action' => $this->dataView['action'],
            'id' => ($this->entity) ? $this->entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']
        )
);
$fh->formInit('');

$fh->openCol(12);
$fh->renderFieldsetIni('Dados da Administradora');
$fh->openCol(3)->closeCol();
$fh->openCol(9)->select('hold')->closeCol();
$fantasiaHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol(3)->text('referenciaSubhold')->closeCol();
$referenciaSubhold = $fh->getLastId();
$fh->openCol(9)->text('razaoSocial')->closeCol();
$fantasiaAdm = $fh->getLastId();
$fh->lineDown();

$fh->openCol(3)->cnpj('cnpj')->closeCol();
$fh->openCol(9)->text('fantasiaAdm')->closeCol();

$fh->lineDown();

$fh->openCol(3)->text('referenciaAdm')->closeCol();
$referenciaAdm = $fh->getLastId();
$fh->openCol(3)->select('tipoPeriodico')->closeCol();

$fh->openCol(3)->text('inscricaoEstadual')->closeCol();

$fh->openCol(3)->select('status')->closeCol();

$fh->lineDown();

echo "<br>";

$fh->setHorizontal(TRUE);
$fh->openCol(6, ["id" => "container-avulso"])->radio('guiaAvulsa')->closeCol();
$fh->lineDown();

$fh->openCol(6)->radio('cartaCondominio')->closeCol();
$fh->lineDown();
$fh->setHorizontal(FALSE);

$fh->renderFieldsetFim();
//
//
echo "<br>";


$list = ('edit' == $this->dataView['action']);

// Carrega o partial de contatos
$partialObject->partial('contatos/partial-form-contato', $fh, [
    'this' => &$this,
    'entity' => $entity,
]);

$fh->renderFieldsetIni("Endereco");
$fh->openCol(12);
$partialObject->partial('enderecos/partial-form-all', $fh, ['this' => &$this]);
$fh->renderFieldsetFim();
$fh->openCol(12)->Submit('submit')->closeCol();
$fh->closeLine()->closeCol()->formEnd();

$fieldsEntity = [
    "idEntity" => isset($this->entity) ? $this->entity->getId() : FALSE
    ,"isEdit" => ("edit" == $this->dataView["action"])
    ,'referenciaSubhold' => $referenciaSubhold
];
?>
<br>
<br>
<br>
<script lang="javascript">

    function isValid() {
        return true;
    }

    $(function () {
        var fields = <?php echo json_encode($fieldsEntity) ?>;
        /**
         * Ao Selecionar uma HOLD, ele verifica se esta contém o text "AVULSO".
         * Se houver, então alerta o usuário de que a Hold selecionada é do tipo
         * avulsa e por consequência disso, a Administradora selecionada também
         * será do tipo avulsa
         * 
         * @since 02/03/2016
         * @author Danilo Dorotheu
         * @return {void}
         */
        $("#hold").change(function () {
            if ($(this).find("option:selected").text().indexOf("AVULSO") > 0) {
                $.notify({
                    message: "Você selecionou uma Hold Avulsa. Portanto, esta Administradora será do tipo avulsa!",
                    type: "info"
                });
                $("#container-avulso").hide();
            } else {
                $("#container-avulso").show();
            }
        });

        //== MENSAGENS DO SISTEMA ==============================================
        /**
         * @see (PHP) flashMessenger
         * @property {object} messagesGroup Necessário para exibir mensagens 
         * na tela
         */
        var messagesGroup = <?php echo json_encode($messages) ?>;
        /**
         * @event Exibe as mensagens do servidor na view
         */
        $.each(messagesGroup, function (type, messages) {
            $.each(messages, function (_, message) {
                $.notify({
                    "message": message,
                    "type": type
                });
            });
        });
        // ========================================================== FIM ======
    });

</script>
