<?php
$fh = &$obj;

//echo '<pre>' , var_dump(get_class_methods($fh));die;

$fh->closeLine()->renderFieldsetIni('Administradora')->setPreFix('administradora');
$idAdministradora = $fh->getIdFor('idAdministradora');
$fh->openCol('12')->text('razaoSocial')->closeCol()->closeCol();
$razaoSocial = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('fantasiaAdm')->closeCol();
$fantasiaAdm = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('cnpj')->closeCol();
$cnpj = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->select('holdVirtual')->closeCol();
$holdVirtual = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('referenciaHold')->closeCol();
$referenciaHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('referenciaSubhold')->closeCol();
$referenciaSubHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('referenciaAdm')->closeCol();
$referenciaAdm = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('inscricaoEstadual')->closeCol();
$inscricaoEstadual = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('codigoCliente')->closeCol();
$codigoCliente = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('tipoPeriodico')->closeCol();
$tipoPeriodico = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('guiaAvulsa')->closeCol();
$guiaAvulsa = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('cartaCondominio')->closeCol();
$cartaCondominio = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('referenciaVv')->closeCol();
$referenciaVv = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
//$fh->lineDown();
//    $fh->openCol('12')->select('bairro')->closeCol();
//$fh->lineDown();
$this->partialObj('tcmed')->partial('holds/partial-form', $fh, ['this' => &$d["this"]]);
$this->partialObj('tcmed')->partial('enderecos/partial-form', $fh, ['this' => &$d["this"]]);

$fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();
?>

<script lang="javascript">
    $(function () {

            var fields= {
//                razaoSocial: "<?php echo $razaoSocial; ?>",
                fantasiaAdm: "<?php echo $fantasiaAdm; ?>",
//                cnpj: "<?php echo $cnpj; ?>",
//                holdVirtual: "<?php echo $holdVirtual; ?>",
//                referenciaHold: "<?php echo $referenciaHold; ?>",
//                referenciaSubhold: "<?php echo $referenciaSubHold; ?>",
//                referenciaAdm: "<?php echo $referenciaAdm; ?>",
//                inscricaoEstadual: "<?php echo $inscricaoEstadual; ?>",
//                codigoCliente: "<?php echo $codigoCliente; ?>",
//                tipoPeriodico: "<?php echo $tipoPeriodico; ?>",
//                guiaAvulsa: "<?php echo $guiaAvulsa; ?>",
//                cartaCondominio: "<?php echo $cartaCondominio; ?>",
//                referenciaVv: "<?php echo $referenciaVv; ?>",
                idAdministradora: "<?php echo $referenciaVv; ?>",
                idHold: "<?php echo $idHold; ?>",
                fantasiaHold: "<?php echo $fantasiaHold; ?>",
            }
        
        action.getEl(fields.fantasiaAdm).keypress(function () {
            action.auto($(this), {
                primary: "fantasiaAdm",
                serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'administradoras', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                noCache: true,
                responseTo: {
                    "idHold": [fields.idHold],
                    "fantasiaHold": [fields.fantasiaHold],
                    "idAdministradora": [fields.idAdministradora],
                },
                params: {
                    rules: {
                        hold: action.getVal(fields.idHold),
                    }
                }
            });
        });
        
        action.preAutoComp("razaoSocial", parametros);
        action.preAutoComp("fantasiaAdm", parametros);
        action.preAutoComp("cnpj", parametros);
    });
</script>