<?php 
/* @var $fh        \Application\View\Helper\FormHelp */
/* @var $resposta  \Tcmed\Entity\Resposta */
/* @var $entity    \Tcmed\Entity\PpraMedicao */
/* @var $form      \Tcmed\Form\PpraMedicao */
$title      = $this->dataView['titulo'    ];
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$entity     = $this->entity;
$user       = $this->userIdentity();
$ret = $form->getValue('ret', '#inter');

$formId     = 'formPpraMedicao';
$form->setAttribute('id', $formId);
$form->setAttribute('target', $ret );
$form->get('ret')->setValue($ret);

echo '<h3>', $title, '</h3>';
?>
<!--
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Listagem</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => 'equipes', 'action' => 'organograma')); ?>">Organograma</button>
</p>
<br />
-->
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(false);
$fh->formInit();
    $inpId  = $fh->getIdFor('id');
    $fh->openCol(5)->renderInputSelect('ppraLocal',
                [
                    'extra' => [
                        ['icon' => 'plus', 'id' => "icon-add-local", 'title' => "Adicionar um novo local."]
                    ]
                ])->closeCol();
    $fh->openCol(5)->renderInputSelect('ppraLocalDet',
                [
                    'extra' => [
                        ['icon' => 'plus', 'id' => "icon-add-localDet", 'title' => "Adicionar um novo Detalhamento de local ."]
                    ]
                ])->closeCol();
    $fh->openCol(2)->Submit('submit',['value' => 'Incluir'])->closeCol();
$fh->lineDown()->openCol(12);
    echo '<div id="showListagemPpraMedicao"></div>';
$fh->closeLine()->formEnd();
//
// === TRANPORTE ==============================================================
$fields = [
    'action'                 => $action
    ,'ret'                   => $ret
    ,'retIndex'              => '#showListagemPpraMedicao'
    ,'id'                    => $form->getValue('id', 0)    
    ,'inpId'                 => $inpId
];
// ===================================================================== FIM ===

// carregar modal somente quando for para o target inter
echo $this->partial('partials/modal',[]);
?>

<script lang="javascritp">   
    
    var isValid = function(){
        return true;
    };
    
    $(function(){
        // =====================================================================
        /**
         * @property {Object} fields Campos de transferencia do PHP, que serão
         * utilizados no javascript
         */
        var fields = <?php echo json_encode($fields) ?>;
        
        var changeData = function(){
            $.processa({
                url    : "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>" 
                , type : "POST"
                , frm  : true
                , data: {
                    subOpcao  : 'loadCad'
                }
            });    
        };
        
        var showPpraMedicaoLista = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" 
                , type: "POST"
                , savePage: false
                , frm : true
                , ret: fields.retIndex
                , data: {
                    id: fields.id
                    , ret      : fields.retIndex
                }
            });    
        };
        showPpraMedicaoLista();
        
        $('#icon-add-local').click(function(){        
            var $form = $(this).closest('form');
            var $ret   = $form.find('input[id="ret"]');
            var retOld = $ret.val();            
            $ret.val('#add-inputsmodal-sistema');
            $form.processa({
                url     : "<?= $this->url($route, array('controller' => 'ppraLocals', 'action' => 'new'), [], FALSE, FALSE); ?>",
                type    : "POST",
                savePage: false,
                data : {
                    subOpcao : 'loadCad'
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('fechar')
                        .setClickOk(function(){
                            $form.processa({
                                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'new'), [], FALSE, FALSE); ?>",
                                ret     : $ret.val(),
                                savePage: false,
                                data : {
                                    subOpcao : 'loadCad'
                                }
                            });
                        })
                        .setSizeModal('lg')
                        .showModal()
                    ;
                }
            });   
            $ret.val(retOld);     
        });
        
        $('#icon-add-localDet').click(function(){        
            var $form = $(this).closest('form');
            var $ret   = $form.find('input[id="ret"]');
            var retOld = $ret.val();            
            $ret.val('#add-inputsmodal-sistema');
            $form.processa({
                url     : "<?= $this->url($route, array('controller' => 'ppraLocalDets', 'action' => 'new'), [], FALSE, FALSE); ?>",
                type    : "POST",
                savePage: false,
                data : {
                    subOpcao : 'loadCad'
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('fechar')
                        .setClickOk(function(){
                            $form.processa({
                                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'new'), [], FALSE, FALSE); ?>",
                                ret     : $ret.val(),
                                savePage: false,
                                data : {
                                    subOpcao : 'loadCad'
                                }
                            });
                        })
                        .setSizeModal('lg')
                        .showModal()
                    ;
                }
            });   
            $ret.val(retOld);     
        });
        
    });
</script>
