<?php
/*
 * @author Paulo Watakabe <watakabe05@gmail.com>
 * @version 1.0
 * @since 23/03/2017
 */
/* @var $fh        \Application\View\Helper\FormHelp */
/* @var $resposta  \Tcmed\Entity\Resposta */
/* @var $entity    \Tcmed\Entity\PpraLocal */
/* @var $form      \Tcmed\Form\PpraLocal */
$title      = $this->dataView['titulo'    ];
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$entity     = $this->entity;
$user       = $this->userIdentity();
$ret = $form->getValue('ret', '#inter');

$formId     = 'formPpraLocal';
$form->setAttribute('id', $formId);
$form->setAttribute('target', $ret );
$form->get('ret')->setValue($ret);

echo '<h3>', $title, '</h3>';
?>
<div id="show-menuPpraLocal">
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Listagem</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Limpar</button>
</p>
<br />
</div>
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(false);
$fh->formInit();
    $inpId  = $fh->getIdFor('id');
    $fh->openCol(12)->renderInputText('nome')->closeCol();
$fh->lineDown();
    $fh->openCol(12)->renderInputSelect('status')->closeCol();
$fh->lineDown();
    $fh->openCol(12)->Submit('submit')->closeCol();
$fh->lineDown()->openCol(12);
    echo '<div id="showListagemPpraLocal"></div>';
$fh->closeLine()->formEnd();
//
// === TRANPORTE ==============================================================
$fields = [
    'action'                 => $action
    ,'ret'                   => $ret
    ,'retIndex'              => '#showListagemPpraLocal'
    ,'id'                    => $form->getValue('id', 0)    
    ,'inpId'                 => $inpId
];
// ===================================================================== FIM ===

// carregar modal somente quando for para o target inter
echo $this->partial('partials/modal',[]);
?>

<script lang="javascritp">   
    
    var isValid = function(){
        return true;
    };
    
    $(function(){
        // =====================================================================
        /**
         * @property {Object} fields Campos de transferencia do PHP, que serão
         * utilizados no javascript
         */
        var fields = <?php echo json_encode($fields) ?>;
        
        
        var showPpraLocalLista = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" 
                , type: "POST"
                , savePage: false
                , frm : true
                , ret: fields.retIndex
                , data: {
                    id: fields.id
                    , ret      : fields.retIndex
                }
            });    
        };
        showPpraLocalLista();
        
        if(fields.ret != '#inter'){
            $('#show-menuPpraLocal').hide();
        }
        
    });
</script>
