<?php
/* @var $table  \Application\View\Helper\Table        */
/* @var $user   \Application\View\Helper\UserIdentity */
$table      = $this->Table();
$user       = $this->UserIdentity();
$controller = 'usuarioParams';
$route      = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Usuario Params</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array("controller" => $controller, "action" => "new")); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead([
    'ID'
    ,'Hold'
    ,'Administradora'
    ,'Empresa'
    ,'Clinica'
    ,'Medico'
    ,'Funcionario'
    ,'Usuario'
    ,'Incluido'
    ,'Alterado'
    ,'Ação'
]);
/* @var $entity \Tcmed\Entity\UsuarioParam */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getHold('NomeHold'),
        $entity->getAdministradora('FantasiaAdm'),
        $entity->getEmpresa('FantasiaEmpresa'),
        $entity->getClinica('FantasiaClinica'),
        $entity->getMedico('NomeMedico'),
        $entity->getFuncionario('NomeFuncionario'),
        $entity->getUsuario('NomeUsuario'),
        $entity->getCreatedAt(),
        $entity->getUpdatedAt(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    $(function () {

    });
</script>