<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
$entity       = $this->entity;
$form         = $this->form;
$partial      = $this->partialObj('application');
$tcmedPartial = $this->partialObj('tcmed');

echo '<h3>', $title, '</h3><br />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();

$id  = $fh->getIdFor('id' );
$ini = $fh->getIdFor('ini');
$fim = $fh->getIdFor('fim');

$fh->openCol(12);
$tcmedPartial->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'hideCnpj' => TRUE]);
$fh->closeCol();

$fh->lineDown();

$fh->openCol(3)->calend('ini')->closeCol();
$fh->openCol(3)->calend('fim')->closeCol();
$fh->openCol(2,3)->buildButton(['id' => 'salvar'   , 'class' => 'btn-block'], '<i class="fa fa-floppy-o"></i> Salvar' , 'primary', TRUE)->closeCol();

$fh->lineDown();

$fh->setPreFix('ppra'   );
    $idPpra = $fh->getIdFor('id');
$fh->removePreFix('ppra');

// =============================================================================
//              FORMULÁRIO DE RESPONSAVEIS DA VIGENCIA
// =============================================================================
$fh->setPreFix('ppraVigenciaResp');

    $fh->openCol(12);
        echo '<legend>Responsáveis</legend>';
    $fh->closeCol();

    $idResponsavel = $fh->getIdFor('id');
    $responsaveis  = $fh->getIdFor('responsaveis');
    $nome          = $fh->getIdFor('nome');
    $vrIni         = $fh->getIdFor('ini');
    $vrFim         = $fh->getIdFor('fim');

    $fh->openCol(3)->calend('ini')->closeCol();
    $fh->openCol(3)->calend('fim')->closeCol();
    $fh->openCol(4)->text('nome', [
        "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
        "dt-clear" => $idResponsavel
    ])->closeCol();

    echo "<div id='include-buttons'>";
        $fh->openCol(1)->buildButton(['id' => 'incluir',        'style' => 'margin-top: 25px', 'class' => 'btn-block'], 'Incluir', 'primary', TRUE)->closeCol();
        $fh->openCol(1)->buildButton(['id' => 'cadastrar-resp', 'style' => 'margin-top: 25px', 'class' => 'btn-block'], '<i class="fa fa-plus"></i> Novo', 'warning', TRUE)->closeCol();
    echo "</div>";
    echo "<div id='edit-buttons' class='hideOn'>";
        $fh->openCol(1)->buildButton(['id' => 'salvar-edit',        'style' => 'margin-top: 25px', 'class' => 'btn-block'], 'Salvar', 'success', TRUE)->closeCol();
        $fh->openCol(1)->buildButton(['id' => 'cancelar-edit',        'style' => 'margin-top: 25px', 'class' => 'btn-block'], 'Cancelar', 'danger', TRUE)->closeCol();
    echo "</div>";

    echo "</div>";

    $fh->openCol(12, ['id' => 'lista'])->closeCol();

$fh->removePreFix('ppraVigenciaResp');
// =============================================================================



$fh->formEnd();

$this->partialObj('tcmed')->partial('ppra-responsavels/mnglist');
echo $this->partial('partials/modal');

// Var de transferencia PHP to JS
$transp = compact(
    'id',
    'idPpra',
    'idResponsavel',
    'nome',
    'responsaveis',
    'vrIni',
    'vrFim',
    'ini',
    'fim'
);
?>
<ul class="nav nav-pills nav-justified">
  <li class="hand"><a>Dados Basicos</a></li>
  <li class="hand"><a>Setor/Cargo</a></li>
  <li class="hand"><a>Aparelhos</a></li>
  <li class="hand"><a>Locais</a></li>
  <li class="hand"><a>Resultados</a></li>
  <li class="hand"><a>Fotos</a></li>
  <li class="hand"><a>Cronograma</a></li>
  <li class="hand"><a>Texto</a></li>
  <li class="hand"><a>Download</a></li>
</ul>
<div id="nav-tabs">
    <div id="tab-0" data-reload="0" data-controller="ppras"                   data-action="dadosBasico"></div>
    <div id="tab-1" data-reload="1" data-controller="ppraOcupacaos"           data-action="show"></div>
    <!--
    <div id="tab-1" data-reload="0" data-controller="ocupacaos"               data-action="listaOcupVigencia"></div>
    -->
    <div id="tab-2" data-reload="0" data-controller="ppraVigenciaAparelhos"   data-action="new"></div>
    <div id="tab-3" data-reload="0" data-controller="ppraMedicaos"            data-action="new"></div>
    <div id="tab-4" data-reload="1" data-controller="ppraMedicaoResuls"       data-action="show"></div>
    <div id="tab-5" data-reload="0" data-controller="ppraVigenciaFotos"       data-action="listaFotos"></div>
    <div id="tab-6" data-reload="0" data-controller="ppraVigenciaCronogramas" data-action="listaCronograma"></div>
    <div id="tab-7" data-reload="0" data-controller="ppraVigenciaTextos"      data-action="texto"></div>
    <div id="tab-8" data-reload="1" data-controller="ppraVigenciaTextos"      data-action="show"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){

        $('.nav-pills').find('li').click(function(){
            var $li   = $(this);
            var index = $('.nav-pills').find('li').index($li);
            $('.nav-pills').find('li').removeClass('active');
            $li.addClass('active');
            var $navtabs = $('#nav-tabs');
            $navtabs.children().hide();
            var ret  = '#tab-' + index ;
            var $tab = $(ret);

            var controller = $tab.data('controller') ;
            var action     = $tab.data('action') ;
            if("" == $tab.html() || $tab.data('reload')){
                $.processa({
                    url: "<?= $this->url($route, array('controller' => 'index', 'action' => 'getRoute'), [], FALSE, FALSE); ?>",
                    type: "POST",
                    savePage : false,
                    data: {
                        controller : controller,
                        action     : action
                    },
                    callback : function(data){
                        $li.closest('form').processa({
                            url : data,
                            type: "POST",
                            savePage : false,
                            ret : ret,
                            data: {
                                ret           : ret,
                                ppraVigencia  : $$(transp.id).val(),
                                ppra          : $$(transp.idPpra).val(),
                                subOpcao      : 'loadCad'
                            }
                        });
                    }
                });
            }
            $tab.show();
        });

        var transp   = <?php echo json_encode($transp) ?>;
        var editando = false;

        $('#salvar').click(function() {
            $(this).closest('form').processa({
                url: "<?= $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>",
            });
        });

        /**
         * Autocompleta o campo 'nome' do ppraResponsavel
         */
        $$(transp.nome).auto({
            primary: "nome",
            serviceUrl: "<?= $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                "id"       : [transp.idResponsavel]
            },
            callback: function(data) {
                if(editando) {
                    $('#cancelar-edit').click();
                }
                $$(transp.idResponsavel).val(data.id);
                $$(transp.nome).val(data.nome);
            },
            showCols: ["nome", "nit", "respPor"]
        });

        /**
         * Abre formulario de cadastro de responsáveis
         * OBS: o parametro 'fromPpraVigencia' serve para dizer ao Controller
         * de ppraResponsavel para guardar os dados do formulario de ppraVigencia,
         * para então autocompletar os campos de ppraVigencia após a inclusão
         * do novo responsavel
         */
        $("#cadastrar-resp").click(function() {
            var $form = $(this).closest('form');
            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $form.processa({
                        url: "<?= $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'new'), [], FALSE, FALSE); ?>",
                        type: "POST",
                        data: {
                            fromPpraVigencia: true,
                        }
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente cadastrar um novo responsável?')
                .showModal()
            ;
        });

        /**
         * Inicializa a lista
         * OBS: Ler partial acima, que injeta o js de montagem do mnglist aqui
         */
        mnglist.init({
            // URL do servidor pra atualizar a lista
            url  : "<?= $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'getListaResp'), [], FALSE, FALSE); ?>",
            // Nome do ID da div que irá retornar a listagem
            ret  : "#lista",
            // Nome do campo a ser inspecionado para manter lista
            field: $$(transp.responsaveis)
        });

        /**
         * Atualiza a listagem e já exibe quem são os responsáveis desta vigencia
         */
        mnglist.atualiza();

        function getDateTime(strDate) {
            var aux = strDate.split('/');
            return Date.parse(aux[2] + '-' + aux[1] + '-' + aux[0] + ' 00:00:00');
        }

        /**
         * Valida os campos ini e fim da vigencia e do responsavel
         */
        function validaDateTime() {
            var iniVigencia     = $$(transp.ini).val();
            var fimVigencia     = $$(transp.fim).val();
            var iniVigenciaResp = $$(transp.vrIni).val();
            var fimVigenciaResp = $$(transp.vrFim).val();

            if("" == iniVigenciaResp || "" == fimVigenciaResp) {
                mnglist.message('Escolha o periodo!!', "danger");
                return false;
            }

            if(getDateTime(iniVigencia) > getDateTime(iniVigenciaResp)) {
                mnglist.message('A data de inicio do responsável deve ser maior que a data de inicio da vigencia!!', "danger");
                return false;
            }

            if(getDateTime(fimVigencia) < getDateTime(fimVigenciaResp)) {
                mnglist.message('A data final do responsável deve ser maior que a data final vigencia!!', "danger");
                return false;
            }

            return true;
        }

        /**
         * Inclui um novo item na lista
         */
        $('#incluir').click(function() {
            if(!validaDateTime()) {
                return false;
            }

            mnglist.addItem({
                id  : $$(transp.idResponsavel).val(),
                ini : $$(transp.vrIni).val(),
                fim : $$(transp.vrFim).val(),
                nome: $$(transp.nome).val()
            });

            mnglist.atualiza();
            $$('clean_' + transp.nome).find('button').click();
        });

        $(document).on('click', '.editar-item-resp', function() {
            var id = $(this).data('id');
            item   = mnglist.getItemBy(id);
            if(!item) {
                return false;
            }

            $(this).closest('tr').addClass('warning');

            $$(transp.idResponsavel).val(item.id);
            $$(transp.vrIni).val(item.ini);
            $$(transp.vrFim).val(item.fim);
            $$(transp.nome).val(item.nome);

            $('#include-buttons').hide();
            $('#edit-buttons').show();
            editando = true;
        });

        $('#cancelar-edit').click(function() {
            editando = false;
            $('#lista').find('.warning').removeClass('warning');
            mnglist.message('Cancelando edição');
            $$('clean_' + transp.nome).find('button').click();
            $('#edit-buttons').hide();
            $('#include-buttons').show();
        });

        $('#salvar-edit').click(function() {
            var id = $$(transp.idResponsavel).val();
            mnglist.editItem({
                id : $$(transp.idResponsavel).val(),
                ini: $$(transp.vrIni).val(),
                fim: $$(transp.vrFim).val()
            });
            mnglist.atualiza();

            $('#cancelar-edit').click();
        });



    });
