<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

echo '<h4>', $title, '</h4>';


if($entity AND $entity->getPpra()):
?>
    <table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tbody>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 40mm; text-align: center;">Local da Atividade:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $entity->getPpra()->getAtividade();?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Acompanhante:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Data da visita:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;"></td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 25mm; text-align: center;">Horário:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;"></td>
            </tr>
        </tbody>
    </table>

<?
endif;