<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

//echo '<h4>', $title, '</h4>';

if($entity AND $entity->getPpra()):
    $linhas = explode(PHP_EOL, $entity->getPpra()->getHistoria());
?>
    <p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12pt; line-height: 115%; font-family: Arial, sans-serif;">A empresa </span>
        <strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: 'Times New Roman'; color: navy; mso-fareast-language: PT-BR;">
            <?= $entity->getPpra()->getEmpresa('razaoSocial');?>
            , 
        </span></strong>
<?
    $qtd = 0;
    foreach ($linhas as $linha):
        if($qtd > 0):
?>
    </p>
    <p class="MsoNormal" style="text-align: justify;">
<?       
        endif;
        $qtd++;
?>
        <span style="font-size: 12pt; line-height: 115%; font-family: Arial, sans-serif;"> 
            <?= $linha;?>
        </span>        
<?        
    endforeach;
?>
    </p>
<?
endif;