<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

echo '<h4>', $title, '</h4>';


if($entity AND $entity->getPpra()):
?>
    <table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tbody>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 40mm; text-align: center;">Construção:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $entity->getPpra()->getConstrucao();?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Piso e Forro:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $entity->getPpra()->getPisoForro();?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Iluminação:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $entity->getPpra()->getIluminacao();?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Ventilação:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $entity->getPpra()->getVentilacao();?></td>
            </tr>
        </tbody>
    </table>

<?
endif;