<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

$locais = [];
if($entity AND $entity->getPpra()){
    $locais = $entity->getPpra()->getLocais();
}
!is_array($locais) && $locais = [];
$item = 1;
foreach ($locais as $seq => $local) : 
$item++;
if($item > 2){
    echo '<p class="pagebreak"></p>' . PHP_EOL;
}
if($item > 2):
?>
<font style='font-size: 14pt; margin-left: 20px; padding: 0px;'><b>&nbsp;3.<?= $item;?> - ELABORAÇÃO</b></font>
<? 
endif;
?>
    <table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tbody>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 40mm; text-align: center;height: 45px;">Local da Atividade:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['local'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Responsável:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['responsavel'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Acompanhante:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['acompanhante'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Data da visita:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;<?= $local['data'];?></td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 25mm; text-align: center;">Horário:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; width: 25mm;">&nbsp;<?= $local['horario'];?></td>
            </tr>
        </tbody>
    </table>
<?php
    $item++;
?>
<font style="font-size: 14pt; margin-left: 20px; padding: 0px;"><b>&nbsp;3.<?= $item;?> - CARACTERÍSTICAS DA EMPRESA</b></font>
    <table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tbody>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 40mm; text-align: center;height: 45px;">Construção:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['construcao'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Piso e Forro:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['pisoForro'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Iluminação:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['iluminacao'];?></td>
            </tr>
            <tr>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;height: 45px;">Ventilação:</td>
                <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;" colspan="3"><?= $local['ventilacao'];?></td>
            </tr>
        </tbody>
    </table>
<?
endforeach;