<?php
/* @var $table \Application\View\Helper\Table */
/*@var $entity \Tcmed\Entity\LiberacaoExame*/
$entity = $this->data["entity"];
$tipo = $this->param($entity->getExameTipo(), "FC_tipo_exame");
$date = date('d/m/Y - H:i');
if("LI" == $entity->getStatusLiberacao()){
    echo <<<EOF
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Conforme contato telefônico foi liberado exame de acordo com os dados abaixo,
        favor nos encaminhar relação dos funcionários ativos do condomínio para inclusão no PCMSO.
    </p>
EOF;
}
if("LA" == $entity->getStatusLiberacao()){
    echo <<<EOF
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Conforme contato telefônico foi liberado exame AVULSO de acordo com os dados abaixo.
EOF;
}
echo <<<EOF
</p>
<br>
<br>
<p>Funcionário: {$entity->getNomeFuncionario()}</p>
<p>Tipo Exame: {$tipo}</p>
<p>Data Liberação: {$entity->getCreatedAt()}</p>
<p>Condomínio: {$entity->getNomeEmpresa()}</p>
<p>CNPJ: {$entity->getCnpj()}</p>
<p>Obs: {$entity->getComentario()}</p>
<br><br><br>
<p>Tel: (11) 3226-7002</p>
<p>email: pcmso@vilavelha.com.br</p>
<br><br><br>
EOF;
    