<?php
/* @var $entity \Tcmed\Entity\LiberacaoExame */
/* 
 * @author Paulo Watakabe <watakabe05@gmail.com>
 * @since 03-03-2016
 */
$controller = 'liberacaoExames';
$route      = 'tcmed/default';
$entity     = $this->entity;
?>
<h1>Redirecionando para agenda Vezes <? echo $entity ? $entity->getExportado() : 'fail' ?></h1>
<script lang="javascript">
    $(function () {
        var id      = "<? echo $entity ? $entity->getFuncionario()->getId() : '' ?>";
        var tipoCon = "<? echo $entity ? $entity->getExameTipo()            : '' ?>";
        if(id !== ""){
            $.processa({
                url : "/tcmed/AgendaAmbuls/index",
                type: "POST",
                savePage: false,
                data: {
                  idFuncionario: id,
                  tipoConsulta: tipoCon
                }
            });
        }
    });
</script>