<?php
/* @var $table \Application\View\Helper\Table */
/* @var $table \Application\View\Helper\Param */
/* 
 * @author Paulo Watakabe <watakabe05@gmail.com>
 * @since 23-02-2016
 */
$table      = $this->table();
$param      = $this->param();
$controller = 'liberacaoExames';
$route      = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1><?= $this->dataView['titulo']; ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
    $lambdaLiberado = function($value, $data) {
        echo '<td nowrap>',
        '<span class="hand" onClick="edit(\'', $value, '\')" title="Editar"><i class="fa fa-pencil"></i> Edit','</span>&nbsp;', PHP_EOL,
        '<br />',
        '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> Del</span>',
        '<br />',
        '<span class="hand exportar" title="Expotar para Agenda"><i class="fa fa-stethoscope"></i> Exp</span>',
        '<br />',
        '<span class="hand lib-email" title="Enviar email"><i class="fa fa-envelope-o"></i> Ema</span>',
        '</td>';
    };
    $lambda = function($value, $data) {
        echo '<td nowrap>',
        '<span class="hand" onClick="edit(\'', $value, '\')" title="Editar"><i class="fa fa-pencil"></i> Edit','</span>&nbsp;', PHP_EOL,
        '<br />',
        '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> Del</span>',
        '</td>';
    };
$table->openTable(TRUE);
$table->renderThead([
    'Ação',
    'Status/ Exportado', 
    'Data/Hora', 
    'Exame', 
    'Administradora', 
    'Empresa', 
    'Endereço Empresa', 
    'Funcionario', 
    'CPF/RG', 
    'Cargo', 
    'Incluido', 
    'Alterado', 
    'Decisão', 
    'Comentario', 
]);
$table->setEditLine('first');
/* @var $entity \Tcmed\Entity\LiberacaoExame */
foreach ($this->data as $entity) {
    // Exporta somente quando esta liberado com empresa e funcionario devidamente cadastrado
    if($entity->getEmpresa() AND $entity->getFuncionario() AND "LI" === $entity->getStatusLiberacao()|| "LA" === $entity->getStatusLiberacao()){
        $table->setLambda($lambdaLiberado);    
    }else{
        $table->setLambda($lambda);    
    }
    $table->renderLine([
        $entity->getId(),
        $param($entity->getStatusLiberacao(),'status_Liberacao') .'<br />Exp. '. $entity->getExportado('str'),
        $entity->getCreatedAt('full'),
        $param($entity->getExameTipo(),'FC_tipo_exame'),
        $entity->getAdministradora()->getRazaoSocial(),
        $entity->getNomeEmpresa(),
        $entity->getEndereco(),
        $entity->getNomeFuncionario(),
        $entity->getCpfFun() . ' /' . $entity->getRg(),
        $entity->getOcupacao()->getCargo(true)->getCargo(),
        $entity->getCreatedBy()->getNome() . '<br />' .  $entity->getCreatedAt('full'),
        $entity->getUpdatedBy() ? $entity->getUpdatedBy()->getNome() . '<br />' .   $entity->getUpdatedAt('full') : '-',
        $entity->getLiberadoBy() ? $entity->getLiberadoBy()->getNome() . '<br />' .   $entity->getLiberadoAt('full') : '-',
        $entity->getComentario(),
    ], 'id="' . $entity->getId() . '"');
}
$table->renderCloseTable();
?>
<br />
<div id="exportandoParaAgendaAmbulatorio"></div>
<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    $(function () {


        $('.exportar').click(function(){
            var $span = $(this);
            var id    = $span.closest('tr').attr('id');
            var msg = "Deseja mesmo colocar esse funcionario na agenda ?";
            if (!confirm(msg)) {
                return;
            }
            var data = {
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'exporta'), [], FALSE, FALSE); ?>" + "/" + id,
                ret: "#exportandoParaAgendaAmbulatorio"
            };
            $.processa(data);
        });
        
        $('.lib-email').click(function(){
            var $span = $(this);
            var id    = $span.closest('tr').attr('id');
            var msg = "Deseja mesmo reenviar esse email ?";
            if (!confirm(msg)) {
                return;
            }
            var data = {
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'email'), [], FALSE, FALSE); ?>" + "/" + id,
                savePage: false,
                callback : function(data){
                    if(data == 'ok'){
                        $.notify({
                            message : "Email enviado com sucesso !!!",
                            type    : "success"
                        });
                    }else{
                        $.notify({
                            message : "Falha ao enviar email !!! " + data,
                            type    : "error"
                        });                        
                    }
                }
            };
            $.processa(data);
        });
    });
    
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>