<h3><?php echo $this->dataView['titulo']; 
$controller = 'cidades';
$route = 'end/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Cidades:');
    $fh->openCol('12')->text('cidadeCodigo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('ufCodigo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('cidadeDescricao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('cidadeCep')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
