<?php
/*
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 * 
 */ 
/* @var $table \Application\View\Helper\Table */
/* @var $param \Application\View\Helper\Param */

$table = $this->table();
$param = $this->Param();
$controller = 'consultaExameCompls';
$route = 'tcmed/default';
?>
<?php
$table->openTable(TRUE);

//Exames	Data	Ficha Cli.	Nome	Observação	Alt/Nor	Ação   

$table->renderThead([
    'Exames', 
    'Data', 
    'Observação', 
    'Alt/Nor', 
    'Ficha Cli.', 
    'Incluido', 
    'Ação'
]);
$lambda = function ($value,$data){
    echo "\t<td nowrap>",
            '<span class="hand edtConExaCom" data-id="', $value, '" title="Editar"><i class="fa fa-pencil"></i> Edit','</span>&nbsp;', PHP_EOL,
            '<span class="hand rmvConExaCom" data-id="', $value, '" title="Deletar"><i class="fa fa-trash"></i> Del</span>',
         "</td>", PHP_EOL;  
};
$lambdaForAudiometria = function ($value,$data){
    echo "\t<td nowrap>",
            '<span class="hand edtConExaCom" data-id="', $value, '" title="Editar"><i class="fa fa-pencil"></i> Edit','</span>&nbsp;', PHP_EOL,
            '<span class="hand rmvConExaCom" data-id="', $value, '" title="Deletar"><i class="fa fa-trash"></i> Del</span>',
            '<span class="hand" onClick="showFormAudiometriaOf(\'', $value, '\')" title="Exibir Audiometria"><i class="fa fa-file-image-o"></i> Exib</span>',
         "</td>", PHP_EOL;  
};

/* @var $entity \Tcmed\Entity\ConsultaExameCompl */
foreach ($this->data as $entity) {
    if(strtoupper($entity->getExameCompl()->getExame()) === "AUDIOMETRIA"){
        $table->setLambda($lambdaForAudiometria);
    }else{
        $table->setLambda($lambda);
    }
    $table->renderLine([
        $entity->getExameCompl()->getExame(),
        $entity->getData(),
        $entity->getObservacao(),
        $param($entity->getResultado()  ,'ExameComplResultado'),
        $entity->getConsulta()->getId(),
        $entity->getCreatedAt(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<style>

div.fixed {
    position: fixed;
    left: 15px;
    top: 50px;
    overflow: scroll;
    border: 1px solid #31b0d5;
    z-index: 100000;
    background-color: #ffffff;
}

</style>
<div id="showAudiometriaForm" class="fixed"></div>
<script lang="javascritp">  

    var showFormAudiometriaOf = function(ConsultaExameCompl){
        console.log(ConsultaExameCompl);
        var obj = {
            url  : "<?php echo $this->url('tcmed/default', array('controller' => 'audiometrias', 'action' => 'show'), [], FALSE, FALSE); ?>/" + ConsultaExameCompl ,
            ret  : "#showAudiometriaForm"
        };
        action.processa(obj);
        $('#showAudiometriaForm').height($(document).height() * 0.90);
        $('#showAudiometriaForm').width($(document).width() * 0.98);
        $('#showAudiometriaForm').show(); 
    };   
    
    $(function(){
        /**
         * Ocultar div da visualização do form de audiometria
         */
        $('#showAudiometriaForm').hide();    
        
        /**
         * função edit já foi configurada globalmente no arquivp partial-form-quick-add de exames complementares
         */
        $('.edtConExaCom').click(function(){
            editConsultaExameComp($(this).data('id'), this);
        });        
        /**
         * função edit já foi configurada globalmente no arquivp partial-form-quick-add de exames complementares
         */
        $('.rmvConExaCom').click(function(){
            delConsultaExameComp($(this).data('id'));
        });        
    });
</script>
