<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;

echo "<h3>{$title}</h3><br />";

/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

$fh->formInit();

$fh->openCol(9)->text('titulo')->closeCol();
$fh->openCol(3)->text('titOrdem')->closeCol();

$fh->formEnd();

// Var de transferencia PHP to JS
$transp = array(

);
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
    });

</script>
