<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;
$partial    = $this->partialObj('application');

/* @var $fh \Applicatgition\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

$fh->formInit();

$ppraVigencia = $fh->getIdFor('ppraVigencia');
$idTit        = $fh->getIdFor('idTit');
$titulo       = $fh->getIdFor('titulo');
$idSub        = $fh->getIdFor('idSub');
$subtitulo    = $fh->getIdFor('subtitulo');
$titOrdem     = $fh->getIdFor('titOrdem');
$subOrdem     = $fh->getIdFor('subOrdem');

//$fh->getIdFor('idTableConfig');
$fh->openCol(4)->text('titulo', [
    'dt-clear' => $idTit . "," . $titOrdem,
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
])->closeCol();

$fh->openCol(2)->text('titOrdem')->closeCol();

$subtituloOpt = (1 == $form->getValue('tipo', 2)) ? 'hideOn' : '';
$fh->openCol(4, ['class' => $subtituloOpt])->text('subtitulo', [
    'dt-clear' => $idSub . "," . $subOrdem . "," . $titulo . "," . $titOrdem . "," . $idTit,
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
])->closeCol();
$fh->openCol(2, ['class' => $subtituloOpt])->text('subOrdem')->closeCol();

$fh->lineDown();

$this->partialObj('tcmed')->partial('ppra-vigencia-textos/partial-imports', $fh, [
    'this'         => &$this,
    'ppraVigencia' => $form->getValue('ppraVigencia')
]);

$fh->lineDown();

$fh->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = compact(
    'texto',
    'ppraVigencia',
    'titulo',
    'idTit',
    'subtitulo',
    'idSub',
    'titOrdem',
    'subOrdem',
    'importaData',
    'verFotos',
    'aparelho',
    'checkFotos'
);
?>
<script src='/js/tinymce/tinymce.min.js'></script>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        /**
         *  Autocompleta o titulo
         */
        $$(transp.titulo).auto({
            serviceUrl: "<?= $this->url($route, array('controller' => $controller, 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            primary: "nome",
            noCache: true,
            filters: function (query) {
                query["rules"] = {
                    inicial       : 1
                    ,ppraVigencia : $$(transp.ppraVigencia).val()
                };
            },
            responseTo: {
                id   : [transp.idTit],
                nome : [transp.titulo],
                ordem: [transp.titOrdem],
            },
            showCols: ['nome', 'ordem']
        });
        /**
         *  Autocompleta o titulo
         */
        $$(transp.subtitulo).auto({
            serviceUrl: "<?= $this->url($route, array('controller' => $controller, 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            primary: "nome",
            noCache: true,
            filters: function (query) {
                query["rules"] = {
                    inicial       : 0
                    ,ppraVigencia : $$(transp.ppraVigencia).val()
                };
            },
            responseTo: {
                id         : [transp.idSub],
                nome       : [transp.subtitulo],
                ordem      : [transp.subOrdem],
                titulo     : [transp.idTit],
                tituloNome : [transp.titulo],
                tituloOrdem: [transp.titOrdem],
            },
            showCols: ['nome', 'ordem']
        });

    });

</script>
