<?php
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
$controller = $dataView['controller'];
$action     = $dataView['action'];
$route      = $dataView['route'];
$ajax       = $dataView['ajax'];



$src = '';
$end = '';
if($ppraVigencia){
    $src = $param('path','hold_dir') . $ppraVigencia->getEmpresa('administradora',['hold',['pathLogo']]);   
    $end = $ppraVigencia->getEmpresa('administradora',['hold',['endereco', ['format']]]); 
}
//$this->mpdf->SetHTMLFooter(
//        '<div class="rodape">'
//        . $end
//        . '</div>');

$oriOld = '';
$number = 1 ;
$quebraPagina = function($opts = [])use($src,$end, &$oriOld, &$number){
    $opt = $opts['exe'] ?? false;
    $ori = $opts['ori'] ?? '';
    $ori = ($ori == 'P') ? '' : $ori ;
    if(!$opt OR $opt == 'close'){
        echo '</div>';
        echo '<div class="rodape',$oriOld,'">' . $end . '<br>pag ' . $number . '</div>';
        echo '</div>';
        $number ++;
    }
    if(!$opt OR $opt == 'open'){
        if($ori == 'L'){
            if(!$opt){
                $this->html = ob_get_clean();
                $this->mpdf->WriteHTML($this->html);   
                ob_start();
                $this->setPagLandescape();
            }
        }else{
            if(!$opt){
                $this->html = ob_get_clean();
                $this->mpdf->WriteHTML($this->html);   
                ob_start();
                $this->setPagPortrait();
            }
        }
        echo ($opt == 'open') ? '<div class="inicioF'.$ori.'">' : '<div class="folha'.$ori.'">';
        echo '<div class="topo',$ori,'">';
        echo "<img style='width: 60mm; height: 20mm;' class='alinhaLogo' src='{$src}' alt='Sem Imagem'>";
        echo '</div>';
        echo '<div class="conteudo',$ori,'">';
    }
};

$checkImg = function($post){
    $checkFotos = $post['checkFotos'];
    !is_array($checkFotos) && $checkFotos = [];
//    if(empty($checkFotos)){
//        echo $post['texto'];
//        return;
//    }

    $allTexto = explode(PHP_EOL, $post['texto']);
    foreach ($allTexto as $key => &$line) {
        if(strpos($line,"<img") === false){
            continue;
        }
//         <img style="width: 100%;" src="../images/get?img=d18e5b437c3fcdd14196b7c970c9d0f8" data-realpath="/var/www/tcmed/data/ppraFotos/ppravigfoto_20170413125622.jpg" />
        $allTexto[$key] = str_replace('src="../images/get?img=', 'data-fakepath="', $allTexto[$key]);
        $allTexto[$key] = str_replace('data-realpath', 'src', $allTexto[$key]);
        $allTexto[$key] = str_replace('height: 100mm;', 'height: 200mm;', $allTexto[$key]);
    }
    echo implode(PHP_EOL, $allTexto);    
};

$laudo   = [];
$pag     = 1 ;
$content = 0 ;
// titulos
foreach ($entitys as $titulo){
//    if(isset($laudo[$pag]['tit'])){
//        throw new Exception('já existe a pagina e titutlo!!');
//    }
    $tit = null;
    if( $titulo->getNome() != 'CAPA' 
    and $titulo->getNome() != 'INDICE' 
    and $titulo->getNome() != 'CRONOGRAMA' 
    and $titulo->getNome() != 'ASSINATURA' 
    and $titulo->getNome() != 'RECOMENDAÇÕES' 
    and $titulo->getNome() != 'ANEXO l' 
    and $titulo->getNome() != 'CROQUIS' 
    and $titulo->getNome() != 'CERTIFICADOS'
    and $titulo->getNome() != 'NÃO EXIBIR'
    ){
        $tit = $titulo->getOrdem() . ' - ' . $titulo->getNome();        
    }
    $laudo[$pag][$content]['tit'] = ['id' => $titulo->getId(), 'tit' => $tit];
    // post dos titulos
    $laudo[$pag][$content]['post'] = [] ;
    foreach ($titulo->listPosts() as $posts){
        $laudo[$pag][$content]['post'][] = ['id' => $posts->getId(),'texto' =>  $posts->getTexto(),'break' =>  $posts->getPageBreak(),'ori' =>  $posts->getOrientacao(), 'checkFotos' => $posts->getCheckFotos()];
        if($posts->getPageBreak()){
            $pag++;
            $content = 0 ;         
        }
    }    
    // sub titulos
    $subCont = 0 ;         
    foreach ($titulo->listSubtitulos() as $subtitulo){
        $laudo[$pag][$content]['subtit'][$subCont]['tit'] =  ['id' => $subtitulo->getId(), 'tit' => $subtitulo->getOrdem() . ' - ' . $subtitulo->getNome()];
        // post dos subtitulos
        $laudo[$pag][$content]['subtit'][$subCont]['post'] = [];
        foreach ($subtitulo->listPosts() as $subpost){
            $laudo[$pag][$content]['subtit'][$subCont]['post'][] = ['id' => $subpost->getId(),'texto' =>  $subpost->getTexto(),'break' =>  $subpost->getPageBreak(),'ori' =>  $subpost->getOrientacao(), 'checkFotos' => $subpost->getCheckFotos()];
            if($subpost->getPageBreak()){
                $pag++;       
                $subCont = $content = 0 ;         
            }
        }
        $subCont++;
    }
    $content++;
}
?>
<style>
 table { 
     border-collapse: collapse; 
 }
 
.folha, .inicioF {
    width            : 195mm;
    height           : 290mm;
    border           : 0px solid #000;
    margin           : 0px;
    padding          : 0px;
    background-color : #fff;
}

h3.titulo {
    font-size: 16pt;
    margin           : 0px;
    padding          : 0px;
}

h4.titulo {
    font-size: 14pt;
    margin           : 0px;
    margin-left      : 20px;
    padding          : 0px;
}

.conteudo{
    height           : 254mm;
    padding          : 0;
    margin           : 0;
    margin-right     : 10px;
    padding-right    : 10px;
    font-size        : 7pt;
}

.rodape{
    padding          : 0;
    padding-right    : 20px;
    text-align       : center
}

.topo{
    padding-left     : 0px;
    padding-right    : 10px;
    height           : 20mm;
}

.folhaL, .inicioFL {
    width            : 295mm;
    height           : 200mm;
    margin           : 0;
    margin-left      : 20px;
    margin-right     : 25px;
    padding          : 0px;
    background-color : #fff;
}

.conteudoL{
    height           : 160mm;
    padding-left     : 10px;
    padding-right    : 10px;
}

.rodapeL{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 10mm;
    display          : table-cell;
    vertical-align   : bottom;
}

.topoL{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 20mm;
}


.p-center{
    width: 100%;
    text-align: center;
}

.alinhaLogo{
    padding-left     : 50px;
}
</style>
    

<?
$first = true;
foreach ($laudo as $pagNum => $pagina): // loop por pagina
    foreach ($pagina as $content) : // loo no conteudo de uma pagina
        $ori = !empty($content['post'])? $content['post'][0]['ori'] : '';
        $first && $quebraPagina(['ori' => $ori, 'exe' =>'open']);
        $first = false;
        if(isset($content['tit'])):
?>
<br>
        <h3 class='titulo'>
            <?=$content['tit']['tit'];?>
        </h3>            
<?
        endif;
        !isset($content['post']) && $content['post'] = [];
        foreach ($content['post'] as $post) : // percorrer todos os post do titulos
?>
            <div style="margin-left: 10px;" class="post">
                <?= $checkImg($post);?>
            </div>
            <? if($post['break']): ?>
                <? 
                    // verifica na proxima pag a posiçao 
                    $next = $laudo[$pagNum + 1][0]['post'][0] ?? '';
                    empty($next) && $next = $laudo[$pagNum + 1][1]['post'][0];
                    // caso na exita um post no titulo da prox pag verifica se tem no subtitulo um post e verifica a posiçao da pagina
                    empty($next) && $next = $laudo[$pagNum + 1][0]['subtit']['post'][0];
                    empty($next) && $next = $laudo[$pagNum + 1][1]['subtit']['post'][0];
    
                    $ori  = $next['ori'] ?? '';   
                    $quebraPagina(['ori' => $ori]); 
                ?>
            <? endif;
        endforeach;
        !isset($content['subtit']) && $content['subtit'] = [];
        foreach ($content['subtit'] as $subCont => $subitem) : // percorrer todos os sub titulos
            if(isset($subitem['tit'])):
?>
<br>
            <h4 class='titulo'>
                <?=$subitem['tit']['tit'];?>
            </h4>
<?
            endif;
            !isset($subitem['post']) && $subitem['post'] = [];
            foreach ($subitem['post'] as $subpost) : // percorrer todos os post do sub titulos
?>
                <div style="margin-left: 15px;" class="post">
                    <?= $checkImg($subpost);?>
                </div>
                <? if($subpost['break']): ?>
                    <? 
                        // verifica na proxima pag a posiçao 
                        $next = $laudo[$pagNum + 1][0]['post'][0] ?? '';
                        empty($next) && $next = $laudo[$pagNum + 1][1]['post'][0];
                        // caso na exita um post no titulo da prox pag verifica se tem no subtitulo um post e verifica a posiçao da pagina
                        empty($next) && $next = $laudo[$pagNum + 1][0]['subtit']['post'][0];
                        empty($next) && $next = $laudo[$pagNum + 1][1]['subtit']['post'][0];

                        $ori  = $next['ori'] ?? '';   
                        $quebraPagina(['ori' => $ori]); 
                    ?>
                <? endif; 
            endforeach;
        endforeach;
    endforeach;
endforeach;
$quebraPagina(['exe'=>'close']);
