<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

?>
<table class="break-line" style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%" cellspacing="0" cellpadding="0">
<thead>
<tr style="background-color: #E6E6E6;">
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding: 5mm; font-weight: bold; font-size: 16pt ; text-align: center; height: 16mm; ">
ITEM
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding: 5mm; font-weight: bold; font-size: 16pt ; text-align: center; height: 16mm; width: 14mm;">
C
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding: 0mm; font-weight: bold; font-size: 16pt ; text-align: center; height: 16mm; width: 14mm;">
N.C.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding: 0mm; font-weight: bold; font-size: 16pt ; text-align: center; height: 16mm; width: 14mm;">
N.A.
</td>
</tr>
</thead>

<tbody>
    
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.3 – Todo local onde existia possibilidade de exposições ao agente biológico deve ter lavatório exclusivo para higiene das mãos provido de água corrente, sabonete líquido, toalha descartável e lixeira provida de sistema de abertura sem contato manual.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.6 – Todos trabalhadores com possibilidade de exposição a agentes biológicos devem utilizar vestimenta de trabalho adequada e em condições de conforto.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.7 – Os equipamentos de Proteção Individual – EPI, descartável ou não, deverão estar a disposição em número suficiente nos postos de trabalho, de forma que seja garantido o imediato fornecimento ou reposição.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.8 – O empregador deve:
<br>a) garantir a conservação e a higienização dos materiais de trabalho;
<br>b) providenciar recipientes e meios de transporte adequados para materiais infectantes, fluídos e tecidos orgânicos.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.10 – Em todo local onde exista a possibilidade de exposição a agentes biológicos, devem ser fornecidos aos trabalhadores instruções escritas, em linguagem acessível, das rotinas realizadas no local de trabalho e medidas de prevenção de acidentes e de doenças relacionadas ao trabalho.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.13 – Os colchões, colchonetes e demais almofadas devem ser revestidos de material lavável e impermeável, permitindo desinfecção e fácil higienização.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.2.4.16 – Devem ser assegurados o uso de materiais perfurocortantes com dispositivo de segurança, conforme cronograma a ser estabelecido pela CTPN.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3 – Dos Riscos Químicos
32.3.1 – Deve ser mantida a rotulagem do fabricante na embalagem original dos produtos químicos utilizados em serviço de saúde.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.2 – Todo recipiente contendo produto químico manipulado ou fracionado deve ser identificado, de forma legível, por etiqueta com o nome do produto, composição química, sua concentração, data de envase e de validade, e nome do responsável pela manipulação ou fracionamento.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.4 – Do Programa de Prevenção de Risco Ambientais – PPRA
32.3.4.1 – No PPRA dos serviços de saúde deve constar inventário de todos os produtos químico, inclusive intermediários e resíduos, com indicação daqueles que impliquem em riscos à segurança e saúde do trabalhador. 
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.7 – Das medidas de proteção 
32.3.7.1 – O empregador deve destinar local apropriado para a manipulação ou fracionamento de produtos químicos que impliquem riscos à segurança e saúde do trabalhador.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.9.3 – Dos Gases e Vapores Anestésicos
32.3.9.3.3 – Os locais onde são utilizados gases ou vapores anestésicos devem ter sistemas de ventilação e exaustão, com o objetivo de manter a concentração ambiental sob controle, conforme previsto na legislação vigente.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.9.4.2 – O vestiário deve dispor de:
<br>a) pia e material para secar as mãos;
<br>b) lava olhos, o qual pode ser substituído por uma ducha tipo higiênica;
<br>c) chuveiro de emergência;
<br>d) equipamentos de proteção individual e vestimentas para uso e reposição;
<br>e) armários para guarda de pertences;
<br>f) recipientes para descarte de vestimentas usadas.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.9.4.5 – A sala de preparo deve ser dotada de Cabine de Segurança Biológica Classe II B2 e na sua instalação devem ser previstos, no mínimo:
<br>a) suprimento de ar necessário ao seu funcionamento;
<br>b) local e posicionamento, de forma a evitar a formação de turbulência aérea.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.3.9.4.7 – Além do cumprimento do disposto na legislação vigente, os Equipamentos de Proteção Individual – EPI deve atender as seguintes exigências:
<br>a) ser avaliados diariamente quanto ao estado de conservação e segurança;
<br>b) estar armazenados em locais de fácil acesso e em quantidade suficiente para a imediata substituição, segundo as exigências do procedimento ou em caso de contaminação ou danos.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4 – Das Radiações Ionizantes
32.4.1 – O atendimento das exigências desta NR, com relação ás radiações ionizantes, não desobriga o empregador de observar as disposições estabelecidas pelas normas especificas da Comissão Nacional de Energia Nuclear – CNEN e da Agência Nacional de vigilância Sanitária – ANVISA, do Ministério da Saúde.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.5.2 – A movimentação individual externa, de corpo inteiro ou de extremidades, deve ser feita através de dosimetria com periodicidade mensal e levando-se em conta a natureza e a intensidade das exposições normais e potenciais previstas.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.12 – As áreas da instalação radiativa devem estar devidamente sinalizadas em conformidade com a legislação em vigor, em especial quanto aos seguintes aspectos:
<br>a) utilização do símbolo internacional de presença de radiação nos acessos controlados;
<br>b) as fontes presentes nestas áreas e seus rejeitos devem ter as suas embalagens, recipientes ou blindagens identificadas em relação ao tipo de elemento radioativo, atividade e tipo emissão;
<br>c) valores das taxas de dose e datas de medição em pontos de referência significativos, próximos ás fontes de radiação, nos locais de permanência e de trânsito dos trabalhadores, em conformidade com o disposto no PPR;
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.14 – Dos Serviços de Radioterapia
<br>32.4.14.1 – Os serviços de Radioterapia devem adotar, no mínimo, os seguintes dispositivos de segurança:
<br>a) salas de tratamento possuindo portas com sistemas de intertravamento, que previnam o acesso indevido de pessoas durante a operação do equipamento;
<br>b) indicadores luminosos de equipamento em operação, localizados na sala de tratamento e em seu acesso externo, em posição visível.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.15 – Dos Serviços de Radiodiagnóstico Médico
32.4.15.1 – È obrigatório manter no local de trabalho e á disposição da inspeção do trabalho o Alvará de Funcionamento vigente concedido pela autoridade sanitária local e o Programa de Garantia da Qualidade.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.15.2 – A cabine de comando deve ser posicionada de forma a:
<br>a) permitir ao operador, na posição de disparo, eficaz comunicação e observação visual do paciente;
<br>b) permitir que o operador visualize a entrada de qualquer pessoa durante o procedimento radiológico.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.4.15.3 – A sala de raios X deve dispor de:
<br>a) sinalização visível na face exterior das portas de acesso, contendo o símbolo internacional de radiação ionizante, acompanhado das inscrições: “raios X, entrada restrita” ou “raios X, entrada proibida a pessoas não autorizadas”.
<br>b) sinalização luminosa vermelha acima de face externa da porta de acesso, acompanhada do seguinte aviso de advertência: “Quando a luz vermelha estiver acesa, a entrada é proibida”. A sinalização luminosa deve ser acionada durante os procedimentos radiológicos.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.5 – Dos Resíduos
<br>32.5.1 – Cabe ao empregador capacitar, inicialmente e de forma continuada, os trabalhadores nos seguintes assuntos:
<br>a) segregação, acondicionamento e transporte dos resíduos;
<br>b) definições, classificações e potencial de risco dos resíduos;
<br>c) sistema de gerenciamento adotado internamente no estabelecimento;
<br>d) formas de reduzir a geração de resíduos;
<br>e) conhecimento das responsabilidades e de tarefas;
<br>f) reconhecimento dos símbolos de identificação das classes de resíduos;
<br>g) conhecimento sobre a utilização dos veículos de coleta;
<br>h) orientações quanto ao uso de Equipamentos de Proteção Individual – EPI’s.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.5.4 – O transporte manual do recipiente de segregação deve ser realizado de forma que não exista o contato do mesmo com outras partes do corpo, sendo vedado o arrasto.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.5.6 – A sala do armazenamento temporário dos recipientes de transporte deve atender, no mínimo, ás seguintes características:
I. ser dotada de:
<br>a) pisos e paredes laváveis;
<br>b) ralo sifonado;
<br>c) ponto de água;
<br>d) ponto de luz;
<br>e) ventilação adequada;
<br>f) abertura dimensionada de forma a permitir a entrada dos recipientes de transporte
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.5.7 – O transporte dos resíduos para a área de armazenamento externo deve atender aos seguintes requisitos:
<br>a) ser feito através de carros constituídos de material rígido, lavável, impermeável, provido de tampo articulado ao próprio corpo do equipamento e cantos arredondados;
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.5.8 – Em todos os serviços de saúde deve existir local apropriado para o armazenamento externo dos resíduos, até que sejam recolhidos pelo sistema de coleta externa.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.6 – Das Condições de Conforto por Ocasião das Refeições
<br>32.6.2 – Os estabelecimentos com até 300 trabalhadores devem ser dotados de locais para refeição, que atendam aos seguintes requisitos mínimos:
<br>a) localização fora da área do posto de trabalho;
<br>b) piso lavável;
<br>c) limpeza, arejamento e boa iluminação;
<br>d) mesas e assentos dimensionados de acordo com o número de trabalhadores por intervalo de descanso e refeição;
<br>e) lavatórios instalados nas proximidades ou no próprio local;
<br>f) fornecimento de água potável;
<br>g) possuir equipamento apropriado e seguro para aquecimento de refeições.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.8. – Da Limpeza e Conservação
32.8.1 – Os trabalhadores que realizam a limpeza dos serviços de saúde devem ser capacitados, inicialmente e de forma continuada, quanto aos princípios de higiene pessoal, risco biológico, risco químico, sinalização, EPI, EPC e procedimentos em situações de emergência.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
<tr>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; padding-left: 2mm; text-align: justify;">
32.8.2 – Para as atividades de limpeza e conservação, cabe ao empregador, no mínimo:
<br>a) providenciar carro funcional destinado á guarda e transporte dos materiais e produtos indispensáveis á realização das atividades;
<br>b) providenciar materiais e utensílios de limpeza que preservem a integridade física do trabalhador;
<br>c) proibir a varrição seca áreas internas;
<br>d) proibir o uso de adornos.
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">
X
</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
<td style="border-bottom: 1px solid #000;border-right: 1px solid #000; font-weight: bold; font-size: 16pt ; text-align: center;">

</td>
</tr>
</tbody>
</table>