<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $param \Application\View\Helper\Param */
$param = $this->Param();
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;
/* @var $emp \Tcmed\Entity\Empresa */
$emp          = $entity->getEmpresa();
?>


<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
    <tbody>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">Equipamento de Proteção Individual</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">Termo de Responsabilidade<br>NR6 Portaria 3214/78</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">Funcionário</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">Registro</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">Setor</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">Função</td>
        </tr>
        <tr>
            <td style="border-right: 1px solid #000;" colspan="2">
                Recebi da empresa <strong><?= $emp->getRazaoSocial();?></strong>. Para uso exclusivo a serviço, os equipamentos de proteção individual, relacionados nesta ficha, tendo recebido orientação de como utilizá-los e estando ciente de que:
            </td>
        </tr>
        <tr>
            <td style="border-right: 1px solid #000;" colspan="2">
                1º) Os equipamentos ficarão sob a minha responsabilidade, comprometendo-me a conservá-lo e mantê-los em ordem.
            </td>
        </tr>
        <tr>
            <td style="border-right: 1px solid #000;" colspan="2">
                2º) Em caso de dano do Equipamento de Proteção Individual, causado por uso inadequado, mau uso ou negligência, a empresa fornecerá um novo equipamento, mediante cobrança do valor de um da mesma marca ou equivalente ao da praça.
            </td>
        </tr>
        <tr>
            <td style="border-right: 1px solid #000;" colspan="2">
                3º) No Caso de rescisão de contrato de trabalho, farei a devolução do EPI’s em perfeito estado de conservação considerando-se o tempo de uso dos mesmos. 
            </td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000; border-right: 1px solid #000;" colspan="2">
                4º) Quando da não utilização dos EPI’s em serviço, estarei sujeito a sanções disciplinares cabíveis que irão desde <strong>simples advertência até dispensa por justa causa.</strong>
            </td>
        </tr>
    </tbody>
</table>
<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Descrição do E. P. I.</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Data da<br>Entrega</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">C. A.</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">Assinatura</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">&nbsp;</td>
        </tr>
    </tbody>
</table>