<?php
$controller   = $this->dataView['controller']; 
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $param \Application\View\Helper\Param */
$param = $this->Param();
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;
/* @var $emp \Tcmed\Entity\Empresa */
$emp          = $entity->getEmpresa();
?>
<h1 style="text-align: center; font-size: 38pt; font-weight: bold;">PPRA</h1>

<br>
<br>
<br>
<h2 style="text-align: center; font-size: 22pt; font-weight: bold;">
    PROGRAMA DE PREVENÇÃO DE<BR>
    RISCOS AMBIENTAIS<br>
    <span style="font-size: 18pt; font-weight: normal;">Portaria Nº 25 de 29/12/1994 e NR-9 do Mtb</span>
</h2>

<br>
<br>
<br>
<h3 style="text-align: center; font-size: 18pt; color: #2e6da4;">
    <?= $emp->getRazaoSocial();?>
</h3>

<br>
<br>
<br>
<div style="text-align: center;">
<?
if($emp) {
    $path = $param('path','empresa_dir') . $emp->getId() . DIRECTORY_SEPARATOR  .  $emp->getPathLogo();   
    $src  = $this->Image($path, true);
    echo PHP_EOL . '<img style="max-width: 100mm;" src="' . $src . '" data-realpath="' . $path . '" />' . PHP_EOL;
}
?>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="font-size: 12pt; font-weight: bold; text-align: right; padding-right: 10MM;">
    São Paulo - SP<br>
    <?= $param(date('m'),'selectMes') . '/' . date('Y');?>
</div>