<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;

?>
<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
    <tbody>
        <tr>
            <td style="line-height: 4; border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; font-weight: bold; font-style: italic; text-align: center;" colspan="2">QUADRO I – Índice de Classificação da Agressividade ou Toxidade ao Agente Ambiental</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;" colspan="2"></td>
        </tr>
        <tr>
            <td style="line-height: 3; border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center; background-color: #E6E6E6;" colspan="2">AGRESSIVIDADE</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; width: 15%; text-align: center; ">ÍNDICE</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">DESCRIÇÃO</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">0</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O EFEITO É MUITO LIMITADO</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O EFEITO É MODERADO E REVERSÍVEL</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">2</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O EFEITO É MÉDIO OU ELEVADO E IRREVERSÍVEL</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">3</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O EFEITO É GRAVE E IRREVERSÍVEL – CARCINOGÊNICO, TERATOGÊNCIO – RISCO INCAPACITANTE</td>
        </tr>
    </tbody>
</table>
<br>
<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
    <tbody>
        <tr>
            <td style="line-height: 4; border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; font-weight: bold; font-style: italic; text-align: center;" colspan="2">QUADRO II – Índice de Classificação da Exposição do Agente Ambiental</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;" colspan="2"></td>
        </tr>
        <tr>
            <td style="line-height: 3; border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center; background-color: #E6E6E6;" colspan="2">EXPOSIÇÃO</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center; width: 15%;">ÍNDICE</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">DESCRIÇÃO</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">0</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O CONTATO É MUITO LIMITADO OU CASUAL</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O CONTATO É LIMITADO E POUCO FREQUENTE</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">2</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O CONTATO OCORRE COM RELATIVA FREQUÊNCIA</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">3</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000;">QUANDO O CONTATO E ELEVADO E FREQUENTE</td>
        </tr>
    </tbody>
</table>
<br>
<table>
    <tr>
        <td>
    Entrando com a somatória dos índices de agressividade e exposição dos Quadros I e II estabelece-se às prioridades para avaliação quantitativa e adoção das medidas de controle.
        </td>
    </tr>
</table>
<br>
<table style="border-top: 1px solid #000;border-left: 1px solid #000;margin: 0; padding: 0; width: 100%">
    <tbody>
        <tr>
            <td style="line-height: 4; border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; font-weight: bold; font-style: italic; text-align: center;" colspan="2">QUADRO III– Prioridades de Avaliação Quantitativa e Controle</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;" colspan="2"></td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center; width: 50%;">SOMATÓRIA DA CLASSIFICAÇÃO</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; text-align: center;">GRADUAÇÃO DA PRIORIDADE</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">0</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">BAIXA</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">1 a 3</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">MEDIA BAIXA</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">4 a 5</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">MEDIA ALTA</td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">6</td>
            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;">ALTA</td>
        </tr>
    </tbody>
</table>