<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $param \Application\View\Helper\Param */
$param = $this->Param();
/* @var $entity \Tcmed\Entity\PpraVigencia */
$entity       = $this->entity;
/* @var $emp \Tcmed\Entity\Empresa */
$emp          = $entity->getEmpresa();

$indice = [];
$pag    = 1 ;
// titulos
foreach ($entitys as $titulo){
    if($titulo->getNome() == 'CAPA' OR $titulo->getNome() == 'INDICE'){
        $pag ++;
        continue;
    } 
    if($titulo->getNome() == 'CRONOGRAMA'){
        $titulo->setNome('CRONOGRAMA DE AÇÕES GLOBAIS ' . date('Y') . '/' . (date('Y') + 1));
    }
    $indice[$titulo->getOrdem() . ' - ' . $titulo->getNome()] = $pag;
    // post dos titulos
    foreach ($titulo->listPosts() as $posts){
        if($posts->getPageBreak()){
            $pag++;
        }
    }    
    // sub titulos
    foreach ($titulo->listSubtitulos() as $subtitulo){
        // post dos subtitulos
        foreach ($subtitulo->listPosts() as $subpost){
            if($subpost->getPageBreak()){
                $pag++;                
            }
        }
    }
}

?>
<h3 style="text-align: center; font-size: 18pt; color: #2e6da4;">INDICE</h3>
<table style="border-top: 1px solid #000; border-left: 1px solid #000; margin: 0; padding: 0; width: 100%">
    <tbody>
        <tr>
            <td style="line-height: 2; border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; font-weight: bold; text-align: center; line-height: 40px;">Título</td>
            <td style="line-height: 2; border-bottom: 1px solid #000;border-right: 1px solid #000; background-color: #E6E6E6; font-weight: bold; text-align: center;">Página</td>
        </tr>
        <?
        foreach ($indice as $item => $pag):
        ?>
        <tr>
            <td style="line-height: 2; border-bottom: 1px solid #000;border-right: 1px solid #000; line-height: 35px;" >&nbsp;<?= $item;?></td>
            <td style="line-height: 2; border-bottom: 1px solid #000;border-right: 1px solid #000; text-align: center;" ><?= $pag;?></td>
        </tr>
        <?
        endforeach;
        ?>
    </tbody>
</table>