<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$entity     = $this->entity;
/* @var $ppraVigencia \Tcmed\Entity\PpraVigencia */
$ppraVigencia = $this->ppraVigencia;
$partial    = $this->partialObj('application');
/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $titulo \Tcmed\Entity\PpraVigenciaTitulo */
/* @var $posts    \Tcmed\Entity\PpraVigenciaPost */
/* @var $subpost  \Tcmed\Entity\PpraVigenciaPost */
$img = '';
$end = '';
if($ppraVigencia){
    $src = $this->Param('path','hold_dir') . $ppraVigencia->getEmpresa('administradora',['hold',['pathLogo']]);   
    $img = $this->Image($src);
    $end = $ppraVigencia->getEmpresa('administradora',['hold',['endereco', ['format']]]); 
}
$oriOld = '';
$quebraPagina = function($opts = [])use($img,$end, &$oriOld){
    $opt = $opts['exe'] ?? false;
    $ori = $opts['ori'] ?? '';
    $id  = $opts['id' ] ?? '0';
    $ori = ($ori == 'P') ? '' : $ori ;
    if(!$opt OR $opt == 'close'){
        echo '</div>';
        echo '<div class="rodape', $oriOld, '">';
        echo $end;
        echo '</div>';
        echo '</div>';
    }
    if(!$opt OR $opt == 'open'){
        echo '<div class="folha', $ori, '">';
        echo '<div class="topo', $ori, '">';
        echo "<img style='width: 60mm; height: 20mm;' src='{$img}' alt='Sem Imagem'>";
        echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
        echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
        echo '<i class="change-orientacao fa fa-refresh hand" title="Alternar a posição de Paisagem para Retrato e vice e versa" data-id="', $id, '"></i>';
        echo '</div>';
        echo '<div class="conteudo', $ori, '">';
        $oriOld = $ori;
    }
};


$laudo   = [];
$pag     = 1 ;
$content = 0 ;
// titulos
foreach ($entities as $titulo){
//    if(isset($laudo[$pag]['tit'])){
//        throw new Exception('já existe a pagina e titutlo!!');
//    }
    $laudo[$pag][$content]['tit'] = ['id' => $titulo->getId(), 'tit' => $titulo->getOrdem() . ' - ' . $titulo->getNome()];
    // post dos titulos
    $laudo[$pag][$content]['post'] = [] ;
    foreach ($titulo->listPosts() as $posts){
        $laudo[$pag][$content]['post'][] = ['id' => $posts->getId(),'texto' =>  $posts->getTexto(),'break' =>  $posts->getPageBreak(),'ori' =>  $posts->getOrientacao()];
        if($posts->getPageBreak()){
            $pag++;
            $content = 0 ;         
        }
    }    
    // sub titulos
    $subCont = 0 ;         
    foreach ($titulo->listSubtitulos() as $subtitulo){
        $laudo[$pag][$content]['subtit'][$subCont]['tit'] =  ['id' => $subtitulo->getId(), 'tit' => $subtitulo->getOrdem() . ' - ' . $subtitulo->getNome()];
        // post dos subtitulos
        $laudo[$pag][$content]['subtit'][$subCont]['post'] = [];
        foreach ($subtitulo->listPosts() as $subpost){
            $laudo[$pag][$content]['subtit'][$subCont]['post'][] = ['id' => $subpost->getId(),'texto' =>  $subpost->getTexto(),'break' =>  $subpost->getPageBreak(),'ori' =>  $subpost->getOrientacao()];
            if($subpost->getPageBreak()){
                $pag++;       
                $subCont = $content = 0 ;         
            }
        }
        $subCont++;
    }
    $content++;
}

?>
<h3><?php echo $title ?></h3>
<br />
<button id="addTexto" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Novo</button>
<button id="goTop" class="btn btn-info"><span class="glyphicon glyphicon-chevron-up"></span> Topo da página</button>
<div class='row'>
    <div class="col-md-12">
        <?
        $fh->setHorizontal(TRUE);
        $fh->openCol(6)->select('modelo')->closeCol();
        $inpModelo = $fh->getLastId();
        $fh->setHorizontal(FALSE);
        ?>
        <button id="loadModelo" class="btn btn-primary">Carregar modelo</button>
        <button id="addModelo" class="btn btn-success">Novo modelo</button>
    </div>
</div>

<?
$first = true;
foreach ($laudo as $pagNum => $pagina): // loop por pagina
    foreach ($pagina as $content) : // loo no conteudo de uma pagina
        $ori = !empty($content['post'])? $content['post'][0]['ori'] : '';
        $id  = !empty($content['post'])? $content['post'][0]['id'] : '';
        $first && $quebraPagina(['ori' => $ori, 'id' => $id, 'exe' =>'open']);
        $first = false;
        if(isset($content['tit'])):
            
?>
        <h3 class='titulo'>
            <?=$content['tit']['tit'];?>
            <i class='edita-titulo fa fa-pencil hand hideOn' title='Editar'  data-id='<?=$content['tit']['id'];?>'></i>
            <i class='delete fa fa-trash hand hideOn' title='Remover' data-id='<?=$content['tit']['id'];?>' data-tipo='titulo'></i>
        </h3>            
<?
        endif;
        !isset($content['post']) && $content['post'] = [];
        foreach ($content['post'] as $post) : // percorrer todos os post do titulos
?>
            <div style="margin-left: 10px;" class="post">
                <i class='fa fa-pencil hand edit-content hideOn' data-id='<?=$post['id'];?>'></i>
                <i class='delete fa fa-trash hand hideOn' title='Remover texto do titulo' data-id='<?=$post['id'];?>' data-tipo='post'></i>
                <?= empty($post['texto']) ? 'vazio' : $post['texto'];?>
            </div>
            <? if($post['break']): ?>
                <div class="p-center">
                    <i class='rm-page-break fa fa-caret-up hand' title='remover quebra de pagina' data-id='<?=$post['id'];?>'></i>
                </div>
                <? 
                
//    echo '<pre>', var_dump($laudo[$pagNum + 1]), '</pre>';
//    echo '<pre>', var_dump($laudo[$pagNum + 1][1]), '</pre>';
//    echo '<pre>', var_dump($laudo[$pagNum + 1][1]['post']), '</pre>';
//    echo '<pre>', var_dump($laudo[$pagNum + 1][1]['post'][0]), '</pre>';
//    echo '<pre>', var_dump($laudo[$pagNum + 1][1]['post'][0]['ori']), '</pre>';
                    // verifica na proxima pag a posiçao 
                    $next = $laudo[$pagNum + 1][0]['post'][0] ?? '';
                    empty($next) && $next = $laudo[$pagNum + 1][1]['post'][0] ?? '';
                    // caso na exita um post no titulo da prox pag verifica se tem no subtitulo um post e verifica a posiçao da pagina
                    empty($next) && $next = $laudo[$pagNum + 1][0]['subtit']['post'][0] ?? '';
                    empty($next) && $next = $laudo[$pagNum + 1][1]['subtit']['post'][0] ?? '';
    
                    $ori  = $next['ori'] ?? '';   
                    $id   = $next['id']  ?? '';   
                    $quebraPagina(['ori' => $ori, 'id' => $id]); 
                ?>
            <? else : ?>
                <div class="p-center">
                <i class='add-page-break fa fa-caret-down hand' title='inserir quebra de pagina' data-id='<?=$post['id'];?>'></i>
                </div>
            <? endif;
        endforeach;
        !isset($content['subtit']) && $content['subtit'] = [];
        foreach ($content['subtit'] as $subCont => $subitem) : // percorrer todos os sub titulos
            if(isset($subitem['tit'])):
?>
            <h4 class='titulo' style="margin-left: 20px;">
                <?=$subitem['tit']['tit'];?>
                <i class='edita-titulo fa fa-pencil hand hideOn' title='Editar'  data-id='<?=$subitem['tit']['id'];?>'></i>
                <i class='delete fa fa-trash hand hideOn' title='Remover' data-id='<?=$subitem['tit']['id'];?>' data-tipo='titulo'></i>
            </h4>
<?
            endif;
            !isset($subitem['post']) && $subitem['post'] = [];
            foreach ($subitem['post'] as $subpost) : // percorrer todos os post do sub titulos
?>
                <div style="margin-left: 10px;" class="post">
                    <i class='fa fa-pencil hand edit-content hideOn' data-id='<?=$subpost['id'];?>'></i>
                    <i class='delete fa fa-trash hand hideOn' title='Remover' data-id='<?=$subpost['id'];?>' data-tipo='post'></i>
                    <?=$subpost['texto'];?>
                </div>
                <? if($subpost['break']): ?>
                    <div class="p-center">
                    <i class='rm-page-break fa fa-caret-up hand' title='remover quebra de pagina' data-id='<?=$subpost['id'];?>'></i>
                    </div>
                    <? 
                        // verifica na proxima pag a posiçao 
                        $next = $laudo[$pagNum + 1][0]['post'][0] ?? '';
                        empty($next) && $next = $laudo[$pagNum + 1][1]['post'][0] ?? '';
                        // caso na exita um post no titulo da prox pag verifica se tem no subtitulo um post e verifica a posiçao da pagina
                        empty($next) && $next = $laudo[$pagNum + 1][0]['subtit']['post'][0] ?? '';
                        empty($next) && $next = $laudo[$pagNum + 1][1]['subtit']['post'][0] ?? '';

                        $ori  = $next['ori'] ?? '';   
                        $id   = $next['id']  ?? '';  
                        $quebraPagina(['ori' => $ori, 'id' => $id]); 
                    ?>
                <? else: ?>
                    <div class="p-center">
                    <i class='add-page-break fa fa-caret-down hand' title='inserir quebra de pagina' data-id='<?=$subpost['id'];?>'></i>
                    </div>
                <? endif; 
            endforeach;
        endforeach;
    endforeach;
endforeach;
$quebraPagina(['exe'=>'close']);
// Var de transferencia PHP to JS
$transp = array(
    'ppra'         => $this->params['ppra'        ],
    'ret'          => $this->params['ret'         ],
    'ppraVigencia' => $this->params['ppraVigencia'],
    'inpModelo'    => $inpModelo
);
?>
<style>

.folha {
    page-break-before: always;
    width            : 195mm;
    height           : 290mm;
    border           : #000 solid 1px;
    margin           : 25px;
    padding          : 0px;
    background-color : #fff;
}

.conteudo{
    height           : 240mm;
    padding-left     : 10px;
    padding-right    : 20px;
}

.rodape{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 20mm;
    display          : table-cell;
    vertical-align   : bottom;
}

.topo{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 20mm;
}

.folhaL {
    page-break-before: always;
    width            : 295mm;
    height           : 200mm;
    border           : #000 solid 1px;
    margin           : 25px;
    padding          : 0px;
    background-color : #fff;
}

.conteudoL{
    height           : 160mm;
    padding-left     : 10px;
    padding-right    : 10px;
}

.rodapeL{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 10mm;
    display          : table-cell;
    vertical-align   : bottom;
}

.topoL{
    padding-left     : 10px;
    padding-right    : 10px;
    height           : 20mm;
}


.p-center{
    width: 100%;
    text-align: center;
}
</style>

<script type="text/javascript">
    $(function() {
        var transp = <?php echo json_encode($transp) ?>;
        
        $('.change-orientacao').click(function(){
            var $btn = $(this);
            gModal.reset('confirm',2).setMsg('Deseja mesmo alterar a posição da folha de retrato para paisagem ou vice-versa ?').setClickOk(function(){
                $.processa({
                    url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'changeOrientacao'), [], FALSE, FALSE); ?>/" + $btn.data('id'),
                    ret: transp.ret,
                    savePage: false
                });
            }).showModal();
        });
        
        $('#loadModelo').click(function(){
            gModal.confirm('Deseja mesmo continuar?<br>Se você continuar os itens alterados deste texto serão todos substituidos pelo modelo',function(){
                $.processa({
                    url     : "<?= $this->url($route, array('controller' => 'ppraVigenciaModelos', 'action' => 'carregar'), [], FALSE, FALSE); ?>",
                    type    : "POST",
                    savePage: false,
                    ret     : transp.ret,
                    data    : {
                        ppra        : transp.ppra,
                        ppraVigencia: transp.ppraVigencia,
                        modelo      : $$(transp.inpModelo).val(),
                        ret         : transp.ret,
                        getForm     : true
                    }
                });
            });
        });
        
        $('#addModelo').click(function(){
            $.processa({
                url     : "<?= $this->url($route, array('controller' => 'ppraVigenciaModelos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                type    : "POST",
                savePage: false,
                data    : {
                    ppra        : transp.ppra,
                    ppraVigencia: transp.ppraVigencia,
                    subOpcao    : 'loadCad',
                    ret         : transp.ret,
                    getForm     : true
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setSizeModal('lg')
                        .setClickOk(function(){
                            $("#formPpraVigenciaModelo").processa({
                                url: "<?= $this->url($route, array('controller' => 'ppraVigenciaModelos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                                ret: transp.ret,
                                savePage: false,
                                data: {
                                    ppra        : transp.ppra,
                                    ppraVigencia: transp.ppraVigencia
                                }
                            });
                        })
                        .showModal() 
                    ;
                }
            });
        });
        $('#addTexto').click(function() {
            $.processa({
                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'new'), [], FALSE, FALSE); ?>",
                type    : "POST",
                savePage: false,
                data    : {
                    ppra        : transp.ppra,
                    ppraVigencia: transp.ppraVigencia,
                    getForm     : true
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setSizeModal('lg')
                        .setClickOk(function(){

                            $("#formPpraVigenciaTexto").processa({
                                url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'new'), [], FALSE, FALSE); ?>",
                                ret: transp.ret,
                                savePage: false,
                                data: {
                                    texto: tinymce.get('texto').getContent()
                                }
                            });
                        })
                        .showModal()
                    ;
                }
            });
        })
        .css({
            position: 'absolute',
            bottom: '50px',
            left: '50px',
            'z-index': 999999999
        });
        
        $('#goTop').on('click', function() {
        $("#page-wrapper").animate({
            scrollTop: 0
            }, 600);
            return false;
        })
        .css({
            position: 'fixed',
            bottom: '50px',
            right: '50px',
            cursor: 'pointer',
            display: 'none'
            
            
        });
       //botão para o topo
        $("#page-wrapper").scroll(function () {
          if ($(this).scrollTop() != 0) {
            $('#goTop').fadeIn();
          } else {
            $('#goTop').fadeOut();
          }
        }); 


        $('.remove-titulo').click(function() {
            var id = $(this).data('id');
            removeData(id);
        });


        $('.remove-conteudo').click(function() {
            var id = $(this).data('id');
            removeData(id);
        });

        // ==========================================================

        /**
         * Exibe os icones de edição e exclusão do Titulo/Subtitulo quando
         * o mouse estiver em cima do post
         */
        $('.titulo').hover(function() {
            $(this).find('.edita-titulo').show();
            $(this).find('.delete').show();
        }, function() {
            $(this).find('.edita-titulo').hide();
            $(this).find('.delete').hide();
        });

        /**
         * Chama o modal de edição do titulo
         */
        $('.edita-titulo').click(function() {
            var id = $(this).data('id');

            $.processa({
                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'editaTitulo'), [], FALSE, FALSE); ?>/" + id,
                savePage: false,
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setClickOk(function(){

                            $("#formTitulo").processa({
                                url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'editaTitulo'), [], FALSE, FALSE); ?>",
                                ret: transp.ret,
                                savePage: false,
                            });
                        })
                        .showModal()
                    ;
                }
            });
        });

        /**
         * Exibe os icones de edição e exclusão do Post quando o mouse
         * estiver em cima do post
         */
        $('.post').hover(function() {
            $(this).find('.edit-content').show();
            $(this).find('.delete').show();
        }, function() {
            $(this).find('.edit-content').hide();
            $(this).find('.delete').hide();
        });

        /**
         * Chama o modal de edição do post
         */
        $('.edit-content').click(function() {
            var id = $(this).data('id');

            $.processa({
                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'editaPost'), [], FALSE, FALSE); ?>/" + id,
                savePage: false,
                type    : "POST",
                data    : {
                    ppra        : transp.ppra,
                    ppraVigencia: transp.ppraVigencia,
                    titulo      : id,
                    loadTexto   : true
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setSizeModal('lg')
                        .setClickOk(function(){

                            $("#formPost").processa({
                                url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'editaPost'), [], FALSE, FALSE); ?>",
                                ret: transp.ret,
                                savePage: false,
                                data: {
                                    texto: tinymce.get('texto').getContent()
                                }
                            });
                        })
                        .showModal()
                    ;
                }
            });
        });

        $('.delete').click(function() {
            var id   = $(this).data('id'  );
            var tipo = $(this).data('tipo');

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>",
                        savePage: false,
                        type    : "POST",
                        data    : {
                            id  : id,
                            tipo: tipo
                        },
                        ret     : transp.ret,
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover estes dados?')
                .showModal()
            ;
        });

        /**
         * Adiciona quebra de página
         */
        $('.add-page-break').click(function(){
            var id = $(this).data('id');
            gModal.reset('confirm',2)
                .setMsg('Deseja mesmo inserir um quebra de pagina aqui?')
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setClickOk(function(){
                    $.processa({
                        url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'addBreak'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret     : transp.ret,
                    })
                }).showModal();
        });

        /**
         * Remove quebra de página
         */
        $('.rm-page-break').click(function(){
            var id = $(this).data('id');
            gModal.reset('confirm',2)
                .setMsg('Deseja mesmo remover a quebra de pagina daqui?')
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setClickOk(function(){
                    $.processa({
                        url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'rmBreak'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret     : transp.ret,
                    })
                }).showModal();
        });

        function removeData(id) {
            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $.processa({
                        url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>/" + id,
                        savePage: false,
                        ret     : transp.ret,
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente remover estes dados?')
                .showModal()
            ;
        }


        $('.remove-titulo').click(function() {
            var id = $(this).data('id');
            removeData(id);
        });


        $('.subtitulo').hover(function() {
            $(this).find('.edita-conteudo').show();
            $(this).find('.remove-conteudo').show();
        }, function() {
            $(this).find('.edita-conteudo').hide();
            $(this).find('.remove-conteudo').hide();
        });

        $('.edita-conteudo').click(function() {
            var id = $(this).data('id');

            $.processa({
                url     : "<?= $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>",
                type    : "POST",
                savePage: false,
                data    : {
                    ppra        : transp.ppra,
                    ppraVigencia: transp.ppraVigencia,
                    titulo      : id,
                    getForm     : true,
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                        .setInputs(data)
                        .setLabelOk('Incluir')
                        .setSizeModal('lg')
                        .setClickOk(function(){

                            $("#formPpraVigenciaTexto").processa({
                                url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>",
                                ret: transp.ret,
                                savePage: false,
                                data: {
                                    texto: tinymce.get('texto').getContent()
                                }
                            });
                        })
                        .showModal()
                    ;
                }
            });
        });

        $('.remove-conteudo').click(function() {
            var id = $(this).data('id');
            removeData(id);
        });
        
        $('.break-line').each(function(){
            var $table = $(this);
            var ind = 0;
            $table.find('tbody').find('tr').each(function(){
                var $tr = $(this);
                $tr.find('td').eq(0).click(function(){   
                    var index = $table.find('tr').index($tr);
                    var $td = $(this);
                    // pegando o id do post que esta no icone edit clicavel dentra da div com classe post.
                    var id = $td.closest('.post').find('i').eq(0).data('id');                    
                    gModal.reset('confirm',2).setMsg('Deseja mesmo inserir uma quebra de pagina abaixo desta linha?').setClickOk(function(){
                        $.processa({
                            url: "<?= $this->url($route, array('controller' => $controller, 'action' => 'addBreakLineInTable'), [], FALSE, FALSE); ?>",
                            ret: transp.ret,
                            savePage: false,
                            type : 'POST',
                            data: {
                                id    : id
                                ,line : index
                            }
                        });                    
                    }).showModal();
//                    gModal.reset('alert',2).setMsg('min aqui!!!' + (index - 2)).showModal();
                });
            });
        });
    });
</script>
