<?php

/* @var $entity \Tcmed\Entity\ExameCompl */
if ($this->resultSet) {
    $array = [];

    switch ($this->subOpcao) {
        case "maisColunas":
            $array[] = [
                'menu_idExame' => "ID",
                'menu_exame' => "Exame",
            ];

            foreach ($this->resultSet as $entity) {
                $array[] = [
                    'idExame' => $entity->getId(),
                    'exame' => $entity->getExame(),
                ];
            }

            break;
        case "multiplosCampos":
            $entities = $this->resultSet;

            $array[] = [
                'menu_idExamecompl' => "ID CID",
                'menu_exame' => "Codigo",
                'menu_codAmbul' => "Descrição",
            ];
            /**
             * Dados encontrados em numeroCid
             */
            foreach ($entities["codAmbul"] as $entity) {
                $array[] = [
                    'idExamecompl' => $entity->getId(),
                    'exame' => $entity->getExame(),
                    'codAmbul' => $entity->getCodAmbul(),
                ];
            }
            /**
             * Dados encontrados em descricaoCid
             */
            foreach ($entities["exame"] as $entity) {
                $array[] = [
                    'idExamecompl' => $entity->getId(),
                    'exame' => $entity->getExame(),
                    'codAmbul' => $entity->getCodAmbul(),
                ];
            }
            break;
        default:
            $array[] = [
                'menu_idExame' => "ID",
                'menu_exame' => "Exame",
            ];

            foreach ($this->resultSet as $entity) {
                $array[] = [
                    'idExame' => $entity->getId(),
                    'exame' => $entity->getExame(),
                ];
            }

            break;
    }

    echo json_encode($array);
} else {
    echo '{}';
}
