<h3><?php echo $this->dataView['titulo']; 
?></h3>
<br />
<?php
$controller = 'examecompls';
$route = 'tcmed/default';
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Dados do Exame:');
    $fh->getIdFor('idFuncionario');
    $fh->openCol('12')->text('codAmbul')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('exame')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
