<?php

/* @var $form \Tcmed\Form\Funcionario */
$form = $this->form;
/**
 * 
 */
$route = $this->dataView["route"];
/**
 * 
 */
$controller = $this->dataView["controller"];
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));

$fh->openLine();
//
$fh->openCol(6, 3);
$fh->buildButton(["id" => "trocaFuncionario", "class" => "btn-block"], "Trocar Funcionário Cadastrado errado para outra empresa", "primary", TRUE);
$fh->closeCol();
//
$fh->jumpLine(1);
//
$fh->openCol(6, 3);
$fh->buildButton(["id" => "rmvDuplicidadeFuncionario", "class" => "btn-block"], "Repara Duplicidade de Funcionário em Uma Mesma Empresa", "primary", TRUE);
$fh->closeCol();
//
$fh->jumpLine(1);
//
$fh->openCol(6, 3);
$fh->buildButton(["id" => "copiaFuncionario", "class" => "btn-block"], "Copiar Funcionário para Outra Empresa", "primary", TRUE);
$fh->closeCol();
//
$fh->closeLine();
?>
<script type="text/javascript">
    $(function(){
        $("#trocaFuncionario").click(function(){
            var option = 1;
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'trocaFuncionario'), [], FALSE, FALSE); ?>/" + option
            });
        });
        
        $("#rmvDuplicidadeFuncionario").click(function(){
            var option = 2;
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'rmvDuplicidadeFuncionario'), [], FALSE, FALSE); ?>/" + option
            });
        });
        
        $("#copiaFuncionario").click(function(){
            var option = 3;
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'copiaFuncionario'), [], FALSE, FALSE); ?>/" + option
            });
        });
    });
</script>