<legend>Consultas
    <button id="fechar" class="btn btn-danger btn-sm pull-right">
        <i class="fa fa-times"></i>
        &nbsp;Fechar
    </button>
</legend>

<?php
if ($this->consultas) {
    /* @var $table \Application\View\Helper\Table */
    $table = $this->table();
    $params = $this->Param();

    $table->openTable(TRUE);
    $table->renderThead(['Data da Consulta', 'Medico', 'Resultado', 'Opções']);

    $lambda = function($value, $data) {
        echo '<td>',
        '<span class="hand exibe-ficha" data-id="' . $value . '"><i class="fa fa-eye"></i> Ver Prontuário</span>',
        //'&nbsp;',
        //'<span class="hand" id="del-oco" data-id="'.$value.'"><i class="fa fa-trash"></i> Deletar</span>',
        '</td>';
    };

    $table->setLambda($lambda);

    /* @var $entity \Tcmed\Entity\Consulta */
    foreach ($this->consultas as $entity) {
        $table->renderLine([
            $entity->getDtConsulta(),
            $entity->getMedico()->getNomeMedico(),
            $params($entity->getResultado()  ,'FC_Resultado'),
            $entity->getId(),
        ]);
    }
} else {
    echo "<p>Este funcionário não possui consultas<p>";
}
?>
<script>
    $(function () {
        $(".exibe-ficha").click(function () {
            var id = $(this).data('id');
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => 'Consultas', 'action' => 'showPdf'), [], FALSE, FALSE); ?>" + "/" + id,
            });
        });
        
        $("#fechar").click(function(){
            $("#container-data").hide();
            return false;
        });
    });
</script>
