<?php

$array = [];

if ($this->data) {
    /* @var $guia \Tcmed\Entity\Guia */
    $guia = $this->data;

    $array[] = [
        /* Dados da Hold, Administracao e Empresa */
        "idHold" => $guia->getEmpresa()->getAdministradora()->getHold()->getId(),
        "nomeHold" => $guia->getEmpresa()->getAdministradora()->getHold()->getNomeHold(),
        "fantasiaHold" => $guia->getEmpresa()->getAdministradora()->getHold()->getFantasiaHold(),
        "referenciaHold" => $guia->getEmpresa()->getAdministradora()->getHold()->getReferenciaHold(),
        "idAdministradora" => $guia->getEmpresa()->getAdministradora()->getId(),
        "fantasiaAdm" => $guia->getEmpresa()->getAdministradora()->getFantasiaAdm(),
        "referenciaAdm" => $guia->getEmpresa()->getAdministradora()->getReferenciaAdm(),
        "idEmpresa" => $guia->getEmpresa()->getId(),
        "fantasiaEmpresa" => $guia->getEmpresa()->getFantasiaEmpresa(),
        "referenciaEmp" => $guia->getEmpresa()->getReferenciaEmp(),
        "cnpj" => $guia->getEmpresa()->getCnpj(),
        /* Dados do Funcionario */
        "nomeFuncionario" => $guia->getNomeFuncionario(),
        "rg" => $guia->getRg(),
        "cpf" => $guia->getCpf(),
        "pis" => $guia->getPis(),
        "carteiraProfissional" => $guia->getCarteiraProfissional(),
        "sexo" => $guia->getSexo(),
        "dtNascimento" => $guia->getDtNascimento(),
        "idSetor" => $guia->getOcupacao()->getSetor()->getId(),
        "nomeSetor" => $guia->getOcupacao()->getSetor()->getNomeSetor(),
        "idCargo" => $guia->getOcupacao()->getCargo()->getId(),
        "cargo" => $guia->getOcupacao()->getCargo()->getCargo(),
        "cbo" => $guia->getOcupacao()->getCargo()->getCbo(),
        "idOcupacao" => $guia->getOcupacao()->getId(),
        "idCargoApelido" => $guia->getOcupacao()->getCargoApelido()->getId(),
        "apelido" => $guia->getOcupacao()->getCargoApelido()->getApelido(),
        "idFuncao" => $guia->getFuncao()->getId(),
        "idFuncaoApelido" => $guia->getFuncaoApelido()->getId(),
        "funcao" => ($guia->getFuncaoApelido()->getApelido()) ?
                $guia->getFuncao()->getFuncao() : $guia->getFuncaoApelido()->getApelido(),
        "dataCad" => $guia->getDataCad(),
    ];
}
echo json_encode($array);
?>

