<?php
$settings = $this->data;

?>
<div id="<?php echo $settings["idModal"] ?>" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php echo $settings["titleModal"] ?></h4>
            </div>
            <div class="modal-body">
                <!-- tratar com jquery via cliente-side -->
            </div>
            <div class="modal-footer">
                <?php
                foreach ($this->data["buttons"] as $button):
                    $type = isset($button["type"]) ? " btn btn-" . $button["type"] : "btn btn-default";
                    $text = isset($button["text"]) ? $button["text"] : "Botão";

                    $atributos = [
                        "id" => isset($button["id"]) ? $button["id"] : "",
                        "class" => isset($button["class"]) ? $button["class"] . $type : $type,
                    ];

                    $aux = "";
                    foreach ($atributos as $key => $value) {
                        $aux .= $key . '="' . $value . '" ';
                    }
                    ?>
                    <button type="button" <?php echo $aux ?>><?php echo $button["text"] ?></button>
                    <?php
                endforeach;
                ?>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->