<?php
/* @author Allan Davini */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];

$controllerFichaClinica = 'fichaClinicas';

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh    = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
), [], FALSE, $this->dataView['ajax']));


// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

?>
<h1><?php echo $title ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Cadastro</button>
    <button class="btn btn-primary" id='exibePendentes'><i class='fa fa-exclamation-circle'></i> Funcionarios Pendentes</button>
    <button class="btn btn-primary pull-right" id='exibePendentes' onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'pesquisaFuncionario')); ?>"><i class='fa fa-search'></i> Pesquisa</button>
</p>
<?php

$fh->formInit(); // ===============================================

$this->partialObj('application')->partial('index/partial-form-listafiltros', null, ['this' => &$this, 'fh' => $fh, 'dataView' => $this->dataView]);

$fh->lineDown();

$fh->openCol(12);
$table->openTable(TRUE);
$table->setOrderList($orderBy);
$table->setLambda(function ($value, $data) {
    echo "\t<td nowrap>",
    '<span class="hand" onClick="edit(\'', $value, '\')" title="Editar"><i class="fa fa-pencil"></i> ', '</span>&nbsp;', PHP_EOL,
    '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> </span>',
    '<span class="hand" onClick="newFichaClinica(\'', $value, '\')" title="Abrir nova ficha clinica"><i class="fa fa-paste"></i> </span>',
    "</td>", PHP_EOL;
});

$table->renderThead([
    ['label' => 'Nome',    'order' => 'nomeFuncionario'],
    ['label' => 'RG'  ,    'order' => 'rg'],
    ['label' => 'Sexo',    'order' => 'sexo'],
    ['label' => 'Empresa'],
    ['label' => 'Status',  'order' => 'status'],
    ['label' => 'Ação']
]);

if(0 == count($this->data)) {
    $table->setEditLine(FALSE);
    echo "<tr><td colspan='6'>Lista Vazia</td></tr>";
}

/* @var $entity \Tcmed\Entity\Funcionario */
foreach ($this->data as $entity) {
    
    $statusRow = "default";
    $entity->getStatus() == "INATIVO"   && $statusRow = "danger";
    $entity->getStatus() == "CANCELADO" && $statusRow = "danger";
    $entity->getStatus() == "BLOQUEADO" && $statusRow = "warning";
    
    $table->renderLine([
        $entity->getNomeFuncionario(),
        $entity->getRg(),
        $entity->getSexo(),
        $entity->getEmpresa()->getFantasiaEmpresa(),
        $entity->getStatus(),
        $entity->getId(),
    ],"class='{$statusRow}'");
}
$table->renderCloseTable();
$fh->formEnd(); // =============================================================

echo "<br>";
echo "<center>{$this->paginationControl($this->data, 'Sliding', 'partials/paginator')}</center>";
?>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function newFichaClinica(key) {
        var msg = "Deseja mesmo incluir uma nova ficha clinica para este funcionario ?";
//        if (!confirm(msg)) {
//            return;
//        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controllerFichaClinica, 'action' => 'new'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }

    $(function () {
        /**
         * @event Botao de visualização de pendentes 
         */
        $("#exibePendentes").click(function () {
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    status: "pendente"
                }
            })
        });
    });
</script>