<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;
$partialObject = $this->partialObj('tcmed');

!isset($d["noPrefixFuncionario"]) and $fh->setPreFix('funcionario'); // ============= INI PREFIX FUNCIONARIO

// Carrega o partial de empresa
$partialObject->partial('empresas/partial-form-all', $fh, $d);

$idFuncionario = $fh->getIdFor('idFuncionario');

$fh->openLine();
$fh->openCol(3)->number('referenciaFun')->closeCol();
$referenciaFun = $fh->getLastId();

$params = array(
    "extra" => array("icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos")
);

if (isset($d["extraNomeFuncionario"])) {
    $params["extra"] = $d["extraNomeFuncionario"];
}

$fh->openCol(5)->text('nomeFuncionario', $params)->closeCol();
$nomeFuncionario = $fh->getLastId();
$fh->closeLine();

!isset($d["noPrefixFuncionario"]) and $fh->removePreFix('funcionario'); // ========== FIM PREFIX FUNCIONARIO

$this->fields = array(
    "nomeFuncionario" => $nomeFuncionario,
    "idFuncionario" => $idFuncionario,
    "referenciaFun" => $referenciaFun,
    "empresa" => $partialObject->fieldsEmpresa,
);
?>
<script type="text/javascript">
    $(function () {

        var fields = <?php echo json_encode($this->fields) ?>;

        /**
         * Autocomplete nomeFuncionario
         * @author Danilo Dorotheu
         */
        $$(fields.nomeFuncionario).auto({
            primary: "nomeFuncionario",
            serviceUrl: "<?php echo $d["this"]->url('tcmed/default', array('controller' => 'Funcionarios', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            filters: function (data) {
                data.rules = {
                    "empresa": $$(fields.empresa.idEmpresa).val()
                };
                return data;
            },
            params: {
                subOpcao: "type1"
            },
            responseTo: {
                referenciaFun: [fields.referenciaFun],
                idFuncionario: [fields.idFuncionario],
                fantasiaEmpresa: [fields.empresa.fantasiaEmpresa],
                referenciaEmp: [fields.empresa.referenciaEmp],
                cnpj: [fields.empresa.cnpj],
                cpf: [fields.empresa.cpf],
                idEmpresa: [fields.empresa.idEmpresa],
                fantasiaAdm: [fields.empresa.fantasiaAdm],
                referenciaAdm: [fields.empresa.referenciaAdm],
                idAdministradora: [fields.empresa.idAdministradora],
                idHold: [fields.empresa.fantasiaHold],
            },
            showCols: ["referenciaFun", "nomeFuncionario", "rg"]
        });
    });
</script>
