<?php
/* @var $form \Tcmed\Form\Funcionario */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$entity = $this->entity;
$form = $this->form;

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));


$partialObject = $this->partialObj('tcmed');

echo '<h2>', $title, '</h2>';

$fh->formInit('Dados do Funcionario', ["noPreFormInit" => TRUE]);
$fh->setPreFix("funcionario");

$idFuncionario = $fh->getIdFor('idFuncionario');

$fh->openCol(2)->buildButton(["id" => "limpar", "class" => "btn-block"], '<i class="fa fa-eraser"></i> Limpar', "primary", TRUE)->closeCol();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--

$fh->openCol(12);
$partialObject->partial('empresas/partial-form-all', $fh, ['this' => &$this]);
$fh->closeCol();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--

$fh->openCol(3)->number('referenciaFun')->closeCol();
$referenciaFun = $fh->getLastId();

$fh->openCol(5)->text('nomeFuncionario', [
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    "dt-clear" => join(",", array($idFuncionario, $referenciaFun)),
])->closeCol();
$nomeFuncionario = $fh->getLastId();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--

$fh->openCol(3)->text("rg")->closeCol();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--

$fh->openCol(3)->text("cpf")->closeCol();
$fh->removePreFix('funcionario');

$fh->openCol(3, 3)->calend("filtro1", [], ["label" => "Data de Movimentação"])->closeCol();
$fh->openCol(3)->calend("filtro2", [], ["label" => "Até"])->closeCol();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--
$fh->setPreFix('funcionario');

$fh->openCol(12);
$fh->checkbox("noCpf");
$fh->closeCol();

$fh->lineDown();   // --------------------------------------| PULA LINHA |--

$fh->setHorizontal(TRUE);
$fh->openCol(8);
$fh->renderInputMultiCheckbox('checkstatus', ['position' => FALSE, 'noClean' => true]);
$fh->closeCol();
$fh->setHorizontal(FALSE);

$fh->lineDown();   // --------------------------------------| PULA LINHA |--
$fh->removePreFix();

$fh->openCol(4, 4)->buildButton(["id" => "pesquisar", "class" => "btn-block"], '<i class="fa fa-search"></i> Pesquisar', "success", TRUE)->closeCol();
$fh->jumpLine(2);
$fh->formEnd();

$fields = array_merge($partialObject->fieldsEmpresa, compact('nomeFuncionario'));

?>
<script type="text/javascript">
    $(function () {

        var fields = <?php echo json_encode($fields) ?>;

        $("#pesquisar").click(function () {
            $(this).closest("form").processa({
                type: "POST",
                url: "<?php echo $this->url('tcmed/default', array('controller' => $controller, 'action' => 'pesquisaFuncionario'), [], FALSE, FALSE); ?>",
            });
        });

        $("#limpar").click(function () {
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => $controller, 'action' => 'pesquisaFuncionario'), [], FALSE, FALSE); ?>",
            });
        });

        $$(fields.nomeFuncionario).auto({
            primary: "nomeFuncionario",
            serviceUrl: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            filters: function (data) {
                data.rules = {
                    "empresa": $$(fields.idEmpresa).val()
                };
                return data;
            },
            callback: function (data) {
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>/" + data["idFuncionario"],
                });
            },
            showCols: ["nomeFuncionario", "rg"]
        });
        
    });
</script>