<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$partial    = $this->partialObj('application');
$table      = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
), [], FALSE, $this->dataView['ajax']));

echo <<<CABECALHO
    <div class="row">
        <div class="col-md-10">
            <h1>{$title} <small>Resultados</small></h1>
        </div>
        <div class="col-md-2">
            <button id="nova-pesquisa" class="btn btn-primary btn-block"><i class="fa fa-search"></i> Refazer Pesquisa</button>
        </div>
    </div>
    <br>
CABECALHO;
            
            
// =============================================================
$fh->formInit(); 
$fh->openCol(12);
$this->partialObj('application')->partial('index/partial-form-listafiltros', null, ['this' => &$this, 'fh' => $fh, 'dataView' => $this->dataView]);
$fh->closeCol();
$fh->closeLine();
$fh->formEnd(); 
// =============================================================

$table->openTable(TRUE);
$table->setLambda(function ($value, $data) {
    echo "\t", '<td nowrap style="font-size: 14pt;">',
            '<span class="hand edit" data-id="'.$value.'" title="Editar"><i class="fa fa-pencil"></i>','</span>&nbsp;', PHP_EOL,
            '&nbsp;',
            '<span class="hand addExame" data-id="'.$value.'" title="Adicionar Exame"><i class="fa fa-plus"></i></span>',
         "</td>", PHP_EOL;  
});

$table->setEditLine("first");
//$table->setEditLine(FALSE);
$table->renderThead([
    'Ação'
    , 'Empresa'
    , 'Nome Funcionário'
    , 'Setor'
    , 'Cargo'
    , 'Inclusão'
    , 'Alterado'
    , 'Admissão'
    , 'Demissão'
    , 'Dt Nasc'
    , 'Status'
]);
/* @var $entity \Tcmed\Entity\Funcionario */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(), //ID
        $entity->getEmpresa('razaoSocial'), //Nome Funcionario
        $entity->getNomeFuncionario(), //Nome Funcionario
        $entity->getOcupacao(TRUE)->getSetor('nomeSetor'), //Cargo
        $entity->getOcupacao(TRUE)->getCargo(TRUE, 'cargo'), //Cargo
        $entity->getCreatedAt(), //Inclusão
        $entity->getUpdatedAt(), //Alterado
        $entity->getDtAdmissao(), //Admissão
        $entity->getDtDemissao(), //Demissão
        $entity->getDtNascimento(), //Dt Nascimento
        $entity->getStatus(), //Status
    ]);
}
$table->renderCloseTable();

echo '<center>', $this->paginationControl($this->data,'Sliding','partials/paginator'), '</center>';

/* +----------------------------------------------------------------------------
 * | MODAL se parametriza usando a variavel global gModal
 * +----------------------------------------------------------------------------
 *  Estrutura do modal, para Confirmar com o usuario a ação desejada.
 * 
 */
echo $this->partial('partials/modal', array());
?>
<script type="text/javascript">
    $(function () {
        $("#nova-pesquisa").click(function () {
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => "funcionarios", 'action' => 'pesquisaFuncionario'), [], FALSE, FALSE); ?>",
            });
        });
        
        $(".edit").click(function(){
            var id = $(this).attr("data-id");
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => "funcionarios", 'action' => 'edit'), [], FALSE, FALSE); ?>/" + id,
            });
        });
        
        $(".addExame").click(function(){
            var id = $(this).attr("data-id");
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'consultas', 'action' => 'formExterno'), [], FALSE, FALSE); ?>" 
                ,savePage: false
                ,callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){ 
                        if($('#dtConsulta').val() == ''){
                            gModal.reset('alert',3).setMsg('A data da consulta é obrigatorio!!!.').showModal();      
                            return;
                        }
                        if($('#tipo').val() == ''){
                            gModal.reset('alert',3).setMsg('O tipo de exame é obrigatorio!!!.').showModal();      
                            return;
                        }
                        $.processa({
                            url: "<?php echo $this->url('tcmed/default', array('controller' => "fichaClinicas", 'action' => 'newOfExterno'), [], FALSE, FALSE); ?>/" + id
                            ,type: "POST"
                            ,frm : 'consulta'
                            ,data : {
                                subOpcao : 'loadCad'
                            }
                        });
                    })
                    .showModal();
                }
            }); 
        });
        
       /* 
        * Esconder filtro que exibe inativos
        */
        $("#popshowInativo").hide();
    });
</script>