<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;
echo $this->partial('partials/modal');

$partial    = $this->partialObj('tcmed');
$partial->partial('ppra-vigencia-resps/mnglist');

echo '<h3>', $title, '</h3>';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$responsaveis        = $fh->getIdFor('responsaveis');
$idPpraVigenciaResp  = $fh->getIdFor('id');

$fh->setPreFix('ppraVigencia');


$fh->openCol(12);
$partial->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'hideCnpj' => TRUE]);
$fh->closeCol();

$fh->lineDown();

$fh->openCol(3)->text('ini')->closeCol();
$fh->openCol(3)->text('fim')->closeCol();

$fh->removePreFix('ppraVigencia');


$fh->lineDown(); // ====================== RESPONSÁVEIS ========================

$fh->openCol(12);
echo '<legend>Responsável</legend>';
$fh->closeCol();

$responsaveis  = $fh->getIdFor('responsaveis');
$idResponsavel = $fh->getIdFor('id');
$nome          = $fh->getIdFor('nome');
$ini           = $fh->getIdFor('ini');
$fim           = $fh->getIdFor('fim');
$nome          = $fh->getIdFor('nome');

$fh->openCol(3)->calend('ini')->closeCol();
$fh->openCol(3)->calend('fim')->closeCol();
$fh->openCol(4)->text('nome', [
    "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    "dt-clear" => $idResponsavel
])->closeCol();
$fh->openCol(1)->buildButton(['id' => 'incluir',        'style' => 'margin-top: 25px', 'class' => 'btn-block'], 'Incluir', 'primary', TRUE)->closeCol();
$fh->openCol(1)->buildButton(['id' => 'cadastrar-resp', 'style' => 'margin-top: 25px', 'class' => 'btn-block'], '<i class="fa fa-plus"></i> Novo', 'warning', TRUE)->closeCol();

$fh->jumpLine(2);

$fh->openCol(12, ['id' => 'lista'])->closeCol();

$fh->lineDown(); // ==================== FIM RESPONSÁVEIS ======================



$fh->openCol(2,5)->buildButton(['id' => 'salvar', 'class' => 'btn-block'], 'Próximo <i class="fa fa-arrow-right"></i>', 'primary', TRUE)->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = compact(
    'responsaveis',
    'idResponsavel',
    'nome',
    'ini',
    'fim'
);

?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        $$(transp.nome).auto({
            primary: "nome",
            serviceUrl: "<?= $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                id       : [transp.idResponsavel],
            },
            showCols: ["nome", "nit", "respPor"]
        });

        $('#salvar').click(function() {
            $(this).closest('form').processa({
                url: "<?= $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>",
            })
        });

        /**
         * Inicializa a lista
         * OBS: Ler partial acima, que injeta o js de montagem do mnglist aqui
         */
        mnglist.init({
            url  : "<?= $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'getListaResp'), [], FALSE, FALSE); ?>",
            ret  : "#lista",
            field: $$(transp.responsaveis)
        });


        $('#incluir').click(function() {
            var id = $$(transp.idResponsavel).val();

            if("" == $$(transp.ini).val() || "" == $$(transp.fim).val()) {
                mnglist.message('Escolha o periodo!!', "danger");
                return false;
            }

            mnglist.addItem({
                id : id,
                ini: $$(transp.ini).val(),
                fim: $$(transp.fim).val(),
            });

            mnglist.atualiza();
            $$('clean_' + transp.nome).find('button').click();
        });

        mnglist.atualiza();

        $('#cadastrar-resp').click(function() {
            var $form = $(this).closest('form');

            gModal.reset("confirm", 1)
                .setClickOk(function () {
                    $form.processa({
                        url: "<?= $this->url('tcmed/default', array('controller' => 'ppraResponsavels', 'action' => 'new'), [], FALSE, FALSE); ?>",
                        type: "POST",
                        data: {
                            fromPpraVigenciaResp: true,
                            // Por algum motivo desconhecido, o servidor não está
                            // conseguindo ler o campo abaixo naturalmente (Como todos
                            // os outros campos do formulario). Então, eu vou enviar
                            // manualmente, forçando então o envio dos dados deste campo
                            "ppraResponsavel[responsaveis]": $$(transp.responsaveis).val()
                        }
                    })
                })
                .setLabelOk("SIM")
                .setLabelNg("NÃO")
                .setMsg('Deseja realmente cadastrar um novo responsável?')
                .showModal()
            ;
        });
    });

</script>
