<?php
$controller  = $this->dataView['controller'];
$action      = $this->dataView['action'];
$route       = $this->dataView['route'];
$title       = $this->dataView['titulo'];
$this->partialObj('application')->partial('index/partial-form-messenger', null, ['this' => &$this]);

$routeParams = array(
    'controller' => $controller,
    'action'     => $action,
);
?>


<div class="row">
    <div class="col-md-12">
        <button id="saveData" class='btn btn-warning pull-left'><i class="fa fa-save"></i> Salvar Guias destes Funcionários (OBRIGATÓRIO CASO FOR IMPRIMIR)</button> 
        <button id="voltaPagina" class='btn btn-primary pull-right'><i class="fa fa-arrow-left"></i> Voltar</button>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <iframe id="iframeAso" width='100%' height='500' frameborder='0' src='<?php echo $this->url($route, $routeParams, [], FALSE, FALSE)?>'></iframe>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        /**
         * Alterar a altura para visualização do aso
         */
        $('#iframeAso').height(($(document).height() * 0.89) - 70);

        $('#saveData').click(function() {
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'salvarGuias'), [], FALSE, FALSE); ?>",
                savePage: false,
                callback: function(data) {
                    $.notify({
                        message: "As Guias dos funcionários abaixo foram salvas no sistema!",
                        type: "success"
                    });
                }
            });
            
            $(this).attr('disabled', true);
        });
        
        $("#voltaPagina").click(function(){
            $("#godown").click();
        });

    });
</script>
