
<h2>Nova Hold</h2>
<br />
<?php
$controller = 'holds';
$route = 'tcmed/default';
$partialObject = $this->partialObj('tcmed');
/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();

/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));
$fh->setHorizontal(false);
$fh->formInit('Informações da Hold');
$fh->openCol(9,3)->text('nomeHold')->closeCol();
$nomeHold = $fh->getLastId();

$fh->lineDown();

$fh->openCol(3)->text('referenciaHold')->closeCol();
$referenciaHold = $fh->getLastId();

$fh->openCol(6)->text('fantasiaHold')->closeCol();
$fantasiaHold = $fh->getLastId();

$fh->openCol(3)->cnpj('cnpj')->closeCol();

$fh->lineDown();

$fh->openCol(3)->select('status')->closeCol();

if ("new" == $this->dataView["action"]) {
    $fh->setHorizontal(TRUE);
    $fh->openCol(4, ["style" => "margin-top: 30px"])->radio('isAvulso')->closeCol();
    $fh->setHorizontal(FALSE);
}

$fh->lineDown();

$fh->openCol(3)->file('uploadLogo')->closeCol();

$fh->openCol(5);

$img = '';
if($this->entity) {
    /* @var $entity \Tcmed\Entity\Hold */
    $entity = $this->entity;
    $src = $this->Param('path','hold_dir') . $entity->getPathLogo();   
    $img = $this->Image($src);
}
echo "<img id='teste' style='width: 270px; height: 100px;' src='{$img}' alt='Sem Imagem' class='img-thumbnail'>";
$fh->closeCol();

$fh->lineDown();




$fh->lineDown();

// Carrega o partial de contatos
$fh->openCol(12);
$partialObject->partial('contatos/partial-form-contato', $fh, [
    'this' => &$this,
    'entity' => $entity,
]);
$fh->closeCol();

$fh->closeLine();

$fh->renderFieldsetIni("Endereço", ['notOpenLine' => TRUE]);
$partialObject->partial('enderecos/partial-form-all', $fh, ['this' => &$this]);
$fh->renderFieldsetFim();
$fh->openLine();
$fh->openCol('12')->Submit('submit')->closeCol();

$fh->closeLine()->formEnd();
?>
<br>
<script lang="javascript">

    function isValid() {
        return true;
    }

    $(function () {
        var messagesGroup = <?php echo json_encode($messages) ?>;
        /**
         * @name createMessages
         */
        $.each(messagesGroup, function (type, messages) {
            $.each(messages, function (_, message) {
                $.notify({
                    "message": message,
                    "type": type
                });
            });
        });
    });

</script>
