<?php
$fh = &$obj;

//echo '<pre>' , var_dump(get_class_methods($fh));die;

$fh->closeLine()->renderFieldsetIni('Holds')->setPreFix('hold');
$idHold = $fh->getIdFor('idHold');
$fh->openCol('12')->text('nomeHold')->closeCol();
$nomeHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('fantasiaHold')->closeCol();
$fantasiaHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('cnpj')->closeCol();
$cnpj = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('referenciaHold')->closeCol();
$referenciaHold = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();

//$fh->lineDown();
//    $fh->openCol('12')->select('bairro')->closeCol();
//$fh->lineDown();
$this->partialObj('tcmed')->partial('enderecos/partial-form', $fh, ['this' => &$d['this']]);

$fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();
?>

<script lang="javascript">
    $(function () {
        
        var parametros = {
            fields:{
                idHold: ["<?php echo $idHold; ?>"],
                nomeHold: ["<?php echo $nomeHold; ?>"],
                fantasiaHold: ["<?php echo $fantasiaHold; ?>"],
                cnpj: ["<?php echo $cnpj; ?>"],
                referenciaHold: ["<?php echo $referenciaHold; ?>"],
            },
            extra:{
                url: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'holds', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                teste: "ola"
            }
        };
        
        $.each(parametros["fields"], function(key, value){
            action.preAutoComp(key, parametros);
        });
        
        
        /*
        action.preAutoComp("nomeHold", parametros);
        action.preAutoComp("fantasiaHold", parametros);
        */
    });
</script>