<h3><?php 
/**
 * @author
 */
echo $this->dataView['titulo']; 
$controller = 'histOcupacionalfuncaos';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp*/
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Historico Ocupacional Funcaos:');
    $fh->openCol('12')->select('funcao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('histOcupacional')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascript">   
    
    function isValid(){
        return true;
    }
    
</script>
