<?php 
/* @var $entity \Tcmed\Entity\CargoApelido */
if($this->resultSet){
    $array = [];

    if($this->subOpcao == '' || !isset($this->subOpcao)) {
        $array[] = [
            'menu_idCargo' => "ID Cargo",
            'menu_cargo' => 'Nome do Cargo',
            'menu_apelido' => 'Apelido do Cargo',
            'menu_descricao' => 'Descrição',
            'menu_idApelido' => 'ID Apelido',
        ];
        foreach ($this->resultSet as $entity) {
            $array[] = [
                'idCargo' => $entity->getCargo()->getIdCargo(),
                'cargo' => $entity->getCargo()->getCargo(),
                'apelido' => $entity->getApelido(),
                'descricao' => $entity->getDescricaoCargo()->getDescricao(),
                'idCargoApelido' => $entity->getId(),
            ];
        }
    }

    echo json_encode($array);
}else{
    echo '{}';
}
