<?php
/* @var $form Adm\Form\Colaborador */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('adm');
$form       = $this->form;

echo '<h3>', $title, '</h3>';
?>

<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Novo</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>"><i class='fa fa-refresh'></i> Atualiza</button>
</p>


<?php
// $ret        = $form->getValue('ret', '#inter');
// $form->setAttribute('target', $ret);
$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('adm')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));

$fh->formInit();
$fh->openCol(12);
$fh->openCol(4)->closeCol();

$inpUsuario = $fh->setPreFix('colaborador')->getIdFor('usuario');
$inpColaborador = $fh->getIdFor('id');
$fh->openCol(4)->renderInputText('usuarioNome', ["extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]])->removePreFix('colaborador')->closeCol();
$inpUsuarioNome = $fh->getLastId();
$fh->openCol(12);
$table->openTable(TRUE);
$table->setOrderList($this->dataView['orderBy']);
$table->renderThead([
    ['label' => 'ID'                   ],
    ['label' => 'Usuário'              ],
    ['label' => 'Horário de início'    ],
    ['label' => 'Horário de término'   ],
    ['label' => 'Período de início'    ],
    ['label' => 'Período de fim'       ],
    ['label' => 'Tempo de almoço'      ],
    ['label' => 'Criado por'           ],
    ['label' => 'Alterado por'         ],
    ['label' => 'Criado em'            ],
    ['label' => 'Alterado em'          ],
    ['label' => 'Status'               ],
    ['label' => 'Ação'                 ],
]);
/* @var $entity \Adm\Entity\Colaborador */
foreach ($this->data as $entity) {

    $table->renderLine([
        $entity->getId(),
        $entity->getUsuario('nome'),
        $entity->getHorIni(),
        $entity->getHorFim(),
        $entity->getPerIni(),
        $entity->getPerFim(),
        $entity->getAlmoco(),
        $entity->getCreatedBy('nome'),
        $entity->getUpdatedBy('nome'),
        $entity->getCreatedAt('full'),
        $entity->getUpdatedAt('full'),
        $entity->getStatus(),
        $entity->getId(),
    ]);
}
    $table->renderCloseTable();

$fh->closeCol();
$fh->closeLine();
$fh->formEnd();
echo $this->partial('partials/modal');
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
</center>

<?php 
// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'
    ,'inpUsuarioNome'    
    ,'inpUsuario'
    ,'inpColaborador'
); 
?>
<script lang="javascript">
    
    //Função do auto-complete
    function isValid(){
        return true;
    }
    
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        $$(transp.inpUsuarioNome).auto({
            primary: "nomeUsuario",
            width : 800,
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'colaboradors', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            responseTo: {
                id: [transp.inpColaborador]
            },
            callback : function(data, defaults){
                $.processa({
                url  : "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>",
                frm  : true,
                type : 'POST'
            });
            },        
            showCols: ["nomeUsuario","emailUsuario","id"]
        });
    });

    function edit(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key,
        });
        
    }
    function del(key) {
        gModal.reset('confirm',2).setMsg('Deseja mesmo excluir este registro?').setClickOk(function(){
            var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
            $.processa(data);
        }).showModal();
    }
    
</script>
