<h3><?php echo $this->dataView['titulo']; 
$controller = 'estados';
$route = 'adm/default';
?></h3>
<br />
<?php

/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Estados:');
    $fh->openCol('12')->text('nomeEstado')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('uf')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('pais')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascript">   
    
    function isValid(){
        return true;
    }
    
</script>
