<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;

$form->setAttribute('id', 'formModalEpcOcupacao');

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
), [], FALSE, $this->dataView['ajax']));

$fh->formInit();

    $idEpcRiscoOcupacao = $fh->getIdFor('idEpcRiscoOcupacao');
    $ocupacao           = $fh->getIdFor('ocupacao');
    $riscoOcupacao      = $fh->getIdFor('riscoOcupacao');

    $fh->setPreFix('epc');
        $idEpc = $fh->getIdFor('idEpc');
        $epc   = $fh->getIdFor('epc');

        $fh->openCol(12)->text('epc', [
            'dt-clear' => $idEpc,
            "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
        ])->closeCol();
    $fh->removePreFix('epc');

$fh->formEnd();

// Var de transferencia PHP to JS
$transp = compact('epc', 'idEpc');
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        $$(transp.epc).auto({
            primary: "epc",
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'Epcs', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                "id": [transp.idEpc],
            },
            showCols: ["epc"]
        });
    });

</script>
