<?php
/* @var $form Application\Form\ChamadoResposta */
/* @var $table \Application\View\Helper\Table */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('tcmed');
$form       = $this->form;
$user       = $this->UserIdentity();
/* @var $param \Application\View\Helper\Param */
$param = $this->Param();

?>


<?php
$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));

$fh->lineDown();
    $fh->openCol(12);
        $table->openTable(TRUE);
        $table->setEditLine(FALSE);
        $table->setOrderList($this->dataView['orderBy']);
        $table->renderThead([
            ['label' => 'ID'                   ],
            ['label' => 'Resposta'             ],
            ['label' => 'Arquivo Anexado'      ],
            ['label' => 'Cópia para'           ],
            ['label' => 'Tempo de resposta'    ],
            ['label' => 'Respondido em'        ],
            ['label' => 'Respondido por'       ],
        ]);

        /* @var $entity \Application\Entity\ChamadoResposta */
        foreach ($this->data as $entity) {
            $table->renderLine([
                $entity->getId(),
                $entity->getTexto(),
                implode('<br>', $entity->getAnexoPath()),
                implode('<br>', $entity->getCopiaPara()),
                $entity->getHoras(),
                $entity->getCreatedAt('full'),
                $entity->getCreatedBy('nome'),
            ]);
        }
        $table->renderCloseTable();
    $fh->closeCol();
$fh->closeLine();
echo $this->partial('partials/modal');
?>
<?php 
// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'
); 
?>
<script lang="javascript">
    
    //Função do auto-complete
    function isValid(){
        return true;
    }
    
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
    });
</script>