<?php
/** ----------------------------------------------------------------------------
  | MEDICOS - getHorarioMedicos
  |------------------------------------------------------------------------------
  | Imprime a lista de todos os médicos, contendo seus respectivos horários
  |
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 09-06-2016
 * @version 1
 */
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url("agenda/default", array('controller' => "horarioMedicos"), [], FALSE));
?>
<nav>
    <ul class="pager">
        <li id="getMesProximo">
            <a href="javascript:void(0)">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Anterior
            </a>
        </li>
        <li>
            <?php echo "Mês " . $this->mesRef; ?>
        </li>
        <li id="getMesAnterior">
            <a href="javascript:void(0)">
                Próximo <i class="fa fa-arrow-right" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>
<?php
$table = $this->table();
$table->openTable(TRUE);


$lambda = function ($value, $data) {
    // Se a coluna dias não possuir valor:
    if(empty($data[1])){
        echo '<td nowrap><span class="hand add-horario" data-id="'.$value.'" title="Adicionar"><i class="fa fa-plus"></i> Add</td>', PHP_EOL;
    }else{
        echo '<td nowrap><span class="hand edit-horario" data-id="'.$value.'" title="Editar"><i class="fa fa-pencil"></i> Editar</td>', PHP_EOL;
    }
};
$table->setLambda($lambda);

//$table->setEditLine(FALSE);
$table->renderThead(['Dr(a).', 'Dias', 'Qtd Hrs Mês', 'Ação']);
/* @var $entity \Tcmed\Entity\Medico */
foreach ($this->data as $entity) {
    /* @var $horarioMedico \Agenda\Entity\HorarioMedico */
    $diasTrab = "";
    $horasTrab = "";
    $horarioMedico = $this->resul[$entity->getId()];

    if ($horarioMedico instanceof \Agenda\Entity\HorarioMedico) {
        $diasTrab = implode(",", $horarioMedico->listAllDiasTrab("unique", "sort"));
        $horasTrab = $horarioMedico->getHorTotal();
    }

    $table->renderLine([
        $entity->getNomeMedico(),
        $diasTrab,
        $horasTrab,
        $entity->getId()
    ]);
}
$table->renderCloseTable();

$fields = array(
    "mesReferencia" => $this->mesRef,
);
?>
<br>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;

        /**
         * Retorna para a view, a lista de médicos com os seus respectivos horários
         * @returns {void}
         */
        function getListaMedicos(mesReferencia, opcao) {
            /**
             * @event
             * Traz a tabela de médicos
             */
            $.processa({
                url: "<?php echo $this->url("agenda/default", array('controller' => "horarioMedicos", 'action' => 'getListaMedicos'), [], FALSE, FALSE); ?>",
                type: "POST",
                savePage: false,
                data: {
                    mesRef: mesReferencia,
                    opcao: opcao
                },
                ret: "#tabela-medicos"
            });
        }

        /**
         * Retorna a lista de médicos junto aos seus respectivos horários do mês
         * anterior em relação ao mês definido na tela
         */
        $('#getMesAnterior').click(function () {
            getListaMedicos(fields.mesReferencia, "anterior");
        });

        /**
         * Retorna a lista de médicos junto aos seus respectivos horários do mês
         * seguinte em relação ao mês definido na tela
         */
        $('#getMesProximo').click(function () {
            getListaMedicos(fields.mesReferencia, "proximo");
        });

        $('.edit-horario').click(function () {
            $.processa({
                url: "<?php echo $this->url("agenda/default", array('controller' => "horarioMedicos", 'action' => 'openHorarioByMedico'), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    mesRef: fields.mesReferencia,
                    idMedico: $(this).attr('data-id')
                },
            });
        });
        $('.add-horario').click(function () {
            $.processa({
                url: "<?php echo $this->url("agenda/default", array('controller' => "horarioMedicos", 'action' => 'new'), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    periodo: fields.mesReferencia,
                    idMedico: $(this).attr('data-id'),
                    subOpcao: "addNewHorario"
                },
            });
        });

    });
</script>
