<br>
<?php
$controller = $this->dataView['controller'];
$route = $this->dataView['route'];
?>
<nav>
    <nav>
        <ul class="pager">
            <li id="mes-prev" class="previous"><a href="javascript:void(0)"><span aria-hidden="true">&larr;</span> Anterior</a></li>
            <li id="mes-next" class="next"><a href="javascript:void(0)">Próximo <span aria-hidden="true">&rarr;</span></a></li>
        </ul>
    </nav>
    <h3 class="text-center" style="margin-top: -40px">Mês <?php echo $this->dateRef ?></h3>
</nav>
<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$lambda = function ($value, $data) {
    // Se a coluna dias não possuir valor:
    echo '<td nowrap><span class="hand edit-horario" data-id="' . $value . '" title="Editar"><i class="fa fa-pencil"></i> Editar</td>', PHP_EOL;
};
$table->setLambda($lambda);
$table->setEditLine("first");
$table->openTable(TRUE);
$table->renderThead([
    ['label' => 'Opções'],
    ['label' => 'Médico'],
    ['label' => 'Hora Inicio', 'options' => ' title="Hora de inicio de trabalho"'],
    ['label' => 'Hora Fim', 'options' => ' title="Hora final de trabalho"'],
    ['label' => 'Folgas'],
    ['label' => 'Qtd Horas', 'options' => ' title="Quantidade de horas trabalhadas por dia"'],
    ['label' => 'Quant Dias', 'options' => ' title="Quantidade de dias definidos para trabalho no mês"'],
    ['label' => 'Horas Mensais', 'options' => ' title="Horas totais de trabalho no mês"'],
    ['label' => 'Resp', 'options' => ' title="Responsável pelo cadastro do horário"']
]);

/**
 * Método de exibição dos dados retornados pelo método abaixo:
 * @see Agenda\Service\HorarioMedico::getDataToViewBy($entities);
 */
foreach ($this->dataEntities as $dataEntity) {
    foreach ($dataEntity as $column) {
        $table->renderLine([
            $column['id'],
            $column['nomeMedico'],
            $column['horaIni'],
            $column['horaFim'],
            $column['diasFolga'],
            $column['quantHorasDia'],
            $column['quantDiasTrab'],
            $column['totalHoras'],
            $column['createdBy'],
        ]);
    }
}

$table->renderCloseTable();

$fields = array(
    "dateRef" => $this->dateRef,
);
?>
<br>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;

        $('.edit-horario').click(function () {
            var id = $(this).attr('data-id');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>/" + id,
            });
        });

        /**
         * Retorna para a view, a lista de médicos com os seus respectivos horários
         * @returns {void}
         */
        function getListagem(mesReferencia, subOpcao) {
            mesReferencia = mesReferencia || fields.dateRef;
            subOpcao = subOpcao || "current";

            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>",
                type: "POST",
                savePage: false,
                data: {
                    dateRef: mesReferencia,
                    subOpcao: subOpcao
                },
                ret: "#tabela-medicos"
            });
        }

        /**
         * Retorna a lista de médicos junto aos seus respectivos horários do mês
         * anterior em relação ao mês definido na tela
         */
        $('#mes-prev').click(function () {
            getListagem(fields.dateRef, "previous");
        });

        /**
         * Retorna a lista de médicos junto aos seus respectivos horários do mês
         * seguinte em relação ao mês definido na tela
         */
        $('#mes-next').click(function () {
            getListagem(fields.dateRef, "next");
        });

    });
</script>