<h3>
    <?php 
    /**
     * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
     */
    /* @var $audiometria \Tcmed\Entity\Audiometria */
    /* @var $funEnt \Tcmed\Entity\Funcionario */
    $controller = 'audiometrias';
    $route = 'tcmed/default';
    $audiometria = $this->entity;
    $funEnt = $audiometria->getFuncionario();
    ?>
</h3>
<table class="table table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th style="width: 10%" class="text-right">Hold</th>
        <td style="width: 10%" class="text-right"><?php echo $funEnt->getEmpresa()->getAdministradora()->getHold()->getId(); ?></td>
        <td colspan="2"><?php echo $funEnt->getEmpresa()->getAdministradora()->getHold()->getNomeHold(); ?></td>
    </tr>
    <tr>
        <th class="text-right">Administradora</th>
        <td class="text-right"><?php echo $funEnt->getEmpresa()->getAdministradora()->getReferenciaAdm(); ?></td>
        <td colspan="2"><?php echo $funEnt->getEmpresa()->getAdministradora(); ?></td>
    </tr>
    <tr>
        <th class="text-right">Empresa</th>
        <td class="text-right"><?php echo $funEnt->getEmpresa()->getReferenciaEmp(); ?></td>
        <td colspan="2"><?php echo $funEnt->getEmpresa(); ?></td>
    </tr>
    <tr>
        <th class="text-right">Funcionario</th>
        <td class="text-right"><?php echo $funEnt->getReferenciaFun(); ?></td>
        <td colspan="2"><?php echo $funEnt->getNomeFuncionario(); ?></td>
    </tr>
    <tr>
        <th class="text-right">Medico</th>
        <td colspan="4"><? echo !is_null($audiometria->getMedico()) ? $audiometria->getMedico()->getNomeMedico() : 'nao tem consulta'; ?></td>
    </tr>
    <tr>
        <th class="text-right">Clinica</th>
        <td colspan="4"><? echo !is_null($audiometria->getConsulta()) ? $audiometria->getConsulta()->getClinica()->getFantasiaClinica() : 'nao tem consulta'; ?></td>
    </tr>
    <tr>
        <th nowrap class="text-right">Sexo</th>
        <td nowrap><?php echo $funEnt->getSexo(); ?></td>
        <th nowrap class="text-right">Nascimento</th>
        <td nowrap><?php echo $funEnt->getDtNascimento(); ?></td>
    </tr>
    <tr>
        <th nowrap class="text-right">Setor</th>
        <td nowrap><?php echo $audiometria->getOcupacao()->getSetor(); ?></td>
        <th nowrap class="text-right">Cargo</th>
        <td nowrap><?php echo $audiometria->getOcupacao()->getCargo(TRUE); ?></td>
    <tr>
        <th nowrap class="text-right">Riscos</th>
        <td nowrap><?php 
            $grauRisco = '';
            foreach ($audiometria->getOcupacao()->listOfCargoRiscos() as $ent) {
                $grauRisco .= $ent->getSomatoria() . ', ';
                echo $ent->getRisco()->getRisco(), ', ';
            } 
        ?></td>
        <th nowrap class="text-right">EPI</th>
        <td nowrap><?php 
            foreach ($audiometria->getOcupacao()->listOfCargoRiscosEpis() as $entityEpis) {
                /* @var $epi \Tcmed\Entity\EpiOcupacao or \Tcmed\Entity\EpiCargo */
                echo $entityEpis->getEpi(); ', ';                    
            } 
        ?></td>
    </tr>
    <tr>
        <th nowrap class="text-right">Grau de Riscos</th>
        <td nowrap><?php echo $grauRisco; ?></td>
        <th nowrap class="text-right">EPC</th>
        <td nowrap><?php 
            foreach ($audiometria->getOcupacao()->listOfCargoRiscosEpcs() as $entityEpcs) {
                /* @var $epi \Tcmed\Entity\EpcOcupacao or \Tcmed\Entity\EpcCargo */
//                echo var_dump($entityEpcs); ', ';                    
                echo $entityEpcs->getEpc(); ', ';                    
            } 
        ?></td>
    </tr>
    <tr>
        <th nowrap class="text-right ">Descrição do Cargo</th>
        <td nowrap colspan="3"><?php echo $audiometria->getOcupacao()->getCargoDescricao(); ?></td>
    </tr>
    <tr>
        <th nowrap class="text-right">Função(ões)</th>
        <td nowrap colspan="3"><?php 
            foreach ($funEnt->getHistOcupacional('atual')[0]->getAllFuncaos() as $ent) {
                echo $ent, ', ';
            } 
        ?></td>
    </tr>
    </thead>
</table>
<?php
/* @var $fh \Application\View\Helper\FormHelp*/
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Dados do Exame Audiometrico:');
    $fh->openCol('6')->calend('data')->closeCol();
    $fh->openCol('3')->radio('alterado')->closeCol();
    $fh->openCol('3')->radio('analise')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->radio('repetir')->closeCol();
    $fh->openCol('3')->radio('ocupacional')->closeCol();
    $fh->openCol('3')->radio('agravamento')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('comentario')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('examinador')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('examinador2')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('examinador3')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('personalizacao')->closeCol();
    $fh->openCol('6')->text('aparelho')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('referencia')->closeCol();
    $fh->openCol('6')->calend('calibracao')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('otoscopia')->closeCol();
    $fh->openCol('6')->select('repouso')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('logoAudiometria')->closeCol();
$fh->lineDown();
    $fh->openCol('4')->radio('otoscopiaEdOd[0]')->closeCol();
    $fh->openCol('4')->radio('srtEdOd[0]')->closeCol();
    $fh->openCol('4')->radio('irfEdOd[0]')->closeCol();
$fh->lineDown();
    $fh->openCol('4')->radio('otoscopiaEdOd[1]')->closeCol();
    $fh->openCol('4')->radio('srtEdOd[1]')->closeCol();
    $fh->openCol('4')->radio('irfEdOd[1]')->closeCol();
$fh->closeLine();
?>

<table class="table table-bordered table-hover table-condensed">
    <caption class="b">Limiares Tonais Orelha Direita</caption>
    <thead>
        <tr>
            <th class="text-center">kHz</th>
            <th class="text-center">250</th>
            <th class="text-center">500</th>
            <th class="text-center">1K</th>
            <th class="text-center">2K</th>
            <th class="text-center">3K</th>
            <th class="text-center">4K</th>
            <th class="text-center">6K</th>
            <th class="text-center">8K</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>VA</td>
            <td><? $fh->openCol('12')->number('limiareVaDir[0]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[1]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[2]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[3]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[4]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[5]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[6]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaDir[7]', ['noLabel' => TRUE])->closeCol(); ?></td>
        </tr>
        <tr>
            <td>VO</td>
            <td></td>
            <td><? $fh->openCol('12')->number('limiareVoDir[0]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoDir[1]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoDir[2]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoDir[3]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoDir[4]', ['noLabel' => TRUE])->closeCol();?></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

<table class="table table-bordered table-hover table-condensed">
    <caption class="b">Limiares Tonais Orelha Esquerda</caption>
    <thead>
        <tr>
            <th class="text-center">kHz</th>
            <th class="text-center">250</th>
            <th class="text-center">500</th>
            <th class="text-center">1K</th>
            <th class="text-center">2K</th>
            <th class="text-center">3K</th>
            <th class="text-center">4K</th>
            <th class="text-center">6K</th>
            <th class="text-center">8K</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>VA</td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[0]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[1]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[2]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[3]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[4]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[5]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[6]', ['noLabel' => TRUE])->closeCol(); ?></td>
            <td><? $fh->openCol('12')->number('limiareVaEsq[7]', ['noLabel' => TRUE])->closeCol(); ?></td>
        </tr>
        <tr>
            <td>VO</td>
            <td></td>
            <td><? $fh->openCol('12')->number('limiareVoEsq[0]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoEsq[1]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoEsq[2]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoEsq[3]', ['noLabel' => TRUE])->closeCol();?></td>
            <td><? $fh->openCol('12')->number('limiareVoEsq[4]', ['noLabel' => TRUE])->closeCol();?></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="9">
                <table class="table table-bordered table-hover table-condensed">
                    <tr>
                        <td align="center"><img id="test" src="<? echo $this->url('tcmed/default',array('controller' => $controller, 'action' => 'getGraphOd', 'id' => $audiometria->getId()),[],FALSE,FALSE) . "?" . rand(0, 1000);?>" /></td>
                        <td align="center"><img id="test" src="<? echo $this->url('tcmed/default',array('controller' => $controller, 'action' => 'getGraphEd', 'id' => $audiometria->getId()),[],FALSE,FALSE) . "?" . rand(0, 1000);?>" /></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="9">
<?
$fh->openLine();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('4');echo '<center>', $fh->buildButton(['id' => 'btnEnviarAudiometriaClose', 'class' => 'btn btn-success'],'Salvar e Fechar'), '</center>';$fh->closeCol();
    $fh->openCol('4')->Submit('submit',['id' => 'btnEnviarAudiometria'])->closeCol();
    $fh->openCol('4');echo '<center>', $fh->buildButton(['id' => 'btnAudiometriaClose', 'class' => 'btn btn-success'],'Fechar'), '</center>';$fh->closeCol();
    
$fh->closeLine()->formEnd();
?>
            </td>
        </tr>
    </tfoot>
</table>

<script lang="javascript">
    var audiometria = {};
    
    audiometria.isValid = function(){
        return true;
    };
    
    audiometria.close = function(){
        $('#showAudiometriaForm').html('').hide();  
    };
    
    $(function(){

        $('#btnEnviarAudiometria').click(function(){
            $(this).sendForm(audiometria);
            return false;
        });
        
        $('#btnEnviarAudiometriaClose').click(function(){
            $(this).sendForm(audiometria);
            audiometria.close();
            return false;
        });
        
        $('#btnAudiometriaClose').click(function(){
            audiometria.close();
            return false;
        });
    });
    
</script>
