<?php 
/**
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 */

/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'audiometrias';
$route = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1><?= $this->dataView['titulo']; ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="novo();">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead([
        'Ação',
        'Realizado',
        'Alterado', 
        'ID', 
    ]);
$table->setEditLine('first');
/* @var $entity \Tcmed\Entity\Audiometria */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getData(),
        $entity->getAlterado(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    $(function () {
    });
    
    var novo = function(){
        module.Sidemenu.hideSideBar();
//        var data = {url: "/tcmed/audiometrias/new"};
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new'), [], FALSE, FALSE); ?>"};
        $.processa(data);
    };
    
    function edit(key) {
        module.Sidemenu.hideSideBar();
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
        
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>