<h3><?php echo $this->dataView['titulo']; 
$controller = 'estados';
$route = 'tcmed/default';
?></h3>
<br />
<?php

 $form->setAttribute('action', $this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']))
      ->prepare();

 echo $this->form()->openTag($form);

 $estadp = $form->get('Estado');

 echo $this->formHidden($estadp->get('idEstado'));
 echo $this->formRow($estadp->get('nomeEstado'));
 echo $this->formRow($estadp->get('uf'));
 echo $this->formRow($estadp->get('status'));

 $pais = $estadp->get('Pais');

 echo $this->formHidden($pais->get('idPais'));
 echo $this->formRow($pais->get('nomePais'));
 echo $this->formRow($pais->get('sigla'));

 echo $this->formHidden($form->get('security'));
 echo $this->formElement($form->get('submit'));

 echo $this->form()->closeTag();



/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini 
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro de Estado:');
    $fh->openCol('12')->text('nomeEstado')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('uf')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('pais')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
 */
?>

<script lang="javascript">   
    
    function isValid(){
        return true;
    }
    
</script>
