    <?php
    $fh = &$obj;

    $fh->closeLine()->renderFieldsetIni('Dados do Estado')->setPreFix('estado');
    $idEstado = $fh->getIdFor('idEstado');
    $fh->openCol('12')->text('nomeEstado')->closeCol();
        $nomeEstado = $fh->getLastId();
    $fh->openCol('12')->text('uf')->closeCol();
        $uf = $fh->getLastId();
    //$fh->openCol('12')->select('idPais')->closeCol();
       // $idPais = $fh->getLastId();
    $fh->openCol('12')->text('status')->closeCol();
        $this->partialObj('tcmed')->partial('paiss/partial-form', $fh, ['this'=>&$d["this"]]);

        $fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();

    ?>

    <script lang="javascript">
    $(function () {

        var parametros = {
            fields:{
                idEstado: ["<?php echo $idEstado; ?>"],
                nomeEstado: ["<?php echo $nomeEstado; ?>"],
                uf: ["<?php echo $uf; ?>"],
                //idPais: ["<?php //echo $idPais; ?>"],
            },
            extra:{
                url: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'estados', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            }
        };

        $.each(parametros["fields"], function(key, value){
            action.preAutoComp(key, parametros);
        });



    //        action.preAutoComp("fantasiaHold", parametros);

    });
    </script>
