<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
$entity       = $this->entity;
/* @var $form \Adm\Form\ColaboradorPonto */
$form         = $this->form;
$id           = $form->getValue('id', 0);
$partial      = $this->partialObj('adm');

echo '<h3>', $title, '</h3><br />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();

$inpColaborador = $fh->getIdFor('colaborador');

$fh->openCol(5,1)->renderInputText('colaboradorNome')->closeCol();
$inpcolaboradorNome = $fh->getLastId();

$fh->openCol(4)->renderInputSelect('tipo')->closeCol();
$fh->lineDown();

$fh->openCol(2,1)->renderInputCalend('data')->closeCol();

$fh->openCol(2)->renderInputText('hora')->closeCol();
$inpHora = $fh->getLastId();

$fh->openCol(2)->renderInputText('ip')->closeCol();

$fh->openCol(3)->renderInputText('origem')->closeCol();

$fh->openCol(9,1)->renderInputTextArea('obs')->closeCol();
$fh->lineDown();

$fh->openCol(3,4)->renderInputSubmit('submit')->closeCol();
$fh->closeLine();

$fh->formEnd();

//if($this->getUsuario('usuario') == null){
//    echo "Preencha o usuário.";
//}


// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'   
    ,'inpHora'
    ,'inpColaborador'
    ,'inpcolaboradorNome'
);
?>
<script lang="javascript">
//Função do auto-complete
    function isValid(){
        return true;
    }
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        $$(transp.inpcolaboradorNome).auto({
            primary: "nomeUsuario",
            width : 800,
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'colaboradors', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            responseTo: {
                id: [transp.inpColaborador]
            },
            showCols: ["nomeUsuario","emailUsuario","idUsuario"]
        });
        
        //reseta o valor que foi carregado na memória do nome usuario
        $$(transp.inpcolaboradorNome).change(function(){
            $$(transp.inpColaborador).val("");
        });
        
        //mascara de horas
        $$(transp.inpHora).mask("99:99");
    });

</script>