<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$orderBy    = $this->dataView['orderBy'   ];
/* @var $param \Application\View\Helper\Param  */
$param      = $this->Param();
/* @var $form \Adm\Form\ColaboradorPonto */
$form       = $this->form;
/* @var $ini \DateTime */
$ini        = $this->ini;
/* @var $fim \DateTime */
$fim        = $this->fim;
$coluns     = $form->getSelectStatus();
$partial    = $this->partialObj('adm');
$user       = $this->UserIdentity();
$nome = [];

/* @var $param \Application\View\Helper\Image  */
$image      = $this->Image();
$path = $param('path','cartao_ponto_logo');
$src = $image($path);
/* @var $entity \Adm\Entity\ColaboradorPonto */
foreach($this->resul as $entity){
    if(empty($nome)){
        $nome = $entity->getColaborador('usuario',['nome']);
    }
}
?>
<table class="table table-bordered">
    <tr>
        <td class="active" align="center"><img src="<?= $src; ?>" alt="não encontrado <?= $path;?>" width="130" height="50"/></td>
        <td class="active" align="center"><h4><b>Cartão de ponto</b></h4></td>
    </tr>
    <tr>
        <td colspan="2" class="active" align="center" ><?php echo "<h4><b>Nome: $nome</b></h4>"; ?></td>
    </tr>
</table>
<?php

$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('adm')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));
$fh->lineDown();
    $fh->openCol(12);
?>
<table class=" table table-striped table-bordered">
    <tr>
        <th><b>DATA</b></th>
        <? /* Tabela com as partes das colunas */
        foreach ($coluns as $colun){
            echo "<th><b>$colun</b></th>";
        }
        ?>
        <th><b>SEMANA</b></th>
    </tr>
           <?php /* @var $entity \Adm\Entity\ColaboradorPonto */
            $data = '';
            foreach ($this->resul as $entity){
                $data[$entity->getData()][$entity->getTipo()] = $entity->getHora();
            } 
            $interval = new \DateInterval('P1D');
            while ($ini <= $fim):
                if($ini->format('w') == 0){
                    $ini->add($interval);
                    continue; 
                }
                $dia = $ini->format('d/m/Y');
            ?> 
    <tr>
        <td align="center"><?php 
        echo $dia;
        ?></td>
        
            <?php
            foreach ($coluns as $colun) {
                if(isset($data[$dia][$colun])){
                    echo "<td align=\"center\">{$data[$dia][$colun]}</td>";
                }else{
                    echo "<td>&nbsp;</td>";
                }
            }
           
            ?>
        <td align="center"><?php 
        echo $param($ini->format('w'),'week_day');
        ?></td>
    </tr>
            <?    
                $ini->add($interval);
            endwhile;
            ?> 
</table>
<?php
        
    $fh->closeCol();
$fh->closeLine();

echo $this->partial('partials/modal');
?>
<div class="container">
    <div class="table-responsive">
        <table class="table">
            <tr>
                <td align="left"><h4><b>
                Concordo:__________________________________________________________
                <?php echo " Data: ".date('d/m/Y')." Horário: ".date('H:i') ?>
                </b></h4></td>
            </tr>
        </table>
    </div>
</div>  
<center>
    <button class="btn btn-primary" id="btn-gera-ponto-pdf"><i class='fa fa-print'></i> Imprimir em PDF</button>
</center>
<br />
<br />
<br />
<br />
<br />
<script lang="javascript">
    $(function(){
        $('#btn-gera-ponto-pdf').click(function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'showPdf'), [], FALSE, FALSE); ?>"
            });
        });
    });
</script>