<?php
$fh = &$obj;

$fh->closeLine()->renderFieldsetIni('Dados da Cidade')->setPreFix('cidade');
$idCidade = $fh->getIdFor('idCidade');
    $fh->openCol('12')->text('nomeCidade')->closeCol();
    $nomeCidade = $fh->getLastId();
    $fh->openCol('12')->select('status')->closeCol();
    $this->partialObj('adm')->partial('estados/partial-form', $fh, ['this'=>&$d["this"]]);
    
$fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();

?>
<script lang="javascript">
    $(function () {
        
        var parametros = {
            fields:{
                idCidade: ["<?php echo $idCidade; ?>"],
                nomeCidade: ["<?php echo $nomeCidade; ?>"],
            },
            extra:{
                url: "<?php echo $d['this']->url('adm/default', array('controller' => 'cidades', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            }
        };
        
        $.each(parametros["fields"], function(key, value){
            action.preAutoComp(key, parametros);
        });
        
        
        
//        action.preAutoComp("fantasiaHold", parametros);

    });
</script>