<?php
$fh = &$obj;

//echo '<pre>' , var_dump(get_class_methods($fh));die;

$fh->closeLine()->renderFieldsetIni('Dados do Logradouro')->setPreFix('logradouro');
$fh->openCol('12')->text('cep')->closeCol();
$cep = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->select('tipoLogradouro')->closeCol();
$tipo = $fh->getLastId();
$fh->lineDown();
$fh->openCol('12')->text('nomeLogradouro')->closeCol();
$nomeLogradouro = $fh->getLastId();
$idLogradouro = $fh->getIdFor('idLogradouro');
$fh->lineDown();
$fh->openCol('12')->select('status')->closeCol();

//$fh->lineDown();
//    $fh->openCol('12')->select('bairro')->closeCol();
//$fh->lineDown();
$this->partialObj('adm')->partial('bairros/partial-form', $fh, ['this'=>&$d["this"]]);

$fh->closeLine()->renderFieldsetFim()->openLine()->removePreFix();

?>

<script lang="javascript">

    $(function () {
        var eleNome = "<?php echo $nomeLogradouro; ?>";
        var eleId = "<?php echo $idLogradouro; ?>";
        var eleCep = "<?php echo $cep; ?>";
        var eleTipo = "<?php echo $tipo; ?>";
        
        var url = "<?php echo $d['this']->url('adm/default', array('controller' => 'logradouros', 'action' => 'autoComp'), [], FALSE, FALSE); ?>";

        function executeAutoComp(element, campos, by) {
            action.autoComp(element, {
                serviceUrl: url,
                params: {
                    searchBy: by,
                    idLogradouro: eleId, //
                    nomeLogradouro: eleNome, //
                    tipoLogradouro: eleTipo, //
                    cep: eleCep //
                },
                responseTo: campos
            });
        }
        
        var campos = {};
        campos[eleNome] = [eleNome]; //
        campos[eleId] = [eleId]; //
        campos[eleCep] = [eleCep]; //
        campos[eleTipo] = [eleTipo]; //
        executeAutoComp(eleNome, campos, "nomeLogradouro");
        
        executeAutoComp(eleCep, campos, "cep");
    });

</script>