<?php 
/**
 * @author
 */

/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'empresaenderecos';
$route = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Empresa Enderecos</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'Endereço Principal', 'Endereço Tipo', 'Empresa', 'Endereco', 'Ação']);
/* @var $entity \Tcmed\Entity\EmpresaEndereco */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getEndPrincipal(),
        $entity->getEndTipo(),
        $entity->getEmpresa()->getIdEmpresa(),
        $entity->getEndereco()->getIdEndereco(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    $(function () {

    });
    
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>