<?php 
/**
 * 
 * Inclui o CSS padrão contendo estilos prontos, para utilização exclusiva em
 * páginas de exibição do PDF
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 10-11-2016
 * 
 */
?>
<style type='text/css'>

    /*
     *  CONFIGURAÇÕES GERAIS ===================================================
     */

    * {
        margin    : 0px;
        padding   : 0px;
    }

    .folha {
        width     : 190mm;
        height    : 280mm;
    }

    .folha-landscape {
        height    : 190mm;
        width     : 280mm;
    }

    /*
     *  CSS BOOTSTRAP ==========================================================
     */
    .table{
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        color: #333;
        font-size: 10px;
    }

    .table tr, 
    .table td, 
    .table th {
        border: 1px solid #ccc;
    }

    .table thead tr {
        border-bottom: 2px solid #ddd;
    }

    .table thead th {
        background-color: #eee;
        font-size: 14px;
    }

    .table td{
        padding-left: 5px;
        padding-right: 5px;
    }

    .table-striped tr:nth-child(even) {
        background: #f9f9f9
    }

    .text-right {
        text-align: right;
    }

    .text-center {
        text-align: center;
    }
</style>