<?php

/* @var $empresa \Tcmed\Entity\Empresa */
/* @var $endereco \Tcmed\Entity\Endereco */
/**
 * Endereco da empresa
 */
$endereco = $empresa->getEndereco();
$complemento = empty($endereco->getComplemento()) ? "&nbsp;" : $endereco->getComplemento();
$dadosColetados = '';
$ppra = $empresa->getPpra();
$saudeAt = ($empresa->getAtividade() == 'SAÚDE');
if($ppra){
    /* @var $vigencia \Tcmed\Entity\PpraVigencia */
    $vigencia = $ppra->listPpraVigencia(['ini' => ['lte', $periodo["iniObj"]], 'fim' => ['gte', $periodo["iniObj"]]], TRUE);
    if($vigencia instanceof \Tcmed\Entity\PpraVigencia){
        /* @var $titulo \Tcmed\Entity\PpraVigenciaTitulo */
        $titulo = $vigencia->listTitulos(['nome' => 'ANÁLISE DOS DADOS COLETADOS', 'status' => 'ATIVO'], TRUE);
        if($titulo instanceof \Tcmed\Entity\PpraVigenciaTitulo){
            $posts = $titulo->listPosts();
            /* @var $post \Tcmed\Entity\PpraVigenciaPost */
            foreach ($posts as $post) {
                $dadosColetados .= $post->getTexto();
            }
        }
    }
}
?>

<style>
    table td, table th {
        border: 1px solid #555;
    }
    
    table { 
        width: 100%;
    }

    .center {
        text-align: center;
    }

    .italic {
        font-style: italic;
    }

    .bg-gray {
        background-color: #ddd;
    }

    .title {
        font-style: italic;
        background-color: #eee;
        text-align: center;
    }

    .pad-10{
        padding-top: 13px;
        padding-bottom: 20px;
        padding-left: 5px;
        padding-right: 5px;
    }
    
    .pad-gamb{
        padding-top: 130px;
        padding-bottom: 13px;
    }

    .bold {
        font-weight: bold;
    }

    table{
        width: 100%;
        border: 1px solid <?php echo $corSistema ?>;
        border-collapse: collapse;
    }

    table td, .tbl-div{
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-weight: 500;
        line-height: 1.1;
        color: inherit;
        font-size: 11px;
    }
    
    .analise-format{
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-weight: 500;
        line-height: 1.1;
        color: inherit;
        font-size: 11px;
    }

    .tbl-div {
        border: 1px solid #333;
        width: 100%;
    }
    
    .alpha-ol {
        list-style-type: lower-latin;
    }
    
    .table-empty{
        width: auto;
        
    }
    .fl {
        page-break-after: always;
    }
</style>
<table>
    <tr class="bg-gray">
        <td class="center">
            <?php
            $img = $param('all','asoDirImage') . "tcmed3.jpg";
            echo '<img src="' . $img . '" width="215" height="60">';
            ?>
        </td>
        <td class="center">
            <p>
                <font color="#2093F7">
                <strong>PCMSO</strong><br>
                Programa de Controle Médico de Saúde Ocupacional<br>
                NR 7<br>
                </font>
                Médico Coordenador Dr. ARTHUR MOREIRA RICCA
            </p>
        </td>
        <td class="center">
            <p>
                Validade<br>
                <?php echo $periodo["ini"] ?><br>
                <?php echo $periodo["fim"] ?>
            </p>
        </td>
    </tr>
</table>

<br><br>

<table>
    <thead>
        <tr class="bg-gray">
            <td colspan="4" class="center"><b>IDENTIFICAÇÃO</b></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="4">
                Empresa<br><?php echo $empresa->getFantasiaEmpresa() ?>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                Nome Abreviado<br><?php echo $empresa->getReferenciaEmp() ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                Endereco<br><?php echo $empresa->getEndereco('format', ['l, n']) ?>
            </td>
            <td>
                Complemento<br><?php echo $complemento ?>
            </td>
            <td>
                CNPJ<br><?php echo $empresa->getCnpj() ?>
            </td>
        </tr>
        <tr>
            <td>
                CEP<br><?php echo $endereco->getLogradouro()->getCep() ?>
            </td>
            <td>
                Cidade<br><?php echo $endereco->getLogradouro()->getBairro()->getCidade()->getNomeCidade() ?>
            </td>
            <td>
                Bairro<br><?php echo $endereco->getLogradouro()->getBairro()->getNomeBairro() ?>
            </td>
            <td>
                UF<br><?php echo $endereco->getLogradouro()->getBairro()->getCidade()->getEstado()->getUf() ?>
            </td>
        </tr>
        <tr>
            <td>
                CNAE<br><?php echo $empresa->getCnae() ?>
            </td>
            <td>
                Grau de Risco<br><?php echo $empresa->getGrauRisco() ?>
            </td>
            <td colspan="2">
                Descrição CNAE<br><?= $empresa->getPpra('atividade'); ?>
            </td>
        </tr>
    </tbody>
</table>
<table>
    <tbody>
        <tr>
            <td class="title bg-gray"><b>INTRODUÇÃO</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify">
                O Programa de Controle Médico de Saúde Ocupacional, também 
                denominado Norma Regulamentadora Nº 7 (NR-7), compõem um conjunto 
                de normas contidas na portaria nº 3.214 de 08 de junho de 1978, 
                que regulamenta o Capítulo V do Título II da Consolidação das Leis 
                do trabalho, relativas à Segurança e Medicina do Trabalho.
                <br><br>
                Esta Norma Regulamentadora – NR – estabelece a obrigatoriedade da 
                elaboração e implementação, por parte de todos os empregadores e 
                instituições que admitam trabalhadores como empregados, do Programa 
                de Controle Médico de Saúde Ocupacional – PCMSO, com a finalidade 
                da promoção e preservação da saúde do conjunto dos seus trabalhadores.
                <br><br>
                O conjunto destas normas regulamentadoras (Portaria nº 3.214 de 08 de junho de 1978) 
                define parâmetros mínimos e diretrizes ferais a serem cumpridas 
                pelo empregador, as quais, no entanto, poderão ser alteradas, de 
                acordo com a negociação coletiva de trabalho em vigor, ou por determinação 
                do médico do trabalho.
                <br><br>
                Caberá a empresa contratante de mão-de-obra prestadora de serviços 
                informar, à TECNOMED, os ricos existentes e auxiliar na elaboração 
                e implementação do PCMSO nos locais de trabalho onde os serviços 
                estão sendo prestados.
            </td>
        </tr>
        <tr>
            <td class="title bg-gray"><b>OBJETIVOS DO PCMSO</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify">
                O programa de controle Médico de Saúde Ocupacional está articulado 
                com as demais normas regulamentadoras, em especial com o Programa 
                de Prevenção de Riscos Ambientais e com a Comissão Interna de Prevenção 
                de Acidentes C.I.P.A quando indicado.
                <br><br>
                O PCMSO é parte integrante do conjunto mais amplo de iniciativas 
                da empresa no campo da saúde dos trabalhadores, devendo estar 
                articulado com o disposto nas demais normas regulamentadoras, com 
                o objetivo de promover e preservar a saúde da totalidade dos trabalhadores 
                da empresa, com relação aos agravos de saúde relacionados com os 
                riscos definidos para sua função.
                <br><br>
                O PCMSO deverá considerar as questões incidentes sobre o indivíduo 
                e a coletividade de trabalhadores, privilegiando o instrumental 
                clínico-epidemiológico na abordagem da relação entre sua saúde e 
                o trabalho.
                <br><br>
                O PCMSO deverá ter caráter de prevenção, rastreamento e diagnóstico 
                precoce dos agravos à saúde relacionados ao trabalho, inclusive de 
                natureza subclínica, além da constatação da existência de casos 
                de doenças profissionais ou danos irreversíveis à saúde dos trabalhadores.
                <br><br>
                O PCMSO deverá ser planejado e implantado com base nos riscos à 
                saúde dos trabalhadores, especialmente os identificados nas avaliações 
                previstas nas demais normas regulamentadoras.
            </td>
        </tr>
        <tr>
            <td class="title bg-gray"><b>RESPONSABILIDADE DO EMPREGADOR</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify">
                1 – Cumprir e fazer cumprir as disposições legais e regulamentares 
                sobre segurança e medicina do trabalho, garantindo a elaboração e 
                efetiva implementação do PCMSO, bem como zelar pela sua eficácia.
 	        <br><br>
                2 – Custear sem ônus para o empregado todos os procedimentos 
                relacionados ao PCMSO.
 	        <br><br>
                3 – Prevenir atos inseguros no desempenho do trabalho.
 	        <br><br>
                4 – Divulgar as obrigações e proibições que os empregados devem 
                conhecer e cumprir.
 	        <br><br>
                5 – Determinar os procedimentos que deverão ser adotados em caso 
                de acidentes do trabalho e doenças profissionais ou do trabalho
 	        <br><br>
                6 – Adotar medidas determinadas pelo Ministério do Trabalho.
 	        <br><br>
                7 – Adotar medidas para eliminar ou neutralizar a insalubridade e 
                as condições inseguras do trabalho.
 	        <br><br>
                8 – Informar aos empregados os riscos profissionais que possam 
                originar-se nos locais de trabalho.
                <br><br>
            </td>
        </tr>
    </tbody>
</table>
    <pagebreak>
<table>
    <tbody>
        <tr>
            <td class="title bg-gray remove-bullet"><b>RESPONSABILIDADE DO EMPREGADO</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify" >
                        1 - Cabe ao empregado:
                        <br><br>
                            1.1 - Cumprir as disposições legais e regulamentares sobre 
                            segurança e medicina do trabalho, inclusive as ordens de serviços 
                            expedidas pelo empregador.
                            <br>
                            1.2 - Usar o EPI fornecido pelo empregador.
                            <br>
                            1.3 - Submeter-se aos exames médicos previstos nas Normas 
                            Regulamentadoras – NR.
                            <br>
                            1.4 - Constitui ao ato faltoso a recusa injustificada do empregado 
                            ao cumprimento do disposto no item anterior.
                            <br>
                            1.5 - O não cumprimento das disposições legais e regulamentadoras 
                            sobre segurança e medicina do trabalho acarretarão ao 
                            empregado a aplicação das penalidades previstas na legislação pertinente.
            </td>
        </tr>
    </tbody>
</table>
<table>
    <tbody>
        <tr>
            <td class="title bg-gray"><b>MÉDICO COORDENADOR</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify">
                
                <p>• Coordenar o PCMSO;</p>
                <p>• Supervisionar diretamente a execução do PCMSO;</p>
                <p>• Dar ciência das doenças ocupacionais ao departamento de Recursos 
                 Humanos para que seja emitido o Registro de Acidente de Trabalho;</p>
                <p>• Prestar esclarecimentos, quando solicitado, sobre os problemas de 
                 saúde ocupacional dos servidores, respeitando o princípio ético do sigilo médico;</p>
                <p>• Realizar os exames médicos previstos para o PCMSO: admissionais, 
                 periódicos, mudança de função, retorno ao trabalho e demissionais, 
                 ou selecionar e orientar profissional médico familiarizado com os princípios 
                 da patologia ocupacional e suas causas, para a execução dos mesmos;</p>
                <p>• Zelar pela padronização dos exames médicos ocupacionais a fim de 
                 que o empregado tenha o mesmo padrão de atendimento independente 
                 da unidade em que estiver vinculado;  Fornecer ao Órgão informações 
                 referentes a profissionais e/ou entidades devidamente capacitados, 
                 equipados e qualificados para a realização dos exames complementares 
                 previstos no PCMSO;</p>
                <p>• Solicitar o afastamento do empregado do trabalho ou da exposição 
                 ao risco quando constatada doença profissional e relatar quais 
                 medidas específicas de controle do fator causal podem ser adotadas.</p>
            </td>
        </tr>
        <tr>
            <td class="title bg-gray"><b>MÉDICO EXAMINADOR</b></td>
        </tr>
        <tr>
            <td class="pad-10" align="justify">
                <p>• Examinar o empregado e registrar em prontuário próprio a anamnese realizada;</p>
                <p>• Dar ciência ao empregado sobre o(s) resultado(s) do(s) exame(s) e orientá-lo;</p>
                <p>• Comunicar ao Médico Coordenador os casos de doenças ocupacionais;</p>
                <p>• Seguir a rotina estabelecida pelo Médico Coordenador;</p>
                <p>• Emitir o Atestado de Saúde Ocupacional – ASO.</p>
            </td>
        </tr>
    </tbody>
</table>
    <table>
        <tbody>
        <tr>
            <td class="title bg-gray"><b>DESENVOLVIMENTO DO PCMSO</b></td>
        </tr>
        <tr>
            <td class="">
                Com um programa específico para a empresa, onde estarão definidas 
                as necessidades de exames complementares, clínicos e sua periodicidade, 
                compete a TECNO MED, realizar os seguintes exames médicos obrigatórios:
                <br>
                    <br>a) Admissional          
                    <br>b) Periódico            
                    <br>c) Demissional          
                    <br>d) Retorno ao Trabalho  
                    <br>e) Mudança de Função    
                <br>
                Exames complementares quando necessário, serão previstos nos quadros 
                e anexos do programa desta norma regulamentadora, para serem realizados 
                em instituições devidamente capacitadas, indicadas pela TECNOMED.
                <br><br>
                <b>Exame Admissional:</b> deverá ser realizado antes que o trabalhador 
                assuma suas atividades, e tenha seu registro profissional efetivado.
                <br>
                <b>Exame Periódico:</b> de acordo com os intervalos mínimos de tempo de 
                tempo abaixo descriminado:
                <br><br>
                1 – Para trabalhadores expostos a riscos ou situações de trabalho 
                que impliquem no desencadeamento ou agravamento de doenças crônicas, 
                os exames deverão ser repetidos a cada ano ou intervalos menores, a critério do médico encarregado, 
                ou se notificado pelo médico agente da 	inspeção do trabalho, ou, 
                ainda, como resultado de negociação coletiva de trabalho.
                <br><br>
                2 – Para os demais trabalhadores:
                <br>
                2.1 – Anual quando menores de dezoito anos e maiores de quarenta 
                e cinco anos de idade.
                <br>
                2.2 – A cada dois anos para os trabalhadores entre dezoito anos 
                e quarenta e cinco anos de idade. 
                <br><br>
                
            <?php                
            if ($empresa->getAtividade() == 'ALIMENTOS'):
            ?>
                <b>Exame Periódico Complementar:</b>
                1 – A critério do Médico Coordenador, para trabalhadores expostos 
                a riscos ou situações de trabalho que impliquem no desencadeamento 
                ou agravamento de doenças do Trabalho.
                <br><br>
                2 – A cada 6 meses conforme norma da Vigilância Sanitária, para 
                trabalhadores manipuladores de alimentos.
                <br><br>
            <?php
            endif;            
            ?>
                
                <b>Exame de Retorno ao Trabalho:</b> deverá ser realizado, obrigatoriamente 
                no primeiro dia de volta ao trabalho, de trabalhador ausente por 
                período igual ou superior a 30 dias por motivo de doença, ou acidente 
                de natureza ocupacional ou não, ou licença maternidade.
                <br><br>
                <b>Exame de Mudança de Função:</b> será obrigatório antes da data da 
                mudança da função. Para fins desta NR, entende-se por mudança de 
                função toda e qualquer alteração de atividade, posto de trabalho 
                ou de setor que implique na exposição do trabalhador a risco diferente 
                daquele a que estava exposto antes da mudança.
                <br><br>
                <b>Exame Demissional:</b> Obrigatório até a data da homologação, desde 
                que o ultimo exame médico ocupacional tenha sido realizado há mais 
                de 135(Cento e trinta e cinco) dias para as empresas de grau de 
                risco 1 e 2 segundo o quadro I da NR-4.
                90(Noventa) dias para as empresas de grau de risco 3 e 4, segundo 
                o quadro I da NR-4.
            </td>
        </tr>
    </tbody>
</table>
    <pagebreak class="fl">
    <table>
        <tbody>
            <tr>
                <td class="title bg-gray"><b>HORÁRIO DE FUNCIONAMENTO</b></td>
            </tr>
            <tr>
                <td class="pad-10">
                    Rua Cincinato Braga 59 – 3º andar – cj 3D1– CEP 01333-011 – Fone 3266-5850
                    <br><br>
                    Horário de Funcionamento do <b>Ambulatório do PCMSO</b> na Tecno Med
                    - de 2ª a 6ª Feiras das <b>07h30min às 15h30min.</b>
                    <br><br>
                    Horário de Funcionamento do <b>Administrativo</b> da Tecno Med
                    - de 2ª a 6ª Feiras das <b>08h00min às 17h00min.</b>
                </td>
            </tr>
            <tr>
                <td class="title bg-gray"><b>ATESTADO DE SAÚDE OCUPACIONAL</b></td>
            </tr>
            <tr>
                <td class="pad-10">
                    Para cada exame médico realizado aos trabalhadores da contratante pela TECNOMED, 
                    será emitido um atestado de saúde ocupacional   ASO    em 02 vias.
                    <br><br>
                    A primeira via deverá ser arquivada no local de trabalho do trabalhador. A segunda 
                    via será obrigatoriamente entregue ao trabalhador.
                </td>
            </tr>
            <tr>
                <td class="title bg-gray"><b>PRONTUÁRIO MÉDIO OCUPACIONAL</b></td>
            </tr>
            <tr>
                <td class="pad-10">
                    Os dados obtidos na anamnese ocupacional, exames clínicos e subsidiários, bem como 
                    as conclusões e medidas aplicadas serão registradas em prontuário clínico individual, 
                    que ficará sob responsabilidade da TECNOMED, por um período mínimo de 20 anos, após o 
                    desligamento do trabalhador.
                </td>
            </tr>
        </tbody>
    </table>
    <table>
        <tbody>
            <tr>
                <td class="title bg-gray"><b>CORRELAÇÃO COM O PPRA</b></td>
            </tr>
            <tr>
                <td class="pad-10" align="justify">
                    <b><u>ANÁLISE DE DADOS COLETADOS:</u></b><br><p><?= strip_tags($dadosColetados, '<br><strong><p>'); ?></p>
                </td>
            </tr>
        </tbody>
    </table>
    <pagebreak class="fl">
        
<?php   

$showSetor = function($setor){
    ?>
    <br>
    <table>
        <tr>
            <td class="bg-gray">Setor: <b><?= $setor; ?></b></td>
        </tr>
    </table>
    <?
};

// ========== INI GERAR PARTE DE EXIBIÇÃO DOS CARGOS E GUARDAR DENTRO DE UMA VARIAVEL
        // coloca dois cargo na pagina e pula
        $qtdPag = 2 ;         
        if ($saudeAt){
            // coloca um cargo na pagina e pula
            $qtdPag = 1 ;
            $biologicoFuncs = [];
        }
        $setor     = '';
        $cargoInd  = 0;        
        ob_start();
        /* @var $ocupacao \Tcmed\Entity\PpraOcupacao */
        foreach ($ocupacaos as $ocupacao) :
            
            $cargoInd++;
            if($cargoInd > $qtdPag){
                echo '<pagebreak>';
                $qtdPag += 4;
            }
            //exibir troca de setor
            if($setor != $ocupacao->getSetor()->getNomeSetor()){
                $setor = $ocupacao->getSetor()->getNomeSetor();
                $showSetor($setor);
            }            
            // pegar os hist desta ocupacao da empresa
            $histOcupcaionals = $ocupacao->getOcupacao()->listHistOcupacional([
                'status'    => 'ATIVO'
                ,'empresa'  => $empresa
//                ,'dtIni'    => ['lte' => $periodo['iniObj']]    
//                ,'dtFim'    => ['gte' => $periodo['iniObj']]    
            ]);
            $cargo = '';
            $funcionarios = [];
            $riscos = '';
            $epis = '';
            $epcs = '';
            // carregando os funcionario
            /* @var $histOcupcaional \Tcmed\Entity\HistOcupacional */
            foreach ($histOcupcaionals as $histOcupcaional) {
                $func = $histOcupcaional->getFuncionario();
                if(is_null($func)){
                    continue;
                }
                $addfuncionario = [];
                $addfuncionario[] = $func->getNomeFuncionario();
                if ($periodo["iniObj"] instanceof \DateTime) {
                    /* @var $idade \DateInterval */
                    $idade = $periodo["iniObj"]->diff($func->getDtNascimento(TRUE));
                    $addfuncionario[] = $idade->y ;
                    $addfuncionario[] = $func->getPeriodicidade($periodo["iniObj"]);
                }else{
                    $addfuncionario[] = 'idade não calculada' ;
                    $addfuncionario[] = 'ANUAL' ;
                }
                $addfuncionario[] = $func->getCpf();                
                $addfuncionario[] = $func->getCarteiraProfissional();                
                $addfuncionario[] = $ocupacao->getOcupacao()->getCargo(true);                
                
                $funcionarios[] = $addfuncionario;                
            }
?>
    <br>
        <table>
            <tr>
                <td class="bg-gray" style="width: 60%"><span class="bold">Cargo: <?php echo $ocupacao->getOcupacao()->getCargo(true); ?></span></td>
                <td class="bg-gray" style="width: 40%">
                    <span class="bold">CBO: <?= $ocupacao->getCargo()->getCbo(); ?></span>
                </td>
            </tr>    
        </table>
        <table>
            <tr>
                <td>FUNCIONÁRIO(S):</td>
                <td>IDADE:</td>
                <td>PERIÓDICO:</td>
            </tr>
            <?
            foreach ($funcionarios as $funcionario) {
                ?>
                <tr>
                    <td><?= $funcionario[0];?></td>
                    <td><?= $funcionario[1];?></td>
                    <td><?= $funcionario[2];?></td>
                </tr>
                <?
            }
            if(empty($funcionarios)){
                ?>
                <tr>
                    <td>Sem Funcionário</td>
                    <td></td>
                    <td></td>
                </tr>
                <?
            }
            ?>
        </table>
        <table>
            <tr>
                <td>Descrição da Ocupação:</td>
            </tr>
            <tr>
                <td><?= $ocupacao->getOcupacao()->getDescricaoCargo()->getDescricao(); ?></td>
            </tr>
        </table>
    
<?            
            $riscos = $ocupacao->getOcupacao()->listOfCargoRiscos();
            /* @var $risco \Tcmed\Entity\RiscoOcupacao */
            $showRisco = '';
            $sep       = '';
            $point     = '.';
            $showEpi = [];
            $showEpc = [];
            foreach ($riscos as $risco) {
                // Montar lista de ocupacoes com risco biologico para emp de atividade saude
                if ($saudeAt AND $risco->getRisco()->getRisco() == 'BIOLÓGICO'){
                    $biologicoFuncs = array_merge($biologicoFuncs, $funcionarios);
                }
                $showRisco .= $sep . $risco->getRisco()->getRisco();
                $sep = '; ';
                /* Lista EPI na tabela */
                $epis = $risco->listEpiRiscoOcupacao();
                /* @var $epi \Tcmed\Entity\EpiRiscoOcupacao */
                foreach ($epis as $epi) {
                    $showEpi[$epi->getEpi()->getEpi()] = $epi->getEpi()->getEpi();
                }
                
                /* Lista EPC na tabela */
                $epcs = $risco->listEpcRiscoOcupacao();
                /* @var $epc \Tcmed\Entity\EpcRiscoOcupacao */
                foreach ($epcs as $epc) {
                    $showEpc[$epc->getEpc()->getEpc()] = $epc->getEpc()->getEpc();
                }
            
            }
            $showRisco .= $point;
            if(empty($showRisco)){
            ?>
                <table>
                    <tr>
                        <td>Risco Ocupanional : Ausência de Exposição a Agentes Nocivos</td>
                    </tr>
                </table>
            <?
            }else{
            ?>
                <table>
                    <tr>
                        <td colspan="3">Risco Ocupanional : <span class="bold"><?=$showRisco;?></span></td>
                    </tr>
                    <tr>
                        <td style="width: 5%"></td>
                        <td style="width: 35%">Equipamento Proteção Individual (EPI): </td>
                        <? if(!empty($showEpi)){ ?>
                        <td><table border="0"><tr><td>• <?= implode('</td></tr><tr><td>• ', $showEpi);?></td></tr></table></td>
                        <?}else{?>
                        <td>Não se Aplica</td>
                        <?}?>
                    </tr>
                    <tr>
                        <td style="width: 5%"></td>
                        <td style="width: 35%">Equipamento Proteção Coletivo (EPC):</td>
                        <? if(!empty($showEpc)){ ?>
                        <td><table border="0"><tr><td>• <?= implode('</td></tr><tr><td>• ', $showEpc);?></td></tr></table></td>
                        <?}else{?>
                        <td>Não se Aplica</td>
                        <?}?>
                    </tr>
                </table>
            <?
            }        
        endforeach;
        
        // guardas os html na variavel
        $htmlSetorCargos = ob_get_contents();
        ob_end_clean();
        
// ========== FIM GERAR PARTE DE EXIBIÇÃO DOS CARGOS E GUARDAR DENTRO DE UMA VARIAVEL

    
// ========== INI GERAR PARTE DE EXIBIÇÃO PARA EMPRESAS DE SAUDE  
if ($saudeAt):         
?>
    <table>
        <tbody>
            <tr>
                <td class="title bg-gray"><b>Segue o disposto na NR-32 que trata da segurança e saúde no trabalho em serviço de saúde:</b></td>
            </tr>
            <tr>
                <td class="pad-10">
                    32.2.3.1
                    <br><br>

                    Na ocorrência de um acidente biológico com a(o) auxiliar de odontologia, com possível contaminação biológica, o empregador deverá ser 
                    avisado imediatamente que caracterizará o acidente de trabalho e emitirá a Comunicação de Acidente de Trabalho, conforme legislação vigente.
                    <br>
                    O(A) auxiliar de odontologia que sofreu o acidente biológico com ferimento da pele, deverá lava-lo com sabão e água corrente, e ser 
                    acompanhado ao hospital de referência para o devido diagnóstico e tratamento.
                    <br>
                    Este acidente deverá ser comunicado ao médico coordenador do PCMSO, para que se faça o devido registro e acompanhamento médico.
                    <br><br>

                    32.2.3.3
                    <br><br>

                    É constatado risco biológico por simples observação, no desempenho das funções do auxiliar de odontologia. Este risco biológico é 
                    classificado como “classe de risco 1” por apresentar baixo risco individual para o trabalhador e para a coletividade, com baixa 
                    probabilidade de causar doença ao ser humano.
                    <br>
                    O local de trabalho do auxiliar de odontologia é o consultório dentário  fazendo a aspiração da saliva do paciente e instrumentando 
                    o dentista em seus procedimentos; realiza também a limpeza do instrumental odontológico sempre usando equipamentos de proteção individual.
                    <br>
                <?php
                foreach ($biologicoFuncs as $func) :
                ?>
                    <br>                    
                    O <?=$func[5];?> senhor(a) <?=$func[0];?> CPF <?=$func[3];?>, carteira profissional nº <?=$func[4];?>
                <?php
                endforeach;
                ?>    
                    <br><br>
                    Para este(s) auxiliar(es) de odontologia são realizados anualmente ou quando houver um acidente exames sorológicos para  Hepatite A, B e C, 
                    AntiHIV e VDRL além de hemograma.
                    <br>
                    Anualmente também é realizado o acompanhamento das vacinas: Hepatite A e B, Gripe Influenza , Duplo Tipo Adulta,(Difteria e Tétano)  
                    Varicela, Tríplice Viral,  Tríplice Bacteriana para adulto e Tuberculose, que fazem parte do calendário vacinal do Ministério da Saúde.
                </td>
            </tr>
        </tbody>
    </table>
<?php
endif;        
// ========== FIM GERAR PARTE DE EXIBIÇÃO PARA EMPRESAS DE SAUDE           
?>
        
    <table>
        <tbody>
            <tr>
                <td class="title bg-gray"><b>ESTOJO DE PRIMEIROS SOCORROS</b></td>
            </tr>
            <tr>
                <td class="pad-10">
                    De acordo com as normas do PCMSO, deverá estar disponível no local de trabalho, um 
                    estojo contendo os materiais necessários ao atendimento de Primeiros Socorros, conforme 
                    discriminação abaixo.
                    <br>
                    Cumpre-se ressaltar, que este estojo destina-se apenas ao atendimento de ferimentos de 
                    gravidade leve, quais sejam, pequenas lesões perfuro-cortantes, contundentes, ou de 
                    lesões irritativas pelo manuseio de substâncias químicas, até que se dê o encaminhamento 
                    adequado ao atendimento da vítima.
                    <br>
                    Lesões de maior gravidade, na ausência de profissionais da área de saúde, deverão ser 
                    acionados sistemas de resgate e remoção especializada, privada, caso haja contratos 
                    específicos, ou públicos através do telefone 193.
                    <br>
                    <table align="center" class="table-empty">
                        <tr>
                            <td colspan="12" class="title bg-gray"><b>CONTEÚDO DO ESTOJO</b></td>
                        </tr>
                        <tr>
                            <td align="right justify">2 Pares</td>
                            <td align="justify">Luvas cirúrgicas tam. médio.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Colar cervical tamanho médio.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Envelope de compressa (gaze) para curativo de 7,5 cm x 7,5 cm estéril.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Envelope de  compressa para curativo de 10 cm x 15 cm estéril.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Caixa de curativo anti-séptico (Band Aid).</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Atadura de crepe de 20 cm x 4,5 m.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Atadura de crepe de 10 cm x 4,5 m.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Pacote de algodão hidrófilo em bolas 100g.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Bandagem elástica de 10 cm x 4,5 m.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Caixa de astes flexíveis (cotonete).</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Frasco de 250 ml de soro fisiológico.</td>
                        </tr>
                        <tr>
                            <td align="right">1 unidade</td>
                            <td align="justify">Tesoura de ponta romba.</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
<?php

    echo $htmlSetorCargos;
    
?>

<div style="width: 300px">
    <?php
        /* @var $medico \Tcmed\Entity\Medico */
    $img = ($medico) ? $param('all','medicoDirAss') . $medico->getAssinatura() : ''; 
    echo '<img width="230" height="58" style="margin-bottom: -10px; margin-left: 25px;" src="' . $img . '">';
    ?>
    <p class="center" style="font-size: 10px">
        ___________________________________________________<br>Médico Coordenador<br>
            <?php echo 'Dr. '.$medico->getNomeMedico() . " CRM " . $medico->getCrm() ?>
    </p>