<?php
/* @var $form Tcmed\Form\ProgramaPcmso */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('tcmed');
$form       = $this->form;

echo '<h3>', $title, '</h3>';
?>


<?php

$lambda = function ($value, &$data){
        if (is_callable($this->funcEdit)) {
            $lambda = $this->funcEdit;
            $lambda($value, $data);
            return;
        }
        echo "\t", '<td nowrap style="font-size: 14pt;">',
                '<span class="hand btn-down-pdf" data-id="', $value, '" title="Fazer Download"><i class="fa fa-cloud-download"></i>','</span>&nbsp;', PHP_EOL,
                '&nbsp;',
                '<span class="hand" onClick="del(\'', $value, '\',this)" title="Excluir"><i class="fa fa-trash"></i></span>',
             "</td>", PHP_EOL; 
};


$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$partialObject = $this->partialObj('tcmed');

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));
$fh->openCol(12);
$table->openTable(TRUE);
$table->setLambda($lambda);
$table->setOrderList($this->dataView['orderBy']);
$table->renderThead([
    ['label' => 'ID'                   ],
    ['label' => 'Empresa'              ],
    ['label' => 'Período'              ],
    ['label' => 'Criado em'            ],
    ['label' => 'Criado por'           ],
    ['label' => 'Ação'                 ],

]);
/* @var $entity \Tcmed\Entity\ProgramaPcmso */
foreach ($this->data as $entity) {
    if($entity->getStatus() == "ATIVO"){
        $table->renderLine([
            $entity->getId(),
            $entity->getEmpresa(),
            $entity->getPeriodo(),
            $entity->getCreatedAt(),
            $entity->getCreatedBy('nome'),
            $entity->getId(),
        ]);
    }
}
    $table->renderCloseTable();

$fh->closeCol();
$fh->closeLine();
$fh->formEnd();
echo $this->partial('partials/modal');
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
</center>

<?php 
// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'

); 
?>
<iframe hidden="true" id="iframe-pdf-dow" src=""></iframe>
<script lang="javascript">
    
$(function(){
    var transp = <?php echo json_encode($transp) ?>;
    
        $('.btn-down-pdf').click(function(){
            var $btn = $(this);
            var pdfId   = $btn.data('id');
            gModal.confirm('Deseja fazer o download do Programa PCMSO?', function(){
                var url  = '<?php echo $this->url($route, array('controller' => $controller, 'action' => 'downloadPdf'), [], FALSE, FALSE); ?>'+'/'+pdfId;
                $('#iframe-pdf-dow').prop('src', url);
            });
        });
});

function del(key) {
    gModal.reset('confirm',2).setMsg('Deseja mesmo excluir este registro?').setClickOk(function(){
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }).showModal();
}

$('#btn-pesquisa').click(function(){
    $.processa({
        url  : "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>",
        frm  : true,
        type : 'POST'                
    });
});
</script>
