<?php
$controller = "programaPcmsos";
$route = "tcmed/default";

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller), [], FALSE));


$fh->openCol(13);
$fh->buildButton([
                    "id"    => "salvaPdf", 
                    "class" => "btn-block glyphicon glyphicon-download-alt"],
                    " Salvar PDF", 
                    "success", 
                    TRUE);
$fh->closeCol();
?>
<iframe id="iframeAso" width='100%' height='500' frameborder='0' 
        src='<?php echo $this->url('tcmed/default', $this->route, [], FALSE, FALSE); ?>'>
</iframe>

<script lang="javascript">
    $(function () {
        /**
         * Alterar a altura para visualização do aso
         */
        $('#iframeAso').height($(document).height() * 0.85);
        
        $('#salvaPdf').click(function(){
            gModal.confirm('Deseja realmente salvar este programa?', function(){
                $.processa({
                    url  : '<?php echo $this->url($route, array('controller' => $controller, 'action' => 'salvaHtml'), [], FALSE, FALSE); ?>'
                    ,type : 'GET'
                    ,savePage : true
                });
            });
        });
    });
    
</script>