<?php 
/* @var $fh    \Application\View\Helper\FormHelp */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
?>
<h3 class=""><?php echo $this->dataView['titulo']; ?></h3>
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Listagem</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Limpar</button>
</p>
<br />
<?php
if(is_array($this->resul)){
    foreach ($this->resul[1] as $key => $vlr){
        if ($this->resul[0] === FALSE){
            echo '<h4 class="alert alert-danger">', $vlr , '</h4>';
        }else{
            echo '<h4 class="alert alert-success">', $vlr , '</h4>';
        }
    }
}
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(true);
$fh->formInit();
    $fh->openCol('4',2)->calend('inicio')->closeCol();
$fh->lineDown();
    $fh->openCol('4',2)->calend('fim')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit',['value' => 'Gerar'])->closeCol();
$fh->lineDown()->openCol(12);
    echo '<div id="showListagemRelatorio"></div>';
$fh->closeLine()->formEnd();
//
// === TRANSPORTE ==============================================================
$fields = [];
// ===================================================================== FIM ===
?>

<script lang="javascritp">   
    
    var isValid = function(){
        return true;
    };
    
    $(function(){
        // =====================================================================
        /**
         * @property {Object} fields Campos de transferencia do PHP, que serão
         * utilizados no javascript
         */
        var fields = <?php echo json_encode($fields) ?>;
        
        var showRelatorioLista = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" 
                , type: "POST"
                , savePage: false
                , frm : true
                , ret: '#showListagemRelatorio'
                , data: {
                    id: fields.id
                    , ret      : '#showListagemRelatorio'
                }
            });    
        };
        
        showRelatorioLista();
        
        
    });
</script>
