<html>
    <head>
    </head>
  <body>
<?php
    $this->__set('controller', 'fichaClinicas');
    $this->__set('subMod', 'tcmed');

    include $this->partial('get-pdf-partial-aso-vv-manual-css'); 
?>
<?php 
        /* @var $agenda \Tcmed\Entity\AgendaAmbul */
        /* @var $relDetFunc \Agenda\Entity\RelatorioDetFunc */
        foreach ($listaRelDetFunc as $relDetFunc) {
            echo "<div class='folha'>";
            $agenda->setFuncionario($relDetFunc->getFuncionario());
            $agenda->setEmpresa($relDetFunc->getRelatorioDetEmp('empresa'));
            $agenda->setAdministradora($relDetFunc->getRelatorioDetEmp('administradora'));
            !isset($data['semMedico']) && $agenda->setMedico($relDetFunc->getRelatorioDetEmp('medico'));
            $agenda->setTipoConsulta($data['tipoExame']);
            
            $via = 'da Empresa';
            include $this->partial('get-pdf-partial-aso-vv-manual'); 
            
            // Se a folha for paisagem imprime o tracejado para corte
            if($this->orientation === 'L'){
                include $this->partial('get-pdf-partial-aso-sep'); 
            }
            
            $via = 'do Funcionario';
            include $this->partial('get-pdf-partial-aso-vv-manual'); 
            
            echo "</div>";
        }
        
?>
  </body>
</html>