<?php
/**
 * 
     * @author Paulo Watakabe <watakabe05@gmail.com>
     * @version 1.0  
     * @since 10-08-2016
 */
/* @var $table      \Application\View\Helper\Table */
/* @var $fh         \Application\View\Helper\FormHelp */
/* @var $partial    \Application\View\Helper\PartialObj */
/* @var $form       \Application\Form\FormFilter */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$table      = $this->table();
$form       = $this->form;
$formId     = 'showRelatorio';
$form->setAttribute('id', $formId);
$_POST['formId'] = $formId;
$form->setAttribute('target', $form->get('ret')->getValue());
$fh         = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial     = $this->partialObj();

// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();
$fh->openCol(8);
?>
<h3 class=""><?= $this->dataView['titulo']; ?></h3>
<p id="relatoriosIndexMenu">
    <button type="button" class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php

$fh->closeCol()->openCol(4)->text('limitePag',['labelWidth' => 6,'clean' => FALSE,'extra' => ['icon' => 'search', 'js' => "atualizaPag()"]]);
$fh->closeCol()->lineDown();

$lambda = function ($value, &$data) {  
        echo "\t<td nowrap>",
                '<span class="hand" onClick="show(\'', $value, '\')" title="Abrir Relatorio"><i class="fa fa-pencil"></i> Abrir','</span>', PHP_EOL,
                '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> Del</span>',
             "</td>", PHP_EOL;  
};

$fh->openCol(12);
    $table->openTable(TRUE);
    $table->setEditLine('first');
    $table->setLambda($lambda);
    $table->setOrderList($this->dataView['orderBy']);
    $table->renderThead([
        'Ação'
        ,['label' => 'Relatorio'         , 'order' => 'id']
        ,['label' => 'Data'              , 'order' => 'createdAt']
        ,['label' => 'Condominios'       , 'order' => 'qtd_cond']
        ,['label' => 'Vidas'             , 'order' => 'qtd_vida']
        ,['label' => 'Periodo Ini'       , 'order' => 'inicio']
        ,['label' => 'Periodo Fim'       , 'order' => 'inicio']
        ,['label' => 'Concluido'         , 'order' => 'percent']
        ,['label' => 'Incluido Por'      , 'order' => 'createdBy']
        ,['label' => 'Alterado Por'      , 'order' => 'updatedBy']
        ,['label' => 'alterado em'       , 'order' => 'updatedAt']
        ]);
    /* @var $entity \Agenda\Entity\Relatorio */
    foreach ($this->data as $entity) {
        $backGround = 'backGroundRed';
        if($entity->getPercent(false) >= 50){
            $backGround = 'backGroundOrange';
        }
        if($entity->getPercent(false) >= 100){
            $backGround = 'backGroundGreen';            
        }
        $table->renderLine([
            $entity->getId(),
            $entity->getId(),
            $entity->getCreatedAt(),
            $entity->getQtdCond(),
            $entity->getQtdFunc(),
            $entity->getInicio(),
            $entity->getFim(),
            $entity->getPercent() . '%<span class="' . $backGround . '"></span>',
            $entity->getCreatedBy('nomeUsuario'),
            $entity->getUpdatedBy('nomeUsuario'),
            $entity->getUpdatedAt('full'),
        ]);
    }
    $table->renderCloseTable();


$fh->closeCol()->closeLine();
$fh->formEnd();

/* +----------------------------------------------------------------------------
 * | MODAL se parametriza usando a variavel global gModal
 * +----------------------------------------------------------------------------
 *  Estrutura do modal, para Confirmar com o usuario a ação desejada.
 * 
 */
echo $this->partial('partials/modal', array());

// === TRANSPORTE ==============================================================
$fields = [
    'ret'     => $form->get('ret')->getValue()
    , 'frm'   => $formId
];
// ===================================================================== FIM ===
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>
<style>
    .backGroundRed{
        background-color: #CC3F3A;
    }    
    .backGroundOrange{
        background-color: #eb8f00;
    }    
    .backGroundGreen{
        background-color: #51a351;
    }    
</style>
<script lang="javascript">
    var fieldsRelatorios = <?php echo json_encode($fields) ?>;
    
    var atualizaPag = function(){        
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" ,
            frm: fieldsRelatorios.frm
        });
    };
    var show = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'show'), [], FALSE, FALSE); ?>" + "/" + key
        });
    };
    var edit = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key
        });
    };
    
    var del = function(key) {
        gModal.reset('confirm',3)
        .setMsg('Deseja mesmo inativar este relatório ?')
        .setLabelOk('SIM Remover')
        .setClickOk(function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key
                , frm: 'showRelatorio'
                , ret : fieldsRelatorios.ret
                , type  : 'POST'
                , data  : {
                    ret : fieldsRelatorios.ret
                }
            });
        })
        .showModal(); 
    };
    
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;
        // Esconder menu superior do index
        if('#inter' !== fields.ret){
            $('#relatoriosIndexMenu').hide();
        }
        
        $('.backGroundRed'   ).closest('TD').addClass('backGroundRed'   );
        $('.backGroundOrange').closest('TD').addClass('backGroundOrange');
        $('.backGroundGreen' ).closest('TD').addClass('backGroundGreen' );
        
    });    
</script>