<?php
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 
 * 
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$partial = $this->partialObj('application');

/* @var $entity Agenda\Entity\RelatorioDetEmp */
$entity = $this->entity;
$listaDetFunc = $entity->listRelatorioDetFunc();
$quantListaDetFunc = count($listaDetFunc);

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

list($data, $hora) = explode(';', (new \DateTime('now'))->format("d/m/Y;H:i"));

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

// -----------------------------------------------------------------------------
echo "<h2>{$title}</h2>";

$fh->formInit()->openCol(12);

echo <<<CABECALHO
    <table class="table table-striped table-bordered">
        <tr>
            <td class="text-right">Holding</td>
            <td>{$entity->getAdministradora('hold', ['referenciaHold'])}</td>
            <td>{$entity->getAdministradora('hold', ['nomeHold'])}</td>
            <td><b>Hora:</b> {$hora} <b>Data:</b> {$data} </td>
        </tr>
        <tr>
            <td class="text-right">Sub-Holding</td>
            <td>{$entity->getAdministradora('referenciaSubhold')}</td>
            <td colspan="2">{$entity->getAdministradora('razaoSocial')}</td>
        </tr>
        <tr>
            <td class="text-right">Empresa</td>
            <td>{$entity->getEmpresa('referenciaEmp')}</td>
            <td>{$entity->getEmpresa('razaoSocial')}</td>
            <td><strong>{$quantListaDetFunc}</strong> Funcionários</td>
        </tr>
        <tr>
            <td class="text-right">Endereco</td>
            <td colspan="3">{$entity->getEmpresa('endereco')}</td>
        </tr>
        <tr class="info">
            <td colspan="4">
CABECALHO;

$fh->setHorizontal(TRUE);
$fh->openCol(4);
echo 'Escolha o tipo de Exame';
$fh->closeCol();
$fh->openCol(4)->checkbox('semMedico')->closeCol();
$semMedicoInput = $fh->getLastId();
$fh->openCol(4)->select('tipoExame')->closeCol();
$tipoExame = $fh->getLastId();
$fh->setHorizontal(FALSE);

echo <<<CABECALHO
            </td>
        </tr>
        <tr class="active">
            <td colspan="4">
                <div class="col-md-2">
                    <button id='gerarPdf' class="btn btn-sm btn-primary btn-block"><i class="fa fa-print"></i> Imprimir</button>
                </div>
                <div class="col-md-2 col-md-offset-3">
                    <button id="voltar" class="btn btn-sm btn-primary btn-block"><i class="fa fa-arrow-left"></i> Voltar</button>
                </div>
                <div class="col-md-2 col-md-offset-3">
                    <button id='gerarAso' class="btn btn-sm btn-primary btn-block"><i class="fa fa-file-pdf-o"></i> Gerar ASOs</button>
                </div>
            </td>
        </tr>
    </table>
CABECALHO;

$table->openTable(TRUE);
$table->setEditLine(TRUE);
$lambda = function($value, $data) {
    echo "<td><input class='select-func' value='{$value}' type='checkbox'</td>", PHP_EOL;
};
$table->setLambda($lambda);

$table->renderThead([
    ['label' => "<input title='Selecionar/Remover Todos' id='select-all' type='checkbox'</td>"],
    ['label' => "Cod."],
    ['label' => "Nome do Funcionario"],
    ['label' => "Sexo"],
    ['label' => "RG"],
    ['label' => "CPF"],
    ['label' => "Data Nasc."],
    ['label' => "Admissão"],
    ['label' => "S.T."],
    ['label' => "Função"],
    ['label' => "Setor"],
]);

/* @var $detFunc \Agenda\Entity\RelatorioDetFunc */
foreach ($listaDetFunc as $detFunc) {

    $histoOcupacional = $detFunc->getFuncionario()->getHistOcupacional('atual');
    if ($histoOcupacional->count() == 1) {
        $ocupacaoAtual = $histoOcupacional->get(0)->getOcupacao();
    }

    $table->renderLine([
        $detFunc->getId(),
        $detFunc->getFuncionario('referenciaFun'),
        $detFunc->getFuncionario('nomeFuncionario'),
        $detFunc->getFuncionario('sexo'),
        $detFunc->getFuncionario('rg'),
        $detFunc->getFuncionario('cpf'),
        $detFunc->getFuncionario('dtNascimento'),
        $detFunc->getFuncionario('dtAdmissao'),
        $detFunc->getFuncionario('status'),
        $ocupacaoAtual->getCargo(TRUE),
        $ocupacaoAtual->getSetor(),
    ]);
}
$table->renderCloseTable();

$fh->closeCol()->formEnd();

// Var de transferencia PHP to JS
$transp = array(
    'tipoExame' => $tipoExame,
    'semMedicoInput' => $semMedicoInput
);
?>
<br>
<br>
<script type="text/javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;

        $('#select-all').click(function () {
            if ($(this).is(':checked')) {
                $('.select-func').prop('checked', true);
            } else {
                $('.select-func').prop('checked', false);
            }
        });

        $('#voltar').click(function () {
            $('#godown').click();
        });

        function getLista() {
            var lista = [];

            $('.select-func').each(function () {
                if ($(this).is(':checked')) {
                    lista.push($(this).val());
                }
            });

            return lista;
        }

        $('#gerarAso').click(function () {
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'gerarAsos'), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    lista: JSON.stringify(getLista()),
                }
            });
            return false;
        });
        
        $("#gerarPdf").click(function(){
            $(this).closest('form').processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'getPdfRelDetEmp', 'id' => $entity->getId()), [], FALSE, FALSE); ?>",
                type: "POST"
            });
            return false;
        });

    });
</script>

