<?php
/**
 * 
     * @author Paulo Watakabe <watakabe05@gmail.com>
     * @version 1.0  
     * @since 10-08-2016
 */
/* @var $table      \Application\View\Helper\Table      */
/* @var $fh         \Application\View\Helper\FormHelp   */
/* @var $partial    \Application\View\Helper\PartialObj */
/* @var $form       \Application\Form\FormFilter        */
/* @var $entity     \Agenda\Entity\Relatorio            */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$table      = $this->table();
$form       = $this->form;
$entity     = $this->entity;
$formId     = 'showRelatorio';
$form->setAttribute('id', $formId);
$_POST['formId'] = $formId;
$fh         = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial     = $this->partialObj();

// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();
$fh->openCol(8);
?>
<h3 class=""><?= $this->dataView['titulo']; ?></h3>
<p id="relatoriosIndexMenu">
    <button type="button" class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>    
    <button type="button" class="btn btn-primary" id="btn_add_emp">Adicionar Empresa</button>
</p>
<?php

$fh->closeCol()->lineDown();

$lambda = function ($value, &$data) {   
    echo "\t<td nowrap>",
            '<span class="hand" onClick="show(\'', $value, '\')" title="Abrir Relatorio"><i class="fa fa-pencil"></i> Abrir','</span>', PHP_EOL,
         "</td>", PHP_EOL;   
};

$fh->openCol(12);
    $empresas = $entity->listRelatorioDetEmp('orderAdm');
    $partial->partialObj('agenda');
    $adm = '';
    /* @var $relatorioDetEmp     \Agenda\Entity\RelatorioDetEmp            */
    foreach ($empresas as $relatorioDetEmp) {
        if(empty($adm) OR $adm != $relatorioDetEmp->getEmpresa()->getAdministradora()->getRazaoSocial()){
            $showAdm = $adm = $relatorioDetEmp->getEmpresa()->getAdministradora()->getRazaoSocial();
        }
        $partial->partial('relatorios/partial-show-empresa', $relatorioDetEmp, ['this' => &$this, 'table' => $table, 'showAdm' => $showAdm]);   
        $showAdm = '';
    }
$fh->closeCol()->lineDown()->openCol(12);
    $fh->renderInputText('empresaNome', [], []);
$fh->closeCol()->closeLine();
$fh->formEnd();
// === TRANSPORTE ==============================================================
$fields = [
    'frm'   => $formId
    ,'ret'  => '#inter'
];
// ===================================================================== FIM ===

/* +----------------------------------------------------------------------------
 * | MODAL se parametriza usando a variavel global gModal
 * +----------------------------------------------------------------------------
 *  Estrutura do modal, para Confirmar com o usuario a ação desejada.
 * 
 */
echo $this->partial('partials/modal', array());
?>
<br />

<script lang="javascript">
    var fieldsRelatorios = <?php echo json_encode($fields) ?>;
    
    var atualizaPag = function(){        
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" ,
            frm: fieldsRelatorios.frm
        });
    };
    var show = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'show'), [], FALSE, FALSE); ?>" + "/" + key
        });
    };
    var edit = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key
        });
    };
    var editRelatorioDetEmp = function(key) {
        $('#relatorioDetEmp').val(key);
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'editRelatorioDetEmp'), [], FALSE, FALSE); ?>" + "/" + key
            , type : 'POST'
            , ret : fieldsRelatorios.ret
            , frm : 'showRelatorio'
        });    
    };
    
    var deltRelatorioDetEmp = function(key){
        gModal.reset('confirm',3)
        .setMsg('Deseja mesmo remover esta empresa do relatório ?')
        .setLabelOk('SIM Remover')
        .setClickOk(function(){
            $('#relatorioDetEmp').val(key);
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>" 
                , frm: 'showRelatorio'
                , data : {
                    subOpcao        : "rmEmpresa"
                }
            });
        })
        .showModal(); 
    };
    
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;
        // Esconder menu superior do index
        if('#inter' !== fields.ret){
            $('#relatoriosIndexMenu').hide();
        }
        
        $('.btn-Open').click(function(){
            var key = $(this).attr('id');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'showAnexo'), [], FALSE, FALSE); ?>" + "/" + key
                , ret : fieldsRelatorios.ret
                , type  : 'POST'
                , data  : {
                    ret : fieldsRelatorios.ret
                    ,id : key
                }
            });
        });
        
        $('#btn_add_emp').click(function(){
            gModal.reset('prompt',2)
            .setMsg('Digite o codigo da emresa que deseja incluir neste relatorio')
            .setLabelOk('Incluir')
            .setInputs('<div id="empAutoComp"></div>')
            .setClickOk(function(){
                if($('#empresaNome').val() == ''){
                    gModal.reset('alert',3).setMsg('Nenhuma empresa foi escolhida!!').showModal();
                    return;
                }
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>" 
                    , frm: 'showRelatorio'
                    , data : {
                        subOpcao : "addEmpresa"
                    }
                });
            })
            .setCloseModal(function(){
                $('#empresaNome').closest('.row').hide().appendTo($('#inter'));
            })
            .showModal(); 
            // Inserindo input form na div do modal
            $('#empresaNome').closest('.row').show().appendTo($('#empAutoComp'));
            
        });
        // Escondendo input de pesquisa da tela
        $('#empresaNome').closest('.row').hide();
        
        
        /* AUTOCOMPLETE: Empresa */
        $('#empresaNome').auto({
            primary: "razaoSocial",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'empresas', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            width: 1000,
            responseTo: {
                "idEmpresa": ['empresa'],
                "razaoSocialEmp": ['empresaNome']
            },
            showCols: ["razaoSocialEmp", "cnpj", "razaoSocialAdm", "fantasiaHold"]
        });
        
    });    
</script>