<?php
/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$flashMessenger = $d['this']->flashMessenger();
$messages = $flashMessenger->getCurrentAllMessages();
$flashMessenger->clearCurrentAllMessages();
?>
<script type="text/javascript">
    $(function () {
        /**===================================================
         * FLASH MESSENGER
         * Exibe as mensagens na tela do usuário
         */
        var messages = <?php echo json_encode($messages) ?>;
        $.flashMessenger(messages);
    });
</script>
