<?php 
/* @var $entity \Tcmed\Entity\Epc */
if($this->resultSet){
    switch ($this->subOpcao){
        default:
            $array[] = [
                'menu_id' => "ID Epc",
                "menu_epc" => "Epc",
                "menu_status" => "Status",
                "menu_descricao" => "Descricao",
            ];
            
            foreach ($this->resultSet as $entity){
                $array[] = [
                    "id" => $entity->getId(),
                    "epc" => $entity->getEpc(),
                    "status" => $entity->getStatus(),
                    "descricao" => $entity->getDescricao(),
                ];
            }
            
            break;
    }
    
    echo json_encode($array);
}else{
    echo '{}';
}
