<?php
/** ===========================================================================|
 * FORM - SET_ENTITY
 * @author SET_AUTHOR
 * @since SET_SINCE
 *
 * IncludeView - v1
 */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;
$partial    = $this->partialObj('tcmed');
$form->setAttribute('id', 'formEpcOcupacao');

echo '<br />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

$idEpc = $fh->getIdFor('id');
$epc   = $fh->getIdFor('epc');

$fh->setHorizontal(TRUE);
$fh->openCol(12)->text('epc', [
    'dt-clear' => $idEpc,
    "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
])->closeCol();
$fh->setHorizontal(FALSE);

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = compact('epc', 'idEpc');
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        $$(transp.epc).auto({
            primary: "epc",
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'Epcs', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            responseTo: {
                "id": [transp.idEpc],
            },
            showCols: ["epc"]
        });
    });

</script>
