<h3><?php echo $this->dataView['titulo']; 
$controller = 'consultas';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$fh->setHorizontal(true);
$fh->formInit('Cadastro Consultas:');
    $fh->openCol('12')->renderInputCalend('dtConsulta')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('resultado')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('normal')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('ocupacional')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->renderInputCalend('dtAcompanhamento')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->renderInputCalend('dtRetorno')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->renderInputCalend('validade')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('observacaoCid')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('observacaoRetorno')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('observacaoFinal')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->checkbox('catAberto')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->checkbox('abrirCat')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('Medico')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('HistOcupacional')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('Administradora')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('Funcionario')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('Empresa')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('Clinica')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
