<?php 
/* @var $fh    \Application\View\Helper\FormHelp */
/* @var $form  \Tcmed\Form\Consulta */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$form->setAttribute('id', 'consulta')
?>
<h4 class=""><?php echo $this->dataView['titulo']; ?></h4>
<?php
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit();
    $fh->openCol('12')->calend('dtConsulta',['labelWidth' => 4])->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('tipo'      ,['labelWidth' => 4])->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('medico'    ,['labelWidth' => 4])->closeCol();
$fh->closeLine()->formEnd();


