<?
/**
 * layout com o CSS do pdf do prontuario
 * @author Paulo Watakabe <watakabe05@gmail.com>
 * @version 1.0  
 * @since 19-05-2016 
 */
?><html>
    <head>
    </head>
  <body>
<STYLE>
body {
	margin       : 0px;
	padding      : 0px;	
}
.folha{
        width        : 210mm;
	height       : 295mm;
	border       : #000 solid 0px;
	margin       : 0px;
	padding      : 0px; 
        font-size    : 8pt ;
}
.topot1{
	font-size     : 14pt ;
	font-weight   : bold; 
	text-align    : center ;
}
table{
        font-size    : 8pt ;
}
.small-f{
        font-size    : 7pt ;
}
.bold-t{
	font-weight   : bold; 
}
.quest, .antecedente, .historico, .medicoes{	
        width        : 89mm;
	border       : #000 solid 1px;
	margin       : 0px;
	padding      : 0px;
        float        : left;
	position     : relative;
	border-radius: 1em;
        margin-bottom : 1px;
}
.antecedente{
        width        : 79mm;
	height       : 41mm;
}
.historico{
        width        : 49mm;
	height       : 41mm;
}
.medicoes{
        width        : 49mm;
	height       : 41mm;
}
.topo{
	border        : #000 solid 1px;
	border-radius : 1em;
        margin-bottom : 1px;
}
.topologo{
	float:left;	
	margin-top        : 5px;
	margin-left       : 10px;
}


.clean .interrogatorio{
	margin       : 0px;
	padding      : 0px;
	border       : #000 solid 0px;
}

.interrogatorio, .identificacao{
	width         : 100%; 
}
.sublinha{
	border-bottom : #000 solid 1px;	 
}
.identificacao{
}

.bordaRadius{
	border        : #000 solid 1px;
	border-radius : 1em; 
        margin-bottom : 1px;   
}

.pergLabel{
	position: fixed;
        overflow: auto;
        width        : 30mm;    
	border        : #000 solid 1px;
}

.metade{
	float        : left;  
        width        : 89mm;    
}

.ajustaText{
        padding-left: 2px;
}

.metadeFolha{
	height       : 130mm;
        padding      : 5px;
        font-size    : 10pt ;
}

.reciCont{
	height       : 60mm;
}

.assinatura{
        text-align   : right;
}
.divisao{
	height       : 10mm;
	border       : 0px;
	margin       : 0px;
	padding      : 0px;	
}
.tracejado{
	height       : 6mm;
	border-bottom: #000 dashed 1px;
}
</STYLE>  


<? 
/**
 * @todo Para exibir a data em portugues o servidor devera ter instaldo o locale do pt_br exemplo para instalacao ubuntu sudo locale-gen pt_BR.utf8 para listar use sudo locale -a
 */

setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');

    // Exibe um ou mais prontuarios dependendo da qtd de ids passados
    /* @var $em    \Doctrine\ORM\EntityManager */
    /* @var $param \Application\View\Helper\Param */
    /* @var $rp    \Tcmed\Entity\Repository\ConsultaRepository */
    /* @var $rpCat \Tcmed\Entity\Repository\CatRepository */
    /* @var $consulta \Tcmed\Entity\Consulta */
    $rp    = $em->getRepository('\Tcmed\Entity\Consulta');
    $rpCat = $em->getRepository('\Tcmed\Entity\Cat');
    $subOpcao = isset($post['subOpcao']) ? $post['subOpcao'] : '';
    $nome = '';
    $hoje = strftime('%A, %d de %B de %Y', strtotime('today'));
    $time =  date("H:i");
    foreach ($ids as $id) {
        $consulta = $rp->find($id);
        if(empty($nome)){
            $nome = $consulta->getFuncionario()->getNomeFuncionario();
            $last = $consulta;
        }
        if($subOpcao == 'comRecibo' AND $nome != $consulta->getFuncionario()->getNomeFuncionario()){
            $atual = $consulta;
            $consulta = $last;
            include $this->partial('gerar-pdf-recibo-folha'); 
            $consulta = $last = $atual;
            $nome = $consulta->getFuncionario()->getNomeFuncionario();
        }    
        
        include $this->partial('gerar-pdf-prontuario-folha'); 
    }
    if($subOpcao == 'comRecibo'){
        $consulta = $last;
        include $this->partial('gerar-pdf-recibo-folha'); 
    }    
    
?>  
  </body>
</html>