<?php
/**
 * layout do recibo do prontuario
 * Recibo dos prontuarios a ser assinado pelo paciente
 * @author Paulo Watakabe <watakabe05@gmail.com>
 * @version 1.0  
 * @since 19-05-2016 
 */

    /* @var $consulta \Tcmed\Entity\Consulta */
    /* @var $matriz   \Tcmed\Entity\Clinica */
    /* @var $contato   \Tcmed\Entity\Contato */

$matriz = $consulta->getClinica()->getMatriz();
$contato = $matriz->listContatos(['principal' => TRUE])[0];

echo <<<END
<div class='folha'>

    <div class="bordaRadius metadeFolha">
        <div>
            <img src="{$logo}" class='topologo'>
            <div class='topot1'>&nbsp;<br>RECIBO DE ENTREGA DE DOCUMENTOS</div>
        </div>
        <p class="ajustaText">
            São Paulo, {$hoje}
        </p>
        <div class="reciCont ajustaText">
            <p class="ajustaText">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Eu, {$consulta->getFuncionario()->getNomeFuncionario()}, declaro ter recebido da empresa 
                {$matriz->getRazaoSocial()}, pessoa jurídica de direito privado, 
                inscrita no CNPJ sob o nº {$matriz->getCnpj()}, os meus prontuários, realizados na clinica 
                {$consulta->getClinica()->getRazaoSocial()}, 
                conforme item 7.4.5.2 da Norma Regulamentadora nº. 7.
            </p>
            <p class="ajustaText">
                Sem mais para o momento.
            </p>
        </div>
        <p class="assinatura">
            ____________________________________________________<br>
            Ass: {$consulta->getFuncionario()->getNomeFuncionario()}
        </p>
        <p>
            {$matriz->getRazaoSocial()}.
            <br><span class="small-f">
            Ambulatório : {$matriz->getEndereco()}
            <br />
            telefone(s) : {$contato->telefone()}
            <br />
            Web Site : {$contato->website()}
            <br />
            E-Mail : {$contato->email()}
            <br />
            Solicitado por {$user['nomeUsuario']} as {$time}hs.
            </span>
        </p>    
    </div>
            
    <div class='divisao'><div class='tracejado'></div></div>   

    <div class="bordaRadius metadeFolha">
        <div>
            <img src="{$logo}" class='topologo'>
            <div class='topot1'>&nbsp;<br>RECIBO DE ENTREGA DE DOCUMENTOS</div>
        </div>
        <p class="ajustaText">
            São Paulo, {$hoje}
        </p>
        <div class="reciCont ajustaText">
            <p class="ajustaText">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Eu, {$consulta->getFuncionario()->getNomeFuncionario()}, declaro ter recebido da empresa 
                {$matriz->getRazaoSocial()}, pessoa jurídica de direito privado, 
                inscrita no CNPJ sob o nº {$matriz->getCnpj()}, os meus prontuários, realizados na clinica 
                {$consulta->getClinica()->getRazaoSocial()}, 
                conforme item 7.4.5.2 da Norma Regulamentadora nº. 7.
            </p>
            <p class="ajustaText">
                Sem mais para o momento.
            </p>
        </div>
        <p class="assinatura">
            ____________________________________________________<br>
            Ass: {$consulta->getFuncionario()->getNomeFuncionario()}
        </p>
        <p>
            {$matriz->getRazaoSocial()}.
            <br><span class="small-f">
            Ambulatório : {$matriz->getEndereco()}
            <br />
            telefone(s) : {$contato->telefone()}
            <br />
            Web Site : {$contato->website()}
            <br />
            E-Mail : {$contato->email()}
            <br />
            Solicitado por {$user['nomeUsuario']} as {$time}hs.
            </span>
        </p>    
    </div>            
            
</div>
            
END;
            