<?php
/* @var $table \Application\View\Helper\Table */
/**
 * +===========================================================================+
 * | VIEW INDEX - v1.5
 * +===========================================================================+
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @version 1.5
 * @since 
 * 
 */
$controller    = $this->dataView['controller'];
$action        = $this->dataView['action'];
$route         = $this->dataView['route'];
$title         = $this->dataView['titulo'];
$dataRequest   = $this->data;
$table         = $this->table();

//Montar tabela para exibição xls.
ob_start();

$headers     = array(
    ['label'   => "Exames"],
    ['label'   => "Funcionário"],
    ['label'   => "Função"],
    ['label'   => "Tipo"],
    ['label'   => "Dt. Exame"],
    ['label'   => "Médico"],
    ['label'   => "ASO"],
);

$totalEmps     = 0; // Contador de Empresas exibidos
$totalSemExame = 0;
$totalGeralFun = 0; // Contador geral de Funcionarios
$totalGeralExm = 0; // Contador geral de Exames 
$dataAtual     = (new \DateTime('now'))->format('d/m/Y');
$imageHold     = '';

foreach ($this->result as $data) {

    /* @var $empresa \Tcmed\Entity\Empresa */
    /* @var $clinica \Tcmed\Entity\Clinica */
    $empresa        = $data['empresa'];
    $clinica        = $data['clinica'];
    $listaConsultas = $data['listaConsulta'];

    $totalEmps++;
    $totalFunc = 0; // Contador de Funcionarios exibidos
    $totalExames = 0; // Contador de Exames exibidos

    $table->openTable(['noScrool' => TRUE, 'default' => ""]);
    $table->setEditLine(FALSE);
    $table->renderThead($headers);
    
    $quant           = count($headers);
    $tdVazio         = "<tr><td colspan={$quant}>Não existem exames para esta empresa no período escolhido</td></tr>";
    $lastFuncionario = null;

    /* @var $consulta \Tcmed\Entity\Consulta */
    /* @var $funcionario \Tcmed\Entity\Funcionario */
    foreach ($listaConsultas as $consulta) {

        /*
         * Vars booleanas para verificar se o funcionario possui consulta e se o
         * usuário deseja exibir estes funcionarios sem consulta
         */
        $isFuncionario = ($consulta instanceof Tcmed\Entity\Funcionario);

        /*
         * Irá exibir os funcionários pendentes apenas se 'examesPendentes'
         * estiver selecionado na view
         */
        if ($isFuncionario AND ! isset($dataRequest['examesPendentes'])) {
            continue;
        }

        /*
         * Se consulta for na verdade um funcionário, então atribuir este Funcionario
         * em $funcionario. Se não, ler o funcionario da consulta
         */
        $funcionario = ($isFuncionario) ? $consulta : $consulta->getFuncionario();

        if ($lastFuncionario !== $funcionario) {
            $totalFunc++;
            $lastFuncionario = $funcionario;
        }

        /*
         * Somente se o funcionário possuir consulta que $totalExames será 
         * incrementado com +1
         */
        !$isFuncionario && $totalExames++;
        $isFuncionario  && $totalSemExame++;

        //                           |     Funcionario sem exames     |         Funcionário com exame     |
        $exameDescr = $isFuncionario ? "Exame Vencido"                : "Exame Clínico";
        $dtConsulta = $isFuncionario ? $funcionario->getUltimoExame() : $consulta->getDtConsulta();
        $tipo       = $isFuncionario ? ""                             : $consulta->getTipo();
        $medico     = $isFuncionario ? ""                             : $consulta->getMedico('nomeMedico');
        $resultado  = $isFuncionario ? ""                             : $this->Param($consulta->getResultado()  ,'FC_Resultado');

        $table->renderLine([
            $exameDescr,
            $funcionario->getNomeFuncionario(),
            $funcionario->getOcupacao('cargo', [TRUE])->getCargo(),
            $tipo,
            $dtConsulta,
            $medico,
            $resultado,
        ]);
    }

    if (0 == $totalFunc) {
        echo $tdVazio;
    }
    
    $table->renderCloseTable();
    
    echo <<<TOPO
        <br>
        <table class='table table-striped table-bordered'>
            <thead>
                <tr>
                    <th colspan='2'>Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan='2'>Total de Funcionários</td>
                    <td style='text-align: left'>{$totalFunc}</td>
                </tr>
                <tr>
                    <td colspan='2'>Total de Exames</td>
                    <td style='text-align: left'>{$totalExames}</td>
                </tr>
                <tr>
                    <td colspan='2'>Total de Funcionários que não realizaram Exames</td>
                    <td style='text-align: left'>{$totalSemExame}</td>
                </tr>
            </tbody>
        </table>
        <hr>
TOPO;
            
    $totalGeralFun += $totalFunc;
    $totalGeralExm += $totalExames;
}


$table->renderCloseTable();


echo <<<TOPO
        <br>
        <table class='table table-striped table-bordered'>
            <thead>
                <tr>
                    <th colspan='2'>Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan='2'>Total de  Funcionários:</td>
                    <td style='text-align: left'>{$totalGeralFun}</td>
                </tr>
                <tr>
                    <td colspan='2'>Total de Exames:</td>
                    <td style='text-align: left'>{$totalGeralExm}</td>
                </tr>
                <tr>
                    <td colspan='2'>Total de Condomínios</td>
                    <td style='text-align: left'>{$totalEmps}</td>
                </tr>
            </tbody>
        </table>
        <hr>
TOPO;
                    
$tabela_dados = ob_get_contents();
ob_get_clean();

//Nome do arquivo
$filename = "Relatorio_Controle_" . date('d-m-Y_H-i-s');
//XLS - exibe a tabela pronta em html para XLS
header("Content-Type:  application/vnd.ms-excel; charset=UTF-8; encoding=UTF-8");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Content-Disposition: attachment; filename=\"".$filename.".xls\"" );

print(($tabela_dados));