<?php
/* @var $fh    \Application\View\Helper\FormHelp */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];

/* @var $param \Application\View\Helper\Param */
$param                  = $this->Param();
/* @var $table \Application\View\Helper\Table */
$table      = $this->table();

    $table->openTable(TRUE);
    
    
    $lambda = function($value, $data) {
        echo "\t",'<td nowrap style="font-size: 14pt; marging : 0 ; padding : 0 ;">',
                '<span class="hand" onClick="showProntuario(\'', $value, '\',this)" title="Exibir o prontuario desta consulta"><i class="fa fa-file-text"></i></span>',
                '&nbsp;&nbsp;',
                '<span class="hand" onClick="openFichaClinica(\'', $value, '\',this)" title="Abrir Ficha clinica"><i class="fa fa-paste"></i></span>',
                '&nbsp;&nbsp;',
                '<span class="hand" onClick="showASO(\'', $value, '\')" title="Exibir ASO em PDF na Tela"><i class="fa fa-file-pdf-o"></i></span>',
             "</td>", PHP_EOL;  
    };
    
    $table->setLambda($lambda);

    $table->setTdopt([
        ' class=""'
        ,' class=""'
        ,' class=""'
        ,' class=""'
        ,' class=""'
        ,' class=""'
        ,' class=""'
        ,' class=""'
    ]);
    
    $table->renderThead([
        'Data'
        ,'Empresa'
        ,'Paciente'
        ,'Medico'
        ,'Tipo'
        ,'CID'
        ,'Resul.'
        ,'Ação'
    ]);
    
    $table->setEditLine('last');
    
    /* @var $entity \Tcmed\Entity\Consulta */
    foreach ($this->consultas as $entity) {
        $cids = $entity->listCid();
        $resultado  = $entity->getResultado();
        $cids = is_array($cids) ? ('<ul><li>' . implode('</li><li>', array_map(
            function($cid) {
                return $cid->getNumeroCid();
            }
            , $cids
        )) . '</li></ul>') : $cids;
        $table->renderLine([
            $entity->getDtConsulta()
            ,mb_substr($entity->getEmpresa('razaoSocial'),0 , 20)
            ,$entity->getFuncionario('nomeFuncionario')
            ,mb_substr($entity->getMedico('nomeMedico'),0 , 20)
            ,$entity->getTipo()
            ,$cids
            ,($resultado == '-') ? $resultado : $param($resultado,'FC_Resultado')
            ,$entity->getId()
        ]);
    }
    
    $table->renderCloseTable();
    
    
    ?>

<script lang="javascript">
    
    var showASO = function (idConsulta) {
        var request = {
            url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'showASO'), [], FALSE, FALSE); ?>" + "/" + idConsulta,
            type: "POST",
        };
        $.processa(request);
    };
    
    var openFichaClinica = function (key) {
        var request = {url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(request);
    };
    
    var showProntuario = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'showPdf'), [], FALSE, FALSE); ?>" + "/" + key,
        });
    };
    
</script>