<?
 
/* @var $fh    \Application\View\Helper\FormHelp */
/* @var $table \Application\View\Helper\Table */
/* @var $acl   \Application\View\Helper\Acl */
$param      = $this->Param();
$table      = $this->table();
$acl        = $this->Acl($this->UserIdentity());
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1><? echo $this->dataView['titulo']; ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => $action)); ?>">Limpar</button>
</p>
<?
$fh->getForm()->loadSelectTipo(TRUE);
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(false);

$fh->formInit()->openCol(12); // ===============================================
$fh->openLine();

    $fh->setPreFix('consulta');
    
        $fh->openCol(12);
            $partial->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'cpfAllow' => FALSE]);
        $fh->closeLine();
    
$fh->lineDown();
        
        $fh->setPreFix('funcionario');
            $idFuncionario   = $fh->getIdFor('idFuncionario');
            $referenciaFun   = $fh->getIdFor('referenciaFun');
            $nomeFuncionario = $fh->getIdFor('nomeFuncionario');

            $fh->openCol(3)->number('referenciaFun', [
                'dt-clear' => $idFuncionario . "," . $nomeFuncionario
            ])->closeCol();

            $fh->openCol(9)->text('nomeFuncionario', [
                'dt-clear' => $idFuncionario . "," . $referenciaFun,
                "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
            ])->closeCol();

        $fh->removePreFix('funcionario');
            
$fh->lineDown();
        
        $fh->openCol(12)->setHorizontal(true)->renderInputMultiCheckbox('resultado',['labelWidth' => 3])->closeCol()->setHorizontal(false);
        
$fh->lineDown();
        
        $fh->openCol(12)->setHorizontal(true)->renderInputMultiCheckbox('normal',['labelWidth' => 3])->closeCol()->setHorizontal(false);
        
$fh->lineDown();
        
        $fh->openCol(12)->setHorizontal(true)->renderInputCheckbox('catAberto',['position' => 'right'],['label' => 'Exibir se tem CAT ou se Pediu Abertura'])->closeCol()->setHorizontal(false);
        
$fh->lineDown();
        
        $fh->openCol(6)->select('tipo')->closeCol();
    
$fh->lineDown();
    
    $fh->openCol(3)->calend('ini')->closeCol();
    $fh->openCol(3)->calend('fim')->closeCol();
    
    $fh->removePreFix('consulta');
        
$fh->lineDown();
    
    $fh->openCol(12)->submit('submit',0,['value' => 'Pesquisar'])->closeCol();
    
$fh->lineDown();
    
    $fh->openCol(3,9)->text('limitePag',['labelWidth' => 8])->closeCol();
    
$fh->lineDown();
    
    $fh->openCol(12);
    
    // === OPCOES DA TABELA ========================================================
    if ($acl('tcmed:fichaClinicas:*', 'allow')) {
        $lambda = function($value, $data) {
            echo "\t<td nowrap>",
                    '<span class="hand" onClick="showASO(\'', $value, '\')" title="Exibir ASO em PDF na Tela"><i class="fa fa-file-pdf-o"></i></span><br>',
                    '<span class="hand" onClick="openFichaClinica(\'', $value, '\',this)" title="Abrir Ficha clinica"><i class="fa fa-paste"></i></span><br>',
                    '<span class="hand" onClick="showProntuario(\'', $value, '\',this)" title="Exibir o prontuario desta consulta"><i class="fa fa-file-text"></i></span><br>',
                    '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i>',
                 "</td>", PHP_EOL;  
        };
    } else {
        $lambda = function($value, $data) {
            echo "\t<td nowrap>",
                    '<span class="hand" onClick="showASO(\'', $value, '\')" title="Exibir ASO em PDF na Tela"><i class="fa fa-file-pdf-o"></i> </span>',
                    '&nbsp;&nbsp;&nbsp;',
                    '<span class="hand" onClick="showProntuario(\'', $value, '\',this)" title="Exibir o prontuario desta consulta"><i class="fa fa-file-text"></i> </span>',
                    '&nbsp;&nbsp;&nbsp;',
                    '<span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> </span>',
                 "</td>", PHP_EOL;  
        };
    }   
    $table->setLambda($lambda);
    // ===================================================================== FIM ===
    
    $table->openTable(TRUE);
    $table->setEditLine('first');
    $table->setOrderList($this->dataView['orderBy']);
    
    $table->setTdopt([
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px" nowrap',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
        'style="font-size: 10px"',
    ]);
    
    $table->renderThead([
        'Ação',
        ['label' => 'Consulta', 'order' => 'dtConsulta'], 
        ['label' => 'Adm', 'order' => 'a.fantasiaAdm', 'options' => ' title="Administradora"'], 
        'Empresa', 
        'Funcionario',
        'Medico',
        'Clinica', 
        ['label' => 'Res'  , 'order' => 'resultado', 'options' => ' title="Resultado"'], 
        ['label' => 'Normal'     , 'order' => 'normal'], 
        ['label' => 'Ocupacional', 'order' => 'ocupacional'], 
        ['label' => 'Ret'    , 'order' => 'dtRetorno', 'order' => 'resultado', 'options' => ' title="Retorno"'], 
        ['label' => 'Val'   , 'order' => 'validade', 'options' => ' title="Validade"'], 
        ['label' => 'Obs Final', 'options' => ' title="Observacao Final"'], 
        ['label' => 'CAT Aberto' , 'order' => 'catAberto'], 
        ['label' => 'Abrir CAT'  , 'order' => 'abrirCat'], 
        'Ocupação', 
    ]);
    /* @var $entity \Tcmed\Entity\Consulta */
    foreach ($this->data as $entity) {
        $table->renderLine([
            $entity->getId(),
            $entity->getDtConsulta(),
            $entity->getAdministradora(),
            "<span class='hand openEmpresa' data-id='{$entity->getEmpresa('id')}'>{$entity->getEmpresa('razaoSocial')}</span>",
            $entity->getFuncionario(),
            $entity->getMedico(),
            $entity->getClinica(),
            $param($entity->getResultado(),'FC_Resultado'),
            $param($entity->getNormal(),'FC_normal'),
            $param($entity->getOcupacional(),'FC_Ocupacional'),
            $entity->getDtRetorno(),
            $param($entity->getValidade(),'FC_validade'),
            $entity->getObservacaoFinal(),
            $entity->getCatAberto(TRUE),
            $entity->getAbrirCat(TRUE),
            $entity->getHistOcupacional(),
        ]);
    }
    $table->renderCloseTable();
    
    $fh->closeCol();

$fh->closeLine();
$fh->closeCol()->formEnd(); // =================================================
// === TRANSPORTE ==============================================================
$fields = array_merge(
        $partial->fieldsEmpresa, 
        [
            "idFuncionario" => $idFuncionario,
            "nomeFuncionario" => $nomeFuncionario,
            "referenciaFun" => $referenciaFun,
//            "fantasiaClinica" => $fantasiaClinica,
//            "idClinica" => $idClinica,
        ]
    );
// ===================================================================== FIM ===
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    
    var isValid = function() {
        return true;
    };
    
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);        
    }
    var atualiza = function() {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'edit'), [], FALSE, FALSE); ?>",
            frm : true            
        });        
    };
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    
    var showASO = function (idConsulta) {
        var request = {
            url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'showASO'), [], FALSE, FALSE); ?>" + "/" + idConsulta,
            type: "POST",
        };
        $.processa(request);
    };
    
    var openFichaClinica = function (key) {
        var request = {url: "<?php echo $this->url($route, array('controller' => 'fichaClinicas', 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(request);
    };
    
    var showProntuario = function(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'showPdf'), [], FALSE, FALSE); ?>" + "/" + key,
        });
    };
    
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;
        
        $('.openEmpresa').click(function() {
            var id = $(this).data('id');
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => 'empresas', 'action' => 'edit'), [], FALSE, FALSE); ?>/" + id,
            });
        });
        
         /*
         * Autocomp de Funcionario
         */
        $$(fields.nomeFuncionario).auto({
            primary: "nomeFuncionario",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'funcionarios', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            params: {
                subOpcao : 'new'
            },
            filters: function (data) {
                data.rules = {
                    empresa           : $$(fields.idEmpresa).val()
                };
                return data;
            },
            callback: function (data) {
                $.processa({
                    url:  "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>", 
                    type: "POST",
                    data: {
                        loadFunc: data["idFuncionario"] 
                    },
                });
                return false;
            },
            showCols: ["nomeFuncionario", "rg"]
        });
        
    });
</script>
