<?php
/* @var $form Tcmed\Form\Cliente */

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$partial    = $this->partialObj('tcmed');
$form       = $this->form;

echo '<h3>', $title, '</h3>';
?>

<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>"><i class='fa fa-plus'></i> Novo</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>"><i class='fa fa-refresh'></i> Atualiza</button>
</p>


<?php
// $ret        = $form->getValue('ret', '#inter');
// $form->setAttribute('target', $ret);
$table = $this->table();

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
                ), [], FALSE, $this->dataView['ajax']));

$fh->formInit();
$fh->openCol(12);
$table->openTable(TRUE);
$table->setOrderList($this->dataView['orderBy']);
$table->renderThead([
    ['label' => 'Ação'                 ],
    ['label' => 'Nome'                 ],
    ['label' => 'Nome Fantasia'        ],
    ['label' => 'Telefone'             ],
    ['label' => 'Email'                ],
    ['label' => 'CNPJ'                 ],
    ['label' => 'Status'               ],
    ['label' => 'Criado por'           ],
    ['label' => 'Criado em'            ],
    ['label' => 'Alterado por'         ],
    ['label' => 'Alterado em'          ],
    ['label' => 'id'                   ],
]);
/* @var $entity \Tcmed\Entity\Cliente */
foreach ($this->data as $entity) {

    $table->renderLine([
        $entity->getId(),
        $entity->getNome(),
        $entity->getNomeFantasia(),
        $entity->getTel(),
        $entity->getEmail(),
        $entity->getCnpj(),
        $entity->getStatus(),
        $entity->getCreatedBy('nome'),
        $entity->getCreatedAt('full'),
        $entity->getUpdatedBy('nome'),
        $entity->getUpdatedAt('full'),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
$fh->closeCol();
echo $this->partial('partials/modal');
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
</center>


<script lang="javascript">

    $(function () {
        
        
    });
    
    
    function edit(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key,
        });
        
    }
    function del(key) {
        gModal.reset('confirm',2).setMsg('Deseja mesmo excluir este registro?').setClickOk(function(){
            var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
            $.processa(data);
        }).showModal();
    }
    
</script>
