<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table = $this->table();
$controller = 'cargos';
$route = 'tcmed/default';
/* @var $fh \Application\View\Helper\FormHelp
 * 
 */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Cargos</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>

<div class="row">
    <div class="col-md-3">
        <?php $fh->renderInputCheckbox("showInativo", [], ["id" => "show-inativo"]) ?> 
    </div>
    <div class="col-md-6  col-md-offset-3">
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon2">Pesquisar Cargo</span>
            <input id="pesquisar-cargo" type="text" class="form-control" placeholder="Digite parte do nome do cargo" aria-describedby="basic-addon2">
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
        </div>
    </div>
</div>

<?php
$lambda = function ($value, $data) {
    echo '<td nowrap><ul style="list-style-type: none; padding: 0px;">',
    '<li><span class="hand" onClick="edit(\'', $value, '\')" title="Editar"><i class="fa fa-pencil"></i> Editar', '</span></li>';
    
    if("ATIVO" == $data[5]){
        echo '<li><span class="hand" onClick="del(\'', $value, '\')" title="Deletar"><i class="fa fa-trash"></i> Remover</span></li>';
        echo '<li><span class="hand" onClick="newCargoApelido(\'', $value, '\')" title="Cadastrar novo apelido pra este cargo"><i class="fa fa-plus"></i> Inserir Apelido</span></li>';
    }
    
    echo "</td></ul>", PHP_EOL;
};
$table->setLambda($lambda);

$table->openTable(TRUE);
$table->renderThead(['ID', 'Cargo', 'Cbo', 'Descricao Cargo', 'Apelidos', 'Status', 'Ação']);
/* @var $entity \Tcmed\Entity\Cargo */
/* @var $apelido \Tcmed\Entity\CargoApelido */
foreach ($this->data as $entity) {
    /**
     * Monta a lista com todos os apelidos deste cargo
     */
    $apelidos = '<ul style="list-style-type: none; padding: 0px;">';
    foreach ($entity->listarCargoApelido() as $apelido) {
        if ("ATIVO" == $apelido->getStatus()) {
            $iconRemover = '<i class="removerApelido fa fa-times hand" data-id="' . $apelido->getId() . '"></i>';
            $iconEditar = '<i class="editarApelido fa fa-pencil hand" data-id="' . $apelido->getId() . '"></i>';
            $apelidos .= '<li>' . $iconEditar . ' ' . $iconRemover . ' ' . $apelido->getApelido() . '</li>';
        }
    }
    $apelidos .= '</ul">';
    /**
     * Renderiza as linhas da tabela
     */
    $table->renderLine([
        $entity->getId(),
        $entity->getCargo(),
        $entity->getCbo(),
        $entity->getDescricaocargo('descricao'),
        $apelidos,
        $entity->getStatus(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);

    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    /**
     * Cria um novo apelido para o cargo
     * @param {type} key
     * @returns {undefined}
     */
    function newCargoApelido(key) {
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => "cargoApelidos", 'action' => 'new'), [], FALSE, FALSE); ?>" + "/" + key,
        });

    }

    $(function () {

        /**
         *  Traz os dados inativos na tela
         *  @author Danilo Dorotheu
         */
        $("#show-inativo").change(function () {
            var teste = $(this).is(":checked");
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'Cargos', 'action' => 'index'), [], FALSE, FALSE); ?>",
                type: "POST",
                savePage: false,
                data: {
                    "showInativo": ($(this).is(":checked")) ? "1" : "0",
                },
            });
        });
        /**
         * Edita o apelido do cargo 
         */
        $(".editarApelido").click(function () {
            var idApelido = $(this).attr("data-id");
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'cargoApelidos', 'action' => 'edit'), [], FALSE, FALSE); ?>/" + idApelido,
            });
        });
        /**
         * Remove o apelido do cargo 
         */
        $(".removerApelido").click(function () {
            if (confirm("Deseja realmente excluir este apelido?")) {
                var idApelido = $(this).attr("data-id");
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => 'cargoApelidos', 'action' => 'delete'), [], FALSE, FALSE); ?>/" + idApelido,
                });
            }
        });

        $("#pesquisar-cargo").auto({
            primary: "cargo",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'cargos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            type: "POST",
            params: {
                subOpcao: "pesquisarCargos",
            },
            callback: function (data) {
                $.processa({
                    url: "<?php echo $this->url($route, array('controller' => 'cargos', 'action' => 'index'), [], FALSE, FALSE); ?>",
                    type: "POST",
                    data: {
                        idCargo: data.idCargo,
                    }
                });
            },
            showCols: ["cargo"]
        });
    });
</script>