<h3><?php echo $this->dataView['titulo']; 
$controller = 'funcaos';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro de Função');
    $fh->openCol('12')->text('funcao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('cbo')->closeCol();
$fh->closeLine();
    $this->partialObj('tcmed')->partial('descricao-funcaos/partial-form', $fh,['this' => &$this]);
$fh->openLine();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascript">   
    
    function isValid(){
        return true;
    }
    
</script>
