<?php
/* @var $table \Application\View\Helper\Table 
 * @author Paulo Watakabe <email>watakabe05@gmail.com</email>
 * 
 */ 

$table = $this->table();
$controller = 'fichaClinicas';
$route = 'tcmed/default';
?>
<?php
$table->openTable(TRUE);
$table->renderThead([
    'Realizado', 
    'Empresa', 
    'Medico', 
    'T. Consulta', 
    'Diagnosticos', 
    'alterado/normal', 
    'Coclusão', 
    'Ação'
]);
/**@autor Danilo Dorotheu <danilo.dorotheu@live.com> */
$lambda = function ($value,$data){
    echo '<td><a><i class="fa fa-eye"></i> Show dados</a></td>';
};
$table->setLambda($lambda);

$table->setLambda($lambda);
/* @var $entity \Tcmed\Entity\Consulta */
/* @var $cid \Tcmed\Entity\Cid */
foreach ($this->data as $entity) {
    $showCids = '<ul>';
    foreach ($entity->listCid() as $cid) {
        $showCids .= '<li>'.  $cid->getNumeroCid() .  '</li>';
    }
    $showCids .= '</ul>';
    $table->renderLine([
        $entity->getDtConsulta(),
        $entity->getEmpresa()->getRazaoSocial(),
        $entity->getMedico()->getNomeMedico(),
        $entity->getTipo(),
        $showCids,
        $entity->getNormal(),
        $entity->getResultado(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />
<br />
<script lang="javascritp">   
    
    
</script>
