<?php
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$form       = $this->form;
$partial    = $this->partialObj('tcmed');

$form->setAttribute('id', 'formAddRisco');

/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action'     => $action,
), [], FALSE, $this->dataView['ajax']));

$fh->formInit();

$idRisco   = $fh->getIdFor('idRisco');
$nomeRisco = $fh->getIdFor('nomeRisco');

$fh->openCol(12)->text('nomeRisco',[
    "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"],
    "dt-clear" => $idRisco
])->closeCol();

$fh->formEnd(); // =================================================

// Var de transferencia PHP to JS
$transp = compact('nomeRisco', 'idRisco');
?>
<br>
<br>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        console.log(transp);

        $$(transp.nomeRisco).auto({
            primary: "risco",
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'riscos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            filters: function (query) {
                query["subOpcao"] = "";
            },
            responseTo: {
                idRisco: [transp.idRisco]
            },
            showCols: ["risco"]
        });
    });

</script>
