<?php
/** ===========================================================================|
 * FORM - SET_ENTITY
 * @author SET_AUTHOR
 * @since SET_SINCE
 * 
 * IncludeView - v1
 */
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];
$entity = $this->entity;
$form = $this->form;
$partial = $this->partialObj('application');

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

/* +----------------------------------------------------------------------------
 * | SHOW MESSENGER
 * +----------------------------------------------------------------------------
 *  Estrutura de exibição de mensagens do sistema, criadas no server-side para
 * alertar o usuário.
 * 
 */
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

/* +----------------------------------------------------------------------------
 * | CALENDÁRIO HORÁRIO MÉDICO
 * +----------------------------------------------------------------------------
 *  Exibe o calendário médico contendo o horarioMedico, que por sua vez, contem
 * os dias (horarioMedicoDia).
 * 
 */
echo '<div id="show-calendario"></div>';

/* +----------------------------------------------------------------------------
 * | LISTAGEM DE BLOCOS
 * +----------------------------------------------------------------------------
 *  Exibe a listagem de blocos.
 * 
 */
echo '<hr>';
echo '<div id="show-blocos"></div>';

/* +----------------------------------------------------------------------------
 * | DADOS DE TRANSFERÊNCIA
 * +----------------------------------------------------------------------------
 *  Array contendo valores que serão utilizados na camada de javascript. 
 * 
 */
$transp = array(
    
);
?>
<br>
<br>
<script lang="javascript">   
    
    function isValid(){
        return true;
    }
    
    
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        /**
         * Carrega o calendário medico
         */
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>",
            ret: "#show-calendario",
            savePage: false
        });
        
        /**
         * Carrega a listagem de blocos
         */
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => "Blocos", 'action' => 'indexCalendario'), [], FALSE, FALSE); ?>",
            ret: "#show-blocos",
            savePage: false
        });
    });
    
</script>