<h3><?php echo $this->dataView['titulo']; 
$controller = 'enderecos';
$route = 'end/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Enderecos:');
    $fh->openCol('12')->text('enderecoCodigo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('bairroCodigo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('enderecoCep')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('enderecoLogradouro')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('enderecoComplemento')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
