<?php 
/* @var $entity \Tcmed\Entity\Epi */
if($this->resultSet){
    switch ($this->subOpcao){
        default:
            $array[] = [
                'menu_id' => "ID Epi",
                "menu_epi" => "Epi",
                "menu_status" => "Status",
                "menu_descricao" => "Descricao",
            ];
            
            foreach ($this->resultSet as $entity){
                $array[] = [
                    "id" => $entity->getId(),
                    "epi" => $entity->getEpi(),
                    "status" => $entity->getStatus(),
                    "descricao" => $entity->getDescricao(),
                ];
            }
            
            break;
    }
    
    echo json_encode($array);
}else{
    echo '{}';
}
