<?php
$controller = $this->dataView['controller'];
$action = $this->dataView['action'];
$route = $this->dataView['route'];
$title = $this->dataView['titulo'];

$partial = $this->partialObj('application');
/* @var $table \Application\View\Helper\Table */
$table = $this->table();

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

?>
<h3><?php echo $title ?></h3>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route,array('controller'=>$controller,'action'=>'new')); ?>">Novo</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route,array('controller'=>'tableConfigColuns','action'=>'index')); ?>">Colun Config</button>
</p>
<?php

$table->openTable(TRUE);
//$lambda = function($value, $data) {
//    echo '<td>value</td>', PHP_EOL;;
//};
//$table->setLambda($lambda);
$table->renderThead(['id', 'Path','Caption','Ação']);
/* @var $entity \Application\Entity\TableConfig */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getEntityPath(),
        $entity->getCaption(),
        $entity->getId()
    ]);
}
$table->renderCloseTable();

echo '<center>', $this->paginationControl($this->data,'Sliding','partials/paginator'), '</center>';

// Var de transferencia PHP to JS
$transp = array(
    
);
?>

<script type="text/javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;
    });
    
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);

    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>

