<h3><?php echo $this->dataView['titulo']; 
$controller = 'funcaoepcs';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Epc Funcao:');
    $fh->openCol('12')->select('eficaz')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('epc')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('funcao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('risco')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
