<?php

// echo '<pre> ' , var_dump($this->resultado) , '';
// array(11) {
//  ["resultado"]=>
//  string(1) "1"
//  ["resultado_txt"]=>
//  string(22) "sucesso - cep completo"
//  ["uf"]=>
//  string(2) "SP"
//  ["cidade"]=>
//  string(9) "GUARULHOS"
//  ["bairro"]=>
//  string(16) "JARDIM GUARULHOS"
//  ["logradouro"]=>
//  string(19) "RUA ABRAHAM LINCOLN"
//  ["complemento"]=>
//  string(0) ""
//  ["tipo_logradouro"]=>
//  string(3) "RUA"
//  ["cep"]=>
//  string(8) "07090100"
//  ["pais"]=>
//  string(6) "Brasil"
//  ["ajax"]=>
//  string(3) "nao"
// }

echo json_encode($this->resultado);