<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
$entity       = $this->entity;
/* @var $form \Tcmed\Form\Produto */
$form         = $this->form;
$id           = $form->getValue('id', 0);
$partial      = $this->partialObj('application');
$admPartial = $this->partialObj('adm');

echo '<h3>', $title, '</h3><br />';

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
            'controller' => $controller,
            'action' => $action,
            'id' => ($entity) ? $entity->getId() : 0,
                ), [], FALSE, $this->dataView['ajax']));

$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

$fh->formInit();
$fh->openCol(5)->renderInputText('nomeProd')->closeCol();

$fh->openCol(4)->renderInputMoeda('valorProd')->closeCol();

$fh->openCol(3)->renderInputCalend('createdAt')->closeCol();

$fh->lineDown();

$fh->openCol(3)->renderInputSelect('unidadeEntrada')->closeCol();

$fh->openCol(3)->renderInputNumber('compraQtd')->closeCol();

$fh->openCol(3)->renderInputSelect('unidadeSaida')->closeCol();

$fh->openCol(3)->renderInputNumber('saidaQtd')->closeCol();

$fh->lineDown();

echo '<hr />';
echo '<div class="col-md-12"><h3>Estoque</h3></div>';

$fh->lineDown();

$fh->openCol(2)->renderInputNumber('estoqueMinimo')->closeCol();

$fh->openCol(2)->renderInputNumber('estoqueMaximo')->closeCol();

$fh->openCol(2)->renderInputNumber('estoqueAtual')->closeCol();

$fh->openCol(3)->renderInputSelect('setor')->closeCol();

$fh->openCol(3)->renderInputSelect('status')->closeCol();

$fh->lineDown();

$fh->openCol(4,4)->renderInputSubmit('submit')->closeCol();
$fh->closeLine();

$fh->formEnd();

//if($this->getUsuario('usuario') == null){
//    echo "Preencha o usuário.";
//}

echo $this->partial('partials/modal');

?>