<?php
/**
 * RETORNA LISTA DE CONTATOS
 * @category Contato
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 19/02/2016
 */
/* @var $table \Application\View\Helper\Table */
/* @var $entity \Tcmed\Entity\Contato */
$entity = $d["this"]->entity;
$fh = &$obj;
$table = $d["this"]->table();

$controller = $d["controller"];
$route = 'tcmed/default';

$incluirContato = '<button id="incluirContato" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Incluir</button>';

echo <<<EOF
    <legend>Outros Contatos {$incluirContato}</legend>
EOF;
/*
 * LISTA CONTATOS
 */    
    
    $fh->openCol(10, ["id" => "listaContatos", "class" => "hideOn"])->closeCol();

/*-----------------------------------------------------------------------------*/

$lambda = function($value, $data) {
    echo <<<EOF
    <td>
        <span data-id="{$value}" class="hand excuirMeioContato">
            <i class="fa fa-trash"></i> 
        </span> 
    </td>
EOF;
};

$table->setLambda($lambda);

$table->openTable(TRUE);
$table->renderThead([
    '<i class="fa fa-user"></i> Contato',
    '<i class="fa fa-phone"></i> Telefone',
    '<i class="fa fa-mobile"></i> Celular',
    '<i class="fa fa-envelope"></i> Email',
    '<i class="fa fa-minus"></i>'
]);

foreach ($entity->listContatos(["principal" => FALSE]) as $contato) {

    $listaMeioContatos = $contato->listMeioContato();

    if (1 > count($listaMeioContatos)) {
        continue;
    }

    $telefone = $listaMeioContatos[0]->getMeioDeContato();
    $celular = $listaMeioContatos[1]->getMeioDeContato();
    $email = $listaMeioContatos[2]->getMeioDeContato();

    $table->renderLine([
        $contato->getNomeContato(),
        $telefone,
        $celular,
        $email,
        $contato->getId()
    ]);
}

$table->renderCloseTable();
?>
<div id="modal" class="modal fade"  tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Incluir Contato</h3>
            </div>
            <div class="modal-body">
                <form id="data-to-send">
                    <?php
                    ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
                <button id="salvar-modal" data-id="<?php echo $entity->getId(); ?>" type="button" class="btn btn-success">Salvar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<br>
<script type="text/javascript">
    $(function () {
        var idEntity = <?php echo $entity->getId(); ?>;

        /**
         * @event Traz modal com informacoes de peso, altura, 
         * pressao e temperatura 
         */
        $(".addMeioContato").click(function () {
            $.processa({
                url: "<?php echo $d["this"]->url($route, array('controller' => $controller, 'action' => "addNewContato"), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    "idContato": $(this).attr("data-id"),
                    "idEntity": idEntity
                },
                callback: function (data) {
                    $("#modal-add").html(data);
                }
            });
            return false;
        });

        $(".excuirMeioContato").click(function () {
            $.processa({
                url: "<?php echo $d["this"]->url($route, array('controller' => "Contatos", 'action' => "delete"), [], FALSE, FALSE); ?>/" + $(this).attr("data-id"),
                callback: function (data) {
                    $.processa({
                        url: "<?php echo $d["this"]->url($route, array('controller' => $controller, 'action' => 'getContatos'), [], FALSE, FALSE); ?>/" + idEntity,
                        callback: function (data) {
                            $("#listaContatos").html(data);
                        }
                    });
                }
            });
            return false;
        });

        $("#incluirContato").click(function () {
            $("#modal").show();
            
            return false;
        });
        
         /**
         * Checa os dados dos campos telefone, email, celular e contato
         * e os envia ao servidor para persistencia
         */
        $("#salvar-modal").click(function () {
            var $modal = $(this).closest("#modal");
            var telefone = $modal.find("#meioDeContato0").val();
            var celular = $modal.find("#meioDeContato1").val();
            var email = $modal.find("#meioDeContato2").val();

            if ($modal.find("#nomeContato").val() == "") {
                $modal.modal("hide");
                $.notify({
                    message: "Você precisa definir o nome do contato!!",
                    type: "danger"
                });
                return false;
            }

            if ("" == telefone && "" == celular && "" == email) {
                $modal.modal("hide");
                $.notify({
                    message: "Vecê precisa inserir ao menos 1 meio de contato!!",
                    type: "danger"
                });
                return false;
            }

            $.processa({
                url: "<?php echo $d["this"]->url($route, array('controller' => $controller, 'action' => 'addNewContatoModal'), [], FALSE, FALSE); ?>",
                type: "POST",
                data: {
                    "idEntity": "<?php echo $idEntity ?>",
                    "nomeContato": $modal.find("#nomeContato").val(),
                    "telefone": telefone,
                    "celular": celular,
                    "email": email,
                },
                callback: function (data) {
                    $modal.modal("hide");
                    $(".modal-backdrop").remove();
                    $.processa({
                        url: "<?php echo $d["this"]->url($route, array('controller' => $controller, 'action' => 'getContatos'), [], FALSE, FALSE) . "/" . $idEntity ?>",
                        callback: function (data) {
                            $("#listaContatos").html(data);
                        }
                    });
                }
            });
        });
        
        
    });
</script>
