<?php
/* @var $table  \Application\View\Helper\Table */
/* @var $guia   \Tcmed\Entity\Guia */
/* @var $entity \Tcmed\Entity\GuiaSemCadastro */
$entity = $this->data['entity'];
$guia = $entity->getGuia();
$hr = date(" H "); 
$saudacao = ($hr <= 12)?'Bom dia!':'Boa tarde!';

echo <<<EOF
<p>{$saudacao}!!!</p><p></p>
<p>Tendo em vista a contratação do Programa de Controle Médico de Saúde Ocupacional por parte de V.S.as., 
solicitamos o envio dos dados dos funcionários do condomínio em assunto para cadastro em nosso sistema.
<p>
<p></p>
<p>Dados Necessários:</p>
<p>
- Nome; <span style=color:red>CPF;</span> RG; 
<span style=color:red>PIS;</span>
Carteira Profissional; Data Admissão; Data Nascimento e Função.
</p>
<p>Pode ser enviado ficha de registro ou relação de funcionários ativos no condomínio, desde que esta relação contenha os dados acima.</p>
<p>Salientamos ainda que, caso exista necessidade de transferência dos Prontuários Clínicos Individuais para 
Médico Coordenardo-Sucessor solicitamos autorização para retirada dos mesmos junto a empresa atual, para tanto necessitamos dos dados abaixo:
</p>
<p></p>
<p>Nome da Empresa: {$entity->getNomeEmpresa()}</p>
<p>Cnpj da Empresa: {$entity->getCnpj()}</p>
<p>Ramo de atividade : {$entity->getAtividade()}</p>
<p>Nome do Médico Coordenardor: </p>
<p>Endereço: </p>
<p>Telefone: </p>
<p>Contato: </p>
<p>
Qualquer dúvida é só ligar.
Tel: 11 3226-9626 Fax: 11 3226-9628<br>
No aguardo.<br>
Atenciosamente,<br>
Vila Velha.
</p>

EOF;
