<?php
/* @var $param  \Application\View\Helper\Param */
/* @var $guia   \Tcmed\Entity\Guia */
/* @var $entity \Tcmed\Entity\GuiaSemCadastro */
/* @var $empresa \Tcmed\Entity\Empresa */
$param   = $this->data['param'];
$entity  = $this->data['entity'];
$empresa = $this->data['empresa'];
$guia = $entity->getGuia();
$hr = date(" H "); 
$saudacao = ($hr <= 12)?'Bom dia!':'Boa tarde!';
$exame = $param($guia->getTipo(), 'FC_tipo_exame');
echo <<<EOF
<p>{$saudacao}!!!</p>
<p></p>
    <h1>Alerta!</h1>
<p>
Foi feito para este condominio um pedido de inclusão de PCMSO porém este se encontra ativo em:
</p>
<p>
Nome da Administradora:     {$empresa->getAdministradora()->getFantasiaAdm()}
</p>
<p>
Nome da Empresa:            {$empresa->getFantasiaEmpresa()}
</p>
<p>
Ramo de atividade :         {$empresa->getAtividade()}
</p>
<p>
Cnpj :                      {$empresa->getCnpj()}
</p>

<h2>Foi gerado Guia para condominio sem cadastro:</h2>

<p>
Nome da Administradora:     {$entity->getAdministradora()->getFantasiaAdm()}
</p>
<p>
Nome da Empresa:            {$entity->getNomeEmpresa()}
</p>
<p>
Ramo de atividade :         {$entity->getAtividade()}
</p>
<p>
Cnpj :                      {$entity->getCnpj()}
</p>
<p>
Nome do Funcionario:        {$guia->getNomeFuncionario()}
</p>
<p>
Exame:                      {$exame}
</p>

<p>
Atenciosamente,<br>
Sistema.
</p>
EOF;
