<?php
/* @var $param  \Application\View\Helper\Param */
/* @var $guia   \Tcmed\Entity\Guia */
/* @var $entity \Tcmed\Entity\GuiaSemCadastro */
$param = $this->data['param'];
$entity = $this->data['entity'];
$guia = $entity->getGuia();
$hr = date(" H "); 
$saudacao = ($hr <= 12)?'Bom dia!':'Boa tarde!';
$exame = $param($guia->getTipo(), 'FC_tipo_exame');
/*
 * DATA DO PAGAMENTO DO CONTRATO EXEMPLO
 * 26/04 A 25/05 VENCIMENTO 15/06 
 */
echo <<<EOF
<p>{$saudacao}!!!</p>
<h2>Alerta !!!</h2>           
<p>Foi gerado no sistema uma guia de encaminhamento Avulsa.</p>
<p>
Nome da Administradora:     {$entity->getAdministradora()->getFantasiaAdm()}
</p>
<p>
Nome da Empresa:            {$entity->getNomeEmpresa()}
</p>
<p>
Ramo de atividade :         {$entity->getAtividade()}
</p>
<p>
Cnpj :                      {$entity->getCnpj()}
</p>
<p>
Nome do Funcionario:        {$guia->getNomeFuncionario()}
</p>
<p>
Exame:                      {$exame}
</p>
<p>
Data:                       {$entity->getCreatedAt()}
</p>

<p>
Atenciosamente,<br>
Vila Velha.
</p>
EOF;
