<?php
/* @var $table \Application\View\Helper\Table */
/*@var $guia \Tcmed\Entity\Guia*/
$entity = $this->data["entity"];
$guia = $entity->getGuia();

$user = $this->data["user"];
$tipo = $this->param($guia->getTipo(), "FC_tipo_exame");
$nameMatriz = strtoupper($this->param("matriz", "matriz_guia"));
$date = date('d/m/Y - H:i');

echo <<<EOF
<i><b>{$nameMatriz}</b></i>

<br><br>

Segue em anexo, a guia de encaminhamento referente ao funcionário <b>{$guia->getNomeFuncionario()}</b>, portador
do <b>RG {$guia->getRg()}</b> e <b>CPF {$guia->getCpf()}

<br><br><br>

<b>Codigo de Autenticidade: <i>{$guia->getId()}</i></b>
<br>
<b>Tipo de Exame: <i>{$tipo}</i></b>
<br>
<b>Clinica: <i>{$guia->getClinica()->getFantasiaClinica()}</i></b>
<br>
<b>Usuario: <i>{$user}</i></b>
<br>
<b>Data: {$date}</b>

EOF;
