<?php
/* @var $guiaSemCadastro \Tcmed\Entity\GuiaSemCadastro */
/* @var $guia \Tcmed\Entity\Guia */
/* @var $empresa \Tcmed\Entity\Empresa */
/* @var $administradora \Tcmed\Entity\Administradora */
/* @var $funcionario \Tcmed\Entity\Funcionario */
/* @var $contato \Tcmed\Entity\Contato */
/* @var $contato \Tcmed\Entity\Clinica */
$guiaSemCadastro = $entity;
$guia            = $guiaSemCadastro->getGuia();
$clinica         = $guia->getClinica();
$enderecoClinica = $clinica->getEndereco();

$ocupacao        = $guia->getOcupacao();
$administradora  = $guiaSemCadastro->getAdministradora();

$telefone        = $guiaSemCadastro->getTelefone();
$celular         = $guiaSemCadastro->getCelular();
$email           = $guiaSemCadastro->getEmail();


$path = $clinica->getPathLogo();
if(file_exists($path)){
    $img = '<img id="imagemLogo" src="' . $path . '">';
}else{
    $img = '';
}


$vencimento = $guia->getCreatedAt(TRUE)->add(new \DateInterval("P30D"))->format("d/m/Y");
$tipoGuia = ucfirst($params($guia->getTipo(), "FC_tipo_exame"));

// S -> Site
!$labelGuia && $labelGuia = 'S'; 

$border = "border-bottom: 1px solid #666;";
$centerAlign = "text-align: center;";
$rightAlign  = "text-align: right;";

/**
 * =====================================================================
 * Renderiza a imagem da Guia
 */

/* @var $param \Application\View\Helper\Image  */
$path = $params('path','guia_logo');

//$path = $params('all','clinicaDir') . $guia->getClinica('pathLogo');
$img  = file_exists($path) ? "<img id='imagemLogo' style='max-width: 200px; margin-left: 20px;' src='{$path}'>": "";

/* @refEmpresa = é uma variavel que renderiza uma td com uma lógica
 * Caso não existir uma Referencia da empresa, renderiza sem parenteses
 * Caso exista uma referencia da empresa, renderiza com parenteses  
 */
$refEmpresa = empty($guiaSemCadastro->getReferenciaEmp()) ?
        "<td style='{$border}' colspan='3'> {$guiaSemCadastro->getNomeEmpresa()}</td>" 
        : "<td style='{$border}' colspan='3'>({$guiaSemCadastro->getReferenciaEmp()}) {$guiaSemCadastro->getNomeEmpresa()}</td>" ;

/* @var $cnpjOrCpfNumber troca os numeros de cnpj para cpf caso esteja vazio */
$cnpjOrCpfNumber = $guiaSemCadastro->getCnpj() != "00.000.000/0000-00"?
        "<td style='{$border}'>{$guiaSemCadastro->getCnpj()}</td>":"<td style='{$border}'>{$guiaSemCadastro->getCpf()}</td>";
/* @var $cnpjOrCpfLabel Troca a label de Cnpj para cpf de acordo com o número */
$cnpjOrCpfLabel  = $guiaSemCadastro->getCnpj() != "00.000.000/0000-00"?
        "<td style='{$border}'><strong>CNPJ:</strong></td>":"<td style='{$border}'><strong>CPF:</strong></td>";
/* ================================================================== */

echo <<<DATA
    <div style='border: 2px solid #111;border-radius: 10px'>
        <table>
            <tr>
                <td style='{$border}'>
                    {$img}
                </td>
                <td style='{$border} {$centerAlign}' colspan='3'>
                    <h2 style='font-size: 18px'>Assessoria e Serviços Técnicos em Medicina S/C</h2>
                    <p>Guia de Encaminhamento</p>
                </td>
            </tr>
            <tr>
                <td>Cod. Autenticidade:</td>
                <td><strong>{$labelGuia}{$guiaSemCadastro->getId()}</strong></td>
                <td>Validade: </td>
                <td><strong>{$vencimento}</strong></td>
            </tr>
            <tr>
                <td style='{$border}'>Tipo de Exame:</td>
                <td style='{$border}' colspan='3'><strong>{$tipoGuia}</strong></td>
            </tr>
                </table>
                <table>
            <tr>
                <td style='{$border}'><strong>Administradora:</strong></td>
                <td style='{$border}' colspan='3'>({$administradora->getReferenciaSubhold()}) {$administradora->getRazaoSocial()}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Empresa:</strong></td>
                {$refEmpresa}
            </tr>
            <tr>
                <td><strong>E-mail:</strong></td>
                <td>{$email}</td>
                <td><strong>Tel:</strong></td>
                <td>{$telefone}</td>
            </tr>
            <tr>
                $cnpjOrCpfLabel
                $cnpjOrCpfNumber
                <td style='{$border}'><strong>CEP:</strong></td>
                <td style='{$border}'>{$guiaSemCadastro->getEndereco()->getLogradouro('cep')}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Funcionário:</strong></td>
                <td style='{$border}' colspan='3'>{$guia->getNomeFuncionario()}</td>
            </tr>
            <tr>
                <td><strong>Setor:</strong></td>
                <td colspan='3'>{$ocupacao->getSetor()}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Cargo:</strong></td>
                <td style='{$border}'>{$ocupacao->getCargo()->getCargo()}</td>
                <td style='{$border}'><strong>CBO:</strong></td>
                <td style='{$border}'>{$ocupacao->getCargo('cbo')}</td>
            </tr>
            <tr>
                <td><strong>RG:</strong></td>
                <td>{$guia->getRg()}</td>
                <td><strong>CPF:</strong></td>
                <td>{$guia->getCpf()}</td>
            </tr>
            <tr>
                <td><strong>PIS:</strong></td>
                <td>{$guia->getPis()}</td>
                <td><strong>Nasc:</strong></td>
                <td>{$guia->getDtNascimento()}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Carteira Trab:</strong></td>
                <td style='{$border}' colspan='1'>{$guia->getCarteiraProfissional()}</td>
                <td style='{$border}'><strong>Matrícula:</strong></td>
                <td style='{$border}' colspan='2'>{$guia->getMatricula()}</td>
            </tr>
            <tr>
                <td style='{$border}' colspan='4'>
                    Apresentar RG, CPF e PIS - Data ____/____/______ as ____:____ horas.
                    <br>Pronto atendimento: CLÍNICA {$clinica}
                    <br>{$guia->getClinica('infoAtendimento')}
                    <br>Local do atendimento: {$enderecoClinica}
                </td>
            </tr>
            <tr>
                <td colspan='4'>
                    <barcode code="{$guiaSemCadastro->getId()}" type="C128A" size="1.5" height="0.4" text="{$guiaSemCadastro->getId()}"/>
                </td>
            </tr>
        </table>
    </div>
DATA;
