<?php
$emailTcmed = $this->param("emailTcmed", "emails_default");
$emailVilaVelha = $this->param("emailVilaVelha", "emails_default");

/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();
?>

<h3>Guia</h3>
<hr>
<div id="email">
    <div class="col-md-12">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <form>
                        <div class="input-group">
                            <input type="text" id="fieldEmail" name="fieldEmail" class="form-control" placeholder="fulano@dominio.com; ciclano@dominio.com">
                            <span class="input-group-btn">
                                <button id="send-email" class="btn btn-success" type="button">
                                    Enviar <i class="fa fa-paper-plane-o"></i>
                                </button>
                            </span>
                        </div><!-- /input-group -->
                    </form>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-4">
                        <button id="email-tcmed" class="btn btn-primary btn-block">Enviar p/ Tecnomed</button>
                    </div>
                    <div class="col-md-4">
                        <button id="email-vilavelha" class="btn btn-primary btn-block">Enviar p/ Vila Velha</button>
                    </div>
                    <div class="col-md-4">
                        <button id="email-tcmedvv" class="btn btn-primary btn-block">Enviar p/ os dois</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <em class="text-center text-success"><mark>DICA: </mark>Para enviar para vários endereços de email, digite os endereços separados por ponto e vírgula (;). Exemplo: fulano@hotmail.com; ciclano@gmail.com ...</em>		
        </div>
    </div>
    <hr>
    <div class="col-md-12">
        <br>
        <br>
    </div>
    <br>
    <br>

    <iframe id="iframeAso" width='100%' height='500' frameborder='0' src='<?php echo $this->url('tcmed/default', $this->route, [], FALSE, FALSE); ?>'></iframe>
    <script lang="javascript">
        $(function () {
            /**
             * Alterar a altura para visualização do aso
             */
            $('#iframeAso').height($(document).height() * 0.89);

            /**
             * Envia requisicao para o servidor
             * 
             * @function sendEmail
             * @param {type} fieldEmail
             * @returns {undefined}
             */
            function sendEmail(fieldEmail) {
                $.processa({
                    url: "<?php echo $this->url('tcmed/default', array('controller' => 'guiaSemCadastros', 'action' => 'email'), [], FALSE, FALSE); ?>",
                    type: "POST",
                    data: {
                        fieldEmail: fieldEmail,
                        idGuia: <?php echo $this->entity->getId(); ?>,
                    }
                });
            }

            $("#email-vilavelha").click(function () {
                sendEmail("<?php echo $emailVilaVelha ?>");
            });
            $("#email-tcmed").click(function () {
                sendEmail("<?php echo $emailTcmed ?>");
            });
            $("#email-tcmedvv").click(function () {
                sendEmail("<?php echo $emailVilaVelha . ";" . $emailTcmed ?>");
            });
            $("#send-email").click(function () {
                var fieldEmail = $("#fieldEmail").val();
                if ("" == fieldEmail) {
                    return false;
                }

                sendEmail(fieldEmail);
            });

            //== MENSAGENS DO SISTEMA ==============================================
            /**
             * @see (PHP) flashMessenger
             * @property {object} messagesGroup Necessário para exibir mensagens 
             * na tela
             */
            var messagesGroup = <?php echo json_encode($messages) ?>;
            /**
             * @event Exibe as mensagens do servidor na view
             */
            $.each(messagesGroup, function (type, messages) {
                $.each(messages, function (_, message) {
                    $.notify({
                        "message": message,
                        "type": type
                    });
                });
            });
            // ========================================================== FIM ======
        });
    </script>