<?php 
/* @var $guia \Tcmed\Entity\Guia */
$guia = $entity;

$vencimento = $guia->getCreatedAt(TRUE)->add(new \DateInterval("P30D"))->format("d/m/Y");
$tipoGuia = ucfirst($params($guia->getTipo(), "FC_tipo_exame"));

// S -> Site
!$labelGuia && $labelGuia = 'S'; 

$border = "border-bottom: 1px solid #666;";
$centerAlign = "text-align: center;";
$rightAlign  = "text-align: right;";

/**
 * =====================================================================
 * Renderiza o HTML de NewOcupacao
 */
$newOcupacao = "";
if ($guia->getNewOcupacao()) {
    $newOcupacao = <<<NEWOCUPACAO
        <tr>
            <td><strong>Novo setor:</strong></td>
            <td colspan='3'>{$guia->getNewOcupacao('setor', ['nomeSetor'])}</td>
        </tr>
        <tr>
            <td style='{$border}'><strong>Novo cargo:</strong></td>
            <td style='{$border}'>{$guia->getNewOcupacao('cargo', [TRUE])}</td>
            <td style='{$border}'><strong>CBO:</strong></td>
            <td style='{$border}'>{$guia->getNewOcupacao('cargo', [FALSE, 'cbo'])}</td>
        </tr>
NEWOCUPACAO;
}
/* ================================================================== */

/**
 * =====================================================================
 * Renderiza a imagem da Guia
 */

/* @var $param \Application\View\Helper\Image  */
$path = $params('path','guia_logo');

//$path = $params('all','clinicaDir') . $guia->getClinica('pathLogo');
$img  = file_exists($path) ? "<img id='imagemLogo' style='max-width: 200px; margin-left: 20px;' src='{$path}'>": ""; 
/* ================================================================== */

/* @var $cnpjOrCpfNumber troca os numeros de cnpj para cpf caso esteja vazio */
$cnpjOrCpfNumber = $guia->getEmpresa('cnpj') != "00.000.000/0000-00"?
        "<td style='{$border}'>{$guia->getEmpresa('cnpj')}</td>":"<td style='{$border}'>{$guia->getEmpresa('cpf')}</td>";
/* @var $cnpjOrCpfLabel Troca a label de Cnpj para cpf de acordo com o número */
$cnpjOrCpfLabel  = $guia->getEmpresa('cnpj') != "00.000.000/0000-00"?
        "<td style='{$border}'><strong>CNPJ:</strong></td>":"<td style='{$border}'><strong>CPF:</strong></td>";
        
echo <<<DATA
    <div style='border: 2px solid #111;border-radius: 10px'>
        <table>
            <tr>
                <td style='{$border}'>
                    {$img}
                </td>
                <td style='{$border} {$centerAlign}' colspan='3'>
                    <h2 style='font-size: 18px'>Assessoria e Serviços Técnicos em Medicina S/C</h2>
                    <p>Guia de Encaminhamento</p>
                </td>
            </tr>
            <tr>
                <td>Cod. Autenticidade:</td>
                <td><strong>{$labelGuia}{$guia->getId()}</strong></td>
                <td>Validade: </td>
                <td><strong>{$vencimento}</strong></td>
            </tr>
            <tr>
                <td style='{$border}'>Tipo de Exame:</td>
                <td style='{$border}' colspan='3'><strong>{$tipoGuia}</strong></td>
            </tr>
                </table>
                <table>
            <tr>
                <td style='{$border}'><strong>Administradora:</strong></td>
                <td style='{$border}' colspan='3'>({$guia->getEmpresa('administradora', ['referenciaSubhold'])}) {$guia->getEmpresa('administradora', ['razaoSocial'])}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Empresa:</strong></td>
                <td style='{$border}' colspan='3'>({$guia->getEmpresa('referenciaEmp')}) {$guia->getEmpresa('razaoSocial')}</td>
            </tr>
            <tr>
                <td><strong>E-mail:</strong></td>
                <td>{$guia->getEmpresa('contatoPrincipal', ['meioDeContatoPrincipal', ['email']])}</td>
                <td><strong>Tel:</strong></td>
                <td>{$guia->getEmpresa('contatoPrincipal', ['meioDeContatoPrincipal', ['telefone']])}</td>
            </tr>
            <tr>
                $cnpjOrCpfLabel
                $cnpjOrCpfNumber
                <td style='{$border}'><strong>CEP:</strong></td>
                <td style='{$border}'>{$guia->getEmpresa('endereco', ['logradouro', ['cep']])}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Funcionário:</strong></td>
                <td style='{$border}' colspan='3'>{$guia->getNomeFuncionario()}</td>
            </tr>
            <tr>
                <td><strong>Setor:</strong></td>
                <td colspan='3'>{$guia->getOcupacao('setor', ['nomeSetor'])}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Cargo:</strong></td>
                <td style='{$border}'>{$guia->getOcupacao('cargo', [TRUE])}</td>
                <td style='{$border}'><strong>CBO:</strong></td>
                <td style='{$border}'>{$guia->getOcupacao()->getCargo('cbo')}</td>
            </tr>
                
            {$newOcupacao}
                
            <tr>
                <td><strong>RG:</strong></td>
                <td>{$guia->getRg()}</td>
                <td><strong>CPF:</strong></td>
                <td>{$guia->getCpf()}</td>
            </tr>
            <tr>
                <td><strong>PIS:</strong></td>
                <td>{$guia->getPis()}</td>
                <td><strong>Nasc:</strong></td>
                <td>{$guia->getDtNascimento()}</td>
            </tr>
            <tr>
                <td style='{$border}'><strong>Carteira Trab:</strong></td>
                <td style='{$border}' colspan='1'>{$guia->getCarteiraProfissional()}</td>
                <td style='{$border}'><strong>Matrícula:</strong></td>
                <td style='{$border}' colspan='2'>{$guia->getMatricula()}</td>
            </tr>
            <tr>
                <td style='{$border}' colspan='4'>
                    Apresentar RG, CPF e PIS - Data ____/____/______ as ____:____ horas.
                    <br>Pronto atendimento: CLÍNICA {$guia->getClinica('fantasiaClinica')}
                    <br>{$guia->getClinica('infoAtendimento')}
                    <br>Local do atendimento: {$guia->getClinica('endereco')}
                </td>
            </tr>
            <tr>
                <td colspan='4'>
                    <barcode code="{$guia->getId()}" type="C128A" size="1.5" height="0.4" text="{$guia->getId()}"/>
                </td>
            </tr>
        </table>
    </div>
DATA;
