<?php
/* @var $table \Application\View\Helper\Table */
/* @var $fh    \Application\View\Helper\FormHelp */
/* @var $partial    \Application\View\Helper\PartialObj */
/* @var $form       \Tcmed\Form\PpraMedicao */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$formId     = 'showListPpraMedicao';
$ret        = $form->get('ret')->getValue();

$form->setAttribute('id', $formId);
$form->setAttribute('target', $ret);
$table   = $this->table();
$fh      = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj();

// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

if($ret == '#inter'){
    $fh->formInit();
    $_POST['formId'] = $formId;
}else{
    $form->remove('ret');
    $fh->renderFieldsetIni()->renderAllHidden();
    $formId = true;
}

$fh->openCol(8);
?>
<div id="ppraMedicaoIndexMenu">
<h3 class=""><?php echo $this->dataView['titulo']; ?></h3>
<p>    
    <button type="button" class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index')); ?>">Atualizar</button>
</p>
<br />
</div>
<?php
$fh->closeCol()->openCol(4)->select('limitePag',['labelWidth' => 6,'clean' => FALSE,'extra' => ['icon' => 'search', 'js' => "atualizaPag()"]]);
$fh->closeCol()->lineDown();
$fh->openCol(12);


    $lambda = function($value, $data) {
        echo "\t", '<td nowrap style="font-size: 14pt;">',
                '<span class="hand" onClick="del(\'', $value, '\',this)" title="Excluir"><i class="fa fa-trash"></i></span>',
             "</td>", PHP_EOL;   
    };
    $table->setLambda($lambda);
    $table->openTable(TRUE);
    $table->setEditLine('first');
    $table->setOrderList($this->dataView['orderBy']);
    $table->setTdopt([
        ''
        ,'class="inputVlr" data-col="seq"'
        ,''
        ,''
        ,'class="inputVlr alr" data-col="qtdFunc"'
        ,'class="alr"'
        ,''
        ,'class="alr"'
        ,''
        ,''
    ]);
    $table->renderThead([
        'Ação'
        ,['label' => 'Seq.'              , 'order' => 'seq'            ]
        ,['label' => 'Local'             , 'order' => 'pl.nome'        ]
        ,['label' => 'Detalhe Local'     , 'order' => 'pld.nome'       ]
        ,['label' => 'Qtd. Vidas'        ]
        ,['label' => 'criado em'         , 'order' => 'createdAt'      ]
        ,['label' => 'Criado por:'       , 'order' => 'createdBy'      ]
        ,['label' => 'Alterado em'       , 'order' => 'updatedAt'      ]
        ,['label' => 'Alterado por:'     , 'order' => 'updatedBy'      ]
        ,['label' => 'Status'            , 'order' => 'status'         ]
    ]);
    /* @var $entity \Tcmed\Entity\PpraMedicao */
    foreach ($this->data as $entity) {
        $table->renderLine([
            $entity->getId(),
            $entity->getSeq(),
            $entity->getPpraLocal('nome'),
            $entity->getPpraLocalDet('nome'),
            $entity->getQtdFunc(),
            $entity->getCreatedAt('full'),
            $entity->getCreatedBy('nomeUsuario'),
            $entity->getUpdatedAt(),
            $entity->getUpdatedBy('nomeUsuario'),
            $entity->getStatus(),
        ]
        , 'data-id="' . $entity->getId() . '"'        
        );
    }
    $table->renderCloseTable();
    
$fh->closeCol()->lineDown();

$fh->openCol('12')->renderInputMoeda('valor',['noLabel' => true,'extra' => ['icon' => 'save', 'js' => "saveValorResposta()"]],['id' => 'valorResposta'])->closeCol(); // oculto 

$fh->closeLine();

if($ret == '#inter'){
    $fh->formEnd();
}
// === TRANSPORTE ==============================================================
$fields = [
    'ret'   => $ret
    , 'frm' => $formId
];
// ===================================================================== FIM ===
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    var fieldsPpraMedicaos = <?php echo json_encode($fields) ?>;
        
    var del = function(key,obj) {
        var msg = "Deseja mesmo excluir este registro?";
        gModal.reset('confirm',2).setMsg(msg).setClickOk(function(){
            var $form = $(obj).closest('form');
            var $ret   = $form.find('input[id="ret"]');
            var retOld = $ret.val();
            $ret.val(fieldsPpraMedicaos.ret);
            $form.processa({
                url    : "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key
                , type : "POST"
                , ret  : fieldsPpraMedicaos.ret
                , data : {
                    subOpcao : 'loadCad'
                }
            });
            $ret.val(retOld);
        }).showModal();
    };
    
    
    var atualizaPag = function(){        
        $.processa({
            url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => $action), [], FALSE, FALSE); ?>" 
            , frm: fieldsPpraMedicaos.frm
            , ret : fieldsPpraMedicaos.ret
            , type : 'POST'
            , data: {
                subOpcao : 'loadCad'
                ,ret     : fieldsPpraMedicaos.ret
            }
        });
    };
    
    
    var idPpraMedicao         = '';
    var oldTdValorResposta    = '';
    var oldTdValorRespostaVlr = '';
    var tdField               = '';
    var editValorResposta = function(){
        var $td = $(this);
        tdField = $td.data('col');
        var id = $td.closest('tr').data('id');
        var $valorResposta = $('#valorResposta');
        if(idPpraMedicao === id){
            return;
        }
        if(oldTdValorResposta != ''){
            oldTdValorResposta.html(oldTdValorRespostaVlr);
        }
        oldTdValorResposta = $td;
        oldTdValorRespostaVlr = $td.html();
        idPpraMedicao = id;
        $valorResposta.val($td.html());
        $td.html('');
        $valorResposta.closest('.form-group').parent().show().appendTo($td); 
        $valorResposta.focus().select();
    };
    
    var saveValorResposta = function(){
        var $valorResposta = $('#valorResposta');        
        $valorResposta.closest('.form-group').parent().hide().appendTo($('#inter'));  
        oldTdValorResposta.html($valorResposta.val());
        if(oldTdValorRespostaVlr !== $valorResposta.val()){
            var dados = {
                id       : idPpraMedicao
            };
            dados[tdField] = $valorResposta.val();
            $.processa({
                url : "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'save'), [], FALSE, FALSE); ?>",
                type : 'POST',
                data : dados,
                callback: function (data, defaults) {
                    data = JSON.parse(data);
                    $.flashMessenger(data.messenger);
                    if(data["result"] == 'ok'){
                        oldTdValorResposta.html(data.valor);
                        atualizaPag();
                    }else{
                        oldTdValorResposta.html(oldTdValorRespostaVlr);
                    }
//                    nextRespostaTarget(null);
                },
                savePage : false,
                last : false
            });
        }else{
            nextRespostaTarget(null);
        }
    };
    
    var nextRespostaTarget = function(opt){
        if(opt){
            var $valorResposta = $('#valorResposta');        
            $valorResposta.closest('.form-group').parent().hide().appendTo($('#inter'));  
            oldTdValorResposta.html($valorResposta.val());
        }
        
        var $auxTdOld = oldTdValorResposta;
        oldTdValorResposta = '';
        idPpraMedicao = '';
        switch(opt){
        case null: 
        case 'dow': 
            $auxTdOld.parent().next('TR').find('.inputVlr').click();   
            break;
        case 'up': 
            $auxTdOld.parent().prev('TR').find('.inputVlr').click();   
            break;
        }      
    };
    
    
    
    $(function () {
        var fields = <?php echo json_encode($fields) ?>;
        // Esconder menu superior do index
        if('#inter' !== fields.ret){
            $('#ppraMedicaoIndexMenu').hide();
        }
        
        $('#valorResposta').closest('.form-group').parent().hide();
        $('.inputVlr').click(editValorResposta);
        
        $('#valorResposta').keyup(function(e) {
            switch(e.which){
            case 13: 
                saveValorResposta();
                break;
            case 38: 
                nextRespostaTarget('up');
                break;
            case 40: 
                nextRespostaTarget('dow');
                break;
            }
        });
        
    });
</script>