<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'appRoles';
?>
<h1>Roles</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url('app/default',array('controller'=>$controller,'action'=>'new')); ?>">Novo</button>
</p>
<?php

    $table->openTable(TRUE)  ; 
    $table->renderThead(['ID','Nome','Herança','Admin','Criado','Atualizado','Ação'])  ;     
    /* @var $entity \Application\Entity\AppRole */
    foreach($this->data as $entity){
        $table->renderLine([
            $entity->getId(),
            $entity->getNome(),
            $entity->getParent(),
            $entity->getIsAdmin()?'sim':'não',
            $entity->getCreatedAt(),
            $entity->getUpdatedAt(),
            $entity->getId(),
        ]);
    } 
    $table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>    
</center>

<script lang="javascript">      
    function edit(key){
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>$controller,'action'=>'edit'),[],FALSE,FALSE);?>" + "/" + key };
        action.processa(data);
    }
    function del(key){
        var msg = "Deseja mesmo excluir este registro?";
        if(!confirm(msg)){
            return;
        }
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>$controller,'action'=>'delete'),[],FALSE,FALSE);?>" + "/" + key };
        action.processa(data);
    }    
</script>