<?php

/**
 * Inicia resultados
 */
if ($this->resultSet) {
    $array = [];
    switch ($this->subOpcao) {
        default :
            /* @var $entity \Tcmed\Entity\PpraOcupacao */
            $array[] = [
                "menu_id"    => "ID da ocupação",
                "menu_local" => "Local da ocupação",
            ];
            foreach ($this->resultSet as $entity) {
                $array[] = [
                    "id"    => $entity->getId(),
                    "local" => $entity->getLocal(),
                ];
            }

            break;
    }

    echo json_encode($array);
}
