<?php 
/* @var $fh        \Application\View\Helper\FormHelp */
/* @var $resposta  \Farol\Entity\Resposta */
/* @var $entity    \Farol\Entity\PpraAparelho */
/* @var $form      \Farol\Form\PpraAparelho */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$entity     = $this->entity;
$ret        = $form->getValue('ret', '#inter');

$formId     = 'formPpraAparelho';
$form->setAttribute('id', $formId);
$form->setAttribute('target', $ret);
?>
<h3 class=""><?php echo $this->dataView['titulo']; ?></h3>
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => $action)); ?>">Limpar</button>
</p>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));
$partial = $this->partialObj('tcmed');
$fh->setHorizontal(false);
$fh->formInit();
    $fh->openCol(6)->renderInputText('nome')->closeCol();
    $fh->openCol(6)->renderInputText('titulo')->closeCol();
$fh->lineDown();
    $fh->openCol(6)->renderInputText('metodo')->closeCol();
    $fh->openCol(6)->renderInputSelect('agente')->closeCol();
$fh->lineDown();
    $fh->openCol(6)->renderInputSelect('status')->closeCol();
    $fh->openCol(6)->Submit('submit')->closeCol();
$fh->lineDown()->openCol(12);
    echo '<div id="showListagemPpraAparelho"></div>';
$fh->closeLine()->formEnd();
//
// === TRANPORTE ==============================================================
$transp = [
    'action'                 => $action
    ,'id'                    => $form->getValue('id', 0)    
    ,'ret'                   => $ret    
];
// ===================================================================== FIM ===

// carregar modal somente quando for para o target inter
echo $this->partial('partials/modal',[]);
?>
<script lang="javascritp">   
    
    var isValid = function(){
        return true;
    };
    
    $(function(){
        // =====================================================================
        /**
         * @property {Object} fields Campos de transferencia do PHP, que serão
         * utilizados no javascript
         */
        var fields = <?php echo json_encode($transp) ?>;
        
        var showPpraAparelhoLista = function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'index'), [], FALSE, FALSE); ?>" 
                , type: "POST"
                , savePage: false
                , frm : true
                , ret: '#showListagemPpraAparelho'
                , data: {
                    id: fields.id
                    , ret      : '#showListagemPpraAparelho'
                }
            });    
        };
        
        showPpraAparelhoLista();
        
    });
</script>
