<?php

$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$title      = $this->dataView['titulo'];
$entity     = $this->entity;
$form       = $this->form;


/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($entity) ? $entity->getId() : 0,
), [], FALSE, $this->dataView['ajax']));
    
echo $fh->openDiv('id="list-cargo-apelido"');
    
    $fh->openLine();    
    $fh->setPreFix('cargoApelido');
        $idCargoApelido = $fh->getIdFor('idCargoApelido');
        $fh->openCol(10)->text('apelido', [
            'dt-clear' => $idCargoApelido,
            "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
        ])->closeCol();
        $apelido        = $fh->getLastId();
    $fh->removePreFix('cargoApelido');
    $fh->closeLine();
    
echo $fh->closeDiv();
// =================================================

// Var de transferencia PHP to JS
$transp = compact(
    'cargo'
    ,'idCargo'
    ,'idCargoApelido'
    ,'apelido'
);
?>
<script lang="javascript">
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;

        $$(transp.cargo).auto({
            primary: "cargo",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'cargos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            type: "POST",
            width: 800,
            params: {
                subOpcao: "pesquisarCargos",
            },
            responseTo: {
                idCargo       : [transp.idCargo],
                idCargoApelido: [transp.idCargoApelido],
                descricao     : [transp.descricao],
            },
            showCols: ["cargo", "descricao","tipo"]
        });

    });
</script>
