<?php

$controller = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$title        = $this->dataView['titulo'];
/* @var $ppra \Tcmed\Entity\Ppra */
$ppra         = $this->ppra;
/* @var $ppraOcupacao \Tcmed\Entity\PpraOcupacao */
$ppraOcupacao = $this->ppraOcupacao;
/* @var $form \Tcmed\Form\PpraOcupacao */
$form         = $this->form;


$ret          = $form->getValue('ret', '#inter');

$form->setAttribute('id', 'formOcupacaoModal');

/* @var $fh \Application\View\Helper\FormHelp */
$fh         = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
    'id' => ($ppraOcupacao) ? $ppraOcupacao->getId() : 0,
), [], FALSE, $this->dataView['ajax']));

$autoComp = [
    'dt-clear' => '',
    "extra"    => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
];
// nao exibir lupa de pesquisa para setor e cargo quando for edição
if($ppraOcupacao){
    unset($autoComp['extra']);
}


$apelidos = FALSE;
if($ppra AND $ppraOcupacao){
    /* @var $ppraOcup  \Tcmed\Entity\PpraOcupacao */
    $ppraOcupacaos  = $ppra->listPpraOcupacao([
        'status' => 'ATIVO'
        ,'cargo' => $ppraOcupacao->getCargo()
    ]);
    foreach ($ppraOcupacaos as $ppraOcup) {
        if(!$ppraOcup->getApelido()){
            continue;
        }
        $apelidos[$ppraOcup->getOcupacao('cargoApelido',['id'])] = $ppraOcup->getOcupacao('cargoApelido',['apelido']);
    }    
}
      


$fh->formInit(); // ===============================================

$fh->setHorizontal(true);

$fh->setPreFix('ppraOcupacao');

$fh->openCol(10)->renderInputSelect('local')->closeCol();

$fh->removePreFix('ppraOcupacao');

$fh->setPreFix('ocupacao');

    $fh->setPreFix('setor');

        $idSetor   = $fh->getIdFor('idSetor');
        $nomeSetor = $fh->getIdFor('nomeSetor');
        $autoComp['dt-clear'] = $idSetor;
        $fh->openCol(10)->text('nomeSetor', $autoComp)->closeCol();

    $fh->removePreFix('setor');

    $fh->lineDown();

    $fh->setPreFix('cargo');
        $idCargo = $fh->getIdFor('idCargo');
        $autoComp['dt-clear'] = $idCargo;
        $fh->openCol(10)->text('cargo', $autoComp)->closeCol();
        $cargo   = $fh->getLastId();
    $fh->removePreFix('cargo');

    $fh->lineDown();    
    
    $fh->setPreFix('cargoApelido');
        $idCargoApelido = $fh->getIdFor('idCargoApelido');
        $fh->openCol(10)->text('apelido', [
            'dt-clear' => $idCargoApelido,
            "extra" => [
                 ["icon" => "arrow-down", "id" => "btn-join-apelido", "title" => "Incluir na lista este apelido"]
                ,["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
                ,["icon" => "plus", "id" => "btn-add-apelido", "title" => "Incluir um novo apelido"]
            ]
        ])->closeCol();
        $apelido        = $fh->getLastId();
    $fh->removePreFix('cargoApelido');
    $fh->lineDown();
        $fh->renderInputRadio('situacao');
    
    $fh->closeLine();

    $divApelido = 'cargo-apelido-list';    
    $fh->openLine(['id' => $divApelido, 'class' => 'border-bottom border-right', 'style' => 'margin : 2px;']);
    $fh->closeLine();
    
    $fh->openLine();
    
$fh->setHorizontal(false);

    $fh->setPreFix('descricaoCargo');

        $idDescricaoCargo = $fh->getIdFor('idDescricaoCargo');
        $descricao        = $fh->getIdFor('descricao');

        $fh->openCol(12)->textarea('descricao', [], ['rows' => '6'])->closeCol();

    $fh->removePreFix('descricaoCargo');
    
$fh->removePreFix('ocupacao');

$fh->closeLine();
$fh->formEnd(); 
// =================================================

// Var de transferencia PHP to JS
$transp = compact(
    'nomeSetor',
    'idSetor',
    'cargo',
    'idCargo',
    'idCargoApelido',
    'apelido',
    'descricao',
    'idDescricaoCargo',
    'ret',
    'apelidos',
    'divApelido'
);
?>
<script lang="javascript">

    function isValid(){
        return true;
    }


    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        $('#btn-add-apelido').click(function(){
            $.processa({
                url     : "<?php echo $this->url($route, array('controller' => 'cargoApelidos', 'action' => 'getForm'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ppra   : transp.ppra
                    ,ret   : transp.ret
                    ,cargo : $$(transp.idCargo).val()
                    ,setor : $$(transp.idSetor).val()
                },
                callback: function (data, defaults) {
                    gModal2.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir Apelido')
                    .setClickOk(function(){
                        $('#formCargoApelidoModal').processa({
                            url : "<?php echo $this->url($route, array('controller' => 'cargoApelidos', 'action' => 'add'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            ret : transp.ret,
                            data: {
                                ret               : transp.ret
                            },
                            callback: function (data, defaults) {
                                console.log(data);
                            }
                        });
                    })
                    .setSizeModal('lg')
                    .showModal();
                }
            });
        });
        
        $$(transp.apelido).change(function(){
            var $cargo =  $$(transp.idCargoApelido);
            $cargo.val('');
        });
        
        $('#btn-join-apelido').click(function(){
            var $cargo =  $$(transp.idCargoApelido);
            var $desc  =  $$(transp.apelido);
            if($cargo.val()=='' && $desc.val() != ''){
                gModal2.alert('O apelido deve ser estar cadastrado no sistema e escolha da lista!!!',1);
            }
            if($cargo.val()==''){
                return;
            }
            var list = action.getPublic('all','listCargoApelido');
            var has = false;
            if(list){
                $.each(list, function(k,v){
                    if(k == $cargo.val()){
                        has = true;
                    }
                });
            }else{
                list = {};
            }
            if(!has){
                list[$cargo.val()] = $desc.val();
            }            
            action.setPublic(list,'listCargoApelido');    
            $$(transp.divApelido).click();
            $cargo.val('');
            $desc.val('');
        });
        
        if(transp.apelidos){
            action.setPublic(transp.apelidos,'listCargoApelido'); 
        }

        $$(transp.divApelido).click(function(){
            var list = action.getPublic('all','listCargoApelido');
            var tb = '';
            tb += '<div class="col-md-2 text-center border-top border-left"><label>ID</label></div>';
            tb += '<div class="col-md-8 text-center border-top border-left"><label>Apelido</label></div>';
            tb += '<div class="col-md-2 text-center border-top border-left"><label>Ação</label></div>';
            if(list){
                $.each(list, function(k,v){
                    tb += '<div class="border-top border-left col-md-2 text-center">'+k+'</div>';
                    tb += '<div class="border-top border-left col-md-8">'+v+'</div>';
                    tb += '<div class="border-top border-left col-md-2 text-center">';
                    tb += '<i title="Excluir este da item da lista" class="fa fa-trash hand btn-rm-cargo-apelido" data-id="'+k+'"></i>';
                    tb += '</div>';
                });
            }
            $(this).html(tb);
            $('.btn-rm-cargo-apelido').click(function(){            
                var list = action.getPublic('all','listCargoApelido');
                var cargo = $(this).data('id');
                var newlist = {};
                $.each(list, function(k,v){
                    if(k != cargo){
                        newlist[k] = v;
                    }
                });
                action.setPublic(newlist,'listCargoApelido');    
                $$(transp.divApelido).click();
            });
        }).click();
        
        $$(transp.cargo).blur(function(){
            action.setPublic(false,'listCargoApelido');   
            $$(transp.divApelido).click();        
        });
        
        $$(transp.nomeSetor).auto({
            primary: "nomeSetor",
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'Setors', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            width: 800,
            filters: function (query) {
                query["rules"]    = {"status": "ATIVO"};
                query["subOpcao"] = "";
            },
            responseTo: {
                idSetor: [transp.idSetor]
            },
            showCols: ["nomeSetor"]
        });

        $$(transp.cargo).auto({
            primary: "cargo",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'cargos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            type: "POST",
            width: 800,
            params: {
                subOpcao: "",
            },
            responseTo: {
                idCargo       : [transp.idCargo],
                idCargoApelido: [transp.idCargoApelido],
                descricao     : [transp.descricao],
            },
            showCols: ["cargo", "descricao","tipo"]
        });

        $$(transp.apelido).auto({
            primary: "apelido",
            serviceUrl: "<?php echo $this->url('tcmed/default', array('controller' => 'cargoApelidos', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            type: "POST",
            width: 800,
//            params: {
//                subOpcao: "pesquisarCargos",
//            },
            filters: function (query) {
                query["rules"]    = {
                    "status" : "ATIVO"
                    ,"cargo" : $$(transp.idCargo).val()
                };
            },
            responseTo: {
                idCargo        : [transp.idCargo],
                cargo          : [transp.cargo],
                idCargoApelido : [transp.idCargoApelido],
                apelido        : [transp.apelido]
            },
            showCols: ["apelido", "cargo"]
        });

    });

</script>
