<?php
/* @var $table \Application\View\Helper\Table */
/* @var $fh    \Application\View\Helper\FormHelp */
/* @var $partial    \Application\View\Helper\PartialObj */
/* @var $ppra  \Tcmed\Entity\Ppra */
/* @var $form  \Tcmed\Form\PpraOcupacao */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'];
$route      = $this->dataView['route'];
$ajax       = $this->dataView['ajax'];
$form       = $this->form;
$table      = $this->table();
$ppra       = $this->ppra;

/* @var $param \Application\View\Helper\Param  */
$param   = $this->Param();


$ret        = $form->getValue('ret', '#inter');
$form->setAttribute('target', $ret);

$fh = $this->formHelp($this,$form,$this->url($route,array('controller'=>$controller,'action'=>$action),[],FALSE,$ajax));

// Messenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);

$partial = $this->partialObj('tcmed');
// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);

?>
<br />
<legend>
    <button id="addOcupacao" class="btn btn-primary"><i class='fa fa-plus'></i> Adicionar Setor ou Cargo</button>
    <a href="<?= $param('linkCbo','link_cbo'); ?>" target="_blank"><button id="CBO" class="btn btn-info"><i class='glyphicon glyphicon-search'></i> Ministério do trabalho CBO</button></a>
</legend>

<?php
//echo '<pre>', var_dump($this->post), '</pre>';
if($ppra){
    /* @var $ppraOcupacao  \Tcmed\Entity\PpraOcupacao */
    $ppraOcupacaos  = $ppra->listPpraOcupacao();
    $qtd = count($ppraOcupacaos);
    foreach ($ppraOcupacaos as $ppraOcupacao) {
        $partial->partial('ppra-ocupacaos/partial-show-ocupacao', $this, [
            'dataView'      => $this->dataView
            ,'post'         => $this->post
            ,'ppraOcupacao' => $ppraOcupacao
            ,'total'        => $qtd
        ]);
    }    
}
// === TRANSPORTE ==============================================================
$transp = [
    'action'                 => $action
    ,'ret'                   => $ret      
    ,'ppra'                  => ($ppra) ? $ppra->getId() : ''      
];
// ===================================================================== FIM ===
?>
<script lang="javascript">
    $(function () {
        var transp = <?php echo json_encode($transp) ?>;
       
       /**
        * remove um Epc ao Risco do cargo
        */
        $('.rmvEpcRiscoOcupacao').click(function(){
            var $btn = $(this);
            var epcRiscoOcupacao =  $btn.data('id');
            var ppraOcupacao     =  $btn.data('ppraocupacao');
            action.setPublic({notHide: true}, 'ppra');
            gModal.confirm('Deseja realmente remover este EPC?',function(){
                $.processa({
                    url     : "<?= $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'deleteEpcRisco'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        ret           : transp.ret,
                        ppra          : transp.ppra,
                        ppraOcupacao  : ppraOcupacao,
                        id            : epcRiscoOcupacao
                    },
                })
            },1);
            
        });
        
       /**
        * Adiciona um Epc ao Risco do cargo
        */
        $(".addEpcRiscoOcupacao").click(function(){
            var $btn = $(this);
            var riscoOcupacao =  $btn.data('riscoocupacao');
            var ppraOcupacao  =  $btn.data('ppraocupacao');
            action.setPublic({notHide: true}, 'ppra');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'EpcRiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type: 'POST',
                data: {
                    riscoOcupacao : riscoOcupacao,
                    ppraOcupacao  : ppraOcupacao
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        if($$('epc[idEpc]').val() == ''){
                            gModal2.alert('Deve escolha um EPC da listagem da pesquisa.',1);
                            gModal.showModal();
                            return;
                        }
                        $('#formModalEpcOcupacao').processa({
                            url     : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'addEpcRiscoOcupacao'), [], FALSE, FALSE); ?>",
                            type    : "POST",
                            savePage: false,
                            ret     : transp.ret,
                            data    : {
                                ppra          : transp.ppra,
                                ret           : transp.ret,
                                ppraOcupacao  : ppraOcupacao
                            },
                        });

                    })
                    .showModal() ;
                }
            });
        });
        
       /**
        * remove um Epi ao Risco do cargo
        */
        $('.rmvEpiRiscoOcupacao').click(function(){
            var $btn = $(this);
            var epiRiscoOcupacao =  $btn.data('id');
            var ppraOcupacao     =  $btn.data('ppraocupacao');
            action.setPublic({notHide: true},'ppra');
                gModal.confirm('Deseja realmente remover este EPI?',function(){
                    $.processa({
                        url     : "<?= $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'deleteEpiRisco'), [], FALSE, FALSE); ?>",
                        savePage: false,
                        ret     : transp.ret,
                        type    : "POST",
                        data    : {
                            ret           : transp.ret,
                            ppra          : transp.ppra,
                            ppraOcupacao  : ppraOcupacao,
                            id            : epiRiscoOcupacao
                        },
                    })
                },1);
        });
       /**
        * Adiciona um Epi ao Risco do cargo
        */
        $(".addEpiRiscoOcupacao").click(function(){
            var $btn = $(this);
            var riscoOcupacao =  $btn.data('riscoocupacao');
            var ppraOcupacao  =  $btn.data('ppraocupacao');
            action.setPublic({notHide : true},'ppra');
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => 'EpiRiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type: 'POST',
                data: {
                    riscoOcupacao : riscoOcupacao,
                    ppraOcupacao  : ppraOcupacao
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        if($$('epi[idEpi]').val() == ''){
                            gModal2.alert('Deve escolha um EPI da listagem da pesquisa.',1);
                            gModal.showModal();
                            return;
                        }
                        $('#formModalEpiOcupacao').processa({
                            url     : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'addEpiRiscoOcupacao'), [], FALSE, FALSE); ?>",
                            type    : "POST",
                            savePage: false,
                            ret     : transp.ret,
                            data    : {
                                ppra          : transp.ppra,
                                ret           : transp.ret,
                                ppraOcupacao  : ppraOcupacao
                            },
                        });

                    })
                    .showModal() ;
                }
            });
        });
        
        /**
        * Remove o Risco da lista
        */
        $(".rmvRiscoOcupacao").click(function () {
            var id = $(this).attr("data-id");
            action.setPublic({notHide: true}, 'ppra');
            gModal.confirm('Deseja realmente remover este Risco?',function(){
                $.processa({
                    url     : "<?= $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'deleteRisco'), [], FALSE, FALSE); ?>",
                    savePage: false,
                    ret     : transp.ret,
                    type    : "POST",
                    data    : {
                        ppra : transp.ppra,
                        idEntity  : transp.idEntity,
                        id        : id
                    },
                })
            },1);
        });
        
//        Remove risco
        $('.rmvOcupacao').click(function(){
            var idOcupacao = $(this).data('id');
            action.setPublic({notHide: false}, 'ppra');
            gModal.confirm('Deseja mesmo excluir este cargo do PPRA?',function(){
                $.processa({
                    url      : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'delete'), [], FALSE, FALSE); ?>",
                    savePage : false,
                    type     : "POST",
                    ret      : transp.ret,
                    data     : {
                        ppra : transp.ppra
                        ,id  : idOcupacao
                        ,ret : transp.ret
                    }
                });                 
            },1);
        });
        
//        Adicionar novo risco
        $('.addOcupacaoRisco').click(function(){
            var idOcupacao = $(this).data('id');
            action.setPublic({notHide: true}, 'ppra');
            $.processa({
                url     : "<?php echo $this->url($route, array('controller' => 'RiscoOcupacaos', 'action' => 'formModal'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ppra : transp.ppra
                    ,ret : transp.ret
                },
                callback: function (data, defaults) {
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setSizeModal('lg')
                    .setClickOk(function(){
                        $('#formModalRiscoOcup').processa({
                            url : "<?= $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'addRisco'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            ret : transp.ret,
                            data: {
                                id                 : idOcupacao
                                ,ret               : transp.ret
                                ,ppra              : transp.ppra
                            }
                        });

                    })
                    .showModal() ;
                    // funcao usada para o botao de copiar risco
                    $('#btn-clone-risco').click(function(){
                        var $riscoOcupacao = $('#riscoOcupacao');
                        if($riscoOcupacao.val() == ''){
                            gModal2.alert('Nenhum risco para copiar os dados foi selecinado!!');
                            return;
                        }
                        gModal2.confirm('Deseja Realmente copiar este risco para a Ocupação Atual ?', function(){
                            $('#formModalRiscoOcup').processa({
                                url : "<?= $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'cpRisco'), [], FALSE, FALSE); ?>",
                                type: "POST",
                                savePage: false,
                                ret : transp.ret,
                                data: {
                                    ppraOcupacao       : idOcupacao
                                    ,ret               : transp.ret
                                    ,ppra              : transp.ppra
                                    ,riscoOcupacao     : $riscoOcupacao.val()
                                }
                            });
                            gModal.getModal().modal('toggle');
//                            setTimeout(function(){gModal.getModal().modal('toggle');}, 500);
                        });           
                    });
                }
            });            
        });
        
        
        
        /**
         * Adiciona uma nova ocupacao
         */
        $('#addOcupacao').click(function() {
            action.setPublic({notHide : false},'ppra');
            $.processa({
                url     : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'getFormPpra'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ppra : transp.ppra
                    ,ret : transp.ret
                },
                callback: function (data, defaults) {
                    action.setPublic(false,'listCargoApelido'); 
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        if($$('ocupacao[cargoApelido][apelido]').val() != ''){
                            var msg  = 'Existe um apelido na area de cadastro que deve ter uma das seguintes ações:<br><br>';
                            msg += '1 - Click na seta para adicionar na lista abaixo.<br>';
                            msg += '2 - Click no icone + para adicionar um novo apelido ao cargo caso ainda não exista<br>';
                            msg += '3 - Apague o item para poder incluir<br>';
                            gModal2.alert(msg);
                            gModal.showModal();
                            return;
                        }
                        if($$('ocupacao[cargo][idCargo]').val() == ''){
                            var msg  = 'Um cargo deve ser escolhido da lista de opções :<br><br>';
                            msg += 'Caso não encotre o cargo na lista ele deverá ser incluido separamamente.<br>';
                            gModal2.alert(msg);
                            gModal.showModal();
                            return;
                        }
                        var list = action.getPublic('all','listCargoApelido');
                        $('#formOcupacaoModal').processa({
                            url : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'new'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            ret : transp.ret,
                            data: {
                                ret               : transp.ret,
                                cargoApelidosJson : JSON.stringify(list)
                            }
                        });
                    })
                    .setSizeModal('lg')
                    .showModal();
                }
            });
        });
        
        /**
         * Editar os itens de um ocupação já incluida  
         */
        $('.edtOcupacao').click(function(){
            var id = $(this).data('id');
            action.setPublic({notHide: false}, 'ppra');
            $.processa({
                url     : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'getFormPpra'), [], FALSE, FALSE); ?>",
                savePage: false,
                type    : "POST",
                data    : {
                    ppra      : transp.ppra
                    ,ret      : transp.ret
                    ,id       : id
                    ,subOpcao : 'loadCad'
                },
                callback: function (data, defaults) {
                    action.setPublic(false,'listCargoApelido'); 
                    gModal.reset('prompt',2)
                    .setInputs(data)
                    .setLabelOk('Incluir')
                    .setClickOk(function(){
                        if($$('ocupacao[cargoApelido][apelido]').val() != ''){
                            var msg  = 'Existe um apelido na area de cadastro que deve ter uma das seguintes ações:<br><br>';
                            msg += '1 - Click na seta para adicionar na lista abaixo.<br>';
                            msg += '2 - Click no icone + para adicionar um novo apelido ao cargo caso ainda não exista<br>';
                            msg += '3 - Apague o item para poder incluir<br>';
                            gModal2.alert(msg);
                            gModal.showModal();
                            return;
                        }
                        var list = action.getPublic('all','listCargoApelido');
                        $('#formOcupacaoModal').processa({
                            url : "<?php echo $this->url($route, array('controller' => 'ppraOcupacaos', 'action' => 'edit'), [], FALSE, FALSE); ?>",
                            type: "POST",
                            savePage: false,
                            ret : transp.ret,
                            data: {
                                ret               : transp.ret,
                                cargoApelidosJson : JSON.stringify(list)
                            }
                        });
                    })
                    .setSizeModal('lg')
                    .showModal();
                }
            });
        });
        
        $('.btn-risco-control').click(function(){
            var $btn = $(this);
            var $span = $btn.find('i').eq(0);
            var $allRiscos = $btn.parent().find('.all-riscos');
            $allRiscos.toggle();
            if($allRiscos.is(":visible")){
                $span.html(' Ocultar Todos os Riscos da Ocupação').removeClass('fa-plus').addClass('fa-minus');
            }else{
                $span.html(' Exibir Todos os Riscos da Ocupação').removeClass('fa-minus').addClass('fa-plus');
            }
        });
        
        
        if(action.getPublic('notHide','ppra')){
            var btn = $('.btn-risco-control');
            var span = btn.find('i').eq(0);
            span.html(' Ocultar Todos os Riscos da Ocupação').addClass('fa-minus');
            action.setPublic({notHide:false}, 'ppra');
        }else{
            $('.all-riscos').hide();
        }
        
    });
    
    var edit = function(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    };
    
    var del = function(key) {
        var msg = "Deseja mesmo excluir este registro?";
        gModal.confirm(msg,function(){
            $.processa({
                url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key
            });
        });
    };
    
</script>