<?php

$result = $this->resultSet;

/* @var $entity \Tcmed\Entity\Empresa */
if ($result) {
    $array = [];
    $array[] = [
        'menu_idEmpresa' => "ID Empresa",
        'menu_razaoSocialEmp' => "Empresa",
        'menu_fantasiaEmpresa' => "Apelido",
        'menu_referenciaEmp' => "Ref Empresa",
        'menu_cnpj'   => "CNPJ",
        'menu_cpf'    => "CPF",
        'menu_idAdministradora' => "ID Adm",
        'menu_fantasiaAdm' => 'Administradora',
        'menu_razaoSocialAdm' =>'Administradora',
        'menu_referenciaAdm' => "Ref Adm",
        'menu_referenciaSubhold' => "Ref Adm",
        'menu_idHold' => "ID Hold",
        'menu_nomeHold' => "Hold",
        'menu_fantasiaHold' => "Hold",
        'menu_referenciaHold' => "Ref Hold",
    ];
    foreach ($result as $empresa) {

        $administradora = $empresa->getAdministradora();
        $hold = $empresa->getAdministradora()->getHold();

        $array[] = [
            'idEmpresa'          => $empresa->getId(),
            'razaoSocialEmp'     => $empresa->getRazaoSocial(),
            'fantasiaEmpresa'    => $empresa->getFantasiaEmpresa(),
            'referenciaEmp'      => $empresa->getReferenciaEmp(),
            'cnpj'               => $empresa->getCnpj(),
            'cpf'                => $empresa->getCpf(),
            'idAdministradora'   => $administradora->getId(),
            'fantasiaAdm'        => $administradora->getFantasiaAdm(),
            'razaoSocialAdm'     => $administradora->getRazaoSocial(),
            'referenciaAdm'      => $administradora->getReferenciaAdm(),
            'referenciaSubhold'  => $administradora->getReferenciaSubhold(),
            'idHold'             => $hold->getIdHold(),
            'nomeHold'           => $hold->getNomeHold(),
            'fantasiaHold'       => $hold->getFantasiaHold(),
            'referenciaHold'     => $hold->getReferenciaHold(),
            'conf_class'         => ("INATIVO" == $empresa->getStatus()) ? "color-red" : "",
        ];
    }
}

echo json_encode($array);
