<h3>
<?php
    echo $this->dataView['titulo'];
    $controller = 'empresas';
    $route = 'tcmed/default';
    /* @var $empresa \Tcmed\Entity\Empresa */
    $empresa = ($this->entity) ? $this->entity : FALSE;
    
    /**
     * @var Object Partials (pedacos) de outras entidades presentes neste form
     */
    $partialObject = $this->partialObj('tcmed');
    
    if($empresa AND $empresa->getAlerta()){
        $partialObject->partial('alertas/partial-show', $this, ['partial' => $partialObject,'empresa' => $empresa]);
    }
?>
</h3>
<br />
<?php
/**
 * @var array Mensagens do servidor que serão lidas na view
 * OBS: Após ler mensagens, fila é apagada
 * @see javascript::createMessages
 */
$messages = $this->flashMessenger()->getCurrentAllMessages();
$this->flashMessenger()->clearCurrentAllMessages();

/* @var $fh \Application\View\Helper\FormHelp */
/* @author Allan Davini */
$fh = $this->formHelp($this, $this->form, $this->url($route, array('controller' => $controller, 'action' => $this->dataView['action']), [], FALSE, $this->dataView['ajax']));
$fh->setHorizontal(FALSE);

$fh->formInit('Cadastro Empresas:');
//$this->partialObj('tcmed')->partial('administradoras/partial-form-all', $fh, ['this' => &$this]);
$idEmpresa = $fh->getIdFor('idEmpresa');

/* @var $fh \Application\View\Helper\PartialObject */
$fh->openCol('12');

$partialObject->partial('empresas/partial-form-all', $fh, ['this' => &$this, 'controller' => $controller, 'noPrefix'=> TRUE]);

$fh->closeCol();
$fh->lineDown();
$fh->openCol('3')->text('inscricaoEstadual')->closeCol();
$fh->openCol('9')->text('fantasiaEmpresa')->closeCol();
$fh->lineDown();
//$fh->openCol('5')->text('guiaAvulsa')->closeCol();
$fh->openCol('3')->text('qtdFunc')->closeCol();
$fh->openCol('3')->select('tipoPeriodico')->closeCol();
$fh->openCol('3')->text('grauRisco')->closeCol();
$fh->openCol('3')->text('cnae')->closeCol();
$inpCnae = $fh->getLastId();
$fh->lineDown();
$fh->openCol('2')->checkbox('hasPpra')->closeCol();
$fh->openCol('2')->checkbox('hasPpp')->closeCol();
// $fh->openCol('12')->text('referenciaAdm')->closeCol();
$fh->lineDown();
$fh->lineDown();
$fh->openCol('4')->select('periodicidade')->closeCol();
$fh->openCol('4')->select('atividade')->closeCol();
$fh->openCol('4')->select('status')->closeCol();
//$fh->openCol('5')->text('latitude')->closeCol();
$fh->lineDown();

$fh->openCol(4)->text('latitude',[
    "extra" => ["icon" => "search", "class" => "open-map", "title" => "Pesquisar"],
])->closeCol();
$fh->openCol(4)->text('longitude', [
    "extra" => ["icon" => "search", "class" => "open-map", "title" => "Pesquisar"],
])->closeCol();
$fh->openCol(4)->text('codigoRua')->closeCol();

$fh->lineDown();

$fh->openCol(3)->file('uploadLogo')->closeCol();
$fh->openCol(5);

$img = '';
if($this->entity) {
    /* @var $entity \Tcmed\Entity\Empresa */
    $entity = $this->entity;
    $src = $this->Param('path','empresa_dir') . $entity->getId() . DIRECTORY_SEPARATOR  .  $entity->getPathLogo();   
    $img = $this->Image($src);
}
echo "<img id='logo-emp' style='width: 270px; height: 100px;' src='{$img}' alt='Sem Imagem' class='img-thumbnail'>";
$fh->closeCol();

$fh->closeLine();
/**
 * @category contato
 */
// =================================================================== CONTATO ======
// Carrega o partial de contatos
$partialObject->partial('contatos/partial-form-contato', $fh, [
    'this' => &$this,
    'entity' => $entity,
]);
// ==============================================================================
/**
 * @category Endereço
 */
// =================================================================== CONTATO ======
$fh->renderFieldsetIni("Endereço");
$fh->lineDown()->openCol(12);
$this->partialObj('tcmed')->partial('enderecos/partial-form-all', $fh, ['this' => &$this]);
$fh->lineDown();
$fh->openCol(12);
$fh->openCol(9)->text('referenciaLocal')->closeCol();
$fh->closeCol();

$fh->lineDown();

$fh->renderFieldsetFim();
// ==============================================================================
$fh->lineDown();

$fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();

$fieldsEntity = [
    "idEntity"  => ($this->entity) ? $this->entity->getId() : 0,
    "idEmpresa" => $idEmpresa,
    "isEdit"    => ($this->dataView["action"] == "edit"),
    "inpCnae"   => $inpCnae,
];
?>
<br>
<br>
<br>
<script lang="javascript">

    function isValid() {
        return true;
    }

    $(function () {
        var fields = <?php echo json_encode($fieldsEntity) ?>;

        //== MENSAGENS DO SISTEMA ==============================================
        /**
         * @see (PHP) flashMessenger
         * @property {object} messagesGroup Necessário para exibir mensagens 
         * na tela
         * @obsolet
         */
        var messagesGroup = <?php echo json_encode($messages) ?>;
        /**
         * @event Exibe as mensagens do servidor na view
         */
        $.each(messagesGroup, function (type, messages) {
            $.each(messages, function (_, message) {
                $.notify({
                    "message": message,
                    "type": type
                });
            });
        });
        
        //mascara de cnae
        $$(fields.inpCnae).mask("99.99-9-99");
        // ========================================================== FIM ======
        /*
         * Altera a funcao padrão do callback run do partial form de empresas
         * @returns {nothing}         
         */
        window.funcaoCallBackPartialEmpresa.run = function(){
            $.processa({
                url  : "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + $$(fields.idEmpresa).val()
            });
        };  
    });

</script>
