<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$controller = $this->dataView['controller'];
$action     = $this->dataView['action'    ];
$route      = $this->dataView['route'     ];
$title      = $this->dataView['titulo'    ];
$orderBy    = $this->dataView['orderBy'   ];
$form       = $this->form;
$partial    = $this->partialObj('application');

/* @var $table \Application\View\Helper\Table */
$table = $this->table();

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, array(
    'controller' => $controller,
    'action' => $action,
), [], FALSE, $this->dataView['ajax']));

// Lê as mensagens do servidor através do flashMessenger
$partial->partial('index/partial-form-messenger', null, ['this' => &$this]);


?>
<h1><?= $title ?></h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route,array('controller'=>$controller,'action'=>'new')); ?>"><i class='fa fa-plus'></i> Cadastro</button>
    <button class="btn btn-primary pull-right" id='exibePendentes' onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'pesquisaEmpresa')); ?>"><i class='fa fa-search'></i> Pesquisa</button>
</p>
<?php

$fh->formInit(); // ===============================================

$this->partialObj('application')->partial('index/partial-form-listafiltros', null, ['this' => &$this, 'fh' => $fh, 'dataView' => $this->dataView]);

$fh->lineDown();

$fh->openCol(12);
$table->openTable(TRUE);
$table->setOrderList($orderBy);
$table->renderThead([
    ['label' => 'Ref'],
    ['label' => 'Nome Empresa',   'order' => 'razaoSocial'],
    ['label' => 'CNPJ',           'order' => 'cnpj'],
    ['label' => 'Administradora'],
    ['label' => 'Tipo',           'order' => 'tipoPeriodico'],
    ['label' => 'Status',         'order' => 'status'],
    ['label' => 'Ação'],
]);
/* @var $entity \Tcmed\Entity\Empresa */
foreach ($this->data as $entity) {
    
    $statusRow = "default";
    $entity->getStatus() == "INATIVO"   && $statusRow = "danger";
    $entity->getStatus() == "CANCELADO" && $statusRow = "danger";
    $entity->getStatus() == "BLOQUEADO" && $statusRow = "warning";
    
    $table->renderLine([
        $entity->getReferenciaEmp(),
        $entity->getRazaoSocial(),
        $entity->getCnpj(),
        $entity->getAdministradora('razaoSocial'),
        $entity->getTipoPeriodico(),
        $entity->getStatus(),
        $entity->getId(),
    ],"class='{$statusRow}'");
}
$table->renderCloseTable();
$fh->closeCol();

$fh->formEnd(); // =============================================================

echo "<br>";
echo "<center>{$this->paginationControl($this->data, 'Sliding', 'partials/paginator')}</center>";


?>
<script lang="javascript">
    
    function isValid() {
        return true;
    }
    
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
</script>