<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = &$obj;
if (!isset($d['cpfAllow'])) {
    $acl = $d['this']->Acl();
    $d['cpfAllow'] = $acl('tcmed:empresas:cpf', 'allow');
}

!isset($d["noPrefix"]) and $fh->setPreFix('empresa');
!isset($d["noAutoCompForEmpresa"]) and $d["noAutoCompForEmpresa"] = TRUE;

$horizontal = $fh->getHorizontal();
$fh->setHorizontal($horizontal);

$idEmpresa      = $fh->getIdFor('idEmpresa');
$referenciaEmp  = $fh->getIdFor('referenciaEmp');
$razaoSocialEmp = $fh->getIdFor('razaoSocial');

$fh->setPreFix('administradora');
    $idAdministradora  = $fh->getIdFor('idAdministradora');
    $fantasiaHold      = $fh->getIdFor('hold');
    $referenciaSubhold = $fh->getIdFor('referenciaSubhold');
    $razaoSocialAdm    = $fh->getIdFor('razaoSocial');

    $fh->openLine();
    $fh->openCol(3)->closeCol();
    $fh->openCol(9)->select('hold', [
        'dt-clear' => $razaoSocialAdm . "," . $referenciaSubhold . "," . $idAdministradora . "," . $referenciaEmp . "," . $razaoSocialEmp . "," . $idEmpresa
    ])->closeCol();

    $fh->lineDown();
    $fh->openCol(3)->number('referenciaSubhold', [
        'dt-clear' => $razaoSocialAdm . "," . $idAdministradora . "," . $referenciaEmp . "," . $razaoSocialEmp . "," . $idEmpresa
    ])->closeCol();

    // -- | Referencia Empresa | ------------------------
    $fh->openCol(9)->text('razaoSocial', [
        'dt-clear' => $referenciaSubhold . "," . $idAdministradora . "," . $referenciaEmp . "," . $razaoSocialEmp . "," . $idEmpresa,
        "extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
        ])->closeCol();
$fh->removePreFix();
    
$fh->lineDown(); // ------------------------------------------| linedown |------

// -- | Referencia Empresa | ------------------------
$fh->openCol(3)->number('referenciaEmp', [
    "dt-clear" => $razaoSocialEmp . "," . $idEmpresa
])->closeCol();

// -- | Razão Social | ------------------------
$tamRazaoSocial = (isset($d["hideCnpj"])) ? 9 : 5;
if (!isset($d["hidePesquisaEmpresa"])) {
    $pesquisaEmpresa = ["extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]];
}

isset($d["hideCnpj"]) and $fh->openCol(3)->closeCol();;

$fh->openCol($tamRazaoSocial)->text('razaoSocial', array_merge($pesquisaEmpresa, [
    "dt-clear" => $referenciaEmp . "," . $idEmpresa
]))->closeCol();


// ===| EXIBIR OU NÃO CAMPO CNPJ |==============================================
if (!isset($d["hideCnpj"])) {

    $maskCpf  = isset($d["maskCpf"])  ? $d["maskCpf"]  : TRUE;
    $maskCnpj = isset($d["maskCnpj"]) ? $d["maskCnpj"] : TRUE;

    $fh->openCol(4)
        ->cnpj('cnpj', [
                'dt-clear' => $idEmpresa . "," . $referenciaEmp . "," . $razaoSocialEmp,
                'extra' => ['icon' => 'exchange', 'id' => "changeCnpfForCpf", 'title' => "TROCAR DE CNPJ PARA CPF E VICE-VERSA"],
                'mask' => $maskCnpj
                    ], ['id' => 'empresaCnpj']);
        $cnpj = "empresaCnpj";

        $fh->cpf('cpf', [
                'dt-clear' => $idEmpresa . "," . $referenciaEmp . "," . $razaoSocialEmp,
                'extra' => ['icon' => 'exchange', 'id' => "changeCpfForCnpj", 'title' => 'TROCAR DE CNPJ PARA CPF E VICE-VERSA'],
                'mask' => $maskCpf
                    ], ['id' => 'empresaCpf'])
    ->closeCol();

    $cpf = 'empresaCpf';
}
// =============================================================================
$fh->closeLine();

!isset($d["noPrefix"]) and $fh->removePreFix('empresa');
$fh->setHorizontal($horizontal);

$nameField = isset($d["nameField"]) ? $d["nameField"] : "fieldsEmpresa";
$this->__set($nameField,[
        "fantasiaHold"          => $fantasiaHold,
        "referenciaSubhold"     => $referenciaSubhold,
        "idAdministradora"      => $idAdministradora,
        "razaoSocialAdm"        => $razaoSocialAdm,
        "idEmpresa"             => $idEmpresa,
        "razaoSocialEmp"        => $razaoSocialEmp,
        "referenciaEmp"         => $referenciaEmp,
        "cnpj"                  => isset($cnpj) ? $cnpj : "",
        "cpf"                   => isset($cpf)  ? $cpf  : "",
        "cpfAllow"              => isset($d['cpfAllow']) ? $d['cpfAllow'] : false,
        "noAutoCompForEmpresa"  => $d["noAutoCompForEmpresa"],
    ]);
?>

<script lang="javascript">


    $(function () {
        var fields = <?php echo json_encode($this->__get($nameField)) ?>;

        function getFantasiaHold() {
            var fantasiaHold = $$(fields.fantasiaHold);
            return (fantasiaHold.find("option:selected").val()
                    == fantasiaHold.find("option:first").val()) ?
                    "" : fantasiaHold.find("option:selected").text();
        }

        /*
         * Funcao de callback deste partial é um objeto global contendo
         *    Os fields Utilizados
         *    E função para callback que podera ser rescrita em qualquer outro phtml que deseje utilizar um call back diferente
         *    @since 25-02-2016
         */
        window.funcaoCallBackPartialEmpresa = {};
        window.funcaoCallBackPartialEmpresa.run = function () {
            window.funcaoCallBackPartialEmpresa.checkCnpjOrCpf();
            console.log('run emp original');
        };
        window.funcaoCallBackPartialEmpresa.adm = {};
        window.funcaoCallBackPartialEmpresa.adm.run = function () {
            console.log('run adm original');
        };
        window.funcaoCallBackPartialEmpresa.cleanEmpresa = function () {
            console.log('cleanEmpresa original');
        };
        window.funcaoCallBackPartialEmpresa.cleanRefEmpresa = function (obj) {
            console.log('cleanRefEmpresa original');
            if ($(obj).val() === "") {
                $$(window.funcaoCallBackPartialEmpresa.fields.idEmpresa).val("");
                $$(window.funcaoCallBackPartialEmpresa.fields.cnpj).val("");
                $$(window.funcaoCallBackPartialEmpresa.fields.razaoSocialEmp).val("");
            }
        };
        
        window.funcaoCallBackPartialEmpresa.cpfEmpresa = function () {
            $empCpf = $('#empresaCpf');
            $empCnpj = $('#empresaCnpj');
            if ($empCpf.is(":visible")) {
                window.funcaoCallBackPartialEmpresa.oldVlrCpf  = $empCpf.val();
                $empCpf.parent().parent().hide();
                $empCnpj.parent().parent().show();
                if(window.funcaoCallBackPartialEmpresa.oldVlrCnpj){
                    $empCnpj.val(window.funcaoCallBackPartialEmpresa.oldVlrCnpj);
                }
            } else {
                window.funcaoCallBackPartialEmpresa.oldVlrCnpj = $empCnpj.val();
                $empCnpj.parent().parent().hide();
                $empCpf.parent().parent().show();
                if(window.funcaoCallBackPartialEmpresa.oldVlrCpf){
                    $empCpf.val(window.funcaoCallBackPartialEmpresa.oldVlrCpf);
                }
            }
        };
        /*
         * Seta objeto com os fields e funçao de pegar a fantasia hold deste partial
         */
        window.funcaoCallBackPartialEmpresa.fields = fields;
        window.funcaoCallBackPartialEmpresa.getFantasiaHold = getFantasiaHold;
        /*
         * Atach uma funçao global para o botao limpar do nome da empresa
         */
        $$('#clean_' + fields.razaoSocialEmp).find('button').eq(0).click(function () {
            window.funcaoCallBackPartialEmpresa.cleanEmpresa();
        });
        /*
         * Esconde campo cpf da empresa da tela
         */
        window.funcaoCallBackPartialEmpresa.checkCnpjOrCpf = function(){
            if ($('#empresaCnpj').val() === '' || $('#empresaCnpj').val() === '00.000.000/0000-00' || $('#empresaCnpj').val() === '-') {
                var esconderDoc = '#empresaCnpj';
                var showDoc     = '#empresaCpf';
                if ($('#empresaCpf').val() === '') {// cpf tb vazio entao preferencia para cnpj
                    esconderDoc = '#empresaCpf';
                    showDoc     = '#empresaCnpj';
                }
            } else {
                var esconderDoc = '#empresaCpf';
                var showDoc     = '#empresaCnpj';
            }
            $(showDoc).parent().parent().show();
            $(esconderDoc).parent().parent().hide();
            // Marcação especial para nao validar esse campo
            $(esconderDoc).val('*');
        };
        window.funcaoCallBackPartialEmpresa.checkCnpjOrCpf();
        
        /*
         * Caso alterar o valor de um campo automaticamente altera o outro com a marcação especial
         */
        $('#empresaCnpj').change(function () {
            $('#empresaCpf').val('*');
        });
        $('#empresaCpf').change(function () {
            $('#empresaCnpj').val('*');
        });
        /*
         * Exibe botão para alternar de cnpj para cpf somente se tiver permissão
         */
        if (fields.cpfAllow) {
            $('#changeCpfForCnpj').click(function () {
                window.funcaoCallBackPartialEmpresa.cpfEmpresa();
            });
            $('#changeCnpfForCpf').click(function () {
                window.funcaoCallBackPartialEmpresa.cpfEmpresa();
            });
        } else {
            $('#changeCnpfForCpf').parent().hide();
            $('#changeCnpfForCnpj').parent().hide();
        }

        /* AUTOCOMPLETE: referencia de subhold */
        $$(fields.referenciaSubhold).auto({
            primary: "referenciaSubhold",
            serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'administradoras', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            width: 800,
            filters: function (query) {
                query["fantasiaHold"] = $$(fields.fantasiaHold).val();
            },
            responseTo: {
                "idAdministradora": [fields.idAdministradora],
                "razaoSocialAdm": [fields.razaoSocialAdm],
                "fantasiaHold": [fields.fantasiaHold]
            },
            callback: funcaoCallBackPartialEmpresa.adm,
            showCols: ["referenciaSubhold", "razaoSocialAdm"]
        });

        /* AUTOCOMPLETE: Administradora */
        $$(fields.razaoSocialAdm).auto({
            primary: "razaoSocial",
            serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'administradoras', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            width: 800,
            filters: function (query) {
                query["fantasiaHold"] = $$(fields.fantasiaHold).find("option:selected").val();
            },
            responseTo: {
                "idAdministradora": [fields.idAdministradora],
                "referenciaSubhold": [fields.referenciaSubhold],
                "fantasiaHold": [fields.fantasiaHold],
                "razaoSocialAdm": [fields.razaoSocialAdm],
            },
            callback: funcaoCallBackPartialEmpresa.adm,
            showCols: ["referenciaSubhold", "razaoSocialAdm", "fantasiaHold"]
        });
        /* AUTOCOMPLETE: parametro que diz se precisa carregar ou não por default carrega
         * @author Paulo Watakabe <watakabe05@gmail.com>
         * @since 08-03-2016 
         */
        if (fields.noAutoCompForEmpresa) {
            /* AUTOCOMPLETE: Empresa */
            $$(fields.razaoSocialEmp).auto({
                primary: "razaoSocial",
                serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'empresas', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                width: 1000,
                responseTo: {
                    "idAdministradora"   : [fields.idAdministradora],
                    "razaoSocialAdm"     : [fields.razaoSocialAdm],
                    "razaoSocialEmp"     : [fields.razaoSocialEmp],
                    "idEmpresa"          : [fields.idEmpresa],
                    "referenciaEmp"      : [fields.referenciaEmp],
                    "referenciaSubhold"  : [fields.referenciaSubhold],
                    "cnpj"               : [fields.cnpj],
                    "cpf"                : [fields.cpf],
                    "fantasiaHold"       : [fields.fantasiaHold]
                },
                filters: function (query) {
                    query["fantasiaHold"]     = getFantasiaHold();
                    query["idAdministradora"] = $$(fields.idAdministradora).val();
                },
                callback: funcaoCallBackPartialEmpresa,
                showCols: ["razaoSocialEmp", "cnpj", "cpf", "razaoSocialAdm", "fantasiaHold"]
            });

            /* AUTOCOMPLETE: Empresa */
            $$(fields.referenciaEmp).auto({
                primary: "referenciaEmp",
                serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'empresas', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                width: 1000,
                responseTo: {
                    "idAdministradora"   : [fields.idAdministradora],
                    "razaoSocialAdm"     : [fields.razaoSocialAdm],
                    "idEmpresa"          : [fields.idEmpresa],
                    "razaoSocialEmp"     : [fields.razaoSocialEmp],
                    "referenciaSubhold"  : [fields.referenciaSubhold],
                    "cnpj"               : [fields.cnpj],
                    "cpf"                : [fields.cpf],
                    "fantasiaHold"       : [fields.fantasiaHold]
                },
                filters: function (query) {
                    query["fantasiaHold"] = getFantasiaHold();
                    query["idAdministradora"] = $$(fields.idAdministradora).val();
                },
                callback: funcaoCallBackPartialEmpresa,
                showCols: ["razaoSocialEmp", "cnpj", "razaoSocialAdm", "fantasiaHold"]
            });

            /* AUTOCOMPLETE: Empresa pelo CNPJ */
            $('#empresaCnpj').auto({
                primary: "cnpj",
                serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'empresas', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                width: 1000,
                responseTo: {
                    "idAdministradora"   : [fields.idAdministradora],
                    "razaoSocialAdm"     : [fields.razaoSocialAdm],
                    "idEmpresa"          : [fields.idEmpresa],
                    "referenciaEmp"      : [fields.referenciaEmp],
                    "razaoSocialEmp"     : [fields.razaoSocialEmp],
                    "referenciaSubhold"  : [fields.referenciaSubhold],
                    "cpf"                : [fields.cpf],
                    "fantasiaHold"       : [fields.fantasiaHold]
                },
                filters: function (query) {
                    query["fantasiaHold"] = getFantasiaHold();
                    query["idAdministradora"] = $$(fields.idAdministradora).val();
                },
                callback: funcaoCallBackPartialEmpresa,
                showCols: ["razaoSocialEmp", "cnpj", "razaoSocialAdm", "fantasiaHold"]
            });
            
            /* AUTOCOMPLETE: Empresa pelo CPF */
            $('#empresaCpf').auto({
                primary: "cpf",
                serviceUrl: "<?php echo $d['this']->url('tcmed/default', array('controller' => 'empresas', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
                width: 1000,
                responseTo: {
                    "idAdministradora"   : [fields.idAdministradora],
                    "razaoSocialAdm"     : [fields.razaoSocialAdm],
                    "idEmpresa"          : [fields.idEmpresa],
                    "referenciaEmp"      : [fields.referenciaEmp],
                    "razaoSocialEmp"     : [fields.razaoSocialEmp],
                    "referenciaSubhold"  : [fields.referenciaSubhold],
                    "cnpj"               : [fields.cnpj],
                    "fantasiaHold"       : [fields.fantasiaHold]
                },
                filters: function (query) {
                    query["fantasiaHold"] = getFantasiaHold();
                    query["idAdministradora"] = $$(fields.idAdministradora).val();
                },
                callback: funcaoCallBackPartialEmpresa,
                showCols: ["razaoSocialEmp", "cnpj", "razaoSocialAdm", "fantasiaHold"]
            });
        }

        /**
         * @event Quando a hold é alterada, os campos
         * de empresa e Adm são apagados 
         */
        $$(fields.fantasiaHold).change(function () {
            $$(fields.idEmpresa).val("");
            $$(fields.idAdministradora).val("");
            $$(fields.razaoSocialEmp).val("");
            $$(fields.razaoSocialAdm).val("");
            $$(fields.referenciaSubhold).val("");
            $$(fields.referenciaEmp).val("");
            $$(fields.cnpj).val("");
        });

        /**
         * @event Quando a Administradora é apagada,
         * os campos de empresa são apagados tambem 
         */
        $$(fields.razaoSocialAdm).focus(function () {
            if ($(this).val() == "") {
                $$(fields.idEmpresa).val("");
                $$(fields.idAdministradora).val("");
                $$(fields.referenciaEmp).val("");
                $$(fields.cnpj).val("");
                $$(fields.razaoSocialEmp).val("");
            }
        });

        /**
         * @event Quando a Referencia da ADM é
         * apagada, então os campos de empresa e a
         * fantasiaHold tambem sao apagados 
         */
        $$(fields.referenciaSubhold).focus(function () {
            if ($(this).val() == "") {
                $$(fields.idEmpresa).val("");
                $$(fields.idAdministradora).val("");
                $$(fields.referenciaEmp).val("");
                $$(fields.cnpj).val("");
                $$(fields.razaoSocialEmp).val("");
                $$(fields.razaoSocialAdm).val("");
            }
        });

        /**
         * @event Quando a referencia da empresa for apagada,
         * então a empresa e o cnpj também deverao ser apagados
         */
        $$(fields.referenciaEmp).focus(function () {
            window.funcaoCallBackPartialEmpresa.cleanRefEmpresa(this);
        });
        /**
         * @event Quando a empresa for apagada, então o cnpj deve ser apagado tambem
         */
        $$(fields.razaoSocialEmp).focus(function () {
            if ($(this).val() == "") {
                $$(fields.idEmpresa).val("");
                $$(fields.cnpj).val("");
            }
        });

    });
</script>
