<?php
/** ============================================================================
 * Gera listagem de Empresas filtrados pela action pesquisaFuncionario
 * 
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 15-04-2016
 * @see Tcmed\Controller\FuncionariosController::pesquisaFuncionarioAction()
 *  ========================================================================== */
?>
<div class="row">
    <div class="col-md-10">
        <h1>Resultado da Pesquisa <small>Empresas</small></h1>
    </div>
    <div class="col-md-2">
        <button id="nova-pesquisa" class="btn btn-primary btn-block"><i class="fa fa-search"></i> Refazer Pesquisa</button>
    </div>
</div>
<br>
<?php
$controller = "empresas";

/** ============================================================================
 * Gera listagem de Empresas filtrados pela action pesquisaFuncionario
 * 
 * @author Danilo Dorotheu <danilo.dorotheu@live.com>
 * @since 15-04-2016
 * @see Tcmed\Controller\EmpresasController::pesquisaEmpresaAction()
 *  ========================================================================== */
$table = $this->table();

$table->openTable(TRUE);
$lambda = function ($value, $data) {
    echo '<td nowrap><span class="hand edit" data-id="' . $value . '" title="Editar"><i class="fa fa-pencil"></i> Editar</td>', PHP_EOL;
};
$table->setEditLine("first");
$table->setLambda($lambda);
//$table->setEditLine(FALSE);
$table->renderThead(['Ação', 'Sub Hold', 'Administradora', 'Ref. Empresa', 'Nome Empresa', 'Rua', 'Numero', 'Cep', 'Cnpj', 'Status']);
/* @var $entity \Tcmed\Entity\Empresa */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(), //ID
        $entity->getReferenciaSubhold(),
        $entity->getAdministradora('fantasiaAdm'),
        $entity->getReferenciaEmp(),
        $entity->getFantasiaEmpresa(),
        $entity->getEndereco('logradouro',['nomeLogradouro']),
        $entity->getEndereco('numero'),
        $entity->getEndereco('logradouro',['cep']),
        $entity->getCnpj(),
        $entity->getStatus(),
    ]);
}
$table->renderCloseTable();
?>
<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>
<script type="text/javascript">
    $(function () {
        $("#nova-pesquisa").click(function () {
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => "empresas", 'action' => 'pesquisaEmpresa'), [], FALSE, FALSE); ?>",
            });
        });

        $(".edit").click(function () {
            var id = $(this).attr("data-id");
            $.processa({
                url: "<?php echo $this->url('tcmed/default', array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>/" + id,
            });
        });
    });
</script>
