<h3><?php echo $this->dataView['titulo']; 
$controller = 'enderecos';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp
 * @author Allan Davini */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Enderecos:');
    $fh->openCol('12')->text('numero')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('complemento')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('fullEndereco')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol(); 
$fh->lineDown();
//    $fh->openCol('12')->select('logradouro')->closeCol();   
//$fh->lineDown();
    $this->partialObj('tcmed')->partial('logradouros/partial-form', $fh,['this' => &$this]);  
    
$fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
