<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table = $this->table();
$controller = 'enderecos';
$route = 'tcmed/default';

// Lê as mensagens do servidor através do flashMessenger
$this->partialObj('tcmed')->partial('index/partial-form-messenger', null, ['this' => &$this]);
?>
<h1>Enderecos</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'separa')); ?>">Separa</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'Tp', 'Logradouro', 'Numero', 'Compl','Bairro', 'Cidade', 'Estado','Status','Ação']);
/* @var $entity \Tcmed\Entity\Endereco */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getLogradouro()->getTipoLogradouro()->getTipo(),
        $entity->getLogradouro()->getNomeLogradouro(),
        $entity->getNumero(),
        $entity->getComplemento(),
        $entity->getLogradouro()->getBairro()->getNomeBairro(),
        $entity->getLogradouro()->getBairro()->getCidade()->getNomeCidade(),
        $entity->getLogradouro()->getBairro()->getCidade()->getEstado()->getNomeEstado(),
        $entity->getStatus(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        $.processa(data);
    }
    $(function () {

    });
</script>