<!DOCTYPE html>
<html>
    <head>
        <?
/**
 * layout com o CSS do pdf do colaborador ponto.
 * @author Danilo Song <danilosong@outlook.com>
 * @version 1.0  
 * @since 12-06-2017 
 */

?>
<!-- Incluindo o CSS do Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<style type="text/css">
    td{
        font: 9px/25px Georgia, serif;
        width: 50px;
        white-space: nowrap;
    }
    td.b{
        font: bold 12px/50px Georgia, serif;
        white-space: nowrap;
    }
    td.b1{
        font: bold 8px/25px Arial, serif;
        text-align:  center;
        white-space: nowrap;
    }
    td.b3{
        font: bold 8px/25px Arial, serif;
    }
    td.alinhar{
        text-align:  center;
        white-space: nowrap;
    }
    td.alr{
        text-align:  right;
        white-space: nowrap;
    }
    .mytab tr:nth-child(odd) {
        background-color:#ffffff;
        width: 50px;
        white-space: nowrap;
    }  
    .mytab tr:nth-child(even) {
        background-color:#e6e6e6;
        width: 50px;
        white-space: nowrap;
    } 
</style>
    </head>
  <body>


<? 
/**
 * @todo Para exibir a data em portugues o servidor devera ter instaldo o locale do pt_br exemplo para instalacao ubuntu sudo locale-gen pt_BR.utf8 para listar use sudo locale -a
 */
//
//setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');


$controller = $dataView['controller'];
$action     = $dataView['action'    ];
$route      = $dataView['route'     ];
$orderBy    = $dataView['orderBy'   ];
/* @var $param \Application\View\Helper\Param  */
/* @var $ini \DateTime */
/* @var $fim \DateTime */

$nome = [];
/* @var $param \Application\View\Helper\Image  */
$path = $param('path','cartao_ponto_logo');

?>
      <table class="table-bordered" width="100%">
            <tr>
                <td class="alinhar"><img src="<?= $path; ?>" alt="não encontrado <?= $path; ?>" width="210" height="80"/></td>
                <td class="alinhar">
                    <b><h4>Relatório de saída <?php echo date('d/m/Y H:i'); ?></h4></b>
                    <h5>
                    <?php
                        if(empty($data['filtro1']) && empty($data['filtro2'])){
                            echo 'Gerado por: '.$user['nomeUsuario'].' (Pesquisa sem filtro de data)';
                        }else{
                            echo 'Gerado por: '.$user['nomeUsuario'].' ('.$data['filtro1']. ' até ' .$data['filtro2'].')';
                        }
                    ?>
                    </h5>
                </td>
            </tr>
      </table>
      <table class="table-bordered mytab" width="100%">
        <tr>
           <td class="alinhar b3">Id               </td>
           <td class="alinhar b3">Setor            </td>
           <td class="alinhar b3">Produto          </td>
           <td class="alinhar b3">Nome             </td>
           <td class="alinhar b3">Conjunto         </td>
           <td class="alinhar b3">Qtd saída        </td>
           <td class="alinhar b3">Data de saída    </td>
           <td class="alinhar b3">Ultima compra    </td>
           <td class="alinhar b3">Estoque atual    </td>
           <td class="alinhar b3">Estoque min      </td>
           <td class="alinhar b3">Estoque max      </td>
        </tr>
            <?php foreach($resul as $entity){ ?>
        <tr>
            <td align="right"><?php echo $entity->getId(); ?>                       </td>
            <td class="alinhar"><?php echo $entity->getProduto('setor'); ?>         </td>
            <td class="alinhar"><?php echo $entity->getProduto('nomeProd'); ?>      </td>
            <td class="alinhar"><?php echo $entity->getUsuario('nome'); ?>          </td>
            <td class="alinhar"><?php echo $entity->getConjunto(); ?>               </td>
            <td align="right"><?php echo $entity->getQtd(); ?>                      </td>
            <td class="alinhar"><?php echo $entity->getCreatedAt(); ?>              </td>
            <td class="alinhar"><?php echo $entity->getProduto('dataUltCompra'); ?> </td>
            <td align="right"><?php echo $entity->getProduto('estoqueAtual'); ?>    </td>
            <td align="right"><?php echo $entity->getProduto('estoqueMinimo'); ?>   </td>
            <td align="right"><?php echo $entity->getProduto('estoqueMaximo'); ?>   </td>
        </tr>
            <?php } ?>
      </table>

      </body>
</html>