<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>
<form id="frm">
    <input name="algo">
    <input name="teste">
    <select name="opcao">
        <option value="Ola">Ola</option>
        <option value="Mundo">Mundo</option>
    </select>
    <input type="checkbox" name="f" value="8">

    <input type="radio" name="radio" value="radio1" checked="checked" id="r1">
    <label for="r1">radio1</label>
    <input type="radio" name="radio" value="radio2" id="r2">
    <label for="r2">radio2</label>
</form>

<button id="bot">Click</button>

<ul id="lista" contenteditable="true">        
     <li>&nbsp;</li>
</ul>

<button id="limpar">Limpar</button>