<?php
    $u = $this->UserIdentity() ;
    $p = $this->Param();
?>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">


        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a id="logo" class="navbar-brand">
            <img src="/img/uni.png" style="width: 100px; height: 40px; margin-top: -10px">
        </a>

    </div>

    <div class="nav navbar-nav">
        <button id="godown" title="Voltar Página" class="btn btn-default navbar-btn"><i class="fa fa-arrow-left"></i></button>
        <button id="goup" title="Avançar Página" class="btn btn-default navbar-btn"><i class="fa fa-arrow-right"></i></button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="refresh" title="Atualizar Página" class="btn btn-default navbar-btn"><i class="fa fa-refresh"></i></button>
        <button id="home" title="Página inicial" class="btn btn-default navbar-btn"><i class="fa fa-home"></i></button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="toggle" title="Acesso Menu Lateral" class="btn btn-default navbar-btn"><i class="fa fa-bars"></i></button>
        <a href="<?php echo $this->url('application-logout', [], [], FALSE, FALSE); ?>" title="Sair do Sistema" class="btn btn-default navbar-btn"><i class="fa fa-sign-out"></i></a>
    </div>

    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        <li style="color: #FFF; font-size:100%;" class="label label-default"><?= "Usuário: " , $u['nomeUsuario']; ?></li>
        <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
        <li>
            <button id="messenger" class="btn btn-success navbar-btn" data-toggle="tooltip" data-placement="left" title="Tooltip on bottom">
                <i class="fa fa-group">  </i>
            </button>
        </li>

        <!-- /.dropdown-user         -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i></a>
            <ul class="dropdown-menu dropdown-user">
<!--                
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a></li>
-->                
                <li class="divider"></li>
                <li><a href="#" id="changePassword"><i class="fa fa-edit fa-fw"></i> Alterar Senha</a></li>
                <li><a href="<?php echo $this->url('application-logout', [], [], FALSE, FALSE); ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
            </ul>
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav">
                <li class="sidebar-search">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </div>
                    </div>
                </li>
            </ul>
            <?php
                if ($u != FALSE){
                    $container = $this->navigation('Navigation')->getContainer();
                    echo $this->NewMenu($container)->setUlClass('nav" id="side-menu')->escapeLabels(false);                    
                }
            ?>
            <ul>
                <?php
//                if ($this->UserIdentity() != FALSE){
//                    echo '<pre>' , var_dump($u);
//                }
                ?>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

<script lang="javascript"> 
        
    $(function(){
        $("#changePassword").click(function () {
            var data = {url : "<?php echo $this->url('app/default',array('controller'=>'usuarios','action'=>'changePasswd'),[],FALSE,FALSE);?>" + "/" + "<?php echo ($u) ? $u['id'] : ''; ?>" };
            action.processa(data);        
        });
        /**
         * Evento no home para chamar novo estilo de menu para navegaçao do usuario
         */
        $("#home").click(function () {
            $.processa({
                url: "<?php echo $this->url($p('route','defaultRoute'), array('controller' => 'index', 'action' => 'buildIndex'), [], FALSE, FALSE); ?>",
            });
            module.Sidemenu.hideSideBar();
        });
        
        /**
         * Esconder o menu lateral pois esta decrepted 
         */
        module.Sidemenu.hideSideBar();
        
        
    });
    /**
     * Soltar request depois que carregar tudo
     */
    globalLogonUser.setAllParams();
    globalLogonUser.AllowRequest();
    setTimeout(function(){
            $("#home").click();
    },500);
</script>
