<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- logo -->
            <a class="navbar-brand" href="javascript:action.processa({url:'app/index/register'});">
                <img src="/img/logo_sistema.jpg" style="width: 130px; margin-top: -10px">
            </a>
        </div>
        <!-- Contents -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <!-- Buttons -->
            <form class="navbar-form navbar-left" role="search">
                <button type="button" class="btn btn-default go godown">
                    <i class="fa fa-arrow-left"></i>
                </button>
                <button type="button" class="btn btn-default btn-xs go goup">
                    <i class="fa fa-arrow-right"></i>
                </button>
                <button id="refreshPage" type="button" class="btn btn-default">
                    <i class="fa fa-refresh"></i>
                </button>
                <button id="menu-hide" type="button" class="btn btn-default">
                    <i class="fa fa-bolt"></i>
                </button>
            </form>

            <!-- Icons -->
            <ul class="nav navbar-top-links navbar-right">

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>

            </ul>

        </div><!-- /.navbar-collapse -->


    </div><!-- /.container-fluid -->
</nav>




<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">

    <form class="navbar-form navbar-left">
        <button class="btn btn-default">
            <i class="fa fa-refresh"></i>
        </button>
    </form>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

    </div>

    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">

                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->

                    <!--                    <button type="button" class="btn btn-default btn-primary">
                                            <i class="fa fa-arrow-left"></i>
                                        </button>-->
                </li>
                <li>
                    <a class="active" href="javascript:action.processa({url:'/app/index/cadastro'});"><i class="fa fa-dashboard fa-fw"></i> Home</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default', array('controller' => 'index', 'action' => 'cadastro')); ?>"><i class="fa fa-pencil fa-fw"></i>Usuario</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default',array('controller'=>'appRoles','action'=>'index')); ?>"><i class="fa fa-pencil fa-fw"></i>Roles</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default',array('controller'=>'appResources','action'=>'index')); ?>"><i class="fa fa-pencil fa-fw"></i>Recursos</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default',array('controller'=>'appPrivileges','action'=>'index')); ?>"><i class="fa fa-pencil fa-fw"></i>Privilegios</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default',array('controller'=>'parametros','action'=>'index')); ?>"><i class="fa fa-pencil fa-fw"></i>Parametros</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default', array('controller' => 'usuarios', 'action' => 'index')); ?>"><i class="fa fa-search fa-fw"></i> Lista Users</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default', array('controller' => 'users', 'action' => 'index')); ?>"><i class="fa fa-search fa-fw"></i> Lista Chat Users</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default', array('controller' => 'grupos', 'action' => 'index')); ?>"><i class="fa fa-search fa-fw"></i> Lista Chat Grupos</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('app/default', array('controller' => 'contatos', 'action' => 'index')); ?>"><i class="fa fa-search fa-fw"></i> Lista Chat Contatos</a>
                </li>
                <li class="primary">
                    <a><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Second Level Item</a>
                        </li>
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Second Level Item</a>
                        </li>
                        <li>
                            <a>Third Level <span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="javascript:action.processa({url:'/app/index/cadastro'});">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="javascript:action.processa({url:'/app/index/cadastro'});">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="javascript:action.processa({url:'/app/index/cadastro'});">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="javascript:action.processa({url:'/app/index/cadastro'});">Third Level Item</a>
                                </li>
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li class="primary">
                    <a><i class="fa fa-bar-chart-o fa-fw"></i> Relatórios<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Relatório Mensal</a>
                        </li>
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Relatório Anual</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li class="primary">
                    <a><i class="fa fa-bar-chart-o fa-fw"></i> Relatórios<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Relatório Mensal</a>
                        </li>
                        <li>
                            <a href="javascript:action.processa({url:'/app/index/cadastro'});">Relatório Anual</a>
                        </li>
                    </ul>

                    <!-- /.nav-second-level -->
                </li>
                <?php if ($this->UserIdentity() != FALSE): ?>
                    <li>
                        <a href="<?php echo $this->url('app/default', array('controller' => 'auth', 'action' => 'logout'), [], FALSE, FALSE); ?>"><i class="fa fa-eject fa-fw"></i> Sair</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>


