<?php
$controller   = $this->dataView['controller'];
$action       = $this->dataView['action'];
$route        = $this->dataView['route'];
$ajax         = $this->dataView['ajax'];
$title        = $this->dataView['titulo'];
$form         = $this->form;
$ret          = $form->getValue('ret', '#inter');
$frm          = 'formPpraLocal';
$form->setAttribute('id', $frm);
$form->setAttribute('target', $ret );

/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this, $form, $this->url($route, compact("controller","action","id"), [], FALSE, $ajax));
$fh->setHorizontal(true);
    /*
     * locais um array multidimenssional com os seguinte itens cada indice do array.
     * - local da atividade.
     * - Acompanhante
     * - data
     * - Horario
     * - contrução
     * - Piso e Forro
     * - Iluminação
     * - Ventilação
     */
$fh->formInit();
    $fh->openCol(12)->renderInputText('locais[local]')->closeCol();
$fh->lineDown();

$inpResponsavel = $fh->getIdFor('responsavelId');
    $fh->openCol(12)->renderInputText('locais[responsavel]',["extra" => ["icon" => "search", "class" => "list-all-autocomp", "title" => "buscar todos"]
    ])->closeCol();
$inpResponsavelNome = $fh->getLastId();

$fh->lineDown();
    $fh->openCol(12)->renderInputText('locais[acompanhante]')->closeCol();
$fh->lineDown();
    $fh->openCol(6)->renderInputCalend('locais[data]')->closeCol();
    $fh->openCol(6)->renderInputText('locais[horario]')->closeCol();
    $inpHora = $fh->getLastId();
$fh->lineDown();
    $fh->openCol(12)->renderInputTextArea('locais[construcao]')->closeCol();
    $fh->openCol(12)->renderInputTextArea('locais[pisoForro]')->closeCol();
    $fh->openCol(12)->renderInputTextArea('locais[iluminacao]')->closeCol();
    $fh->openCol(12)->renderInputTextArea('locais[ventilacao]')->closeCol();
$fh->formEnd();

echo $this->partial('partials/modal');

// Var de transferencia PHP to JS
$transp = compact(
    'id'
    ,'action'
    ,'controller'
    ,'frm'
    ,'ret'
    ,'inpHora'
    ,'inpResponsavel'
    ,'inpResponsavelNome'
);
?>
<script lang="javascript">
    function isValid(){
        return true;
    }
    $(function(){
        var transp = <?php echo json_encode($transp) ?>;
        
        $$(transp.inpResponsavelNome).auto({
            primary: "nome",
            width : 600,
            serviceUrl: "<?php echo $this->url($route, array('controller' => 'ppraResponsavels', 'action' => 'autoComp'), [], FALSE, FALSE); ?>",
            noCache: true,
            callback: function (data) {
                
                $$(transp.inpResponsavel).val(data.id);
            },
//            responseTo: {
//                id : [transp.inpResponsavel]
//            },
            showCols: ["nome","id", "situacao"]
        });
        
        //reseta o valor que foi carregado na memória do fornecedor
        $$(transp.inpResponsavelNome).change(function(){
            $$(transp.inpResponsavel).val("");
        });
        
        //mascara de horas
        $$(transp.inpHora).mask("99:99");
    });
</script>